### ISSUE TITLE
PETSc meta-issue

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#1003]
Various things need fixing with PETSc:

- Consolidate all the version interfaces into one
- Deprecate <3.4
- Configure: e50674f introduced some oddness, especially on Archer
- No proper working tests that it works
- #805 
- #625 
- #157

**Comment by dschwoerer** [comment]
BOUT++ Extended Slow Tests is now building and running PETSc:
https://omadesala.alfa1024.info/~bout-test/2018-04-27_14:32/

Support for 3.9 is missing (from the BOUT++ side)

**Comment by ZedThree** [comment]
That's cool, thanks!

**Comment by d7919** [comment]
Has this now been addressed with #1050?

**Comment by ZedThree** [comment]
Mostly fixed in #1050, just #625 which is difficult to reproduce
