### ISSUE TITLE
Use of environment variables in configure/makefiles

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#1004]
This is mostly just for reference for myself.

We should take care not to clobber or change the following environment variables in configure:

- `CXXFLAGS`
- `LDFLAGS`
- `LIBS`
- `CPPFLAGS`

These might be set by the user. We already have `EXTRA_LIBS/INCS`, as well as `BOUT_FLAGS` -- we should add to those instead of the user flags. We can then save/restore the user flags and include the appropriate internal flag when necessary.

We also don't need the following lines in `configure.ac` any more:

```
AC_ARG_VAR(CXXFLAGS,[Extra compile flags])
AC_ARG_VAR(LDFLAGS,[Extra linking flags])
AC_ARG_VAR(LDLIBS,[Extra linking libraries])
```
as they are covered by `AC_SUBST(PRECON_SOURCE)`.

We should also set `LDLIBS` and `LDADD` to the value of `LIBS` (see http://www.roland-illig.de/articles/article-1.html). This likely not important, but could be useful for the future.

**Comment by bendudson** [comment]
Automake system now replaced with CMake.
