### ISSUE TITLE
Minor : Lots of blank lines when building with make

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#1009]
I think we get a blank line due to the new dependency line in the rule for building object files. Obviously not a major issue but can be a bit unfortunate when using `make -j` as then get lots of blanks lines at end which pushes the usual output of the screen. 

Obviously very minor but could potentially obscure warnings by pushing them off the top of the screen but is there anyway to suppress this blank line?

**Comment by dschwoerer** [comment]
I cannot reproduce this with gmake on next with fedora.

Which branch are you on?
What make?
What machine?

**Comment by d7919** [comment]
This is with next and on Marconi -- I wonder if it is because the compiler is intel rather than gcc?

**Comment by dschwoerer** [comment]
Solved in #1031
