### ISSUE TITLE
Test-include readme

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#1010]
@dschwoerer  would it be possible to add a readme for test-include as it's not immediately obvious (to me) what the purpose is? From reading this it looks like it's just checking that we can compile a file that includes the header, but presumably this should be checked by the fact that we can build the library? Is it just that when we do the library source files we typically have several includes and this might be hiding the fact that some headers don't include everything they need? If this is true then I think there are tools like include-what-you-use which might be able to do this checking as part of some of the static analysis tools that have been tested.

This test seems to be quite slow compared to others at the moment. Is it possible to speed this up (e.g. using static analysis tools rather than trying to compile lots of files)?

**Comment by dschwoerer** [comment]
Yes, the test is there to ensure that every header file can be included in any order.

Note that *the library builds* is not sufficient. Clang formatting some files caused issues, as they reordered the headerfile include order: https://travis-ci.org/boutproject/BOUT-dev/jobs/363257731
Thus I wrote this test, to prevent this.
I am happy to disable it by default.

I tried include-what-you-use, but that choked on mpi, and produced thus garbage.
If you can get this to work - feel free to replace the test.
I will add a readme and disable in a PR

**Comment by dschwoerer** [comment]
Resolved by #1012
