### ISSUE TITLE
clang-format version dependent

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1017]
I noticed that clang-format's output is version dependent.

Different between v4 and v5 can be seen here:
https://travis-ci.org/boutproject/BOUT-dev/jobs/369284888

If v6 and v7 are different again, than this is going to be a problem, if we want to have everything clang-auto formatted as currently planned by #538 

Is there a way to define our style more precisely to prevent this?
Should we expect a specific version of clang installed?

**Comment by ZedThree** [comment]
That's a pain. We can try to tighten up the `.clang-format` config file which might help to some extent. I don't know how forwards compatible they are, which might be a sticking point.

We probably don't want tests to fail due to differences in formatting regardless.

**Comment by dschwoerer** [comment]
I am avoiding the test-failures by removing any white space for comparison
Here is a branch with different formattings:
https://github.com/boutproject/BOUT-dev/commits/clang-format-diff
Here is e.g. the difference from v6 to v5:
https://github.com/boutproject/BOUT-dev/commit/b305c8c7475b49696c4239964c8fc214e0aa0dd1

**Comment by ZedThree** [comment]
Oh dear, those are not great. I'll have a go at tightening up the format config file

**Comment by dschwoerer** [comment]
Did you have a look?
I would remove the clang-format from #538 - although I thought it would be really nice to have an automatic way to format the code.

**Comment by ZedThree** [comment]
Closing this: clang-format good, but tests relying on output of clang-format: bad. So we won't do that.
