### ISSUE TITLE
redefining value is possible

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1018]
This parses just fine in BOUT.inp
```
[neutrals]
type=diffusion
type=parallel
```
Is this intended to have the same value defined twice?
Should there be a warning somewhere, that the first value is overwritten?

**Comment by bendudson** [comment]
Probably should be a warning. Possibly an error if its in the same input file; overriding using command line options should be allowed.

**Comment by dschwoerer** [comment]
Resolved by #1021
