### ISSUE TITLE
./configure can no longer find libfftw3.a

### ISSUE THREAD

**Issue by loeiten** [boutproject/BOUT-dev#103]
When ```./configure``` BOUT++, the configure can no longer find libfftw3-dev as installed as described in the manual. 

The output of configure reads

```
Searching for FFTW library
 -> Path not given. Searching for library...
 -> Found fftw-wisdom executable
checking for /usr/include/fftw3.h... yes
checking for /usr/lib/libfftw3.a... no
checking for /usr/lib64/libfftw3.a... no
ERROR: FFTW not found. Required by BOUT++
```

I guess this comes from commit 2bad94c04346d1c7a41431011988b6eecbb342dc, where search paths of ```libfftw3.a``` has been changed. Should these be changed back?

**Comment by dschwoerer** [comment]
In earlier versions, a missing libfftw3.a was ignored.
This was inconsistent with the other library, where both the .a and .h was required.

**Comment by dschwoerer** [comment]
For fedora-like distribution, the packages fftw-devel and fftw-static.
I think there are two options, ether check for the shared objects, or update the documentation.

**Comment by loeiten** [comment]
As pointed out by Dr. Alf Köhn, this is still a bug on some (maybe several) distributions.

Installing ```libfftw-dev``` with ```sudo``` puts some of the files into the ```/usr/lib/x86_64-linux-gnu/``` folder, which ```./configure``` currently does not search for.

If ```fftw``` is installed both with ```sudo``` and locally, it looks like the search starts in the ```/usr/``` directory and throws a message when the lib-files are not found there, without searching in ```$HOME/local/```.

I suggest to append ```/usr/lib/x86_64-linux-gnu/``` to the searchable paths.

**Comment by ZedThree** [comment]
This is the case on Ubuntu 14.04, at least. I think this is also a more general concern than just FFTW.

One option would be to use pkg-config to check the location of a package. Something like:

    PKG_CHECK_MODULES([fftw3], [fftw3 >= 3.3.3])

should set `FFTW3_LIBS` and `FFTW3_CFLAGS` to their correct values. However, I'm not sure how they interact with setting the paths manually. Maybe a check to see if a path is given to the `--with-package` option, and if so, use that path, if not, use pkg-config.

Alternatively, we could do some parsing of `/etc/ld.so.conf`, but I feel that might be a little gross.

Another option would be to enable setting `--with-package-lib` and `--with-package-inc` as separate arguments.

Lastly, we could check environment variables like `PACKAGE_LIBPATH` and `PACKAGE_INCPATH`, for example, and set the paths according to them.

**Comment by dschwoerer** [comment]
Another option would be, as it is e.g. done in ESPResSo, to check whether the library can be linked,
instead of checking for the files to be present. This is done by AC_COMPILE_IFELSE / AC_LINK_IFELSE.

This would also allow to check whether e.g. lapack or blas are actually available at configure time, and not at compile time.

I also added /usr/lib/x86_64-linux-gnu/ to the search path, although it should not be needed.
Instead of introducing additional variables, one can set the environment variables directly, in case it is installed in a non standard place.

**Comment by loeiten** [comment]
Fixed in commit fcaffc25576aea5125f6aeb2d4f3a7a506715529

**Comment by zhangmingzhou14753** [comment]
Has the problem been solved? I also encountered this problem.

**Comment by dschwoerer** [comment]
It should be. What BOUT++ version are you using?

**Comment by zhangmingzhou14753** [comment]
Thank you for your reply！I am using&nbsp;boutproject/BOUT-dev: BOUT++: Plasma fluid finite-difference simulation code in curvilinear coordinate systems (github.com)&nbsp;this version.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "boutproject/BOUT-dev"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月11日(星期三) 晚上7:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [boutproject/BOUT-dev] ./configure can no longer find libfftw3.a (#103)





 
It should be. What BOUT++ version are you using?

**Comment by dschwoerer** [comment]
Can you include the full error and output? Maybe also attach config.log?

**Comment by zhangmingzhou14753** [comment]
Thank you for your reply！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "boutproject/BOUT-dev"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月12日(星期四) 上午6:48
***@***.***&gt;;
抄送:&nbsp;"Zhang ***@***.******@***.***&gt;;
主题:&nbsp;Re: [boutproject/BOUT-dev] ./configure can no longer find libfftw3.a (#103)





 Can you include the full error and output? Maybe also attach config.log?
