### ISSUE TITLE
Compiling error with BOUT++ v4.1.2

### ISSUE THREAD

**Issue by BodaYuan** [boutproject/BOUT-dev#1043]
Hi! When I was update my BOUT++ to the latest stable version on TSCC in UCSD, it could not proceed during the 'make'  procedure. 
Here below is the error report,
Which machine you’re compiling on,
TSCC supercomputer cluster in San Diego Supercomputer Center of UCSD
The output from make, including full error message,
  Compiling  pnetcdf.cxx
In file included from pnetcdf.cxx(26):
pnetcdf.hxx(64): error: no instance of overloaded function "PncFormat::openr" matches the argument list
In file included from pnetcdf.cxx(26):
            argument types are: (const std::string)
In file included from pnetcdf.cxx(26):
    bool openr(const string &name, int mype) {return openr(name);}
                                                     ^

../../../../include/bout/array.hxx(74): warning #3180: unrecognized OpenMP #pragma
  #pragma omp atomic
          ^

../../../../include/bout/array.hxx(342): warning #3180: unrecognized OpenMP #pragma
  #pragma omp critical (store)
          ^
          detected during instantiation of "Array<T>::Array(int) [with T=BoutReal={double}]" at line 116 of "../../../../include/fieldperp.hxx"

../../../../include/bout/array.hxx(364): warning #3180: unrecognized OpenMP #pragma
  #pragma omp critical (store)
          ^
          detected during instantiation of "Array<T>::~Array() [with T=BoutReal={double}]" at line 62 of "../../../../include/fieldperp.hxx"

../../../../include/bout/array.hxx(90): warning #3180: unrecognized OpenMP #pragma
  #pragma omp atomic
          ^

compilation aborted for pnetcdf.cxx (code 2)
gmake[4]: *** [pnetcdf.o] Error 2
gmake[3]: *** [pnetcdf] Error 2
gmake[2]: *** [impls] Error 2
gmake[1]: *** [fileio] Error 2
gmake: *** [src] Error 2

The make.config file in the BOUT++ root directory,

[make.config.zip](https://github.com/boutproject/BOUT-dev/files/1965031/make.config.zip)

**Comment by johnomotani** [comment]
I think the parallel-netcdf interface is still 'experimental' and hasn't been updated for a while. The regular netcdf interface is our usual I/O option. I suggest you remove --with-pnetcdf from your configure command: hopefully that should resolve this error.

**Comment by BodaYuan** [comment]
Thanks John. But actually I did not include --with-pnetcdf in the configure command. And before I updating the BOUT-dev I also updated my NetCDF-C library to the latest version NetCDF-C++ V4.3.0. So is it possible that it has been a default option for the new netcdf-c library to load parallel-netcdf with configuring?

**Comment by d7919** [comment]
Could you attach the config.log?

**Comment by d7919** [comment]
A hacky workaround might be to remove `-DPNCDF` from `BOUT_FLAGS` in `make.config`but this may still fail to compile if configure has picked up the parallel library rather than the serial version (can still be fixed manually.by changing `EXTRA_LIBS` and `EXTRA_INCS` but more work).

I'm guessing configure has found both parallel and serial netcdf and has tried to include both, even though you've not asked for the parallel form.

**Comment by BodaYuan** [comment]
@d7919 Hi David, please find the attached config.log. Many thanks!
[config.log](https://github.com/boutproject/BOUT-dev/files/1965208/config.log)

**Comment by bendudson** [comment]
The default in both `master` and `next` branches is for configure to look for parallel netcdf : https://github.com/boutproject/BOUT-dev/blob/next/configure.ac#L479
Configure may be finding pnetcdf (mistakenly or not) and attempting to compile with it. I don't think we test pnetcdf, so at least this should be changed to be off by default.

Can you try configuring with 
```
--with-pnetcdf=no
```

**Comment by BodaYuan** [comment]
@bendudson Thanks Ben, I think this --with-pnetcdf=no command works. But now there is another problem showing up during gmake procedure, which is like, 
 Compiling  field.cxx
../../include/bout/array.hxx(74): warning #3180: unrecognized OpenMP #pragma
  #pragma omp atomic. 
It seems like the problem with the intel compiler.

**Comment by dschwoerer** [comment]
If it is just the warning, it means you are compiling without OpenMP support (which is perfectly fine) - and the compiler is only warning you that it is ignoring these instruction, which is expected.

That should not prevent the build to fail.

**Comment by BodaYuan** [comment]
@dschwoerer OK, thank you. Thank you all guys!
