### ISSUE TITLE
ShiftedMetric geometry

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#1065]
I'm having trouble understanding how to set up the metrics when using `mesh:paralleltransform=shifted`. Should I calculate the metric the same way as for a field-aligned simulation, or do I need to set g13 and g_13 to zero because x derivatives (and Laplacian inversions?) are done with on an orthogonal x-z grid? 

Would be nice to update https://github.com/boutproject/BOUT-dev/blob/next/manual/sphinx/user_docs/parallel-transforms.rst#shifted-metric to explain this issue.

**Comment by johnomotani** [comment]
I was wondering whether the Clebsch differential operators are compatible with shifted metric. I think they are? Because the geometry coefficients for ShiftedMetric are (I think?) calculated by setting the integrated shear to zero, 'I=0`, so for each point in y, we have a separate field-aligned coordinate system with 'theta_0' the position of that y-point.

Is that right?

**Comment by bendudson** [comment]
Yes, that is the idea: On each poloidal plane we define a local coordinate system in which `theta_0` is defined so that the integrated shear is locally zero.
