### ISSUE TITLE
Replacing Bunch in python tools

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#1071]
In a bunch (ha) of modules, we use the `bunch` module. This provides a dict-like data structure that has fields that can be accessed with the dot notation, as well as dict-style. Basically, a combination of `namedtuple` and `dict`.

Unfortunately, it doesn't have great support for Python 3, and looks to have been replaced by a few forked projects.

I'm in favour of just replacing it everywhere with plain `dict`s. This would be a breaking change though, so would probably have to wait awhile.

**Comment by bendudson** [comment]
Agree this should be removed and replaced by a standard data type.

**Comment by dschwoerer** [comment]
Can we close this?
Bunch (boututils version) is used in:
```
tools/pylib/boututils/efit_analyzer.py
tools/pylib/boututils/moment_xyzt.py
tools/pylib/boututils/read_geqdsk.py
tools/tokamak_grids/pyGridGen/analyse_equil_2.py
tools/tokamak_grids/pyGridGen/follow_gradient.py
tools/tokamak_grids/pyGridGen/rz_curvature.py
tools/tokamak_grids/pyGridGen/process_grid.py
tools/tokamak_grids/pyGridGen/analyse_equil.py
tools/tokamak_grids/pyGridGen/analyse_equil_3.py
tools/tokamak_grids/pyGridGen/curvature.py
tools/tokamak_grids/pyGridGen/local_gradient.py
tools/tokamak_grids/pyGridGen/workflow.py
tools/tokamak_grids/pyGridGen/read_geqdsk.py
tools/tokamak_grids/pyGridGen/create_grid.py
```

I guess they can all be deleted in v5?

**Comment by bendudson** [comment]
Yes, I think most, perhaps all of that can be removed. Certainly pyGridGen is obsolete and replaced by Hypnotoad.
