### ISSUE TITLE
Undefined variable in restart.split

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#1076]
`xs` and `ys` aren't defined here: https://github.com/boutproject/BOUT-dev/blob/master/tools/pylib/boutdata/restart.py#L120

As far as I can tell, they've been like that since the initial commit. I guess this function isn't used much if no one's noticed!

What are they supposed to be?

**Comment by bendudson** [comment]
Looks like that function doesn't actually do anything anyway. I think redistribute does what this function is intended to do, so `split` can be removed
