### ISSUE TITLE
FieldGenerators error: ‘BoutException’ was not declared in this scope

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#108]
After the recent merges into master when I try to build BOUT++ I get :

~~~~
In file included from fieldgenerators.cxx:2:0:
fieldgenerators.hxx: In member function ‘virtual FieldGenerator* FieldRound::clone(std::list<FieldGenerator*>)’:
fieldgenerators.hxx:240:63: error: ‘BoutException’ was not declared in this scope
       throw BoutException("round function must have one input");
~~~~

I'm guessing this is a simple fix (add `#include <boutexception.hxx>` to `fieldgenerators.hxx`)

**Comment by bendudson** [comment]
Sorry, I guess make only recompiled fieldfactory.cxx and not fieldgenerators.cxx. The new round() function is only defined in the header, so I guess it didn't make a difference. Should now compile.
