### ISSUE TITLE
Parsing incomplete expressions with ExpressionParser returns null rather than exception

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#1090]
For instance:

```cpp
auto fieldgen = parser.parseString("2 +");
```

`fieldgen` is `nullptr`, whereas other incomplete or malformed expressions raise `ParseException`. I'm hesitant to say it's a bug, because in e.g. `Options::get`, we explicitly check if we get a `nullptr` or a real `FieldGenerator` back.

Would it be better for such expressions to throw exceptions, or are there situations where returning null makes more sense?

**Comment by bendudson** [comment]
There are a few places in ExpressionParser which return NULL (or 0). I think they can all be changed to throw ParseException, and I agree it makes sense to throw rather than return null.

**Comment by ZedThree** [comment]
From what I can tell, we just throw a BoutException if we get null back anyway. Changing it to a more explicit ParseException might be better. One downside would be user code that catches BoutExceptions would need to be modified to catch ParseExceptions instead.

**Comment by bendudson** [comment]
I think most places (all?) which use ExpressionParser use it via FieldFactory, since that adds most of the functions and the interface to the Options tree. Perhaps everywhere that ExpressionParser is called e.g.
https://github.com/boutproject/BOUT-dev/blob/master/src/field/field_factory.cxx#L359
FieldFactory could catch ParseException and convert it to BoutException?

**Comment by ZedThree** [comment]
That would work. An alternative might be to make ParseException inherit from BoutException?

**Comment by bendudson** [comment]
Ah yes, that might be nicer... It does make ExpressionParser less independent of BOUT++, but for error handling this probably makes sense.

**Comment by bendudson** [comment]
Fixed in #1091
