### ISSUE TITLE
Unexpected behaviour with bout_abs and isMultiple in monitor.hxx

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#1093]
`bout_abs` returns -1 if its argument is negative. Given the name, I would expect it to do something like return the absolute value. What is the intended behaviour? Can it just be replaced with `std::abs`?

I'm not 100% sure what `isMultiple` is supposed to do. It looks like it's supposed to return `true` if either argument is a multiple of the other one, but:
- if either argument is `int` zero, there's a divide-by-zero. For `double`, evaluates to `true`
- it evaluates to `true` for **any** `int` arguments
- it evaluates to `true` for some surprising `double` arguments, e.g. `isMultiple(3., 4.) == true`

What is the intended behaviour? What is its range of validity? Can it just be replaced with modulo?

**Comment by ZedThree** [comment]
Also, what is `class MonitorFunc` for? It doesn't seem to be used anywhere, as far as I can tell

**Comment by dschwoerer** [comment]
MonitorFunc is a fall-back for the previously used functions, that could be used as monitors.
Any function passed will be converted to such a monitor.
It is intended to provide a smooth transition for user code.

I will investigate the other issues.

**Comment by ZedThree** [comment]
More questions, I'm afraid:

- Is `Monitor::operator==` actually implemented anywhere? I'm not sure how this would work exactly, short of having a unique ID or something
- Are `Monitor`s `delete`d anywhere? I think `Solver::monitors` would be better as `list<unique_ptr<Monitor>>`. `Solver::addMonitor` would need to take a `unique_ptr<Monitor>`, but we could just overload and deprecate the raw pointer version. One further complicated is that C++11 doesn't have `make_unique` for some reason, but it's easy enough to add our own version
- For `MonitorFunc`, you said "any function passed will be converted" -- passed to what? There was a deprecated overload of `Solver::addMonitor`, but that's been removed now, so I think `MonitorFunc` can go

**Comment by dschwoerer** [comment]
* MonitorFunc should have been removed as part of that cleanup
* Yes, `==` is nether implemented nor used - will be removed
* I think deleting in the deletion of the solver is equivalent of requesting a unique_ptr - potentially with the exception that the other one is clearer from the interface. I am happy to change to unique_ptr or shared_ptr (in case the someone wants to use the same monitor for a different solver ...

**Comment by ZedThree** [comment]
Fixed in #1094 and #1098 

`*Monitor` should be replaced by `unique_ptr<Monitor>` in a future version, probably as part of a more general move to smart pointers
