### ISSUE TITLE
Initial conditions test case

### ISSUE THREAD

**Issue by bendudson** [boutproject/BOUT-dev#110]
The test-initial example currently fails, since the calculation of initial conditions has changed since 2010. This test should be updated to test the calculation of initial conditions more thoroughly. The expression parser is checked in test-fieldfactory, but other aspects of initialisation should be tested.  

I favour removing the old (BOUT) style switches (xs_opt, ys_opt, zs_opt etc.) as they can be replaced by expressions, so it may not be worth creating a test case to check these.

**Comment by ZedThree** [comment]
Fixed in #345
