### ISSUE TITLE
Naulin Laplace solver

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#1123]
@loeiten 
Hi Michael, I've been looking at wrapping up your 'Naulin-solver' as an option for BOUT++. Is that OK? And is it OK if we take some of your documentation and release it with BOUT++ under the LGPL? We'll include appropriate attribution and references to CELMA of course. Is there anything particular you'd like included/excluded?

Best regards,

John

**Comment by ZedThree** [comment]
I asked a couple of weeks ago: https://github.com/CELMA-project/CELMA/issues/14

He said it wasn't a problem and very kindly relicensed CELMA as LGPL, so I think you can go ahead.

**Comment by loeiten** [comment]
Hi there

Yes, of course. I would've loved to do it myself, but I don't have too much time to do it with at the moment. I would also love to give you a paper to reference, but that is under construction (and probably won't be ready until the rest of the CELMA code is refactored).
Awesome that you volunteer to do it :D.
Just be aware that the solver not applicable for general geometries (see section 9.3.2 in the [thesis](https://github.com/CELMA-project/dissertation/releases/download/v1.1.x/17_PhD_Loeiten.pdf) for details).
