### ISSUE TITLE
--enabled-shared doesn't build shared library

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#1126]
I would expect that the configure options `--enabled-shared` would build the shared library by default, but it doesn't seem to. 

Related: the Cython wrapper doesn't appear to actually need the shared library, as the Travis test just builds the static `libbout++.a`. Ideally we would condense the shared and python Travis builds into a single build to save some resources

**Comment by dschwoerer** [comment]
Closed by #1984
