### ISSUE TITLE
Grid generation from geqdsk with NaNs

### ISSUE THREAD

**Issue by nick-walkden** [boutproject/BOUT-dev#113]
This is quite a specific issue, but one that I have run into a few times now when dealing with output from equilibrium codes like Fiesta. 

The read_neqdsk.pro function which reads geqdsk files into hypnotoad skips over NaNs. If Nans are present then this can cause the reading of arrays to be shifted, resulting on odd behaviour, but not raising any errors. 

A quick solution is to add a check for NaNs, which then replaces the NaN with a string '+0.0' which can then be read consistently. I have tested this independently in python and it seems to work, but it may be dangerous to mask NaNs in this manner. I will put this quick fix into a separate branch for now.

**Comment by bendudson** [comment]
This sounds like a reasonable fix, and better than just skipping over NaNs. It would be good to print a warning message that the input contained NaNs.

**Comment by bendudson** [comment]
This was fixed in commit 80a634f9
