### ISSUE TITLE
Missing coordinates pdf

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#1136]
When the old tex documentation files were removed this also removed the files for used to generate the coordinates pdf (and possibly others). This coordinates information is referred to in the readthedocs manual but hasn't actually been merged into it and hence this information is currently missing from the repo. Should be easy to reinstate these files and perhaps a little more effort to migrate to rst.

**Comment by ZedThree** [comment]
Currently going through them and fixing the rst. Looks mostly fine, just pandoc doesn't deal with labels properly, so I'm having to do those manually.

**Comment by bendudson** [comment]
Fixed in #1139
