### ISSUE TITLE
Remove mesh->zlength

### ISSUE THREAD

**Issue by bendudson** [boutproject/BOUT-dev#114]
The length of the domain in Z is stored in zlength, which should be consistent with mesh->dz

zlength = dz * (ngz-1)

Whereas differencing methods use dz, FFT-based methods use zlength. The need to keep zlength and dz consistent has caused problems several times. Either
a) zlength is removed, and calculated from dz and ngz wherever needed
b) zlength is made a function, returning dz * (ngz-1). 
In either case, changes to dz would automatically change zlength.

**Comment by d7919** [comment]
Out of these options I would prefer b) as I can see it being easy to miscalculate `zlength` (e.g. forgetting the -1). Is it likely that someone may try to set zlength and then hope that `dz` is updated? This is the main motivation that I can think of to prefer a) to b) but I'm not sure it's likely to be a real concern.

Another alternative would be to introduce a `mesh->setDz(BoutReal dz)` function (and presumably other equivalent routines for `dx` and `dy`) which is how we then recommend people to change the spacings. This routine would update `zlength` to be consistent with the new `dz`.

Of course this has the **disadvantage** of introducing a bit of extra code *and* meaning people should update their models if they want to take advantage of this safe guard. One **advantage** however, is that it does mean that we wouldn't have to touch any of the usage of `zlength` anywhere else. A further (small) advantage of this would be that it doesn't introduce any additional overhead in accessing zlength (i.e. no calculation required and no function call). An final (potential) advantage is that it wouldn't break backwards compatibility; existing models that handle `zlength` and `dz` correctly would not need to be updated (although obviously it would still be recommended).

**Comment by ZedThree** [comment]
My vote is to replace zlength by a function. I'm not against introducing setters, but then we should probably have getters as well, and we would have to think whether we wanted to do this for everything.

Changing `zlength` -> `zlength()` everywhere should be trivial, and those instances we don't catch, the compiler will anyway.
