### ISSUE TITLE
make build-check duplicates test_suite_make

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#1147]
`make build-check` compiles all the tests, which seems to duplicate `test_suite_make`. Do we need both? If not, which one should we remove?

**Comment by dschwoerer** [comment]
`make build-check` calls `test_suite_make` [1]

With #989 `test_suite_make` will only be a tiny wrapper, which could be removed ...

[1] https://github.com/boutproject/BOUT-dev/blob/next/tests/integrated/makefile
