### ISSUE TITLE
BOUT.settings can be invalid

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1161]
If a value has an empty default, this causes the generated `BOUT.settings` to be invalid.
Should string values be allowed to be empty?

The current result is:
```
Error encountered during initialisation
====== Exception thrown ======
        Empty key or value
        Line: equilibrium_file_path =
Enable checking (configure with --enable-check or set flag -DCHECK > 1) to get a trace
====== Exception path ======
```
Expected result is:
Ether not write empty strings to bout.settings, or ignore empty variables. In the second case, an exception should be raised if they are read, but are not of string type.

Which of the 2 should be preferred?

**Comment by bendudson** [comment]
Can empty strings be written to `BOUT.settings` as `""`  ?

**Comment by ZedThree** [comment]
That would be best. Either that or reading in empty values as empty strings?

**Comment by bendudson** [comment]
Possibly both: Write out "" and read in empty values as empty strings. As long as the parsing then fails if a number, boolean or expression is requested.
