### ISSUE TITLE
Travis clear up jobs

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#1170]
We currently have a lot of jobs in Travis which means it's taking a very long time.

I propose we do some/all of the following:
- *Don't hit ctrl+enter before finishing writing the issue*
- Merge the python and shared jobs
- Drop the non-debug clang build
- Only build the unit tests with gcc-7, add `-Werror` and allow failure
- Enable debug/checks, etc. in the default build and drop the debug job (less sure of)

Any objections?

**Comment by d7919** [comment]
I didn't see this issue but I think #1196 probably addresses most of these -- can this issue be closed or do you think there's further we could do?

**Comment by bendudson** [comment]
I think this has largely been fixed.
