### ISSUE TITLE
Marconi instructions

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1187]
It seems on Marconi the default is to compile for the login node, not the compute nodes.
To my understanding, that means that AVX512 is disabled.

Should the manual be amended with something like:
```
./configure --enable-checks=0 CPPFLAGS="-Ofast -funroll-loops -xCORE-AVX512 -mtune=skylake" --host skl
```

**Comment by bendudson** [comment]
Has anyone else been able to test this? Should the manual be updated?

**Comment by dschwoerer** [comment]
Is now documented in manual: https://bout-dev.readthedocs.io/en/latest/user_docs/advanced_install.html#marconi
