### ISSUE TITLE
PETSc version

### ISSUE THREAD

**Issue by bendudson** [boutproject/BOUT-dev#119]
PETSc's fondness for changing API means BOUT++ is becoming increasingly full of things like

#if BOUT_HAS_PETSC_3_3
   // do something
#else 
  // do something else
#endif 

Rather than having a separate symbol for each version of PETSc, I propose changing to only having two:

BOUT_HAS_PETSC    (boolean)
BOUT_PETSC_VERSION  (floating point number)

so we can use things like

#if BOUT_PETSC_VERSION >= 3.3
  // Do something
#else 
  // do something else
#endif

**Comment by d7919** [comment]
Something along those lines would certainly be useful. Looking to the future (i.e. when we've maybe lost some support for older PETSc versions) it may be useful to note that more recent versions of PETSc actually provide macros for this in their headers. For example [see here](http://www.mcs.anl.gov/petsc/petsc-dev/include/petscversion.h).
