### ISSUE TITLE
Class for timestep monitors?

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#1191]
I implemented a timestep monitor for STORM. The only way I could think to enable the output I wanted was to have a global object that could be accessed by the custom timestep monitor function.

I think it would be nice to have instead (or in addition, for backward compatibility) the option to pass a Monitor object, like Solver::addMonitor. We'd need to add a new method to Monitor like `Monitor::call_timestep_monitor(Solver *solver, BoutReal time, Boutreal last_dt)`.

I think this should be fairly simple to implement. I see two questions:
1. Keep the function-passing version for backward compatibility?
2. Use the same `Monitor` class, or have a separate `TimestepMonitor` class? 

PS the manual is out of date, it says a function rather than a Monitor object should be passed to Solver::addMonitor. https://github.com/boutproject/BOUT-dev/blob/next/manual/sphinx/user_docs/time_integration.rst#monitoring-the-simulation-output

**Comment by ZedThree** [comment]
This is something we should consider when thinking about the `Solver`/`PhysicsModel` interface going forward.
