### ISSUE TITLE
Attribute output

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#1192]
At the moment, we set variable attributes every time the output is written.
* Might this be a performance issue if we output from a timestep_monitor? [based on very cursory observations, I/O doesn't seem to be a significant fraction of the runtime even with timestep monitoring turned on and outputting some scalars]
* I think the effect of this is to overwrite the attributes every time they are set, so in the end we record the attributes at the final timestep. Not sure if there's a better way to do this. If we restart a simulation and the attribute changes, the original value would not be recorded. I guess attributes should not be allowed to change during a single run (do we check for this?)? Maybe if attributes are not allowed to change, and we check for this, we could set the attribute in the file just when it is set and never reset it. Then it would make sense to check if the attribute has already been set in the file (e.g. if we are restarting a simulation) and that the value is the same. Question: what to do if the value is not the same? For an attribute like CELL_LOC it is probably an error if the value is not consistent when restarting, but there might be other (even user-defined) attributes which could change correctly.

**Comment by d7919** [comment]
#1092 is related

**Comment by dschwoerer** [comment]
Resolved by #1195
