### ISSUE TITLE
Archive/delete BOUT, BOUT-2.0 repos

### ISSUE THREAD

**Issue by bendudson** [boutproject/BOUT-dev#1206]
I think these repos should be either archived or deleted. No-one should be using them, and the tags and history are all in BOUT-dev if anyone really wants an old version of BOUT++.

**Comment by d7919** [comment]
Agreed!

**Comment by ZedThree** [comment]
Yep, agreed! Should we put a "this is now archived" notice in the respective READMEs? Or just go ahead and archive them?

**Comment by bendudson** [comment]
Done!
