### ISSUE TITLE
Adding traceback to BoutException

### ISSUE THREAD

**Issue by loeiten** [boutproject/BOUT-dev#121]
Would it make sense to add some sort of back-trace to `BoutException`?
The advantage is of course the potential to shorten debugging time, while the drawbacks could be difficulties to make this portable/that it may confuse users not familiar with the stack trace.

Examples of implementation using `execinfo.h` is given in the answers below
http://stackoverflow.com/questions/77005/how-to-generate-a-stacktrace-when-my-gcc-c-app-crashes

**Comment by d7919** [comment]
I've not looked into it but doesn't the `msg_stack` variable contain essentially this information, so it would simply be a matter of printing the entire list?

**Comment by bendudson** [comment]
This might indeed be quite nice. I have some concern about how to make sure it compiles with non-gnu compilers, and maybe on things like AIX, *BSD, OSX etc. One possibility might be to have configure try compiling a test case (as is done now to determine the floating point type for CVODE), and only include this functionality if the test works.

msg_stack provides something like this, but it relies on the code developer pushing and popping messages. The advantage is that the messages can (in principle) be more informative, but it does have some overhead. The entire msg_stack list should be printed in the event of a crash, see line 517 of bout++.cxx

  output.write("\n****** SEGMENTATION FAULT CAUGHT ******\n\n");
#ifdef CHECK
  /// Print out the message stack to help debugging
  msg_stack.dump();
#else
...

**Comment by d7919** [comment]
One other issue to keep in mind could be the demangling of names, though there is some discussion of this in a later answer on the same thread.

Presumably one option to encourage the developer to populate the `msg_stack` would be to provide a macro along the lines of the below, this also has the benefit of having no overhead when doing a production run, being portable and allows more fine scale traces if required (i.e. can have multiple messages added within a single routine).

~~~~
#ifdef CHECK
#define TRACE(name,idname) int idname = msg_stack.push("In "+str(name)+ " in "+__FILE__+" at "+to_string(__LINE__))
#define ENDTRACE(idname) msg_stack.pop(idname)
#else
#define TRACE(name)
#define ENDTRACE
#endif
~~~~

Of course this still requires the developer to add the `TRACE(name)` and `ENDTRACE` lines manually. It may be possible to remove the requirement on the presence of `ENDTRACE` by making `msg_stack.push` return something which `pop`s the message when it goes out of scope (i.e. leaves the routine).

**Comment by bendudson** [comment]
Nice! One way to avoid ENDTRACE is to use MsgStackItem (include/msg_stack.hxx). This is used like:

{
  MsgStackItem mymsg("Starting something here");
  ...
} // mymsg goes out of scope and is destroyed, popping the message

One way to avoid creating variables with the same name (multiple mymsg) might be to use idname, or maybe have TRACE1, TRACE2, ... 

#ifdef CHECK
#define TRACE(name) MsgStackItem trace("In "+str(name)+ " in "+__FILE__+" at "+to_string(__LINE__));
#define TRACE1(name) MsgStackItem trace1("In "+str(name)+ " in "+__FILE__+" at "+to_string(__LINE__));
#define TRACE2(name) MsgStackItem trace2("In "+str(name)+ " in "+__FILE__+" at "+to_string(__LINE__));
#else
#define TRACE(name)
#define TRACE1(name)
#define TRACE2(name)
#endif 

If someone uses TRACE twice in the same scope then they should get a compiler error along the lines of "trace already defined on this line... " so it should be clear what has happened (I think).

**Comment by d7919** [comment]
Ah the `MsgStackItem` looks very handy!

Some way to ensure message handles aren't being reused would indeed be important. Another approach would to do something like:

~~~~~
#define TRACE(name) MsgStackItem msgTrace_ ## __LINE__(........) 
~~~~~

which would ensure unique variable names for each trace, but does mean you can only remove the messages by them going out of scope.

**Comment by loeiten** [comment]
I cannot really see the disadvantage of the last suggestion by @d7919  as compared with the one proposed by @bendudson . Maybe one could even have

```c++
 MsgStackItem trace("In "+str(name)+ " in "+__FILE__+" in " +__func__+ " at "+to_string(__LINE__));
```

if we decide to use ```-std=c++11```.

Would it also be possible to print the stack to all log files?
For example could ```void MsgStack::dump()``` print to all processors something like "Error detected on processor x"  and then the back trace.

In what file would the macro need to be written?

**Comment by dschwoerer** [comment]
I think a stacktrace is advantageous.
First, I don't need to push messages for every function, which is a duplication of work, and therefore error prone, if I should start every function with this.
Secondly, a backtrace can include line numbers, if compiled with -g.
as the physics run function can be quite long, I get an error telling me, where the error happened. An error telling me, it was somewhere in this function is (at least for me) completely useless, (basically) all errors happen there.
About the compatibility issue: I think it should be checked and guarded by ifdefs, but this should be no reason not to include this, as there is no disadvantage for non supported systems/compilers.

**Comment by dschwoerer** [comment]
Should be in v4.0.0-RC
