### ISSUE TITLE
Delete comm_group?

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#1213]
I don't think this is used anywhere any more. Delete?

[Source](https://github.com/boutproject/BOUT-dev/blob/master/src/sys/comm_group.cxx)
[Header](https://github.com/boutproject/BOUT-dev/blob/master/include/comm_group.hxx)

**Comment by bendudson** [comment]
Deprecate for now? Then delete next major version.

**Comment by ZedThree** [comment]
Sounds good

**Comment by d7919** [comment]
Closed by #1406
