### ISSUE TITLE
Possible unnecessarily strict ASSERT in second order DDZ?

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#1217]
The assert at https://github.com/boutproject/BOUT-dev/blob/next/src/mesh/index_derivs.cxx#L1619 seems to impose something about the choice of `MZ` that the rest of the code doesn't currently require (although may recommend). 

Should we remove this assert?

**Comment by d7919** [comment]
In the same area of code I should note that we don't respect the value of `fft_derivs_filter` unlike for the first order FFT based derivatives. Should we add this in?

**Comment by bendudson** [comment]
Agree, this should be a warning rather than an assertion. Not great for FFT performance, but not actually required.

**Comment by d7919** [comment]
We actually already have a warning in boutmesh. In the branch `use_bout_for_everywhere` I've removed this assert and expanded the warning that's generated slightly to note this is a performance concern.

This branch also introduces the fft_derivs_filter for the second order fft method.

**Comment by bendudson** [comment]
Now fixed in `next`
