### ISSUE TITLE
Vector3D DDZ not calculated correctly

### ISSUE THREAD

**Issue by loeiten** [boutproject/BOUT-dev#123]
`Vector3D DDZ` is declared in [derivs.hxx](../blob/master/include/derivs.hxx) (currently) line 57-59, however, it's implementation in [derivs.cxx](../blob/master/src/sys/derivs.cxx) (currently) line 1970-1996 only takes into account the derivatives of the component, and not the derivatives of the basis vectors (see D'Haeseeler eqation (2.6.17) and (2.6.32) for details).

I suggest to replace this with the correct definitions. The correct definitions are handy when defining terms like `brackets(const Field3d &f, const Vector3D &a, ...)`.

**Comment by bendudson** [comment]
Basis vectors don't vary in Z since the metric tensor is constant in Z.

**Comment by bendudson** [comment]
Ah wait a minute... Good point. This should probably be fixed :)

**Comment by loeiten** [comment]
Indeed, I find that
![1](https://cloud.githubusercontent.com/assets/7699917/11474667/c110d556-9779-11e5-93b5-337c0103dbe1.gif)
![2](https://cloud.githubusercontent.com/assets/7699917/11474693/eb951d3c-9779-11e5-9ac0-61c2dd03ea0a.gif)

If

![3](https://cloud.githubusercontent.com/assets/7699917/11474706/fa1024a6-9779-11e5-8cda-98e3470873b2.gif)

then

![4](https://cloud.githubusercontent.com/assets/7699917/11474708/febdecfe-9779-11e5-913b-ac4016ddda74.gif)
which should be non-zero if we allow ```z``` components of the metric elements to vary with ```x``` and ```y```.


I think I just bumped into a similar kind of bug in ```Vector3D V_dot_Grad(const Vector3D &v, const Vector3D &a)```. I find that
![5](https://cloud.githubusercontent.com/assets/7699917/11474843/a2844a86-977a-11e5-8eea-141f845a56d1.gif)

and

![6](https://cloud.githubusercontent.com/assets/7699917/11474847/a674efd8-977a-11e5-8227-936cb836c9d1.gif)

Comparing this to (current) line 579-610 in [vecops.cxx](../blob/master/src/field/vecops.cxx), it looks like ```G1_23```, ```G2_13``` and ```G3_12``` terms are missing

**Comment by bendudson** [comment]
Thanks Michael. I don't think these routines have been used really, at
least not in curvilinear coordinates. These connexion terms are difficult
to get right, and in my (limited) experience introduce noise and numerical
issues. For a full-velocity neutrals model I ended up having to transform
vectors into cartesian coordinates, advect them, then transform back,
rather than trying to handle the changing basis vectors directly.

**Comment by dschwoerer** [comment]
Can this be closed?

**Comment by bendudson** [comment]
This has now been fixed (though not completely tested)
