### ISSUE TITLE
`pow(Field3D, FieldPerp)` returns Field3D -- should be FieldPerp?

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#1233]
Raising a `Field3D` to the power of a `FieldPerp` returns a `Field3D`, whereas the other mixed operations return a `FieldPerp`.

It's not clear that returning a `Field3D` makes sense, as a `FieldPerp` is at a fixed `y` location. Change to return a `FieldPerp`?

**Comment by bendudson** [comment]
Fixed by #1234
