### ISSUE TITLE
Field::applyBoundary with region string doesn't warn

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#1258]
It seems the `applyBoundary(string, string)` routines don't complain if the passed region string is not found. I propose we should throw if we don't match the passed region.

Further I'd have expected the first string to be `condition` and the second string the `region` (as the other overloads of `applyBoundary` just specify `condition` (something the throw suggested above would make clear). If we swapped the order we might be able to avoid some of the other overloads by setting a default `region`. 

Finally should we possibly be looking to replace/augment the string `region` with either a Region or a Region name?

**Comment by bendudson** [comment]
Agree that `applyBoundary(string, string)` should be deprecated, and replaced with something better involving Regions. The `BoundaryRegion` object should be replaced, but needs to have some additional information: the direction that the boundary is in, and if it is a parallel boundary which needs to use yup/down fields.

**Comment by bendudson** [comment]
Fixed in #1265
