### ISSUE TITLE
Field?D::setBoundaryTo doesn't appear to be working

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#1259]
When I do something as simple as the below on a grid with two x-guard cells I find that `tmp(0,?,?)` is still -1 suggesting the `setBoundaryTo` hasn't set all boundary points. Further I find that `tmp(1,?,?)` is coming out as 7. 

~~~~
Field3D tmp = -1.0, tmp2 = 3.0;
tmp.setBoundaryTo(tmp2);
~~~~

This might be me misunderstanding what `setBoundaryTo` is meant to do -- I think it should just copy the values in the boundary cells from one field into another. The documentation for `setBoundaryTo` on readthedocs says `Another way to set the boundaries is to copy them from another variable:` and gives the example `a.setBoundaryTo(b); // Copy b's boundaries into a`.

**Comment by d7919** [comment]
In the case given above by setting the value to 7 `tmp` is 3 inbetween `ix = 1` and `ix=2` -- it seems the routine is applying `dirichlet` boundaries using the input (`tmp2`) to indicate what value we want to have at the boundary rather than just copying values as the documentation suggests.

**Comment by bendudson** [comment]
Probably the documentation needs updating; it does set the boundary value, not the guard cells. If needed, we could add a function `setGuardsTo` which could copy guard cell values.
