### ISSUE TITLE
Local mesh being overridden by global

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#1267]
I think the line at 
https://github.com/boutproject/BOUT-dev/blob/72c6fba3ed12be57f006364e66ab05a1e6584947/src/field/field3d.cxx#L113 should be removed as it forces the Field3D to use the global mesh even though we first copy the local mesh pointer from the passed Field2D.

**Comment by bendudson** [comment]
Yes, agreed

**Comment by bendudson** [comment]
Fixed in PR #1269
