### ISSUE TITLE
Geometry/topology fields at poloidal boundary

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#1294]
I've run into a bug when interpolating metrics, etc. near the y-boundary of closed field line regions. I think I know how to fix it; writing down here for comments and so I don't forget any parts:

* The integrated shear is not continuous when crossing from poloidal angle theta=2pi -> theta=0. Therefore the metric components, etc., are not necessarily continuous across the boundary.
* To get the correct metric components when we interpolate to a `CELL_YLOW` grid the guard cells of the `CELL_CENTRE` metric components need to contain the values corresponding to extending the metric components continously from the grid cells.
* When reading geometry from input file options, this is initially done 'correctly' -- 'y' is negative in the lower boundary guard cells and >2pi in the upper boundary guard cells; but then the guard cells are overwritten by a call to `communicate`.
* When reading the grid from a file, the y-guard cells are not included, so the communication is needed to fill the guard cells, but does not give the 'correct' values

I think this bug also causes a problem when y-derivatives of the metric are taken, e.g. to calculate G1/G2/G3 https://github.com/boutproject/BOUT-dev/blob/8389878169b4e4824c2d486dad7d9d65fa0db8c5/src/mesh/coordinates.cxx#L313-L315

Steps to fix the bug:

* Add an option to skip communication when reading variables from the grid to `Mesh::get(Field2D)` (`Mesh::get(Field3D)` already has this option)
* When loading geometrical quantities, skip communications so that the y-boundary guard cells have correct values
    * for backward compatibility, do communicate if a grid file does not include y-boundary guard cells
* Update hypnotoad to calculate and output the y-boundary guard cell values (I'd be grateful if someone would be willing to update hypnotoad...). This is the enhancement requested in #24.

**Comment by johnomotani** [comment]
Maybe useful to note that this bug doesn't affect simulations using shifted-metric. For those the integrated shear does not contribute to the metric components used, so all the geometrical quantities should be periodic in y, in which case communicating is fine.

**Comment by johnomotani** [comment]
This is going to be more complicated than I first thought: the current netcdf file format will only store y-guard cells for the SOL and PFR targets, not for the closed field-line region. We'd have to change the format to take account of the mesh topology if we wanted to store the guard cells that I'm claiming above are needed :disappointed:

**Comment by johnomotani** [comment]
I think this is actually an issue for ShiftedMetric simulations as well: the zShift variable has a discontinuity somewhere which will make yupPhs and ydownPhs wrong next to the discontinuity.
https://github.com/boutproject/BOUT-dev/blob/5a76a9107806e95653bb15974fe4d821a61470d1/src/mesh/parallel/shiftedmetric.cxx#L77-L90

The simplest fix for this whole issue would be to extrapolate metric, zShift, etc. into the guard cells at the processor boundaries where there is a branch cut. Need to work out a way to identify those boundaries though [see discussion on slack, 8/10/2018]. (As noted above, a 'better' solution would need changes to the input file format.)

**Comment by d7919** [comment]
Is there a particular issue with there being a jump in `zShift` here?

**Comment by d7919** [comment]
I think @ZedThree and I may have looked into this a little while ago and found that it does actually work out correctly when combined with twist-shift, but I may be thinking of a different issue. Hopefully @ZedThree can recall more!

**Comment by johnomotani** [comment]
I think I see what you mean, as long as all the signs work out correctly. I think it's still worth fixing as part of this because (i) fixing the zShift angle and not having a twist-shift would get rid of an FFT; (ii) TwistShift is false by default and the documentation doesn't say that you have to set `mesh:twistshift=true` if using ShiftedMetric (or at least I didn't see it on a search or skim through).

**Comment by d7919** [comment]
Yes, I did have a branch that tried putting twist-shift into the shifted metric (not sure if I pushed it though). It would be nice to remove twist-shift from communicate as we may wish to apply it independently of communication. There's of course the issue of what would happen if the user was not using shiftedmetric but wanted twist-shift conditions.

**Comment by ZedThree** [comment]
The discontinuity in `zShift` is fine, as it's actually continuous modulo 2 pi.

I seem to recall most of this actually working in practice, but it took us awhile to get our heads around it.

@johnomotani Can you provide a minimal example that does the wrong thing? Preferably in the form of a test that can be added to the test suite!

**Comment by johnomotani** [comment]
I'm still working on the test... but I think at least for ShiftedMetric simulations everything is fine. Digging a bit, and looking at hypnotoad output, zShift is continuous through both PF regions. In the core there is a discontinuity and we need twist-shift *on* to get correct results. I think it would be nicer to add/subtract shiftAngle from zShift in the boundary guard cells that need a twist-shift, but that's a minor detail.

I don't understand quite how the connectivity works in the fully-field-aligned case. Say you have a single-null simulation, you start at one target with two field lines close to each other near the separatrix but one in the SOL and one in the PF. You follow them around to the other target and neither has a branch-cut or twist-shift. Physically, they could end up at just about any toroidal angles, but in the BOUT++ grid they are adjacent (although the grid is sheared) at the second target also. Is something slightly funny going on here? It's not clear to me how even a sheared grid in the x-z plane could take account of the integrated shear going across both SOL and PF regions at the same time? I guess it makes very little difference to a simulation because (i) there wouldn't be correlations wrapping that far around SOL->PF->SOL and (ii) the grids would be so sheared by then that anyone sensible would be using ShiftedMetric anyway, but still I'm curious...

**Comment by johnomotani** [comment]
Fixed in #1635.
