### ISSUE TITLE
Coordinates::Div_par broken

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1298]
This is broken, as `f` and its derivative can be at different locations.
```
const Field3D Coordinates::Div_par(const Field3D &f, CELL_LOC outloc,
                                   DIFF_METHOD method) {
  TRACE("Coordinates::Div_par( Field3D )");

  // Perversely the relevant coordinates object might not be `this` if                                        
  // f isn't at the same location.                                                                            
  if (f.getLocation() != location)
    return f.getCoordinates()->Div_par(f, outloc, method);

  if (f.hasYupYdown()) {
    // Need to modify yup and ydown fields                                                                    
    Field3D f_B = f / Bxy;
    if (&f.yup() == &f) {
      // Identity, yup and ydown point to same field                                                          
      f_B.mergeYupYdown();
    } else {
      // Distinct fields                                                                                      
      f_B.splitYupYdown();
      f_B.yup() = f.yup() / Bxy;
      f_B.ydown() = f.ydown() / Bxy;
    }
    return Bxy * Grad_par(f_B, outloc, method);
  }

  // No yup/ydown fields. The Grad_par operator will                                                          
  // shift to field aligned coordinates                                                                       
  return Bxy * Grad_par(f / Bxy, outloc, method);
}
```
Now the different coordinates need to know about each other.

I guess I will just disable checks -.-

edit, to make it clear, this line is causing issues
```
  return Bxy * Grad_par(f / Bxy, outloc, method);
```
as `Bxy` needs to be different to `Bxy`

**Comment by d7919** [comment]
Yes, sorry I missed this when I was "fixing" (?) the other location issues here. I think `return Bxy ` should become `return f.getCoordinates(outloc)->Bxy `.

**Comment by dschwoerer** [comment]
Ah, yes, I was stupid.
`f/f.getCoordinates()->Bxy` should do the job - not at all complicated -.-

Thanks for the fast help :+1:

**Comment by d7919** [comment]
As it stands `f` should always be at the same location of `Bxy` due to the first statements after the `TRACE` macro. It should only be the result of `Grad_par` that as at a different location, and hence just the `Bxy` that multiplies this result should be at `outloc`, I think.

**Comment by johnomotani** [comment]
I also ran into the same thing when writing a test for difops at staggered locations. I'm planning to make a PR with fixes for this and some other small things as well as the test, hopefully in the next few days. My working branch is https://github.com/boutproject/BOUT-dev/tree/test-difops, but it's very much work in progress at the moment, I'll rebase it before I make a PR.

**Comment by dschwoerer** [comment]
Oh, that is confusing.
That is why Div_par was twice on the call stack - ::Div_par calls at the outloc location.
I have a fix in c374fe0 - but in that case I guess I will wait for your branch with tests ...

**Comment by d7919** [comment]
Your fix is nicer than what I put in with the recursive call. The one thing that I haven't thought through with your commit fix is the `Grad_par` call which is calling a coordinates routine. This currently calls the `this` version (i.e. metrics at `outloc`), which I think does work out mostly fine*. I think there's perhaps a decision that should be made here as to if `outloc` makes sense as an input argument to the coordinates derivative routines or do we always want to force `outloc==location`?

*I note that the 2D version of `grad_par` doesn't actually explicitly ask for the derivative at `outloc` -- this is actually ok as the other changes I made here recently should ensure this derivative is done at the same location as the coordinates object. I should note that both forms of `Grad_par` implicitly assume `outloc==location` but we don't assert this, which we probably should (or remove outloc).

**Comment by johnomotani** [comment]
I think forcing `outloc==location` in the Coordinates routines and removing the outloc argument makes a lot of sense.

**Comment by d7919** [comment]
I think the main downside is that then the interface looks different from the non-coordinate member versions of these routines. I'm not sure how much of an issue this is though.
