### ISSUE TITLE
No staggering in `applyYdiff(Field2D)`

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#1311]
Whilst we accept a location in `applyYdiff(Field2D)` we don't appear to use this when filling the stencil for use in the derivative function.

**Comment by d7919** [comment]
This also seems to be true for `applyZdiff(Field3D)`.

**Comment by johnomotani** [comment]
I think we should implement staggering for the Field2D operators. I have this in a couple of places actually. I'd favour the approach in #1290, using templates to have the same code for Field3D and Field2D: less lines for a bug to hide in. I've also got a plain implementation in #1176: ab43f72d9db8c1d831295cb93b2c7ebe18acb565.

**Comment by d7919** [comment]
There's an optimisation project underway (for v4.3) that is looking to rejig the index_derivs routines etc. to provide better support for vectorisation that will also make it easier to have the same code for the two Fields.

**Comment by d7919** [comment]
I guess the `Z` staggering might be more difficult because of the FFT method?

**Comment by ZedThree** [comment]
Output location is not handled in `indexVDDX(Field2D)`

**Comment by d7919** [comment]
Addressed by #1384

**Comment by d7919** [comment]
Closed by #1384
