### ISSUE TITLE
Do boutcore build utilities understand `enum class`?

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#1314]
I've been doing some work with `enum class` statements in `include/bout_types.hxx`. Currently the travis boutcore build tests seem to fail (https://travis-ci.org/boutproject/BOUT-dev/jobs/440155082#L1267). I suspect `tools/pylib/_boutcore_build/resolve_enum.pxd.in` may need modifying to recognise `enum class` (and possibly the inv version as well)  but I'm not really sure where to start with any of this.

**Comment by dschwoerer** [comment]
Should be fixed in c168c2d218d922be29ee27e9156e4e4bcdaec7c5
Is it sufficient to keep it in this branch, or should I rebase and merge into next?

**Comment by d7919** [comment]
Thanks for looking into this and providing a fix so quickly! I think this should possibly be a separate fix -- we already have enum class in next so it would be nice to be able to support this already there (the specific branch with the commit may never make it into next as it's just experimental).

I'm slightly concerned that there needs to be a change in the c++ variable names to allow this. I'm guessing this might be quite specific to the particular case here but if this is a more general limitation then developers have to keep two languages in mind when writing!

**Comment by bendudson** [comment]
Fixed in #1328
