### ISSUE TITLE
Issue when using Grad_perp

### ISSUE THREAD

**Issue by ZeyuLI92** [boutproject/BOUT-dev#1324]
Hi. I met a problem when try to merge a elm-4f code from BOUT-3.1 version to BOUT-4.1 version. Everytime when I use the `Grad_perp` operator to operate on a 3D field (like Pressure in 4f model), the simulation would stop and the following error message would be thrown out:
```
Error encountered
====== Exception thrown ======
Field3D: Operation on non-finite data at [2][2][0]
====== Back trace ======
 -> Field3D(Field3D&) on line 79 of 'field3d.cxx'
 -> Grad_perp( Field3D ) on line 84 of 'vecops.cxx'
 -> Running RHS: PvodeSolver::rhs(0.000000e+00) on line 287 of 'pvode.cxx'
 -> Initialising PVODE solver on line 73 of 'pvode.cxx'
```

I tried to applyBoundary and mesh->communicate before I use` Grad_perp` operator, but it doesn't work. I am wondering if there is some comments on this problem. Thanks.

**Comment by ZedThree** [comment]
`lowPass_poloidal` was removed in v4.2 in this commit: 0726cd02cd

We removed it along with a number of other functions that were implemented as member functions of `Mesh` that made no use of its internals (i.e. they could be free functions). Some of them also appeared to be quite specific to certain physics models, so weren't a good fit for the main library. Unfortunately, `Mesh` has grown rather crusty over the years and we're trying to trim it back.

You should be able to reimplement those functions in your physics model by copy-pasting.

If you think `lowPass_poloidal` would be more generally useful and would like it back in the main library, we'd be very grateful if you could write a suitable test for it.
