### ISSUE TITLE
Failed to execute 3D heat conduction

### ISSUE THREAD

**Issue by akapawat** [boutproject/BOUT-dev#1327]
I modified conduction example to model heat conduction in 3D as followed.
```
 ddt(T) = Laplace(T)*chi;
```
it compiled smoothly but when I try to run with 'mpirun conduction' there was an error. I also tried to run without mpirun command but there was mpirun abort showing in error output. I suspect there might be some issue on my mpirun command rather than the code because similar codes run smoothly on my supervisor's computer.
I have attached both output as well as BOUT.inp. If anyone knows how to fix this please help. Thank you in advance.
[error_log_mpirun.txt](https://github.com/boutproject/BOUT-dev/files/2494526/error_log_mpirun.txt)
[error_log_normal_run.txt](https://github.com/boutproject/BOUT-dev/files/2494527/error_log_normal_run.txt)
[BOUT_inp.txt](https://github.com/boutproject/BOUT-dev/files/2494533/BOUT_inp.txt)

**Comment by dschwoerer** [comment]
Pvode failed, that can have plenty of reasons.

Thinks you can try:
* smaller time-step, plot T, see whether you can see any fluctuations build up
* increase accuracy of solver
* check boundaries are all set appropriately
* many more, depending on why this is happening
* lack of communication could also be an issue, but as it also happens on one node, this is at least not the only reason

**Comment by akapawat** [comment]
Thanks you all. I fixed the boundary condition and it runs fine now.
By the way, does anyone know where can I learn about how to set up boundary condition and grids because all I've been doing is just trial and errors. It would be good to know how exactly they works.

**Comment by d7919** [comment]
The documentation for BOUT++ at https://bout-dev.readthedocs.io/en/latest/ provides some discussion of these topics.

**Comment by d7919** [comment]
Reported as fixed
