### ISSUE TITLE
Advection of vectors

### ISSUE THREAD

**Issue by loeiten** [boutproject/BOUT-dev#133]
I would like to calculate terms on the form

![codecogseqn 1](https://cloud.githubusercontent.com/assets/7699917/11838914/47ee0eb4-a3ea-11e5-99d3-7dee1ffeec82.gif)

I have not found any general way to rewrite this for general geometries, so my current approach has been to make advection operators for vector quantities. This is currently implemented in https://github.com/boutproject/BOUT-dev/tree/vector_operators, but the operators are untested.

I've started to make some test routines in https://github.com/boutproject/BOUT-dev/tree/vector_operators/examples/test-vector-operators, but it turns out to be more time consuming than first expected, and I have to abandon testing these new operators for general geometry.

It could be that other people would have use for the implemented (but untested) operators, so I therefore post it as an "enhance request" here.

**Comment by nick-walkden** [comment]
I presume you have looked in literature, but appendix B of this paper might help

http://scitation.aip.org/docserver/fulltext/aip/journal/pop/17/10/1.3500283.pdf?expires=1450264245&id=id&accname=2116485&checksum=D597A16EF85A14EB66625697FEA84E53

They seem to have neglected the parallel advection terms though, and its not clear to me why they have done this.

**Comment by JensMadsen** [comment]
.... and they miss alot of other terms as well :-D Could be easier with an approach were you do not have to expand these kind of expressions. That would make your code more flexible and less error prone

**Comment by loeiten** [comment]
Closing this as wont-fix.
The stated problem seems difficult to deal with numerically, and should maybe rather be done by hand before implementing.
