### ISSUE TITLE
make clean remove .mk files?

### ISSUE THREAD

**Issue by bendudson** [boutproject/BOUT-dev#1330]
When updating to the `next` branch, errors appeared:
```
$ make
make[2]: *** No rule to make target '../../include/bout/dataiterator.hxx', needed by 'field.o'.  Stop.
```
I think the cause is leftover dependency files (e.g. `src/field/.field.mk`). I think `make distclean`, if not regular `make clean` should remove these files.

**Comment by d7919** [comment]
Yes these should definitely be removed at distclean if not also with clean.
