### ISSUE TITLE
Python tools should be packaged properly

### ISSUE THREAD

**Issue by TomNicholas** [boutproject/BOUT-dev#1347]
Currently all the python tools in pylib are stored in a subdirectory of the main BOUT repository. This causes a few problems:

1) The pylib is not packaged, so it can't be installed directly by python package managers such as pip and conda. The only way to import the scripts is to add them directly to your pythonpath, but this is not encouraged python practice. 

2) Not being able to use package managers properly makes tracking dependencies harder. With a proper `setup.py` file we can issue warnings about deprecated python versions, for example.

3) Any commits to BOUT++ python tools will be mixed in with commits to the main C++ codebase, which makes the git history less clear.

4) Users who want to fork just the core code or just the analysis tools have to fork both in one go, which is wasteful.

### Solution:

The best way to improve this would be to completely separate the python tools into their own repository, which is stored under [boutproject](https://github.com/boutproject), similar to the way [CHERAB](https://github.com/cherab) does it.

This repo could then by structured properly as a python package, with an informative `setup.py`, `__init__.py`'s, and a directory structure following the [recommended patterns](https://docs.python-guide.org/writing/structure/). 

Migrating all the python files to a new repo would be a breaking change in the sense that user's `$PYTHONPATH`s would no longer point to the right place, but it would not be hard to fix.

If we wanted then this package could then be uploaded to PYPI or Conda, or we could also just show people how to use pip or conda to install from their cloned source files directly. (or let them keep just adding the root directory to their pythonpaths)

Ideally the tools for each language (MATLAB etc.) would be placed in their own repo too, but it's most important to do it for python because it should be structured as a separate pure python package.

**Comment by johnomotani** [comment]
The discussion in #1337 is relevant here.

**Comment by d7919** [comment]
I think this could be done as a non-breaking change. We could simply treat the repository for the python module as a git sub-module so when you clone git you can (optionally/automatically) also clone a particular version of the python repository. This might make allow us to have a staged approach, where we migrate the python code, start providing a pip package but allow the existing approach to using the python tools to continue to work and provide notice that as of version 5 you'll need to pip install the python and change your paths to point to the new location. Then with the next major release we can roll over to the new approach. 

I think there's an advantage to splitting some of the python into a separate repository independent of being able to pip install the module.

**Comment by loeiten** [comment]
If anyone with owner rights to create a repo in `boutproject` could copy the current `pylib` to a repo and make a pip package out of it that would be highly appreciated. I there is already a package for a [python2](https://pypi.org/project/boutpy/) compatible version on pypi, and I think having an "official" python3 pip version has a lot of benefits. @bendudson or @ZedThree, would any of you have anything against making the repo?

**Comment by bendudson** [comment]
Happy Easter! No objections, sounds like a good idea to me. Should we make the code compatible with both python 2 and 3, or have separate repos? Is `boutpy` a name everyone's happy with?

**Comment by loeiten** [comment]
Happy Easter to all of you too 🐣 😄!
Splendid!
I vote against taking python 2 compatibility too much into consideration (see [this repo](https://gitlab.com/conderls/boutpy) and https://pythonclock.org for details). 
Also, the [`boutpy`](https://pypi.org/project/boutpy/) name seems to be taken. Maybe it can be called `bout-tools` or something similar to avoid confusion with the ongoing [PythonInterface](https://github.com/boutproject/BOUT-dev/labels/PythonInterface) projects.

**Comment by d7919** [comment]
Hmm, that pip project seems to have ported/copied most of the existing python tools straight out of this repo but they don't appear to be up to being kept up to date. I'd be happy with a different name like bout-tools. It's of course possible to keep the "bout-tools" repository available in the usual place by adding it as a sub-module to the main bout-repository in case people want to keep the same setup locally.

**Comment by loeiten** [comment]
If anyone who can create a repo in the `boutproject` group with the name `bout-tool`, I can copy the code, set up the pip package and create a submodule in the `BOUT-dev` repo.
@bendudson or @ZedThree: Would you have the possibility to create the bare repo?

**Comment by bendudson** [comment]
Done! https://github.com/boutproject/bout-tools Thanks @loeiten !

**Comment by loeiten** [comment]
So, in all my naïvety, I though that you could compile a package with several sub packages without a common root. If this really is possible, I haven't found out how to do it, and when I'm thinking about it, I can see why this may not be the best idea. As far as I see it, this gives us two options:

**Option one**: Put whatever directories in `pylib` into a `bout_tools` directory, so that all packages must be imported as `from bout_tools.what_ever_subpackage import module`.

*Pros*:
- Everything will be collected in one repo

*Cons*:
- All import statements will must change to `from bout_tools.`


**Option two**: We make one repo for each package in `pylib`

*Pros*:
- Except `boutdata` and `boututils`, the modules seems to be fairly well separated logically
- One can run independent test suites for each repo 

*Cons*:
- There are strong dependencies (hopefully not circular) between `boutdata` and `boututils`
- One must install several different pip packages

In my mind the second option appears to be cleanest, but it means that the following new repos must be made (I do not mind making pip packages of them):
- `boutdata`
- `boututils`
- `zoidberg`
- `post_bout`
(`bout-tools` can then be renamed to for example `boutdata`).
If I understand it correctly `_boutcore_build` is intimately connected with the `BOUT-dev` code, and should maybe be allowed to reside where it is, or possibly be refactored to somewhere else. I do not think `bout_runners` is used by anyone at the moment, and as I plan to do a large overhaul on it, it doesn't need its own repo yet.

Any thoughts @dschwoerer, @bendudson or @ZedThree?

**Comment by TomNicholas** [comment]
I just want to point out that any solution to this should take into account that most of `boutdata` and `boututils` are soon going to be replaced by xBOUT. In fact in a lot of cases it would probably make more sense to reimplement the desired tool using xBOUT (a lot of the scripts we currently have would become one or two lines with the new tools) and submit that as a PR.

Also @loeiten if you're planning to rewrite `bout_runners` then it might be a good idea to discuss what that would actually look like first, and how it could integrate best with other bout python tools development (like xBOUT, and restructured input file parsing classes).

**Comment by loeiten** [comment]
I see your point @TomNicholas. Do you know how soon `xBOUT` is going to supersede `boutdata` and `boututils`, and are the classes and functions just better implementations of the two other packages?

If the answer to one of these questions are "No" I suggest that we make a pip package for each package as described above, and deprecate the packages as `xBOUT` becomes ready.

As for `bout_runners`, my idea of refactoring stems from the fact that I cannot use it to run my code with SLURM queuing, and it contains so much technical debt that I doubt it can be useful for anyone but me. However, if anyone would find `bout_runners` useful I'd love to discuss the layouts with anyone interested. Any ideas on how to approach here @TomNicholas?

**Comment by TomNicholas** [comment]
> Do you know how soon xBOUT is coming?

Basically as soon as [this PR](https://github.com/pydata/xarray/pull/2616) is merged into xarray then it will be usable. That doesn't have a definite date, but I can ensure that it happens before the next release of xarray, which normally happen every couple of months.

> are the classes and functions just better implementations of the two other packages?

For many of the main data classes in `boutdata` and `boututils` then yes, but those packages also contain a bunch of random scripts which do other things. Each of those scripts could be reimplemented much more easily with the new improved data classes, but I haven't actually gone through each one. I guess the process of switching over would involve someone deliberately doing that for the most commonly-used scripts (and this process could start now).

> I suggest that we make a pip package for each package as described above, and deprecate the packages as xBOUT becomes ready.

Yeah that probably does make sense, I really just wanted to make sure people are aware of where any new development efforts should be directed.


> However, if anyone would find bout_runners useful I'd love to discuss the layouts with anyone interested. 

I think something like `bout_runners` could be useful for other users, but it has to be built in a way that is general enough to be agnostic to the particular use case. For example I have a [simple script](https://gist.github.com/TomNicholas/252d5ba052a8ef9a768aaa9231122b2d) which allows you to specify job parameters in a config file and then run it from the command line. Perhaps we should discuss the possible layouts on another issue (or maybe make a new slack channel)?

**Comment by loeiten** [comment]
Wow...that's a PR for grown-ups.

So it sounds like we agree that making the pip packages makes sense :).
I suggest to let the `README` in the repo clearly state that there is an ongoing transition to `xBOUT`, and put the transition in the [roadmap](https://github.com/boutproject/BOUT-dev/projects/3) or as a [project](https://github.com/boutproject/BOUT-dev/projects/4) (if these are still used).

Yes, let's discuss `bout_runners` somewhere else. We can have some initial discussion on slack, and raise an issue once we deprecate the current version.

@bendudson: Could you please rename `bout-tools` to `boutdata` and make a new repo for `boututils`? I can then package them as pip packages and update #1708 to just include these as a submodule.

**Comment by bendudson** [comment]
Thanks @TomNicholas and @loeiten for sorting this out. I've renamed `bout-tools` to `boutdata` and added `boututils`.

**Comment by TomNicholas** [comment]
Thanks @bendudson. Shall I close this issue then?

> Wow...that's a PR for grown-ups.

Yeah it turned out to be very very complicated... But I've learnt loads about python & OSS from doing it!

> Let's discuss bout_runners somewhere else.

I've made a slack channel to discuss `bout_runners` @loeiten .

@bendudson I think it would be good to make xBOUT a project? At the moment I've tried to manage that with lots of different issues with different tags, but a project would be useful to track progress.

**Comment by loeiten** [comment]
[`boututils`](https://pypi.org/project/boututils/) and [`boutdata`](https://pypi.org/project/boutdata/) are now available as pip packages, and PR #1740 has been created.

To test out the pip install on a bare ubuntu, you can run build the following Docker image and inspect the environment in a container.

```Dockerfile
FROM ubuntu:18.04

# Intall apt dependencies
RUN apt-get -yqq update
RUN apt-get -yqq upgrade
RUN apt-get -yqq install python3
RUN apt-get -yqq install python3-pip
# Needed for netCDF4
RUN apt-get -yqq update
RUN apt-get -yqq install libhdf5-serial-dev
RUN apt-get -yqq install netcdf-bin
RUN apt-get -yqq install libnetcdf-dev
# Needed for mayavi
RUN apt-get -yqq install locales
RUN apt-get -yqq install libsm6
RUN apt-get -yqq install libxext6
RUN apt-get -yqq install libxrender-dev
RUN apt-get -yqq install libxt6
RUN apt-get -yqq install libgl1-mesa-glx
RUN apt-get -yqq install libfontconfig
RUN apt-get -yqq install libxkbcommon-x11-0
ENV QT_QPA_PLATFORM offscreen
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN pip3 install boututils
RUN pip3 install boutdata
```

**Comment by ZedThree** [comment]
Pretty sure this is done, plus there's xBOUT. In v5 we'll delete all the pylib stuff we don't need in the main repo.

**Comment by dschwoerer** [comment]
> In v5 we'll delete all the pylib stuff we don't need in the main repo.

@ZedThree was this actually done?

**Comment by bendudson** [comment]
- `boutdata` and `boututils` are now submodules: https://github.com/boutproject/BOUT-dev/tree/next/tools/pylib
   (There is a separate question of whether these should be merged)
- There are other tools in the repository that should probably be removed: https://github.com/boutproject/BOUT-dev/tree/next/tools
   e.g. I'm fairly sure IDL support is broken, and is unlikely to be supported.
