### ISSUE TITLE
Unused code in index_derivs

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#1352]
We define a couple of limiter functions and some routines (`DDX_KT_LR` and `DDX_KT`) that don't seem to be used anywhere. Can these be removed?

**Comment by bendudson** [comment]
Yes I think so. I think they may have been used for testing, though I don't think ever used. Probably didn't work very well, but they'll still be in the history if needed.

**Comment by d7919** [comment]
Removed in #1384
