### ISSUE TITLE
Crash on fedora rawhide

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1359]
I tried to build next for fedora rawhide, and all runs fail:
```
----- test-interpolate -----
rm: cannot remove 'data/BOUT.dmp.*.nc': No such file or directory
getmpirun: using the default mpirun -np
Making Interpolation test
Running Interpolation test
------------------------------
Using hermitespline interpolation
Traceback (most recent call last):
  File "./runtest", line 60, in <module>
    s, out = launch_safe(cmd, runcmd=MPIRUN, nproc=nproc, pipe=True)
  File "/builddir/build/BUILDROOT/bout++-next-4.2.0-20181107gitf07014d.fc30.x86_64/usr/lib/python3.7/site-packages/boututils/run_wrapper.py", line 275, in launch_safe
    (s,command,out))
RuntimeError: Run failed with 132.
Command was:
./test_interpolate mesh:nx=20 mesh:dx=0.0625 MZ=16 interpolation:type=hermitespline
Output was
LOCALE_PATH = '/locale'
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node b17eb66923f442c39bb20da575d98754 exited on signal 4 (Illegal instruction).
--------------------------------------------------------------------------
```

Does anybody saw something similar or has ideas?
Otherwise, I would try again in a while, maybe this is an issue in rawhide ...

**Comment by dschwoerer** [comment]
More details:
https://copr-be.cloud.fedoraproject.org/results/davidsch/bout/fedora-rawhide-x86_64/00820950-bout++-next/

**Comment by bendudson** [comment]
What happens if you configure with `--disable-nls`? Odd that locale path is set to /locale rather than the more usual /usr/shared/locale or similar

**Comment by d7919** [comment]
I don't seem to have the same issue on Fedora 27 but I do note that configure reports:

~~~~
 Natural language support: yes (path: ${datarootdir}/locale)
~~~~

so if `${datarootdir}` is not known this would look like `/locale`.

**Comment by d7919** [comment]
This is set in the makefile as `${prefix}/share` with `prefix = /usr/local` when not specifying anything to configure. Is it possible this specific setup is not setting prefix here as it's (I think) trying to build a package?

**Comment by d7919** [comment]
From the log it looks like configure is using ` --prefix=/usr`. Configure accepts `--localedir` to specify the directory to use so it might be worth seeing if you can add this to point to the correct place.

**Comment by d7919** [comment]
Whilst the tests didn't seem to fail in my case I can see that at compilation time we have `-DBOUT_LOCALE_PATH=/locale`. I think this is because at the point of fixing BOUT_FLAGS we have yet to define `${datarootdir}`.

**Comment by dschwoerer** [comment]
Yes, fedora 27 to 29 are fine, just 30 is having the issue.

I set `--datarootdir=%{_libdir}/$mpi/share` - so that is where the locale files get installed - but for some reason BOUT++ looks in 't know that.

Thanks for the help, with that I found an error: BOUT_FLAGS forces a static evaluation. That means setting datarootdir afterwards gets ignored.
I will try whether that fixes the issue :+1:

**Comment by d7919** [comment]
Yes I think the static evaluation is needed for the current way that we provide a define which contains all of the BOUT_FLAGS so we can report this during the startup. There may be a more elegant way of doing this.

**Comment by dschwoerer** [comment]
Yes, I think putting the prefix definition before the static evaluation should fix that. But that means BOUT++ needs to be installed without overwriting prefix. This is fine if I am building packages, but means that BOUT++ will not work (with locale support at least) without being installed.

If that causes crashes, if the locale files are not found - should they then be disabled by default?

**Comment by bendudson** [comment]
If the files aren't found then it isn't supposed to crash,  just not do the translations.  Something about trying to access a directory which doesn't exist?

**Comment by dschwoerer** [comment]
Maybe. It might very well be a bug in rawhide, which is the unstable development version of fedora.

**Comment by dschwoerer** [comment]
Now master fails. Again rawhide. Again illegal instruction.
https://copr-be.cloud.fedoraproject.org/results/davidsch/bout/fedora-rawhide-x86_64/00821051-bout++/build.log.gz
