### ISSUE TITLE
zeroComponent(int) and getData(int)

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#136]
I think both commands are confusing, as they don't use the int, which is given as argument.
Additionally, I couldn't find a place where they are used.
Is there a reason for them, or could they be removed?

**Comment by bendudson** [comment]
Happy new year!

This was part of a (not very good) abstraction for writing to file. Fields and vectors inherit from FieldData (include/field_data.hxx). The integer arguments to getData(int) and zeroComponent(int) functions are used in vectors (e.g. include/vector2d.hxx line 150) to select between the x,y, and z components. 

At the moment these functions are not used anywhere:

getData(int)
zeroComponent(int)
getSuffix(int)

so yes, they can be removed.  What is used is almost as bad:

1. In the DataFile the various data classes (Fields, Vectors) are handled separately
2. In Mesh::communicate 
msg_len in src/mesh/mesh.cxx line 224:  BoutRealSize()   to get the number of reals per grid point (e.g. Field = 1, Vector = 3)
pack_data in src/mesh/impls/bout/boutmesh.cxx line 2272 : getData(int, int, int, BoutReal*) to put data into a buffer
unpack_data in src/mesh/impls/bout/boutmesh.cxx line 2301 : setData(int, int, int, BoutReal*) to get data from a buffer into a field/vector.
