### ISSUE TITLE
Checking in Field constructors

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#1361]
Currently, there's lots of checking via calls to `checkData` all over the place, and I wonder if it's possible to remove some of them. Take the following example:

```cpp
Field3D f, a{0.0}, b{a};

f = (a + 1) * b;
```
There are seven calls to `checkData(Field3D)` (one in the copy ctor for `b`, two in the addition, three in the multiplication, one in the assignment) and two to `checkData(BoutReal)` (one in the initialisation of `a`, one in addition).

I would like to remove the `checkData(Field3D)` from the copy-constructor and -assignment operator. This would allow e.g. making them both `noexcept`. We've got much better at pre- and post-conditions in Field operations so I think it would be ok to relax them in copy construction/assignment.

A potential downside would be not catching the following situations:

```cpp
Field3D a, b{a};
// or
void foo(Field3D f);
Field3D c;
foo(c);
```

I think the first case is probably too rare to worry about and would be caught as soon you tried to use `b`.
The second case is likely also very rare -- we normally don't pass Fields by value, and this could be solved by calling `checkData(f)` immediately inside `foo` anyway (which we should be doing!).

See e.g. #914 for a related issue.

**Comment by d7919** [comment]
I would certainly support removing the checks on copying fields. I think it should be valid to create a copy of an empty field -- it's just an error to then try to read/write data from this without allocating first.

**Comment by ZedThree** [comment]
Removed in #1533
