### ISSUE TITLE
error installing bout++ on LISA cluster at SURFsara in Amsterdam

### ISSUE THREAD

**Issue by westerhof** [boutproject/BOUT-dev#1370]
result of make:
login1:~/BOUT-dev> make
  Compiling  field.cxx
  Compiling  field2d.cxx
  Compiling  field3d.cxx
  Compiling  fieldperp.cxx
  Compiling  field_data.cxx
  Compiling  fieldgroup.cxx
  Compiling  field_factory.cxx
  Compiling  fieldgenerators.cxx
  Compiling  initialprofiles.cxx
  Compiling  vecops.cxx
  Compiling  vector2d.cxx
  Compiling  vector3d.cxx
  Compiling  where.cxx
  Compiling  globalfield.cxx
  Compiling  generated_fieldops.cxx
  Compiling  nc_format.cxx
  Compiling  ncxx4.cxx
  Compiling  pnetcdf.cxx
  Compiling  h5_format.cxx
h5_format.cxx: In constructor 'H5Format::H5Format(bool)':
h5_format.cxx:68:48: error: too many arguments to function 'herr_t H5Eset_auto1(H5E_auto1_t, void*)'
   if (H5Eset_auto(H5E_DEFAULT, nullptr, nullptr) < 0)
                                                ^
In file included from /sara/sw/hdf5-intel-1.8.10/include/hdf5.h:28:0,
                 from h5_format.hxx:50,
                 from h5_format.cxx:24:
/sara/sw/hdf5-intel-1.8.10/include/H5Epublic.h:216:15: note: declared here
 H5_DLL herr_t H5Eset_auto1(H5E_auto1_t func, void *client_data);
               ^
h5_format.cxx: In constructor 'H5Format::H5Format(const char*, bool)':
h5_format.cxx:102:48: error: too many arguments to function 'herr_t H5Eset_auto1(H5E_auto1_t, void*)'
   if (H5Eset_auto(H5E_DEFAULT, nullptr, nullptr) < 0)
                                                ^
In file included from /sara/sw/hdf5-intel-1.8.10/include/hdf5.h:28:0,
                 from h5_format.hxx:50,
                 from h5_format.cxx:24:
/sara/sw/hdf5-intel-1.8.10/include/H5Epublic.h:216:15: note: declared here
 H5_DLL herr_t H5Eset_auto1(H5E_auto1_t func, void *client_data);
               ^
h5_format.cxx: In member function 'virtual const std::vector<int> H5Format::getSize(const char*)':
h5_format.cxx:180:54: error: too many arguments to function 'hid_t H5Dopen1(hid_t, const char*)'
   hid_t dataSet = H5Dopen(dataFile, name, H5P_DEFAULT);
                                                      ^
In file included from /sara/sw/hdf5-intel-1.8.10/include/hdf5.h:27:0,
                 from h5_format.hxx:50,
                 from h5_format.cxx:24:
/sara/sw/hdf5-intel-1.8.10/include/H5Dpublic.h:145:14: note: declared here
 H5_DLL hid_t H5Dopen1(hid_t file_id, const char *name);
              ^
h5_format.cxx: In member function 'bool H5Format::addVar(const string&, bool, hid_t, int)':
h5_format.cxx:258:62: error: too many arguments to function 'hid_t H5Dopen1(hid_t, const char*)'
   hid_t dataSet = H5Dopen(dataFile, name.c_str(), H5P_DEFAULT);
                                                              ^
In file included from /sara/sw/hdf5-intel-1.8.10/include/hdf5.h:27:0,
                 from h5_format.hxx:50,
                 from h5_format.cxx:24:
/sara/sw/hdf5-intel-1.8.10/include/H5Dpublic.h:145:14: note: declared here
 H5_DLL hid_t H5Dopen1(hid_t file_id, const char *name);
              ^
h5_format.cxx:294:116: error: too many arguments to function 'hid_t H5Dcreate1(hid_t, const char*, hid_t, hid_t, hid_t)'
     dataSet = H5Dcreate(dataFile, name.c_str(), write_hdf5_type, init_space, H5P_DEFAULT, propertyList, H5P_DEFAULT);
                                                                                                                    ^
In file included from /sara/sw/hdf5-intel-1.8.10/include/hdf5.h:27:0,
                 from h5_format.hxx:50,
                 from h5_format.cxx:24:
/sara/sw/hdf5-intel-1.8.10/include/H5Dpublic.h:143:14: note: declared here
 H5_DLL hid_t H5Dcreate1(hid_t file_id, const char *name, hid_t type_id,
              ^
h5_format.cxx:317:128: error: too many arguments to function 'hid_t H5Acreate1(hid_t, const char*, hid_t, hid_t, hid_t)'
     hid_t myatt_in = H5Acreate(dataSet, "bout_type", variable_length_string_type, attribute_dataspace, H5P_DEFAULT, H5P_DEFAULT);
                                                                                                                                ^
In file included from /sara/sw/hdf5-intel-1.8.10/include/hdf5.h:25:0,
                 from h5_format.hxx:50,
                 from h5_format.cxx:24:
/sara/sw/hdf5-intel-1.8.10/include/H5Apublic.h:105:16: note: declared here
 H5_DLL hid_t   H5Acreate1(hid_t loc_id, const char *name, hid_t type_id,
                ^
h5_format.cxx:334:58: error: too many arguments to function 'hid_t H5Dopen1(hid_t, const char*)'
     dataSet = H5Dopen(dataFile, name.c_str(), H5P_DEFAULT);
                                                          ^
In file included from /sara/sw/hdf5-intel-1.8.10/include/hdf5.h:27:0,
                 from h5_format.hxx:50,
                 from h5_format.cxx:24:
/sara/sw/hdf5-intel-1.8.10/include/H5Dpublic.h:145:14: note: declared here
 H5_DLL hid_t H5Dopen1(hid_t file_id, const char *name);
              ^
h5_format.cxx:363:117: error: too many arguments to function 'hid_t H5Dcreate1(hid_t, const char*, hid_t, hid_t, hid_t)'
       dataSet = H5Dcreate(dataFile, name.c_str(), write_hdf5_type, init_space, H5P_DEFAULT, H5P_DEFAULT, H5P_DEFAULT);
                                                                                                                     ^
In file included from /sara/sw/hdf5-intel-1.8.10/include/hdf5.h:27:0,
                 from h5_format.hxx:50,
                 from h5_format.cxx:24:
/sara/sw/hdf5-intel-1.8.10/include/H5Dpublic.h:143:14: note: declared here
 H5_DLL hid_t H5Dcreate1(hid_t file_id, const char *name, hid_t type_id,
              ^
h5_format.cxx: In member function 'bool H5Format::read(void*, hid_t, const char*, int, int, int)':
h5_format.cxx:441:54: error: too many arguments to function 'hid_t H5Dopen1(hid_t, const char*)'
   hid_t dataSet = H5Dopen(dataFile, name, H5P_DEFAULT);
                                                      ^
In file included from /sara/sw/hdf5-intel-1.8.10/include/hdf5.h:27:0,
                 from h5_format.hxx:50,
                 from h5_format.cxx:24:
/sara/sw/hdf5-intel-1.8.10/include/H5Dpublic.h:145:14: note: declared here
 H5_DLL hid_t H5Dopen1(hid_t file_id, const char *name);
              ^
h5_format.cxx: In member function 'bool H5Format::write(void*, hid_t, const char*, int, int, int)':
h5_format.cxx:549:54: error: too many arguments to function 'hid_t H5Dopen1(hid_t, const char*)'
   hid_t dataSet = H5Dopen(dataFile, name, H5P_DEFAULT);
                                                      ^
In file included from /sara/sw/hdf5-intel-1.8.10/include/hdf5.h:27:0,
                 from h5_format.hxx:50,
                 from h5_format.cxx:24:
/sara/sw/hdf5-intel-1.8.10/include/H5Dpublic.h:145:14: note: declared here
 H5_DLL hid_t H5Dopen1(hid_t file_id, const char *name);
              ^
h5_format.cxx: In member function 'bool H5Format::read_rec(void*, hid_t, const char*, int, int, int)':
h5_format.cxx:649:54: error: too many arguments to function 'hid_t H5Dopen1(hid_t, const char*)'
   hid_t dataSet = H5Dopen(dataFile, name, H5P_DEFAULT);
                                                      ^
In file included from /sara/sw/hdf5-intel-1.8.10/include/hdf5.h:27:0,
                 from h5_format.hxx:50,
                 from h5_format.cxx:24:
/sara/sw/hdf5-intel-1.8.10/include/H5Dpublic.h:145:14: note: declared here
 H5_DLL hid_t H5Dopen1(hid_t file_id, const char *name);
              ^
h5_format.cxx: In member function 'bool H5Format::write_rec(void*, hid_t, const char*, int, int, int)':
h5_format.cxx:755:54: error: too many arguments to function 'hid_t H5Dopen1(hid_t, const char*)'
   hid_t dataSet = H5Dopen(dataFile, name, H5P_DEFAULT);
                                                      ^
In file included from /sara/sw/hdf5-intel-1.8.10/include/hdf5.h:27:0,
                 from h5_format.hxx:50,
                 from h5_format.cxx:24:
/sara/sw/hdf5-intel-1.8.10/include/H5Dpublic.h:145:14: note: declared here
 H5_DLL hid_t H5Dopen1(hid_t file_id, const char *name);
              ^
h5_format.cxx: In member function 'virtual void H5Format::setAttribute(const string&, const string&, const string&)':
h5_format.cxx:822:65: error: too many arguments to function 'hid_t H5Dopen1(hid_t, const char*)'
   hid_t dataSet = H5Dopen(dataFile, varname.c_str(), H5P_DEFAULT);
                                                                 ^
In file included from /sara/sw/hdf5-intel-1.8.10/include/hdf5.h:27:0,
                 from h5_format.hxx:50,
                 from h5_format.cxx:24:
/sara/sw/hdf5-intel-1.8.10/include/H5Dpublic.h:145:14: note: declared here
 H5_DLL hid_t H5Dopen1(hid_t file_id, const char *name);
              ^
h5_format.cxx: In member function 'virtual void H5Format::setAttribute(const string&, const string&, int)':
h5_format.cxx:847:65: error: too many arguments to function 'hid_t H5Dopen1(hid_t, const char*)'
   hid_t dataSet = H5Dopen(dataFile, varname.c_str(), H5P_DEFAULT);
                                                                 ^
In file included from /sara/sw/hdf5-intel-1.8.10/include/hdf5.h:27:0,
                 from h5_format.hxx:50,
                 from h5_format.cxx:24:
/sara/sw/hdf5-intel-1.8.10/include/H5Dpublic.h:145:14: note: declared here
 H5_DLL hid_t H5Dopen1(hid_t file_id, const char *name);
              ^
h5_format.cxx: In member function 'void H5Format::setAttribute(const hid_t&, const string&, const string&)':
h5_format.cxx:879:127: error: too many arguments to function 'hid_t H5Acreate1(hid_t, const char*, hid_t, hid_t, hid_t)'
     myatt_in = H5Acreate(dataSet, attrname.c_str(), variable_length_string_type, attribute_dataspace, H5P_DEFAULT, H5P_DEFAULT);
                                                                                                                               ^
In file included from /sara/sw/hdf5-intel-1.8.10/include/hdf5.h:25:0,
                 from h5_format.hxx:50,
                 from h5_format.cxx:24:
/sara/sw/hdf5-intel-1.8.10/include/H5Apublic.h:105:16: note: declared here
 H5_DLL hid_t   H5Acreate1(hid_t loc_id, const char *name, hid_t type_id,
                ^
h5_format.cxx: In member function 'void H5Format::setAttribute(const hid_t&, const string&, int)':
h5_format.cxx:904:118: error: too many arguments to function 'hid_t H5Acreate1(hid_t, const char*, hid_t, hid_t, hid_t)'
   hid_t myatt_in = H5Acreate(dataSet, attrname.c_str(), H5T_NATIVE_INT, attribute_dataspace, H5P_DEFAULT, H5P_DEFAULT);
                                                                                                                      ^
In file included from /sara/sw/hdf5-intel-1.8.10/include/hdf5.h:25:0,
                 from h5_format.hxx:50,
                 from h5_format.cxx:24:
/sara/sw/hdf5-intel-1.8.10/include/H5Apublic.h:105:16: note: declared here
 H5_DLL hid_t   H5Acreate1(hid_t loc_id, const char *name, hid_t type_id,
                ^
h5_format.cxx: In member function 'virtual bool H5Format::getAttribute(const string&, const string&, std::__cxx11::string&)':
h5_format.cxx:919:65: error: too many arguments to function 'hid_t H5Dopen1(hid_t, const char*)'
   hid_t dataSet = H5Dopen(dataFile, varname.c_str(), H5P_DEFAULT);
                                                                 ^
In file included from /sara/sw/hdf5-intel-1.8.10/include/hdf5.h:27:0,
                 from h5_format.hxx:50,
                 from h5_format.cxx:24:
/sara/sw/hdf5-intel-1.8.10/include/H5Dpublic.h:145:14: note: declared here
 H5_DLL hid_t H5Dopen1(hid_t file_id, const char *name);
              ^
h5_format.cxx: In member function 'virtual bool H5Format::getAttribute(const string&, const string&, int&)':
h5_format.cxx:936:65: error: too many arguments to function 'hid_t H5Dopen1(hid_t, const char*)'
   hid_t dataSet = H5Dopen(dataFile, varname.c_str(), H5P_DEFAULT);
                                                                 ^
In file included from /sara/sw/hdf5-intel-1.8.10/include/hdf5.h:27:0,
                 from h5_format.hxx:50,
                 from h5_format.cxx:24:
/sara/sw/hdf5-intel-1.8.10/include/H5Dpublic.h:145:14: note: declared here
 H5_DLL hid_t H5Dopen1(hid_t file_id, const char *name);
              ^
At global scope:
cc1plus: warning: unrecognized command line option '-Wno-cast-function-type'
../../../../make.config:295: recipe for target 'h5_format.o' failed
make[4]: *** [h5_format.o] Error 1
../../../make.config:120: recipe for target 'hdf5' failed
make[3]: *** [hdf5] Error 2
../../make.config:120: recipe for target 'impls' failed
make[2]: *** [impls] Error 2
../make.config:120: recipe for target 'fileio' failed
make[1]: *** [fileio] Error 2
make.config:120: recipe for target 'src' failed
make: *** [src] Error 2

[make.zip](https://github.com/boutproject/BOUT-dev/files/2580418/make.zip)

**Comment by ZedThree** [comment]
Please could you also upload `config.log` and the output of `h5cc -showconfig`? I suspect you are getting these errors because the HDF5 library has been compiled in 1.6 compatibility mode. You may need to recompile HDF5 to use the 1.8 API, or contact your system admin.

**Comment by westerhof** [comment]
login1:~/BOUT-dev> h5cc -showconfig
            SUMMARY OF THE HDF5 CONFIGURATION
            =================================

General Information:
-------------------
                   HDF5 Version: 1.8.10-patch1
                  Configured on: Fri Feb  8 17:18:27 CET 2013
                  Configured by: mz043@software.irc.sara.nl
                 Configure mode: production
                    Host system: x86_64-unknown-linux-gnu
              Uname information: Linux software.irc.sara.nl 3.4.6-sara2 #1 SMP Tue Jul 31 16:56:51 CEST 2012 x86_64 GNU/Linux
                       Byte sex: little-endian
                      Libraries:
             Installation point: /sara/sw/hdf5-intel-1.8.10

Compiling Options:
------------------
               Compilation Mode: production
                     C Compiler: /sara/sw/modules-ng-64/wrappers/sara/icc -m64 ( Intel(R) C Intel(R) 64 Compiler Version 13.1.0.146 Build 20130121)
                         CFLAGS:
                      H5_CFLAGS: -std=c99  -O
                      AM_CFLAGS:
                       CPPFLAGS:
                    H5_CPPFLAGS: -D_POSIX_C_SOURCE=199506L   -DNDEBUG -UH5_DEBUG_API
                    AM_CPPFLAGS: -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_BSD_SOURCE
               Shared C Library: yes
               Static C Library: yes
  Statically Linked Executables: no
                        LDFLAGS:
                     H5_LDFLAGS:
                     AM_LDFLAGS:
                Extra libraries:  -lz -lrt -lm
                       Archiver: ar
                         Ranlib: ranlib
              Debugged Packages:
                    API Tracing: no

Languages:
----------
                        Fortran: yes
               Fortran Compiler: /sara/sw/modules-ng-64/wrappers/sara/ifort -m64 ( Intel(R) Fortran Intel(R) 64 Compiler Version 13.1.0.146 Build 20130121)
          Fortran 2003 Compiler: no
                  Fortran Flags:
               H5 Fortran Flags:  -O3
               AM Fortran Flags:
         Shared Fortran Library: yes
         Static Fortran Library: yes

                            C++: yes
                   C++ Compiler: /sara/sw/modules-ng-64/wrappers/sara/icpc -m64 ( Intel(R) C++ Intel(R) 64 Compiler Version 13.1.0.146 Build 20130121)
                      C++ Flags:
                   H5 C++ Flags:
                   AM C++ Flags:
             Shared C++ Library: yes
             Static C++ Library: yes

Features:
---------
                  Parallel HDF5: no
             High Level library: yes
                   Threadsafety: no
            Default API Mapping: v16
 With Deprecated Public Symbols: yes
         I/O filters (external): deflate(zlib)
         I/O filters (internal): shuffle,fletcher32,nbit,scaleoffset
                            MPE: no
                     Direct VFD: no
                        dmalloc: no
Clear file buffers before write: yes
           Using memory checker: no
         Function Stack Tracing: no
                           GPFS: no
      Strict File Format Checks: no
   Optimization Instrumentation: no
       Large File Support (LFS): yes
[config.log](https://github.com/boutproject/BOUT-dev/files/2580534/config.log)

**Comment by westerhof** [comment]
I think you were right.
I have changed from the default hdf5 module to another module for hdf5 rerun .configure and make and the library has been created.

Thanks for the quick response
Egbert Westerhof
DIFFER
Eindhoven, NL
