### ISSUE TITLE
Change definition of `UNUSED` macro to not change name of argument

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#1393]
Currently, `UNUSED(x)` changes the name of `x` to `UNUSED_x` so as to prevent accidental use of `x`. However, the majority of the warnings in `next` at the minute are due to variables unused only at certain `CHECK` levels (mostly `CHECK = 0`), so are only "maybe unused"\* so it is not a mistake to use one.

Should we change `UNUSED` or add a new `MAYBE_UNUSED` to clarify these situations?

Also, a lot of the warnings come from derivatives taking more arguments (e.g. `DIFF_METHOD`) than they actually want, for consistency with other functions. I'm not sure this is wise. We should either make those options useful, which #1384 does for some cases, or remove the argument.

---

\* C++17 adds the `[[maybe_unused]]` attribute, so we could test if the compiler has that

**Comment by d7919** [comment]
I'd prefer adding a maybe_unused so we can maintain the checking that we get from the current unused implementation.

**Comment by bendudson** [comment]
Fixed in #1403
