### ISSUE TITLE
Missing positional argument in dirname in BoutOptionsFile

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#1426]
`os.path.dirname` requires a path argument. Guess this should be `filename`?

https://github.com/boutproject/BOUT-dev/blob/b30d255341fc7544ae56ba91e4c792c2e6df68b8/tools/pylib/boutdata/data.py#L355

**Comment by johnomotani** [comment]
@ZedThree yes, that's right. The intention is to get nx/ny/nz from output files in case they can't be found from `BOUT.inp` or a gridfile; the assumption is that output files would be in the same directory as the `BOUT.inp`.

Looking at it again now, I wonder whether it is a good idea to try this at all... Possibly when I wrote this I was thinking that it would pick up options that might have been given on the command line, but now I'm thinking that BoutOptionsFile should probably not depend on the output of runs (you might get different results from using BoutOptionsFile before and after running a simulation, which should only happen if the user requests it explicitly). The constructor takes nx/ny/nz arguments, so a user can pass in the values from dump files if they want to. I propose we should delete lines 352-360 and jump straight to trying to read from the grid file; to be consistent with C++ code, we should probably also prefer to read nx/ny from the gridfile before reading from `BOUT.inp`?
https://github.com/boutproject/BOUT-dev/blob/b30d255341fc7544ae56ba91e4c792c2e6df68b8/tools/pylib/boutdata/data.py#L352-L360

**Comment by ZedThree** [comment]
Pretty sure this is fixed now
