### ISSUE TITLE
Duplicate time zone

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#1428]
The output of `std::string toString<>(const time_t& time)` seems to duplicate the time zone -- for instance lines like `Run started at  : Mon 10 Dec 2018 12:23:38 GMT GMT` appear in the output of jobs (note the duplicate `GMT`). 

I suspect the format used in the `strftime(buffer, 80, "%Ec %Z", tm);` call probably just needs to drop the `%Z`, however this may be LOCALE dependent?

**Comment by dschwoerer** [comment]
Fixed by #1440
