### ISSUE TITLE
FV::Div_par_K_Grad_par region bug?

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#1429]
Do we know if `FV::Div_par_K_Grad_par` is working? I happened to look at it, and the loop is over `"RGN_ALL"` where I would expect `"RGN_NOBNDRY"`
https://github.com/boutproject/BOUT-dev/blob/ea2986bdbb250ce257290888150da53a8b11299b/src/mesh/fv_ops.cxx#L138

Last time the loop was written out as a nested loop (at 72f1ce2), the bounds were `xstart`/`xend` and `ystart`/`yend`
https://github.com/boutproject/BOUT-dev/blob/72f1ce2f88f55c19d0dbac9c274c6a9173b137b6/src/mesh/fv_ops.cxx#L118-L120

**Comment by d7919** [comment]
Yes, that's an error I think as we end up indexing out of bounds. This should use `RGN_NOBNDRY` I suspect. I think this was introduced in https://github.com/boutproject/BOUT-dev/commit/0ece38e22728f2b21bb6a5ad1bbf4cb0daefb2db. 

The logic at https://github.com/boutproject/BOUT-dev/blob/ea2986bdbb250ce257290888150da53a8b11299b/src/mesh/fv_ops.cxx#L144 looks a bit like it's guarding against going out of bounds but I don't think that's actually what's happening.

**Comment by ZedThree** [comment]
Fixed in #1434
