### ISSUE TITLE
y-guards included in FFT DDZ intentionally?

### ISSUE THREAD

**Issue by loeiten** [boutproject/BOUT-dev#143]
When calculating `g=DDZ(f)` using the FFT method, I find that the ghost cells in `y` of `g` is alway set, whereas the ghosts in `x` remains unspecified. Are the `y`-ghost calculated every time intentionally?

In `src/sys/derivs.cxx` under `const Field3D DDZ(const Field3D &f, CELL_LOC outloc, DIFF_METHOD method, bool inc_xbndry)` I see that I can set `inc_xbndry` to calculate the `x` ghost cells as well, but I see no way to not calculate the ghost in `y` due to the for loop

``` c++
for(int jy=0;jy<mesh->ngy*(xlt-xge);jy++) {
  rfft(f[xge][jy], ncz, cv);
  ...
}
```

If it is not intentionally it is maybe not that serious, but is a (small) source of extra unnecessary calculation.

**Comment by bendudson** [comment]
I think this was probably intentional, for calculating mixed Y-Z derivatives without having to set boundaries or communicate in Y. It would probably be best to add a flag or switch of some kind to specify whether it should include the Y boundaries as done for the X boundaries.

**Comment by dschwoerer** [comment]
This seems to have changed since 2016 and can be closed.
See https://github.com/boutproject/BOUT-dev/blob/master/src/mesh/index_derivs.cxx#L1377
