### ISSUE TITLE
Non-fourier Delp2

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#1435]
It would be helpful to provide a Delp2 implementation that does not depend on using fft's or the Laplace tridiagonal coefficients. 

Would this be `Laplace_perp`, is `Delp2` just `Laplace_perp` with some assumptions?

**Comment by johnomotani** [comment]
> Would this be Laplace_perp, is Delp2 just Laplace_perp with some assumptions?

Nearly but not quite... `Laplace_perp(f) = Laplace(f) - Laplace_par(f)`; that means it includes some y-derivative terms that are dropped/neglected in Delp2. I agree it would be helpful to have a non-fft version of Delp2. It's needed for testing, e.g. in `test-multigrid_laplace`
https://github.com/boutproject/BOUT-dev/blob/ea2986bdbb250ce257290888150da53a8b11299b/tests/integrated/test-multigrid_laplace/test_multigrid_laplace.cxx#L278-L287

**Comment by d7919** [comment]
Thanks, that was what I thought. I didn't realise that routine existed in the tests -- I'm happy to port that to `Delp2` in the library if it would be useful.

**Comment by johnomotani** [comment]
I guess we need to keep the existing behaviour of `Delp2` for backward compatibility. So is it better to:
1. Have a new function. Downside is that then we have 3 functions for different implementations/approximations of the same operator, which is confusing.
2. Add the functionality to one of the existing functions with some arguments.

I'm inclined to suggest going for 2, but implement by adding an option to `Laplace_perp` like `neglect_y_derivatives`. While we're at it we could add a slightly more optimized implementation of the full `Laplace_perp` (the current one, for example, calls `D2DY2` twice, once in `Laplace` and once in `Laplace_par`). So something like:
```
const Field3D Coordinates::Laplace_perp(const Field3D &f, CELL_LOC outloc, bool neglect_y_derivatives) {
  TRACE("Coordinates::Laplace( Field3D )");
  ASSERT1(location == outloc || outloc == CELL_DEFAULT);

  Field3D result = G1 * ::DDX(f, outloc) + G3 * ::DDZ(f, outloc) + g11 * D2DX2(f, outloc) +
                   g33 * D2DZ2(f, outloc) +
                   2.0 * (g12 * D2DXDY(f, outloc) + g13 * D2DXDZ(f, outloc) + g23 * D2DYDZ(f, outloc));
  if (!neglect_y_derivatives) {
    result +=  (G2 - DDY(J / g_22, outloc)) * ::DDY(f, outloc) + (g22 - 1./g_22) * D2DY2(f, outloc);
  }

  ASSERT2(result.getLocation() == f.getLocation());

  return result;
}
```

and then update `Laplace_perp` in `src/mesh/difops` to call the implementation in `Coordinates`, and similarly for `Field2D`.

**Comment by d7919** [comment]
Yes I agree, although I would probably put the flag onto `Delp2` (`use_fft` or similar) -- that way `Delp2` and `Laplace_perp` always mean the same thing no matter the inputs (I don't mean `Delp2==Laplace_perp`).

**Comment by johnomotani** [comment]
@d7919 agreed: putting the flag on `Delp2` so `Delp2` doesn't have y-derivatives and `Laplace_perp` always does makes a lot of sense.
