### ISSUE TITLE
Unreachable shiftZ in ShiftedMetric

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#1437]
The `shiftZ(const Field3D &f, const Field2D &zangle)` method of `ShiftedMetric` is private, so unreachable from outside `ShiftedMetric`, and not used anywhere in `ShiftedMetric`. The `shiftZ(const BoutReal *in, int len, BoutReal zangle, BoutReal *out)` method is also private and I think only used in the implementation of `shiftZ(Field3D,Field2D)`.

It looks like `shiftZ(Field3D,Field2D)` was intended to be a public method/function. It doesn't depend on `zShift` or any other internals of `ShiftedMetric`. Should it be moved out of `ShiftedMetric` and kept as a free function in `field3d.cxx`?

https://github.com/boutproject/BOUT-dev/blob/ea2986bdbb250ce257290888150da53a8b11299b/src/mesh/parallel/shiftedmetric.cxx#L179-L214

**Comment by d7919** [comment]
Yes, I think this was probably there as an initial thought as to how to replace the free function. Do we want/need a routine to explicitly do `shiftZ` on a field or do we expect this to only ever be done through the parallel transform?

**Comment by ZedThree** [comment]
I'm in favour of removing them, unless anyone can come up with a use-case. They would be trivial to reimplement in the future if we changed our minds.
