### ISSUE TITLE
copy of unintialised field fails at run time

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#145]
Field3D a;
Field3D b=a; // segfault

Expected result:
a) throw BoutException
b) ignore (don't copy, as there is nothing to copy)

I'm not sure what would be the better solution.

**Comment by bendudson** [comment]
I can't reproduce this. Running the code:

#include <bout.hxx>
int main(int argc, char** argv) {
  BoutInitialise(argc, argv);

  Field3D a;
  Field3D b = a;

  BoutFinalise();
  return 0;
}

I get 

terminate called after throwing an instance of 'BoutException'
====== Back trace ======
 -> Field3D: Assignment from Field3D
  what():  Field3D: Operation on empty data

Is CHECK disabled in your test?

**Comment by dschwoerer** [comment]
Your right, CHECK was disabled.
Sorry for the inconvinince.
