### ISSUE TITLE
Deprecate invert_laplace free functions?

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#1452]
There's a comment above the `invert_laplace()` functions saying:
https://github.com/boutproject/BOUT-dev/blob/b30d255341fc7544ae56ba91e4c792c2e6df68b8/include/invert_laplace.hxx#L237-L238
`laplace_tridag_coefs` is still used in `Delp2()` and some boundary conditions, so we probably need to keep that, but can we remove/deprecate the `invert_laplace()` free functions?

**Comment by bendudson** [comment]
I'm in favour of deprecating them for now, then removing them in the next release

**Comment by ZedThree** [comment]
Deprecated in #1453
