### ISSUE TITLE
error in calculus.py

### ISSUE THREAD

**Issue by rheinonen** [boutproject/BOUT-dev#1477]
In function deriv2D in calculus.py, N should be cast as an int on line 109. Otherwise, old_div may return a float, and so an exception is thrown when N-1 is used as an index.

**Comment by bendudson** [comment]
Thanks for this bug report! I've made a PR #1478 which I think fixes the problem, at least in the `next` branch. I'll make another patch for the `master` branch.

**Comment by ZedThree** [comment]
Fixed in #1479
