### ISSUE TITLE
Finalising PETSc. Warning: Instances of PetscLib still exist.

### ISSUE THREAD

**Issue by loeiten** [boutproject/BOUT-dev#148]
I get the following warning from [petsclib.cxx](https://github.com/bendudson/BOUT/blob/master/src/sys/petsclib.cxx) while using PETSc:

```Finalising PETSc. Warning: Instances of PetscLib still exist.```

Am I'm somehow using PETSc in the wrong way?
I'm creating an instance (only one) in ```myCode::init(bool restarting)```, setting the coefficents with ```->setCoefX``` for each timestep in ```myCode::rhs(BoutReal t)```, and I'm using the ```user``` preconditioner.

**Comment by bendudson** [comment]
I guess this is because the solver is not being deleted, so when the code exits there is still a solver using PETSc.

If you define a destructor myCode::~myCode() and in there delete the solver you created in myCode::init(), do you still get this error?

**Comment by loeiten** [comment]
Deleting the solver worked.
Thank you for the help :)
