### ISSUE TITLE
Compile during configure

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1488]
I tried to configure with `--with-sundials=... ` on marconi (with -mtune=skylake --host skl, see manual), but that fails with:
```
checking for /marconi/home/userexternal/dschwoer/local/sundials//include/sundials/sundials_config.h... configure: error: cannot check for file existence when cross compiling
```
I could easily add the -mtune=skylake etc after configure, but then part of the library will not have AVX512 enabled.

I guess the easiest way would be to make sure that pvode is compiled after configure, like the rest is.
Is there a reason why this is done at configure time?

**Comment by ZedThree** [comment]
This should work with CMake?

**Comment by ZedThree** [comment]
`configure` is deprecated in 5.0
