### ISSUE TITLE
test-solver fails with petsc 3.6.4

### ISSUE THREAD

**Issue by bshanahan** [boutproject/BOUT-dev#1516]
the integrated test "test-solver" fails with PETSc v3.6.4:

./runtest 
getmpirun: using the default mpirun -np
Making solver test
Running solver test
Traceback (most recent call last):
  File "./runtest", line 15, in <module>
    status, out = launch_safe("./test_solver", runcmd=MPIRUN, nproc=nproc, mthread=nthreads, pipe=True)
  File "/home/brendan/BOUT-4/tools/pylib/boututils/run_wrapper.py", line 275, in launch_safe
    (s,command,out))
RuntimeError: Run failed with 1.
Command was:
./test_solver

Output was

Removed 'power' eigen solver
Removed 'snes' eigen solver

Testing the following solvers:
  euler
  imexbdf2
  karniadakis
  petsc
  pvode
  rk3ssp
  rk4
  rkgeneric

LOCALE_PATH = '/usr/local/share/locale'
Testing euler solver: PASSED
Testing imexbdf2 solver: PASSED
Testing karniadakis solver: PASSED
Testing petsc solver: FAILED
Testing pvode solver: PASSED
Testing rk3ssp solver: PASSED
Testing rk4 solver: PASSED
Testing rkgeneric solver: PASSED

 => Some failed tests

    petsc got: 0.781449, expected: 0.785398
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[10668,1],0]
  Exit code:    1
--------------------------------------------------------------------------

**Comment by ZedThree** [comment]
Can you try with PETSc 3.9? 3.6 is about the version where it actually starts to work properly

**Comment by bshanahan** [comment]
@ZedThree Works with 3.9.4

**Comment by ZedThree** [comment]
Does your PETSc 3.6 have SUNDIALS support? According to the summary of my testing in #1050, 3.6 should work out of the box, but I don't think I had it compiled with SUNDIALS, in which case it would use BDF by default, which I've not tested.

**Comment by bshanahan** [comment]
I do not have sundials support in 3.6.4

**Comment by ZedThree** [comment]
Should be fixed in both master and next now, fix was: https://github.com/boutproject/BOUT-dev/pull/1627/commits/f1e44db813e217072beea78b8c9d69097e0f9d0b
