### ISSUE TITLE
Testcases

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#152]
I had a look at test-staggered in the example folder.
Am I right that the test does never return an error (unless matplotlib / etc. is missing)?

If I have a file `runtest`, I expect, if I call it, it will tell me if the result is wrong. Though I couldn't find some where that checks this.
In this case, the graphs for staggered and not staggered look different - is this correct behaviour?
[test_staggered.pdf](https://github.com/boutproject/BOUT-dev/files/100891/test_staggered.pdf)

Anyway, that `runtest` does not check for errors is not unique to this `test`, and I have fixed some in pr #150 

I think all tests should be checked whether they
- are real tests
- if not:
  - upgrade them
  - or, if not possible, rename them

**Comment by d7919** [comment]
I think there are (at least) two classes of test included in examples. There are some which provide a quantitative check (against regressions for example) and other which provide a more qualitative comparison. Only the first type should be included in `test_suite` whilst the second type are sometimes used to test things by eye that are not easily automated (for example comparing solutions on different grids) or to serve as an example for *how to test* a specific technique, they are also sometimes used to demonstrate a difference between two approaches (as is happening in this case I think) so it's not easy to implement a quantitative check here to verify that two approaches are "indeed different in the correct way".

Possibly we should group the regression tests in a specific location to make this clear?

**Comment by dschwoerer** [comment]
I think that's what I meant. If it is possible to check e.g. for convergence, do that in a script called runtest, othterwise if it can be only interpreted with sufficent experience, and therefore not automatic, rather call it runexample.

That way i could run all ./runtest files before I submit, to reduce my chances of introducing a bug somewhere.

In this case, renaming test-staggered to staggered would help clarify it.

Maybe it would also make sense to split the examples folder in a test folder and an example folder?
The test folder would include checks which can be automated, but are maybe not included in the test_suite (e.g. MMS/GBS) - but it would be easy to run them all, if the computer is sufficiently fast.

**Comment by d7919** [comment]
Maybe we could extend `test_suite` to take an argument (e.g. `full=True`) which flags to expand the list of tests to include a full set? That way we are clearly defining which tests are part of the test suite and which are essential parts and which are optional.

**Comment by bendudson** [comment]
Certainly renaming and organising the tests and examples would be good. There are examples of methods/techniques, and there are tests. There are also examples which are also tests, such as the interchange and resistive drift wave tests run at the end of test_suite. 

I would certainly be in favor of renaming test-staggered to staggered, and keeping the test prefix for things which are actually tests. 

The runtest vs runexample suggestion also makes a lot of sense

-------- Original Message --------

**Comment by ZedThree** [comment]
This is part of the "test push" campaign/project for 4.1.
