### ISSUE TITLE
Parallelisation fails even on one processor

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#1537]
Reproduce with MWE:

```
#include <bout/physicsmodel.hxx>

class MWE : public PhysicsModel {
public:
  int init(bool restarting) {
    solver->add(f, "f");
    return 0;
  }
  int rhs(BoutReal time) {
    mesh->communicate(f);
    ddt(f) = 0.0;
    return 0;
  }
private:
  Field3D f;
};

BOUTMAIN(MWE);

```
using an input file containing

```
MZ = 1

MXG = 2
MYG = 2

[mesh]
ny = 1
nx = 8 + 2*MXG
```

Running with `mpirun -np 1 ./mwe` leads to the following error:

```
Finding value for NXPE (ideal = 2.828427)
	Candidate value: 1
	 -> ny/NYPE (1/1 = 1) must be >= MYG (2)
Error encountered during initialisation: Could not find a valid value for NXPE. Try a different number of processors.
terminate called after throwing an instance of 'BoutException'
  what():  Could not find a valid value for NXPE. Try a different number of processors.
```

This indicates that we can't find a good decomposition, which is a bit surprising as we only have one processor. I'm not sure I understand why this check (`ny/NYPE >= MYG`) is required -- I guess it's because in this situation filling in the guard cells in one direction would require communication with more than one processor (or some order to be imposed on the communication). However here all the guard cells are (at least in some sense) boundary cells so this shouldn't pose the same issue I think.

**Comment by bendudson** [comment]
This check is indeed so that guard cells could be filled. The check `ny/NYPE >= MYG` should probably (I think) only be used when `NYPE > 1`.
