### ISSUE TITLE
gtest-all.o is compiled without BOUT_FLAGS

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1560]
We put `-fPIC` into `BOUT_FLAGS`, but gtest-all.o is compiled without.
Thus linking fails, with `-specs=/usr/lib/rpm/redhat/redhat-hardened-ld` - as it tries to produce a PIE executable.

Is there a reason gtest-all is compiled without?

This is in the 4.2.1 release

**Comment by ZedThree** [comment]
Fixed in #1573
