### ISSUE TITLE
Hard coded variables in Petsc time stepper

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#157]
In the various PETSc time stepper implementations there are variables hard coded for a specific test case (search advect1d). For example see [here](https://github.com/boutproject/BOUT-dev/blob/master/src/solver/impls/petsc-3.4/petsc-3.4.cxx#L412).

This could potentially lead to issues or sub-optimal performance. In addition this could make the code somewhat confusing, even if this section isn't active in a particular setup.

**Comment by bendudson** [comment]
The various petsc timesteppers really need 

1) consolidating into a smaller number of implementations, using ifdefs where needed for different APIs

2) updating to the newer version. It looks like the petsc timestepper capabilities have improved significantly since the current code was written. No doubt the API has also changed


-------- Original Message --------

**Comment by d7919** [comment]
Yes I agree, this is actually why I came across this -- I was thinking about rewriting the PETSc solver(s) both to cut down on repeated code and to offer access to newer features.

Is there a consensus on what the oldest version of PETSc we wish to support is?

I was thinking of trying to move to a model where there is a generic PETSc solver which defines virtual functions for each of the logical PETSc steps. My vague idea was that to add support for a particular version, let's say 3.4,  we create an impl which inherits from this generic sovler, overriding any of the virtual functions for which the API has changed. Then to add a newer version, let's say 3.5, we can then inherit from the 3.4 impl, and hence only have to redefine any of the logical steps where the API has changed. 

I've not got far through the design yet so I'm not sure if this is a good approach or not. The main advantages I can see are that it should cut down on a lot of repeated code and adding a new version is pretty much limited to the minimal amount of code that needs to be redefined in order to match the new API.

**Comment by bendudson** [comment]
The alternative is to have PETSC_VERSION_GE macros scattered around the code for choosing between different APIs. I've added a fall-back implementation in the petsc-version branch. I'm not sure what the best approach would be. The trouble with the virtual function approach might be that it's difficult to predict which bits will change, and sometimes it's the data structures which appear/change/disappear, not just the function calls

-------- Original Message --------

**Comment by d7919** [comment]
Yes, the change of objects is perhaps the biggest headache. 

I'll try to have a look into prototyping something to do this using the different approaches. Is it reasonable to drop support for petsc<3.4 or should I aim for maintaining support right back to 3.1?

**Comment by bendudson** [comment]
Yes, I think 3.4 is old enough. But then that's the version on my laptop (Debian). Archer has 3.5 and 3.6. Anyone need anything older?

-------- Original Message --------

**Comment by ZedThree** [comment]
Fixed in #1050
