### ISSUE TITLE
Check that the manuals are building

### ISSUE THREAD

**Issue by loeiten** [boutproject/BOUT-dev#159]
- [X] `figs/boutmesh-comms.pdf` is missing in the manual.
- [ ] Should we maybe also have the manuals as ready-made pdfs in the `manual` folder in case people do not have the proper TeX tools to build the manuals?

**Comment by bendudson** [comment]
I'm reluctant to include more binaries in the repository, as they don't tend to diff or compress well. Better might be to just update the manual online more frequently. I've put the latest version on the documentation page here: http://boutproject.github.io/doc.html

**Comment by loeiten** [comment]
That makes sense :).

The ```make``` in the manual section works again. However, when I'm trying to access http://www-users.york.ac.uk/~bd512//bout/user_manual.pdf (typo with two ```//```?) from http://boutproject.github.io/doc.html, I'm getting

```
Sorry, you are not allowed to view this file [Error: 403]

Access to this file has been restricted and you are not allowed to view it.
```

The same happens with http://www-users.york.ac.uk/~bd512/, where I've been able to connect to before. I've tried on different connection, with the same result. Did something change with the york pages?

**Comment by JensMadsen** [comment]
Er du ikke til turbulence group meeting? :-D

Jens Madsen
PPFE, DTU Physics
Denmark
________________________________

**Comment by d7919** [comment]
There is also the possibility of getting Travis to include building the manual as part of the commit tests. It would also be possible to get this to upload the generated file somewhere.

There's an example [here](http://blog.gockelhut.com/2014/09/automatic-documentation-publishing-with.html), though this commits the manual through git we could always try something else (or add a separate repo to track the pdf?).

**Comment by ZedThree** [comment]
The manuals are now built automatically on readthedocs: http://bout-dev.readthedocs.io/en/latest/
