### ISSUE TITLE
iteration over inner and outer Y boundaries

### ISSUE THREAD

**Issue by nick-walkden** [boutproject/BOUT-dev#162]
At present when the mesh->iterateBndryUpper/LowerY()  function is called in double null geometry it iterates over both the inner and outer boundaries. In some cases the user may wish to limit iteration to just the inner upper/lower or the outer upper/lower boundaries. My proposal is to add the following functions to the boutmesh class

iterateBndryUpperInnerY() 
iterateBndryUpperOuterY() 
iterateBndryLowerInnerY() 
iterateBndryLowerOuter()

These functions should have a similar functionality to the current  iterateBndryUpper/LowerY() functions with an additional check on ny_inner to establish whether the boundary is outer or inner. One implication is that the RangeIterator returned if the boundary is not in the processor should now be null which would prevent iteration over the boundary, rather than just allow iteration over the guard cells (which will have no effect after communications). 

Finally with the additional functions above, the   iterateBndryUpper/LowerY() functions could then just return 

iterateBndryUpperInnerY()  + iterateBndryUpperOuterY() 

This should ensure backward compatibility and avoid breaking any code. There is a possibility that this may cause an issue if an iteration over the guard cells of a non-boundary containing processor is required by using the above functions (though this seems like an odd use of the boundary iteratory). Does this happen in BOUT?

**Comment by d7919** [comment]
These routines have been added so I think this issue should be closed. Also see #734
