### ISSUE TITLE
sundials 2 is old

### ISSUE THREAD

**Issue by wphu** [boutproject/BOUT-dev#1644]
sundials 2 is old, could support new sundials version?

**Comment by ZedThree** [comment]
I've made a start on this. Getting SUNDIALS 3 working was not too bad, version 4 has changed quite a lot of the interface but I should hopefully have a PR ready to go tomorrow

**Comment by wphu** [comment]
@ZedThree, got the situation, nice job.

**Comment by ZedThree** [comment]
SUNDIALS versions > 2.6 now supported in `next`
