### ISSUE TITLE
Possible bug in Boutmesh::addBoundaryRegions?

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#1656]
Am I being dim, or should the y-indices be `yend, LocalNy - 1`? All the `RGN*_UPPER_Y` regions are similar -- copy-paste error?

https://github.com/boutproject/BOUT-dev/blob/1c8d7699c096a98dd28af393bd1ac32e4ffec6af/src/mesh/impls/bout/boutmesh.cxx#L2219-L2222

I think these are only important if the boundaries are evolved, and I guess we don't do that very often

**Comment by d7919** [comment]
Looks like copy-paste to me.

**Comment by bendudson** [comment]
Yes agreed, these should be different from the `LOWER` regions. Good spot!
