### ISSUE TITLE
Crashes in unit tests due to mpark variant

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1665]
I tried to run the unit tests with mpark variant packaged by fedora (1.3.0) - and after fixing that the unit tests checked out mpark, I got illegal instruction error when running the unit tests.

With 1.4.0 I get a segmentation fault.

The default version works fine.

My question is, should the other versions work as well?

**Comment by ZedThree** [comment]
Works for me with mpark commits 2931971 (1.3), 4988879 (1.4) and 0b488da (current master).
I've also tried the single header version from the 1.3 release.

So, yes, it should work with any version -- actually, just tried e1ddb34, (1.1.0) and that's the earliest that worked for me, so anything v1.1.0+ should work.

Can you check against the github version, or check if fedora are doing something weird to the source files?

**Comment by dschwoerer** [comment]
I have tried both the version in fedora, and 1.4 from upstream, as well as 1.3 from upstream, directly checking it out in the sub-module.

I tried to reproduce it now, with current next, but it worked without issues, so it seems whatever caused this, was fixed in next ...
