### ISSUE TITLE
tests/integrated/test-squash - corner cells are nan

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1680]
The issue is that the tests compares whether the fields are the same.

Here `dx` is causing issues. The fields are the same, but `nan != nan` by design.
So the naive approach fails to compare.

Is it intended that `dx` corner cells are `nan`?
If so, I can filter them out ...

Output of test:
```
  5.21405983s make
  0.13965154s ./squash -q -q -q nout=2
  0.04966664s mv data/BOUT.dmp.0.nc f1.nc
  0.00384355s rm -f f2.nc
getmpirun: using the default mpirun -np
  0.10781288s ./squash -q -q -q nout=2
  0.83071661s ../../../bin/bout-squashoutput -qdcl 9 data --outputname ../f2.nc
  0.05857587s verify f1.nc f2.nc
Traceback (most recent call last):
  File "./runtest", line 78, in 
    verify("f1.nc", "f2.nc")
  File "./runtest", line 64, in verify
    raise RuntimeError("data mismatch in ", v, err, d1[v], d2[v])
RuntimeError: ('data mismatch in ', 'dx', '(0, 0): nan != nan\n(0, 3): nan != nan\n(3, 0): nan != nan\n(3, 3): nan != nan\n', BoutArray([[nan,  1.,  1., nan],
           [ 1.,  1.,  1.,  1.],
           [ 1.,  1.,  1.,  1.],
           [nan,  1.,  1., nan]]), BoutArray([[nan,  1.,  1., nan],
           [ 1.,  1.,  1.,  1.],
           [ 1.,  1.,  1.,  1.],
           [nan,  1.,  1., nan]]))
```

**Comment by johnomotani** [comment]
> Is it intended that dx corner cells are nan?

This is the expected behaviour since the changes I made in #1646. I think it makes sense as corner guard cells shouldn't be relied on anyway...

**Comment by dschwoerer** [comment]
Must have missed that part of the PR

Should that be reflected in the documentation?

Do you want to fix the test?

**Comment by johnomotani** [comment]
I think it makes sense for the test just to ignore the corner guard cells.

@ZedThree is there somewhere I should update the manual?

**Comment by dschwoerer** [comment]
Yes, I think as well the corner cells should be ignored :-)

If just been wondering whether you wanted to fix the test, as you broke it, or whether I should do it ... no strong preference ether way ...

**Comment by johnomotani** [comment]
I'll get it! Sorry, I'd read too quickly and assumed this was a comment on a PR where you were already working on test-squash... PR coming in a min :+1:

**Comment by dschwoerer** [comment]
No, I had fixed Yesterday, and was confused that it failed today :sweat_smile: 

Thanks for fixing :+1:
