### ISSUE TITLE
Make check failed: 'ascii' codec can't decode

### ISSUE THREAD

**Issue by aeiou6630** [boutproject/BOUT-dev#1700]
Dear all,

I run BOUT++ on TSCC (Triton Shared Computing Cluster) in UCSD, California, USA. I followed the steps of installation and finished up to the "make" step. However, when running the "make check" step, it shows error when check-integrated-tests.

Here are the steps I took:
(1) `cd BOUT-dev`
(2) `module unload intel` 
(3) `module load gnu openmpi_ib fftw hdf5 python`
(4) `export PYTHONIOENCODING=utf-8`
(5) `make check`

And then it showed the error message:

  **File "./test_suite", line 112, in <module>
    req_met, req_expr = requirements.check("./runtest")
  File "../requirements/requirements.py", line 73, in check
  File "/opt/python/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 560: ordinal not in range(128)
make: *** [check-integrated-tests] Error 1**

I don't understand what it means. I attach the files including:
(1) make.config: from /BOUT-dev
(2) runtest: from /BOUT-dev/tests/integrated/test-code-style
(3) TextPrinted.txt: the text printed after I did the "make check"

Here's the link:
[MakeCheckFailed_TSCC_v1.zip](https://github.com/boutproject/BOUT-dev/files/3129796/MakeCheckFailed_TSCC_v1.zip)

Please help me on this if possible. Thanks!

**Comment by dschwoerer** [comment]
This error does not seem to be specific about BOUT++, but rather it seems python is ignoring the utf8 encoding.
Does `python3 -c "print(chr(246), chr(9786), chr(9787))"` return 'ö ☺ ☻'?

If that doesn't work, try to fix that issue first ...

Otherwise, to debug this, I think we would need ether access to the system, or more details about the system ...

**Comment by aeiou6630** [comment]
Thanks a lot for your reply. 

I've checked that the command you mentioned correctly produced the characters you showed on our system. So I guess it's more like a problem specific to our system. I'll ask the maintainer of TSCC first to see if there's constructive advice, and reply here.

Thank you again.

**Comment by aeiou6630** [comment]
Hi,

I asked the maintainer, who told me to add the following commands before `make check`.

`export LANGUAGE=en_US.UTF-8`
`export LC_ALL=en_US.UTF-8`
`export LANG=en_US.UTF-8`
`export LC_TYPE=en_US.UTF-8`

Now the problem is solved. 
Thank you!
