### ISSUE TITLE
"x + y + z + 3" as int

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1701]
If the expression `x + y + z + 3` is parsed as an int - I thought it should fail, because the location is not known.

However, the current behaviour, is to return 3, and set all variables to zero.

Do we want to keep the current behaviour?

**Comment by bendudson** [comment]
Yes, the default is to assume x=y=z=0 when evaluating scalars e.g. https://github.com/boutproject/BOUT-dev/blob/next/src/sys/options.cxx#L219 
Some possibilities would be to:
 - Have a generator property, something like `constant`, which is true for numbers etc. but false for `x`, `y`,`z`,`t`. When creating a generator the dependencies are known, so this property could be tracked. Some overhead in creation, and more boilerplate code in the generators
- A simpler way would be to just evaluate the value at a few different locations, and compare the result. This has a small runtime overhead, but would be quite simple to implement.

**Comment by dschwoerer** [comment]
I am currently rewriting part of this, which would make it quite easy to throw if x is used in a const expression - I just wasn't sure whether we want to keep the old behaviour, or whether it is fine to have a breaking change ...

I will implement it now to keep it as is, this way we will be able to first enable warnings, and later throw ...

**Comment by ZedThree** [comment]
We have something in now that deals with this, and we can deal with `x, y, z` at staggered locations. Except... I think we're still missing some bits. `FieldFactor::create*D` takes a `CELL_LOC` argument, but `GridFromOptions::get` doesn't pass the location argument.

If I change it to do so, this ends up causing problems with `getAtLoc` in `coordinates.cxx` due to the interpolation. I'm not 100% sure what's going on yet.

**Comment by johnomotani** [comment]
Ah, I never thought about creating the metrics from an input file when I was writing the staggered coordinates stuff! I agree passing location to `Mesh::get()` is the way to go. It should be easy to modify hypnotoad2 to include CELL_LOCATION attributes to its outputs, so `Mesh::get()` could check the locations of `dx_ylow`, etc. (if they are given in the grid file), as well as evaluate expressions at correct locations.
