### ISSUE TITLE
Hypnotoad: Bug in the computation of ShiftAngle

### ISSUE THREAD

**Issue by friva000** [boutproject/BOUT-dev#1729]
ShiftAngle is computed on line 306 of process_grid.pro as
`loop[xi] = f[xi,yi[N_ELEMENTS(yi)-1]] - f[xi,yi[0]]` i.e., it is computed as zShift(ix,y=yend)-zShift(ix,y=ystart), where ystart and yend are the first and the last points in the periodic (core) domain. However, ShiftAngle should be the integral from 0 to 2*pi of nu(psi,theta) [or from -pi to pi, or... nu is a periodic function in theta]. This means that in the computation of ShiftAngle there is an error of order dy, (ystart and yend are shifted by dy/2 from the boundaries of the domain).

This also affects the computation of zShift in setParallelTransform, since ShiftAngle is used to compute zShift in the y guard cells at the Branch cuts, which may be used to compute the field aligned fields at those point (useful for parallel derivatives and interpolation).

**Comment by bendudson** [comment]
Yes agree; this was changed at some point and did not take into account the last dy.
