### ISSUE TITLE
Communication of field aligned field at branch cut

### ISSUE THREAD

**Issue by friva000** [boutproject/BOUT-dev#1731]
When using `paralleltransform = shifted`, the `TwistShift` option must be false. This means that all fields are assumed y periodic in the core region. However, fields that are field aligned (for example obtained from calling the `toFieldAligned`) are not periodic in y. This means that, if a field aligned field is communicated, the guard cells of that field at the branch cut are wrong. 

Three possible solutions:
1) Always throw an exception if the user tries to communicate a field aligned field
2) Put NaNs in the guard cells at the branch cut 
3) Do not force `TwistShift = false` for `paralleltransform = shifted`, but discriminate between field aligned fields and fields in quasi-ballooning coordinates when communicating

**Comment by ZedThree** [comment]
Fixed in #1732
