### ISSUE TITLE
coordinates_type labels

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#1747]
The labels in `coordinates_type` are horrible at the moment. Maybe we should fix them before the 4.3 release?

At the moment:
1. `coordinates_type == orthogonal` means grid file has been generated for `ShiftedMetric` simulations - i.e. grid points are at (r,theta,phi) positions. We can also generate grids (e.g. with Hypnotoad) that use 'non-orthogonal' coordinates, meaning `g_xy != 0` but these can still be compatible with `ShiftedMetric`.
2. `coordinates_type == field_aligned` means grid file is compatible with `ParallelTransformIdentity` - i.e. field-aligned tokamak coordinates with integrated shear `I != 0` or slab, 2d drift plane, etc.
3. `coordinates_type == fci` means grid file is compatible with `FCITransform`

Maybe (1) should be renamed to `toroidal`?

**Comment by ZedThree** [comment]
D'oh! It's Friday afternoon, that's my excuse and I'm sticking to it.

Maybe just rename it "parallel_transform" and make it 1:1 with the
transforms?

**Comment by johnomotani** [comment]
Closed by #1756.
