### ISSUE TITLE
Wrong location for `Div_par_CtoL(Field3d)`?

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#1781]
In `Div_par_CtoL` we seem to create the result at `CELL_CENTRE` but I would have expected `CELL_YLOW` (similarly we get coordinates at the centre location as well). 

https://github.com/boutproject/BOUT-dev/blob/f454d2548fabf63112c5b3a0e7937b3dc9f9ade4/src/mesh/difops.cxx#L458

My guess is that this is just a simple copy-paste error, although the later loop does vary from the form in `Div_par_LtoC`.

**Comment by johnomotani** [comment]
@d7919 that is a bug, but I think there are more bugs in these methods... For example, in `Div_par_CtoL`, the expression `(var(jx, jy, jz) / metric->Bxy(jx, jy) - var.ydown()(jx, jy - 1, jz) / metric->Bxy(jx, jy - 1))` is giving a parallel gradient half way between the `(jx,jy)` cell-centre point and the point one step back along the magnetic field line, but if we're using `ShiftedMetric` a result at `CELL_YLOW` should be staggered half a point poloidally. This is the same issue as the normal staggered derivative operators that means we need to transform to fully field-aligned coordinates to do staggered derivatives.

I don't think we should support these `CtoL`/`LtoC` methods any more. Can we deprecate them and (for now) replace the bodies with standard derivative operators, e.g.
```
const Field3D Div_par_CtoL(const Field3D &var) {
  ASSERT1(var.getLocation(CELL_CENTRE);
  return Div_par(var, CELL_YLOW);
}
```
then remove the functions entirely in 5.0?

**Comment by ZedThree** [comment]
Looks like this is still an issue in v4.3.0? Are all of the `CtoL` and `LtoC` methods in `difops` deprecated?

**Comment by johnomotani** [comment]
> Looks like this is still an issue in v4.3.0? Are all of the CtoL and LtoC methods in difops deprecated?

I think they should be deprecated, but they're not marked as deprecated at the moment. I think it should be a fairly quick job to replace all the implementations as suggested in my comment above. Shall I make a PR doing that? I guess no one objects to removing the `CtoL`/`LtoC` methods, as there haven't been any comments asking for them to stay.

**Comment by ZedThree** [comment]
Go for it :) I'm happy to do it otherwise

**Comment by ZedThree** [comment]
Deprecated in #1822, will be removed in v5
