### ISSUE TITLE
Evaluation of nonlinear brackets

### ISSUE THREAD

**Issue by JosephThomasParker** [boutproject/BOUT-dev#179]
I've been doing Scalasca profiling of nonlinear simulations that use the `BRACKET_ARAKAWA` method (circa line 1400 in `src/mesh/difops.cxx`).  A lot of time is spent in repeatedly accessing the Field3D elements.

**Comment by d7919** [comment]
You might want to check out the code in my shiftztweak branch. I've included a slightly optimised version of this which can save a fair bit of time compared to the standard approach. Note this introduces the BRACKET_ARAKAWA_OPT method rather then replacing the existing one.

**Comment by bendudson** [comment]
Thanks Joseph! Is this improved in the "next" branch? There the indexing and back-end storage of data arrays has been improved, so it uses (x,y,z) rather than [x][y][z] and should be faster.

**Comment by JosephThomasParker** [comment]
Thanks - I'll have a look.  I found that accessing each value once at the start of each loop iteration halved the time spent in the function.  For the filaments problem I was looking at (in CCFE's version of the code), that amounted to 20% of the runtime.

**Comment by d7919** [comment]
Yes I think I ended up with similar gains, although for my problem the brackets accounted for a large part of the run time. My branch also contains an optimisation for the `zShift` code used in `shiftedXderiv` and `TwistShift` operations which gives a significant improvement to performance (YMMV), although with the changes upcoming in next I'm not sure if these changes will be required (hence why I've not merged these into master).

**Comment by dschwoerer** [comment]
I have also done a different implementation, in the branch https://github.com/dschwoerer/BOUT-dev/tree/fast_arakawa, which is faster if it uses a fast differentiation, e.g. https://github.com/dschwoerer/BOUT-dev/tree/fastdiff-cleaned ...
