### ISSUE TITLE
Region::unique returns new object

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#1792]
Very minor API "bug":  https://github.com/boutproject/BOUT-dev/blob/c87c8603adb7e462a556c47c44433e7f7c07d7fe/include/bout/region.hxx#L594-L598

Should probably return `Region<T>&` instead.

We could also mark `Region<T>::asUnique` with `[[nodiscard]]` to emphasise we should be doing something with _that_ return value. `[[nodiscard]]` is C++2a and not actually implemented in many compilers, but most compilers ignore unknown attributes (although _that_ is technically a C++17 feature!)

**Comment by bendudson** [comment]
Good catch! I guess the function did what it was supposed to, but had higher cost than needed.

**Comment by ZedThree** [comment]
I can't take the credit, it was MSVC surprisingly!
