### ISSUE TITLE
Proper way to copy a Field

### ISSUE THREAD

**Issue by loeiten** [boutproject/BOUT-dev#180]
What is the proper way of copying a field in BOUT++.

Let's say I have something like

```c++
Field3D a, b;

/*
 * Setting a to something here
 */
a = b;

// A function which changes the ghost cells of b
func(b);
```

As a result, also the ghost cell of `a` is changed in the above example. If I instead write

```c++
Field3D a, b;

/*
 * Setting a to something here
 */
a = 1.0*b;

// A function which changes the ghost cells of b
func(b);
```

The ghost cell of  `a` will not change, as the overloaded operator is returning a new `Field3D`.

The question is: What is the proper way to copy the contents of `a` into `b` without letting them point to the same address in memory?

**Comment by bendudson** [comment]
To ensure that b is unique, call

b.allocate();

I suggest that any function which modifies its inputs should call the allocate method to avoid these issues.

There is a copy() function:

b = copy(a);

Which is equivalent to

b = a;
b.allocate();

**Comment by loeiten** [comment]
Thanks, this worked perfectly :)
