### ISSUE TITLE
grid generator(hypnotoad) doesn't work

### ISSUE THREAD

**Issue by AlexLyash** [boutproject/BOUT-dev#1802]
Dear Developers,
The latest version of hypnotoad doesn't work for me. I guessed an old IDL version could be the reason for this. So I tried hypnotoad version from here https://github.com/bendudson/Hypnotoad.
It worked better in some way. I could generate a mesh, but when I try to output it, it sticks and constantly suggest me to smooth plasma parameters. Do you have any ideas how to solve this problem?

**Current hypnotoad version output:**

> IDL Version 7.1 (linux x86_64 m64). (c) 2009, ITT Visual Information Solutions
> Installation number: .
> Licensed for use by: IA-BAS
> 
> IDL> hypnotoad
> % Compiled module: HYPNOTOAD.
> % Compiled module: CW_FIELD.
> % Compiled module: XMANAGER.
> IDL> 
> Open G-eqdsk (neqdsk) file
> Trying to read file /home/alexey/BOUT-dev/tools/tokamak_grids/gridgen/efit/g014220.00200
> % Variable is undefined: READ_NEQDSK.
> % Execution halted at: EVENT_HANDLER     166
>    /home/alexey/2019_sep13_grid_script/BOUT-dev/tools/tokamak_grids/gridgen/h
>   ypnotoad.pro
> %                      WIDGET_PROCESS_EVENTS
> %                      $MAIN$          

**Outdated hypnotoad version output:**

> IDL> 
> Open G-eqdsk (neqdsk) file
> Trying to read file /home/alexey/BOUT-dev/tools/tokamak_grids/Hypnotoad-master/g014220.00200
> % Compiled module: READ_NEQDSK.
> % Compiled module: STRSPLIT.
>    nxefit =       65 nyefit =       65
> % Compiled module: NEXT_DOUBLE.
> % Compiled module: REGEX_EXTRACT.
> % Compiled module: READ_1D.
> % Compiled module: READ_2D.
>          149          37
> Successfully read equilibrium
> % Compiled module: ANALYSE_EQUIL.
> % Compiled module: DIFF.
> % Compiled module: CONTOUR_LINES.
> % Compiled module: LINE_CROSSINGS.
> 
> Number of critical points:          14
> Critical point 0
>    X-point
> % Compiled module: STR.
>    Starting index: 19, 14
>    Refined  index: 18.4501, 13.5504
>    Position: 0.61926941, -1.1530979
>    F = 0.0234576
> Critical point 1
>    O-point
>    Starting index: 4, 17
>    Refined  index: 3.74214, 16.4852
>    Position: 0.17343371, -0.96967506
>    F = 0.0339272
> Critical point 2
>    X-point
>    Starting index: 18, 51
>    Refined  index: 18.0530, 50.0747
>    Position: 0.60723259, 1.1296709
>    F = 0.0249633
> Critical point 3
>    O-point
>    Starting index: 4, 48
>    Refined  index: 3.83515, 47.4524
>    Position: 0.17625307, 0.96577621
>    F = 0.0343002
> Critical point 4
>    O-point
>    Starting index: 15, 4
>    Refined  index: 14.2885, 3.85607
>    Position: 0.49312076, -1.7589958
>    F = -0.00326002
> Critical point 5
>    O-point
>    Starting index: 14, 61
>    Refined  index: 13.7170, 60.3398
>    Position: 0.47579535, 1.7712357
>    F = -0.00274556
> Critical point 6
>    O-point
>    Starting index: 29, 32
>    Refined  index: 28.1561, 31.8239
>    Position: 0.91348124, -0.011006355
>    F = -0.0463324
> Critical point 7
>    X-point
>    Fitted location deviates too much
>    => X-point probably not valid
>    Starting index: 4, 32
>    Refined  index: 2.84826, 31.1422
>    Position: 0.14633773, -0.053610921
>    F = 0.0314377
> Critical point 8
>    O-point
>    Starting index: 48, 50
>    Refined  index: 47.8507, 49.5377
>    Position: 1.5104745, 1.0961037
>    F = 0.157723
> Critical point 9
>    X-point
>    Starting index: 54, 45
>    Refined  index: 54.0353, 44.5346
>    Position: 1.6979447, 0.78341150
>    F = 0.105277
> Critical point 10
>    O-point
>    Fitted location deviates too much
> % Compiled module: CLOSEST_LINE.
>    Starting index: 53, 41
>    Refined  index: 53.0480, 40.3641
>    Position: 1.6680169, 0.52275634
>    F = 0.132400
> Critical point 11
>    O-point
>    Starting index: 54, 24
>    Refined  index: 53.0163, 23.8297
>    Position: 1.6670573, -0.51064229
>    F = 0.132061
> Critical point 12
>    X-point
>    Starting index: 55, 20
>    Refined  index: 54.3523, 19.4008
>    Position: 1.7075547, -0.78744864
>    F = 0.103692
> Critical point 13
>    O-point
>    Fitted location deviates too much
>    Starting index: 49, 15
>    Refined  index: 48.0387, 14.5275
>    Position: 1.5161722, -1.0920283
>    F = 0.159647
> Number of O-points: 9
> Number of X-points: 5
> Primary O-point is at 0.91348124, -0.011006355
> 
> Keeping x-points        0       1       2       3       4
> % Compiled module: SAFE_COLORS.
> % Compiled module: INTERPOL.
> % Compiled module: CRITICAL_BNDRY.
> % Compiled module: OPLOT_CRITICAL.
> IDL> 
> Write output file
> ERROR: Need to generate a mesh first
> IDL> 
> % Compiled module: CREATE_GRID.
> Checking settings
> % Compiled module: STR_CHECK_PRESENT.
>   rad_peaking not specified. Setting to 0.00000
>   pol_peaking not specified. Setting to 0.00000
> Calculating DCT...
> % Compiled module: DCT2DSLOW.
> Finished DCT
> % Compiled module: RESTRICT_PSI_RANGE.
> X-point locations: 
>   0: 1.00000
>   1: 1.02158
>   2: 1.11434
>   3: 2.14966
>   4: 2.17237
> Number of x-points in range: 2
> 
> Refining x-point locations...
>   0: (18.4501, 13.5504) 0.0234576
> % Compiled module: REFINE_XPOINT.
> % Compiled module: LOCAL_GRADIENT.
> % Compiled module: EVALCOSPFAST.
>    -> (18.4755, 13.5388) 0.023453932
>   1: (18.0530, 50.0747) 0.0249633
>    -> (18.1672, 50.1123) 0.024961943
> Primary X-point is number 0
>    at R = 0.61926941 Z = -1.1530979
> Distributing radial points automatically
> % Compiled module: RADIAL_GRID.
> Keeping same inner psi for all regions
> Keeping same outer psi for all regions
> % Compiled module: OPLOT_CONTOUR.
> % Compiled module: DERIV.
> % Compiled module: REVERSE.
> Finding theta location of x-point 0
> % Compiled module: LEG_SEPARATRIX.
> % Compiled module: EVALCOSP.
> % Compiled module: THETA_DIFFERENTIAL.
> % Compiled module: THETA_LINE.
> % Compiled module: FOLLOW_GRADIENT.
> % Compiled module: FFT_INTERP.
> % Compiled module: REAL_PART.
> Finding theta location of x-point 1
> % Compiled module: INT_TABULATED.
> % Compiled module: UNIQ.
> Generating sol psi:       1.02158      1.10000
> Generating sol psi:       1.02158      1.10000
> % Compiled module: INT_FUNC.
> PSI     0.900000    0.0164786
> % Compiled module: MEAN.
> % Compiled module: MOMENT.
> START:(0.0563284, 0.0625677, 0.0624060, 0.0491728) -> (0.011735953, 0.0095153976, 0.012029576, 0.013748821)
> ADJUST:(0.0681573, 0.0688244, 0.0624060, 0.0447025) -> (0.012354514, 0.011686811, 0.013265359, 0.012860776)
> PSI     0.900000    0.0164786
> START:(0.0712429, 0.0726805, 0.0728422, 0.0831167) -> (0.015098639, 0.024796214, 0.014831073, 0.017409910)
> ADJUST:(0.0712429, 0.0726805, 0.0881390, 0.100571) -> (0.016488994, 0.024796214, 0.018327477, 0.023300046)
> Keeping the grid stictly within the boundary
> Gridding regions 0 to 2
>    x-point index            0
>     => Gridding range:     0.0164786    0.0304366
>    SOL index            1
>     => Gridding range:     0.0164786    0.0304366
>    x-point index            1
>     => Gridding range:     0.0164786    0.0304366
>    => These regions only good until f = 0.028284204
>    => i.e. Normalised psi of 1.0691596
> SETTING PSI_OUT           0           1
> Gridding regions 3 to 5
>    x-point index            1
>     => Gridding range:     0.0164786    0.0304366
>    SOL index            0
>     => Gridding range:     0.0164786    0.0304366
>    x-point index            0
>     => Gridding range:     0.0164786    0.0304366
> ** Re-running grid generator with changed settings
> psi outer =       1.06916      1.10000
> Checking settings
> Calculating DCT...
> Finished DCT
> X-point locations: 
>   0: 1.00000
>   1: 1.02158
> Number of x-points in range: 2
> 
> Refining x-point locations...
>   0: (18.4501, 13.5504) 0.0234576
>    -> (18.4755, 13.5388) 0.023453932
>   1: (18.0530, 50.0747) 0.0249633
>    -> (18.1672, 50.1123) 0.024961943
> Primary X-point is number 0
>    at R = 0.61926941 Z = -1.1530979
> Distributing radial points automatically
> Finding theta location of x-point 0
> Finding theta location of x-point 1
> Generating sol psi:       1.02158      1.10000
> Generating sol psi:       1.02158      1.06916
> PSI     0.900000    0.0164786
> START:(0.0563284, 0.0625677, 0.0624060, 0.0491728) -> (0.011735953, 0.012011861, 0.012029576, 0.013748821)
> ADJUST:(0.0619612, 0.0688244, 0.0624060, 0.0491728) -> (0.013034990, 0.013278028, 0.012029576, 0.013748821)
> PSI     0.900000    0.0164786
> START:(0.0712429, 0.0726805, 0.0728422, 0.0831167) -> (0.015098639, 0.024796214, 0.014831073, 0.023776461)
> ADJUST:(0.0948243, 0.0726805, 0.0969529, 0.0831167) -> (0.018398947, 0.030219464, 0.020638927, 0.032374604)
> Keeping the grid stictly within the boundary
> Gridding regions 0 to 2
>    x-point index            0
>     => Gridding range:     0.0164786    0.0282842
>    SOL index            1
>     => Gridding range:     0.0164786    0.0282842
>    x-point index            1
>     => Gridding range:     0.0164786    0.0282842
> Gridding regions 3 to 5
>    x-point index            1
>     => Gridding range:     0.0164786    0.0304366
>    SOL index            0
>     => Gridding range:     0.0164786    0.0304366
>    x-point index            0
>     => Gridding range:     0.0164786    0.0304366
> Successfully generated mesh
> IDL> 
> Write output file
> % Compiled module: PROCESS_GRID.
> % Compiled module: GEN_SURFACE.
> % Compiled module: SPLINE.
> ****Minimum pressure is very small:      0.00000
> ****Setting minimum pressure to 1% of maximum
> % Compiled module: GET_YESNO.
> % Compiled module: DDX.
> % Compiled module: FFT_DERIV.
> Midplane index           28
> Force imbalance:       0.62218354       9.3987595
> Calculating pressure profile from force balance
> Force imbalance:       0.75104766       9.9545162
> % Compiled module: INT_Y.
> MIDPLANE INDEX =           28
> 
> ==== Calculating curvature ====
> *** Calculating curvature in cylindrical coordinates
> % Compiled module: RZ_CURVATURE.
> 
> ==== Calculating parallel current ====
> % Compiled module: ADJUST_JPAR.
> % Compiled module: DDY.
> Force imbalance:       0.75104766       9.9545162
> MIDPLANE INDEX =           28
> 
> ==== Calculating curvature ====
> *** Calculating curvature in cylindrical coordinates
> 
> ==== Calculating parallel current ====
> Force imbalance:       0.75104766       9.9545162
> MIDPLANE INDEX =           28
> 
> ==== Calculating curvature ====
> *** Calculating curvature in cylindrical coordinates
> 
> ==== Calculating parallel current ====
> Force imbalance:       0.75104766       9.9545162

**Comment by bendudson** [comment]
Hello,
For the current version, it looks like IDL can't find a function `READ_NEQDSK`. This is one of the files in the `tools/idllib` directory : https://github.com/boutproject/BOUT-dev/tree/master/tools/idllib

To fix this, the IDL_PATH variable needs to be set using
```
export IDL_PATH=+$BOUT_TOP/tools/idllib:'<IDL_DEFAULT>':\$IDL_PATH
```
where $BOUT_TOP is the BOUT-dev directory containing the configure script. IDL should then be able to find the `read_neqdsk` file. You can test this by running in IDL
```
IDL> .r read_neqdsk
```
