### ISSUE TITLE
Parallel_transform and paralleltransform

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#1810]
In v4.3.0 I seem to be getting an issue if I set `mesh:parallel_transform` to something other than identity. It seems this is a new option in v4.3.0-rc in addition to `mesh:paralleltransform`. 

I've probably just missed where this was introduced and the discussion related to this but I can currently get some quite unexpected behaviour if I the wrong variable by mistake, which is relatively easy given the similarity (also the `_` version needs `shiftedmetric` rather than `shifted`). 

Is this to do with loading the correct type of parallel transform from grid files?

**Comment by ZedThree** [comment]
I believe the underscore version is from checking the grid was created with
the correct transform. Originally it was "coordinate_type" or similar, and
I suggested the change. I didn't anticipate that it would clash with the
other input parameter!

I'm not sure how best to proceed, but it likely needs renaming. There's an
issue here with it being set in hypnotoad too

**Comment by johnomotani** [comment]
With the fix proposed in #1812, I'm not sure `parallel_transform` needs renaming, but if it does, then indeed it needs updating in Hypnotoad too.

**Comment by ZedThree** [comment]
I think this is sufficiently fixed.
