### ISSUE TITLE
Trouble building next branch library

### ISSUE THREAD

**Issue by ADimits** [boutproject/BOUT-dev#1821]
I get multiple similar errors when trying to build the next branch. Typical output is shown below. The attempted builds are with mpich using gcc as the underlying compilers. The same happens with gcc versions 4.8.5, 6.3.0, 8.?, I have tried on Ubuntu and Debian Virtualbox VMs and at NERSC on Cori Haswell, using the gnu environment.

==========
  Compiling  cyclic.cxx
In file included from boutmesh.cxx:36:
In file included from ./boutmesh.hxx:7:
In file included from ../../../../include/bout/mesh.hxx:49:
In file included from ../../../../include/bout/deriv_store.hxx:42:
In file included from ../../../../include/options.hxx:46:
../../../../include/bout/sys/variant.hxx:24:10: fatal error: 
      'mpark/variant.hpp' file not found
#include "mpark/variant.hpp"

==========

**Comment by d7919** [comment]
I think if you run `git submodule update --recursive --init` this should resolve the issue.

We have a new external dependency and the build system doesn't currently automatically check this out. It's possible that running `make check` may also fetch this dependency as a (unanticipated) side effect.

**Comment by d7919** [comment]
I should also note that there's a new release being prepared (v4.3.0) that is currently a bit ahead of next so if you're working on changes etc. then you may wish to branch off v4.3.0-rc rather than next.

**Comment by ADimits** [comment]
Great - Thanks David. That (the first suggestion) fixed it. I'll try the second another time. Andris.

**Comment by d7919** [comment]
A fix to avoid the user having to do anything has been added to the latest 4.3.0 release and merged with next so I will mark this as closed by #1823

**Comment by d7919** [comment]
Closed by #1823
