### ISSUE TITLE
Development strategy for 5.0

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#1825]
v4.3.0 is finally, finally going to be released. After which, we planning on moving to a new major version where we can make breaking changes. This raises a couple of points:

1. v5.0 is likely to be some time in development before release. How best to handle small, non-breaking, features?

2. How do we best handle upgrading physics models from v4.x to v5.x?

One solution is have a long-lived `v4.4.x` "backport" branch. All development should still be done in next, but small, non-breaking, changes could be flagged as candidates for backporting into `v4.4.x`. We would then merge into `next` and cherry-pick (or similar) the changes into `v4.4.x`.

Similarly, when merging breaking changes, we would deprecate the broken feature in `v4.4.x` (along with guidance on how to fix it). This would provide a stepping stone to using v5.0.

This isn't without issues, of course. It's more stuff to maintain. And `v4.4.x` will likely build with a lot of deprecation warnings. But this may allow us to still provide new features on a shorter timescale than 5.0.

**Comment by johnomotani** [comment]
I'm strongly in favour of being able to add new features to a stable release before v5.0 comes out. A backport branch sounds like a reasonable solution to me.

**Comment by ZedThree** [comment]
Another thing that I'd like to discuss/impose are some guiding design principles for the next evolution of BOUT++. First, I believe we have two core values for what BOUT++ _is_:

1. BOUT++ is flexible
2. BOUT++ is fast

roughly in that order. We have a whole variety of different numerical methods that users can switch between at runtime, and we've tried to make them as fast as possible. You can simulate edge turbulence on 2000 cores or bubbles in chocolate on one.

With that in mind, I've been attempting to come up with some concrete guidelines for 5.0. This is a work in progress, and I'd like to write this up properly somewhere. For now, here is a bit of a brain dump:

## Pointers

Ideally, I would like us to move towards raw pointers meaning _exclusively_ a non-owning, nullable reference. What that translates to is, if a function is passed something that is a raw pointer (for example `MySolver(Options* options)`) we can instantly know two things: "something else" owns the object and will take care of managing its lifetime; and it might be `nullptr` so we can do something else (for example, here we could choose to use `Options::root()` instead).

This then means that factories and things that create objects should return `std::unique_ptr<T>` instead of `T*`. If you call a function that returns a `unique_ptr` you know instantly that it's "yours", with the added benefit of not needing to remember to call `delete`.

## Runtime options

Many objects have some degree of configuration, such as the absolute tolerance for adaptive `Solver`s. Because we want runtime flexibility, these objects should take an `Options` argument.
In order to make testing easier though, everything that does take an `Options` should also take the configuration as arguments. An example:

```cpp
class MySolver : public Solver {
public:
  const BoutReal atol{1e.-12};
  MySolver(Options& options) : atol(options["atol"].withDefault(1.e-12)) {}
  MySolver(BoutReal atol) : atol(atol) {}
};
```

We should also pass the "correct" `Options` section. That is, a function or object that takes an `Options` just looks in the top-level section for its keys and subsections. So we would create a `MySolver` like:

```cpp
MySolver solver(Options::root()["solver"]);
```

Bearing in mind that we might want to pass `nullptr` and use the global options, we might write `MySolver` like:

```cpp
class MySolver : public Solver {
  Options* options{nullptr};
public:
  const BoutReal atol{1e.-12};
  MySolver(Options& options_) :
    options(options_ == nullptr ? &Options::root() : options_),
    atol((*options)["atol"].withDefault(1.e-12)) {}
  MySolver(BoutReal atol) : atol(atol) {}
};
```

which might be a verbose enough that we have some helper function for setting the `options` member variable. We also need to do `(*options)["key"]`, which might prompt use to wrap it somehow. Might be a good use of `shared_ptr`?

## Factories
    
When users have a choice of implementation of an operator or similar, the objects should be constructed using a factory, and preferably the generic `Factory`. This should hopefully make them much more maintainable by cutting down on duplicated code, as well as enabling users to register their own implementations:

```cpp
RegisterInFactory<Solver, MySolver> register("mysolver");
// solver is std::unique_ptr<Solver>
auto solver = Factory<Solver>::getInstance().create("mysolver");
```

My plan is to convert many of the ad-hoc custom factories to use `Factory` as an early part of 5.0.

**Comment by ZedThree** [comment]
The backport branch is `v4.4.0-alpha`. I think we'll need to feel our way forward in terms of how backporting will actually work. Either backportable stuff should branch off `v4.4.0-alpha` and then get cherry-picked or rebased into `next`, or vice-versa. I suspect the former will be cleaner, at least in terms of not accidentally bringing in incompatible stuff from next.

**Comment by ZedThree** [comment]
We certainly achieved some of these goals
