### ISSUE TITLE
Issues with LaplacePDD

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#1828]
Does anyone use LaplacePDD? I think there's at least one bug in it:

https://github.com/boutproject/BOUT-dev/blob/123e774f865d4c98d378b909b89accd7efd56dc3/src/invert/laplace/impls/pdd/pdd.cxx#L172-L174

`data.jy` should probably come before `kz`. I only noticed because I'm getting a warning about converting `kz * kwaveFactor` to an `int` which definitely smells wrong.

Secondly, `test-laplace` fails if I use PDD (and run it only with nproc=4), with max differences between 0.1 and 10. This requires the above fix, or else it throws out-of-bounds.

The header to PDD says it neglects "small" corrections and has a big warning:

> CHECK IF THIS ALGORITHM PRODUCES REASONABLE RESULTS FOR YOUR PROBLEM

This suggests it probably needs its own tests, and its assumptions stating up front. I guess `test-laplace` violates these assumptions somehow.

**Comment by bendudson** [comment]
This was a test, the paper promised great things, but I don't think it ever worked. The bug probably didn't help, but I suspect it's just not a very good method. I vote for removing in 5

**Comment by ZedThree** [comment]
Do we still want to remove LaplacePDD? We never "officially" deprecated it

**Comment by bendudson** [comment]
Yes I vote for removing it. Joseph's methods are certainly better and probably faster
