### ISSUE TITLE
Problem using RGN_OUTER_X

### ISSUE THREAD

**Issue by AdamD94** [boutproject/BOUT-dev#1836]
I might be misinterpreting how regions are intended to be used but I think the firstX() check below should be lastX(), maybe it's a copy-paste error from the previous region?
I think as it stands RGN_OUTER_X will always be empty.
Am I misinterpreting or should I open a pull request?

https://github.com/boutproject/BOUT-dev/blob/c52eba6b74a56765f456cfac2d2bd1988a05235f/src/mesh/impls/bout/boutmesh.cxx#L2341-L2356

**Comment by d7919** [comment]
That certainly looks like a bug to me.
