### ISSUE TITLE
Micro-optimzining division

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#1840]
Following the optimization of division by `BoutReal` in #1824, might it be worth doing a similar thing for division of `Field3D` by `Field2D`, as this is a common operation in derivatives and differential operators?

**Comment by d7919** [comment]
I think we already do - we have special handling for this case where we loop over the 2d region and then have an explicit loop over z. I thought we pulled out the division so the inner loop was a multiply, bit I don't have the code to hand so could be wrong. Timing these operations the division is still somewhat slower than other operations so there may be something to be said for storing the reciprocal of some common coordinate quantities.

**Comment by johnomotani** [comment]
You're right @d7919 - we do do this already. Sorry, I should have checked before posting!

I'd agree storing some commonly used reciprocals, intermediate things (e.g. `1./sqrt(g_22)`) would be a good idea.
