### ISSUE TITLE
Sundials-5 linking

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#1844]
Sundials v5 by default installs itself with a `lib64` directory instead of `lib`. I'm working around this at the moment by making a link `lib->lib64` in Sundials's install directory. Can it be handled automatically instead?

Sundials-5.0.0 seems to work fine otherwise.

**Comment by ZedThree** [comment]
It looks like both the configure and cmake build systems should look in `lib64`. Do you have a config.log or error message I could look at?

**Comment by johnomotani** [comment]
Sorry, I'd made a mistake somewhere else. I wish I knew what it was, but I changed some other arguments to configure and now the sundials linking works fine.
