### ISSUE TITLE
TimerTest.GetTime fails sometimes

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1864]
On Fedora 31, this failed now 2 out of 3 times on a kvm host (AFAIK):
```
[ RUN      ] TimerTest.GetTime
sys/test_timer.cxx:26: Failure
The difference between timer.getTime() and elapsed.count() is 0.012817351000000001, which exceeds bout::testing::TimerTolerance, where
timer.getTime() evaluates to 0.0010988409999999999,
elapsed.count() evaluates to 0.013916192000000001, and
bout::testing::TimerTolerance evaluates to 0.00050000000000000001.
[  FAILED  ] TimerTest.GetTime (15 ms)
[----------] 10 tests from TimerTest (30 ms total)
```
and
```
[ RUN      ] TimerTest.GetTime
sys/test_timer.cxx:26: Failure
The difference between timer.getTime() and elapsed.count() is 0.0073374699999999996, which exceeds bout::testing::TimerTolerance, where
timer.getTime() evaluates to 0.0011076980000000001,
elapsed.count() evaluates to 0.0084451679999999994, and
bout::testing::TimerTolerance evaluates to 0.00050000000000000001.
[  FAILED  ] TimerTest.GetTime (8 ms)
[----------] 10 tests from TimerTest (25 ms total)
```
Is this expected that it fails sometimes?
Could we decrease the accuracy, or maybe switch to a relative error, so that if we run on a busy system we are less likely to encounter this?
Or is there something wrong?
NB: it failed once with mpich and once with openmpi.

**Comment by dschwoerer** [comment]
The build succeeded now. Should I close this? It failed 2 out of 5 times ...

**Comment by ZedThree** [comment]
This is unfortunate, but an "acceptable" failure of sorts. It's difficult to make this test robust because the the `sleep` functions have some jitter we can't control due to the OS, scheduler, etc.

One suggestion I've seen is to change the `sleep_for(1ms)` to `sleep_until(system_clock::now() + 1ms)`. I don't completely understand why this might be better, but might be worth a try?

**Comment by dschwoerer** [comment]
Thanks for looking into it.
I hope servers aren't that busy in the future, will close this as won't fix

**Comment by opoplawski** [comment]
I'm running into this fairly consistently now with Fedora 35/36 armv7hl builds.  E.g.: https://kojipkgs.fedoraproject.org//work/tasks/1459/73681459/build.log

**Comment by ZedThree** [comment]
Hi @opoplawski, apologies this a slightly annoying test. Would you be able to try two fixes for us?

The test is in `tests/unit/sys/test_timer.cxx`. The first fix is to limit the scope of the timer:

```cpp
TEST(TimerTest, GetTimeLabelInScope) {
  auto start = Timer::clock_type::now();

  {
    Timer timer{"GetTimeLabelInScope test"};

    std::this_thread::sleep_for(bout::testing::sleep_length);
  }

  auto end = Timer::clock_type::now();
  Timer::seconds elapsed = end - start;

  EXPECT_NEAR(Timer::getTime("GetTimeLabelInScope test"), elapsed.count(),
              bout::testing::TimerTolerance);
}
```

This looks more correct than the current version at any rate. If that doesn't fix the issue, we could change the `EXPECT_NEAR` to `EXPECT_LT`:

```cpp
TEST(TimerTest, GetTimeLabelInScope) {
  const auto start = Timer::clock_type::now();

  Timer timer{"GetTimeLabelInScope test"};

  std::this_thread::sleep_for(bout::testing::sleep_length);

  const auto test_time = Timer::getTime("GetTimeLabelInScope test");

  const auto end = Timer::clock_type::now();
  const Timer::seconds elapsed = end - start;

  EXPECT_LT(test_time, elapsed.count());
}
```

**Comment by dschwoerer** [comment]
The setup of armv7 has been changed, and this does not seem to cause issues anymore.

I can have look if the issue reappears.
