### ISSUE TITLE
Generalising the PETSc interface

### ISSUE THREAD

**Issue by cmacmackin** [boutproject/BOUT-dev#1873]
Following up on the work done for #1771 and #1805:

As discussed at the BOUT++ workshop, the choice of which grid cells to include in a PETSc vector/matrix is problem dependent. The PETSc interface currently just selects the cells which I needed for writing the 3D AMG Laplace solver (#1803). We need to consider how best to generalise the interface to work for any problem. This can be done using my new [`OperatorStencil` class](https://github.com/boutproject/BOUT-dev/blob/0a842b75d39d7a4debeb4b564883066eb81d7262/include/bout/operatorstencil.hxx). My current thoughts on how to do this are summarised below:

- Pass a stencil when creating a `GlobalIndexer` object
- Iterate over `RGN_NOBNDRY`, getting the stencil for each
    - If no stencil is available, that cell will be excluded from the PETSc representation of the field
    - If a stencil is available, any boundary cells which it includes will be placed in a list
- Iterate over the list of boundary cells, getting the stencil for each
    - If no stencil is available, this is an error (the `OperatorStencil` object is inconsistent)
    - If a stencil is available, add any boundary cells which are not in the first list to a second one
- Iterate over the second list and repeat until no new cells are added
- Create `Region<>` objects representing the boundaries and the domain as a whole
- Use the latter-most of these regions to iterate over and fill field objects with global indices
- While doing this, build up information on the sparsity pattern, to be saved as a component of the `GlobalIndexer`
- Add routines to get the `Region<>` objects from the `GlobalIndexer`, `PetscVector`, and `PetscMatrix` classes

The main issues to be resolved with this is how to avoid performing the rather expensive operation multiple times. There could no longer be a global instance of the `GlobalIndexer` which corresponded to the global mesh, as there would be different `GlobalIndexer`s for this mesh depending on the stencil being used. Probably the simplest approach would be to require the user to pass the a shared pointer to a `GlobalIndexer` to the constructors for `PetscVector`/`PetscMatrix`. There could also be a method to get the shared pointer from the vectors and matrices.

Thoughts @ZedThree @johnomotani @bendudson @xxu?

**Comment by cmacmackin** [comment]
While working on this, I discovered that the boundary region `RGN_INNER_X` and `RGN_OUTER_X` are not created for `IndPerp` (neither are the Y-boundary regions, but that makes sense). Is there a reason for this? It would be helpful to me if these two regions were available. Is it alright if I update `BoutMesh::addBoundaryRegions()` to create them?

**Comment by ZedThree** [comment]
Likely just an oversight. Feel free to add them!

**Comment by cmacmackin** [comment]
I've now completed my generalisation of the interface. It is currently living in the [algebraic multigrid branch](https://github.com/boutproject/BOUT-dev/pull/1803). Is it alright if these changes just get merged in when that branch does, or would people prefer that I cherrypick those commits and create a separate branch/pull request for them?

**Comment by ZedThree** [comment]
If it's completely trivial to do so, that might be nice, yes. Otherwise, I'm happy for them to go in that PR.

**Comment by cmacmackin** [comment]
Resolved with the merging of #1889
