### ISSUE TITLE
Debugging optimization flags

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#1879]
While debugging a build configured with `./configure --enable-debug ...` with gdb, at a certain point in the program (but not at other points) I got `value has been optimized out` messages for a bunch of variables. Removing the `-Og` flag (by editing `make.config`), so that `-O0` was used fixed this problem. Compiler was gcc-4.6. I don't think this change is a 'fix' because [gcc's documentation](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html) says
> Optimize debugging experience. -Og should be the optimization level of choice for the standard edit-compile-debug cycle, offering a reasonable level of optimization while maintaining fast compilation and a good debugging experience. It is a better choice than -O0 for producing debuggable code because some compiler passes that collect debug information are disabled at -O0.

so I'm just posting this in case other people run into the same issue.

**Comment by ZedThree** [comment]
Unfortunately, `-Og` is a little buggy, if you'll excuse the pun. It's supposed to be close to `-O1` in terms of optimisation, but retaining the debug info. Only it currently errs too much on the "optimise" side and not enough on the "debug" side.

From what I gather, there may be some fix coming, but I would be surprised if it lands before gcc 10.

We probably do want to fix `--enable-debug` to only use `-O0`.
