### ISSUE TITLE
FieldData::setBoundary(const std::string &region, BoundaryOp *op) not implemented

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#1884]
https://github.com/boutproject/BOUT-dev/blob/51daa8ff4cf9bbeb2fffb67d6ef7055f4e39b07a/src/field/field_data.cxx#L45-L59

This method is not implemented. It should probably be either implemented correctly or removed to avoid confusion. At least it should throw an exception rather than silently not doing anything.

**Comment by ZedThree** [comment]
Fixed in #1949
