### ISSUE TITLE
configure does ignore missing make

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1893]
Building fails, but configure does not complain about missing `make`

Anybody bothered or close as wont fix?

**Comment by bendudson** [comment]
On what system(s) might "make" be missing? Sure, can fix, but probably not a high priority.

**Comment by dschwoerer** [comment]
archlinux, if you start from a minimal system and run `pacman -S openmpi fftw netcdf-cxx gcc` - then make is missing.
I just noted, but thought is not that important, so only reported here, and am perfectly happy to close as won't fix, as we might anyway be switching to cmake.

**Comment by dschwoerer** [comment]
So for me #1892 fixes this somewhat

**Comment by ZedThree** [comment]
I've just read through several autotools guides and the autoconf manual, and it doesn't look like anybody ever tests for `make`. As I'm very much hoping we'll move entirely to CMake, closing this as "won't fix"
