### ISSUE TITLE
cmake: Missing numpy

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1901]
Several tests fail if numpy isn't present

**Comment by ZedThree** [comment]
Is this specific to CMake? I would've thought this would be independent of the build system.

We do have a `requirements.txt` which lists the required packages, but maybe we to be clearer that they must be installed for the tests to work.

**Comment by dschwoerer** [comment]
I haven't checked, just found that many tests failed when I tested the cmake build system.
Do you autogenerte the cmake requirements from the tags in the runtest?

Unlike autotools, cmake does this at configure time. How would that deal with the python interface?
That is never present at configure time, but might be present at check time.

**Comment by ZedThree** [comment]
> I haven't checked, just found that many tests failed when I tested the cmake build system.

Are you building in the same environment?

> Do you autogenerte the cmake requirements from the tags in the runtest?

No, just hardcoded.

> Unlike autotools, cmake does this at configure time. How would that deal with the python interface?
> That is never present at configure time, but might be present at check time.

The Python API is not built yet using CMake as I've not worked out how to tackle it yet. But it will likely become a configure-time option, so we will know if it's available or not when adding tests.

**Comment by dschwoerer** [comment]
> > I haven't checked, just found that many tests failed when I tested the cmake build system.
> 
> Are you building in the same environment?

I have tested, and autotools fails the same way ...
Probably not worth fixing, as the error should be easy to fix.
