### ISSUE TITLE
cmake: list of disabled tests

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1903]
It would be great to get a lest of tests that are not run, and potentially also why.

**Comment by ZedThree** [comment]
During the configure step, this list is printed:

```
-- Not building test test-invertable-operator, requirement not met: BOUT_HAS_PETSC
-- Not building test test-io-hdf5, requirement not met: BOUT_HAS_HDF5
-- Not building test test-petsc-laplace, requirement not met: BOUT_HAS_PETSC
-- Not building test test-petsc-laplace-MAST-grid, requirement not met: BOUT_HAS_PETSC
-- Not building test test-restart-io-hdf5, requirement not met: BOUT_HAS_HDF5
-- Not building test test-slepc-solver, requirement not met: BOUT_HAS_SLEPC
```

It would be a bit of work to get the list as a target, but not impossible.

**Comment by dschwoerer** [comment]
:+1: Thanks, missed that.

printing the list when running `make check` would be great, but not necessary. I'll close for now ...

**Comment by ZedThree** [comment]
Could be better, but does currently work
