### ISSUE TITLE
cmake: integrated checks missing

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1904]
with autoconf 50 checks are run. cmake only has 37:

 - [x] test-interpolate
 - [x] test-stopCheck
 - [x] test-griddata-yboundary-guards
 - [x] test-twistshift-staggered
 - [x] test-slepc-solver
 - [x] test-code-style
 - [x] test-fieldgroupComm
 - [x] test-restarting
 - [x] test-attribs
 - [x] test-delp2
 - [x] test-solver
 - [x] test-snb
 - [x] test-squash
 - [x] test-griddata
 - [x] test-petsc_laplace_MAST-grid
 - [x] test-multigrid_laplace
 - [x] test-drift-instability
 - [x] test-drift-instability-staggered
 - [x] test-io_hdf5
 - [x] test-vec
 - [ ] test-include
 - [x] test-petsc_laplace
 - [ ] test-region-iterator
 - [x] test-invpar
 - [x] test-compile-examples
 - [x] test-twistshift
 - [x] test-coordinates-initialization
 - [x] test-gyro
 - [x] test-smooth
 - [x] test-cyclic
 - [x] test-command-args
 - [ ] test-fieldfactory
 - [x] test-restart-io
 - [x] test-interchange-instability
 - [x] test-naulin-laplace
 - [x] test-compile-examples-petsc
 - [x] test-invertable-operator
 - [x] test-io
 - [x] test-initial
 - [x] test-laplace
 - [ ] test-boutcore/collect-staggered
 - [ ] test-boutcore/simple-model
 - [ ] test-boutcore/boundaries-mms
 - [ ] test-boutcore/mms-ddz
 - [ ] test-boutcore/collect
 - [ ] test-boutcore/legacy-model
 - [x] test-yupdown
 - [x] test-restart-io_hdf5
 - [x] test-options-netcdf
 - ~~test-subdir~~
 - [x] test-stopCheck-file

The boutcore tests probably depend on building boutcore.

**Comment by ZedThree** [comment]
Need work/in progress:

- boutcore tests need boutcore building -- needs some work
- test-compile-examples/-petsc need CMakeLists.txt adding for example -- halfway there with this, need to finish off and make PR
- test-include -- need to think how to translate this

Won't fix/might delete:

- test-subdir is a test of the makefile build system, so not needed for CMake
- test-squash -- is this going to be replaced by xBOUT?
- test-fieldfactory -- this is mostly replaced by unit tests, just the multiple processors bit that isn't, but hopefully the mockable MPI interface can be used to fully replace it
- test-code-style -- I want to replace this by just running clang-tidy

**Comment by dschwoerer** [comment]
> Need work/in progress:
> 
>     * boutcore tests need boutcore building -- needs some work

I created https://github.com/boutproject/BOUT-dev/issues/1940 to track this

>     * test-include -- need to think how to translate this

This relies on `bout-config`.
If that is ported, it shouldn't be an issue anyway. If we create a `BOUT++.pc` that would allow to make bout-config just a wrapper. Anyway I think we shouldn't force cmake on users for there own projects.

> Won't fix/might delete:
> 
>     * test-subdir is a test of the makefile build system, so not needed for CMake

removed from list :+1: 

>     * test-code-style -- I want to replace this by just running clang-tidy

note that different versions produce different results (at least for clang-format)
So making this work outside of travis is difficult. Otherwise I agree, clang provides some very nice tools for this.

**Comment by johnomotani** [comment]
> test-squash -- is this going to be replaced by xBOUT?

The functionality might eventually move into xBOUT (although last I heard there were still performance issues to resolve), but I think keeping `bin/bout-squash` and testing it in the BOUT-dev repo is still useful, because an xBOUT test can't run BOUT++, whereas this test can use a BOUT++ executable to generate correct inputs, and verify that `bout-squash` (whatever Python tools are used inside it) behaves correctly.

**Comment by ZedThree** [comment]
Crossed off test-compile-examples and test-compile-examples-petsc; done in #2021 by using `-DBOUT_BUILD_EXAMPLES=on` to build everything.

I think test-region-iterator can possibly go -- I'm not sure what it gives us over the unit tests.

test-include turns out to be a little trickier than I thought to do completely within CMake, so it might need to still rely on `bout-config`

**Comment by bendudson** [comment]
Personally I think having `bout-config` is quite nice: simple but effective. It makes configuration with many other build systems, makefiles, or users own random ad-hoc scripts easier. I think it's probably good to have a test that uses it, even if we end up using (and recommending) cmake for everything else.

**Comment by ZedThree** [comment]
`test-code-style` replaced with running clang-tidy. Might need to tone it down a bit, it's much noisier than I was hoping

**Comment by dschwoerer** [comment]
boutcore tests by #2589
