### ISSUE TITLE
Travis: permissions?

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1915]
I am unable to restart this job:
https://travis-ci.org/boutproject/BOUT-dev/jobs/651943498

**Comment by ZedThree** [comment]
I thought if you had write permissions to this repo you had permissions on Travis. Not sure. I've restarted the job

**Comment by dschwoerer** [comment]
I used to have permissions to do that. But the buttons are gone, even though I am still logged in ...
