### ISSUE TITLE
BOUT version number

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#192]
What is the current version number of BOUT++?

the configure.ac currently states 2.0 and the bout.hxx says 3

What confuses me even more is that master and next have the same numbers - although the provide quite different interfaces.

Why I am interested: I would like to be able to differentiate between master and next at compile time to use e.g. different loop iterator ...

**Comment by bendudson** [comment]
Hi David,

The version number has historically only been used in the output post processing, so changes in version number were usually when the format of the output changed.

The version number of master should be 3, and next should be 4. Next is currently 3, but I have a branch of next which removes the extra point in z, and bumps the version number to 4. Will merge shortly.

Ben

-------- Original Message --------
