### ISSUE TITLE
cflags in `bout-config` broken

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1921]
cflags in `bout-config` are wrong, as the quoting does not work reliably.
This is the case for configure. (cmake is missing `bout-config`)

I've been wondering for a while whether there is a nicer way to build against BOUT++, rather then depending on the `makefile` used by BOUT++ to get the right flags.

`cmake` is obviously one way, another would be `pkg-config`, that seems to be also (somewhat) supported by PETSc.

Another option would be to at put the defines in a file, then only the libs and normal flags need to be exposed via e.g. `pkg-config`, `bout-config` or similar.

edit: reproduce via:
```
./configure
bin/bout-config --cflags
```
result:
```
-I/home/dave/soft/bout-dev/tmp/include -I/usr/include -I/usr/include -I/home/dave/soft/bout-dev/tmp/externalpackages/mpark.variant/include -g -DHAS_PRETTY_FUN
CTION -Wall -Wextra -Wnull-dereference -Wno-cast-function-type -O2 -DCHECK=2 -DSIGHANDLE -DLOGCOLOR -DBOUT_VERSION_STRING=4.3.0 -DBOUT_VERSION_DOUBLE=4.30 -DB
ACKTRACE -DBOUT_HAS_FFTW -DNCDF4 -DHDF5 -DLAPACK -DBOUT_HAS_PVODE -DBOUT_HAS_GETTEXT -DBOUT_LOCALE_PATH=/usr/local/share/locale -DBOUT_FLAGS_STRING= -g -DHAS_
PRETTY_FUNCTION -Wall -Wextra -Wnull-dereference -Wno-cast-function-type -O2 -DCHECK=2 -DSIGHANDLE -DLOGCOLOR -DBOUT_VERSION_STRING=4.3.0 -DBOUT_VERSION_DOUBL
E=4.30 -DBACKTRACE -DBOUT_HAS_FFTW -DNCDF4 -DHDF5 -DLAPACK -DBOUT_HAS_PVODE -DBOUT_HAS_GETTEXT -DBOUT_LOCALE_PATH=/usr/local/share/locale
```
Expected output:
`-DBOUT_FLAGS_STRING=` is quoted, `-DBOUT_VERSION_STRING` is quoted, etc.

**Comment by ZedThree** [comment]
The quoting thing seems pretty tricky, as it currently has to go through several instances of both make and shell. `BOUT_VERSION_STRING` is gone in #1920 at least. I've not found an easy fix for `BOUT_FLAGS_STRING`. Likely needs a bunch more machinery.

I plan on moving more command line defines into a generated config header (plus consistent naming and namespacing etc.). This should hopefully solve most of the problems.

CMake should be able to generate `bout-config` pretty easily, modulo some name changes of variables to be consistent between CMake and the makefiles.

Providing a `pkg-config` file should also be possible, but it's harder to find decent best practices guides. I'm not convinced PETSc do this correctly, as they put `-fopenmp` in `cflags_extra` and not in any of the library-related flags for instance.
