### ISSUE TITLE
error when running make for an example of lapd-drift

### ISSUE THREAD

**Issue by bellsis83** [boutproject/BOUT-dev#1923]
HI all,,

I am trying to run an example of lapd-drift but i have got an error when run make.
The error is as below:

$ make
  Compiling  lapd_drift.cxx
lapd_drift.cxx: In member function ‘virtual int LAPDdrift::rhs(BoutReal)’:
lapd_drift.cxx:508:36: warning: ‘const Field3D Grad_par_LtoC(const Field3D&)’ is deprecated: Grad_par_LtoC is deprecated. Staggering is now supported in Grad_par. [-Wdeprecated-declarations]
       jpar = ((Tet*Grad_par_LtoC(ni)) - (Nit*Grad_par_LtoC(phi)))/(fmei*0.51*nu);
                                    ^
In file included from ../../include/bout.hxx:41:0,
                 from ../../include/bout/physicsmodel.hxx:40,
                 from lapd_drift.cxx:6:
../../include/difops.hxx:254:22: note: declared here
 inline const Field3D Grad_par_LtoC(const Field3D &var) {
                      ^~~~~~~~~~~~~
lapd_drift.cxx:508:63: warning: ‘const Field3D Grad_par_LtoC(const Field3D&)’ is deprecated: Grad_par_LtoC is deprecated. Staggering is now supported in Grad_par. [-Wdeprecated-declarations]
       jpar = ((Tet*Grad_par_LtoC(ni)) - (Nit*Grad_par_LtoC(phi)))/(fmei*0.51*nu);
                                                               ^
In file included from ../../include/bout.hxx:41:0,
                 from ../../include/bout/physicsmodel.hxx:40,
                 from lapd_drift.cxx:6:
../../include/difops.hxx:254:22: note: declared here
 inline const Field3D Grad_par_LtoC(const Field3D &var) {
                      ^~~~~~~~~~~~~
lapd_drift.cxx:543:38: warning: ‘const Field3D Grad_par_CtoL(const Field3D&)’ is deprecated: Grad_par_CtoL is deprecated. Staggering is now supported in Grad_par. [-Wdeprecated-declarations]
         ddt(ni) += Grad_par_CtoL(jpar); // Left hand differencing
                                      ^
In file included from ../../include/bout.hxx:41:0,
                 from ../../include/bout/physicsmodel.hxx:40,
                 from lapd_drift.cxx:6:
../../include/difops.hxx:226:22: note: declared here
 inline const Field3D Grad_par_CtoL(const Field3D &var) {
                      ^~~~~~~~~~~~~
lapd_drift.cxx:572:39: warning: ‘const Field3D Grad_par_CtoL(const Field3D&)’ is deprecated: Grad_par_CtoL is deprecated. Staggering is now supported in Grad_par. [-Wdeprecated-declarations]
         ddt(rho) += Grad_par_CtoL(jpar); // Left hand differencing
                                       ^
In file included from ../../include/bout.hxx:41:0,
                 from ../../include/bout/physicsmodel.hxx:40,
                 from lapd_drift.cxx:6:
../../include/difops.hxx:226:22: note: declared here
 inline const Field3D Grad_par_CtoL(const Field3D &var) {
                      ^~~~~~~~~~~~~
lapd_drift.cxx:616:50: warning: ‘const Field3D Grad_par_LtoC(const Field3D&)’ is deprecated: Grad_par_LtoC is deprecated. Staggering is now supported in Grad_par. [-Wdeprecated-declarations]
         ddt(ajpar) += (1./fmei)*Grad_par_LtoC(phi); // Right-hand deriv with b.c. Necessary for sheath mode
                                                  ^
In file included from ../../include/bout.hxx:41:0,
                 from ../../include/bout/physicsmodel.hxx:40,
                 from lapd_drift.cxx:6:
../../include/difops.hxx:254:22: note: declared here
 inline const Field3D Grad_par_LtoC(const Field3D &var) {
                      ^~~~~~~~~~~~~
lapd_drift.cxx:625:59: warning: ‘const Field3D Grad_par_LtoC(const Field3D&)’ is deprecated: Grad_par_LtoC is deprecated. Staggering is now supported in Grad_par. [-Wdeprecated-declarations]
         ddt(ajpar) -= (1./fmei)*(Tet/Nit)*Grad_par_LtoC(ni);
                                                           ^
In file included from ../../include/bout.hxx:41:0,
                 from ../../include/bout/physicsmodel.hxx:40,
                 from lapd_drift.cxx:6:
../../include/difops.hxx:254:22: note: declared here
 inline const Field3D Grad_par_LtoC(const Field3D &var) {
                      ^~~~~~~~~~~~~
lapd_drift.cxx:629:51: warning: ‘const Field3D Grad_par_LtoC(const Field3D&)’ is deprecated: Grad_par_LtoC is deprecated. Staggering is now supported in Grad_par. [-Wdeprecated-declarations]
         ddt(ajpar) -= (1.71/fmei)*Grad_par_LtoC(te);
                                                   ^
In file included from ../../include/bout.hxx:41:0,
                 from ../../include/bout/physicsmodel.hxx:40,
                 from lapd_drift.cxx:6:
../../include/difops.hxx:254:22: note: declared here
 inline const Field3D Grad_par_LtoC(const Field3D &var) {
                      ^~~~~~~~~~~~~
lapd_drift.cxx:667:44: warning: ‘const Field3D Grad_par_LtoC(const Field3D&)’ is deprecated: Grad_par_LtoC is deprecated. Staggering is now supported in Grad_par. [-Wdeprecated-declarations]
         ddt(te) -= ajpar * Grad_par_LtoC(te);
                                            ^
In file included from ../../include/bout.hxx:41:0,
                 from ../../include/bout/physicsmodel.hxx:40,
                 from lapd_drift.cxx:6:
../../include/difops.hxx:254:22: note: declared here
 inline const Field3D Grad_par_LtoC(const Field3D &var) {
                      ^~~~~~~~~~~~~
lapd_drift.cxx:671:53: warning: ‘const Field3D Grad_par_CtoL(const Field3D&)’ is deprecated: Grad_par_CtoL is deprecated. Staggering is now supported in Grad_par. [-Wdeprecated-declarations]
         ddt(te) -= 2./3. * Tet * Grad_par_CtoL(ajpar);
                                                     ^
In file included from ../../include/bout.hxx:41:0,
                 from ../../include/bout/physicsmodel.hxx:40,
                 from lapd_drift.cxx:6:
../../include/difops.hxx:226:22: note: declared here
 inline const Field3D Grad_par_CtoL(const Field3D &var) {
                      ^~~~~~~~~~~~~
lapd_drift.cxx:683:61: warning: ‘const Field3D Grad_par_CtoL(const Field3D&)’ is deprecated: Grad_par_CtoL is deprecated. Staggering is now supported in Grad_par. [-Wdeprecated-declarations]
         ddt(te) += 0.71*2./3. * Tet/Nit * Grad_par_CtoL(jpar);
                                                             ^
In file included from ../../include/bout.hxx:41:0,
                 from ../../include/bout/physicsmodel.hxx:40,
                 from lapd_drift.cxx:6:
../../include/difops.hxx:226:22: note: declared here
 inline const Field3D Grad_par_CtoL(const Field3D &var) {
                      ^~~~~~~~~~~~~
  Linking lapd_drift

I would appreciate if you would give me any advice.

Best,

**Comment by dschwoerer** [comment]
Hi @bellsis83,

Thanks for contacting us. In the output you showed, there is no error, just warnings (unless there would be something below the `Linking lapd_drift`).

The output contains many warnings about functions that are deprecated.
The example is using functions that will be removed in the future.
For now all this is fine, and the example will be adjusted before we fully drop the deprecated functions.

If you should have any further issues, please feel free to ask again :+1:

**Comment by bellsis83** [comment]
Hi @dschwoerer,
Thanks for prompt reply. I tried to run the example. but I've got a error as below. Please take a look at the error and I would appreciate if you give me advice!!

$ mpirun -np 16 ./lapd_drift
BOUT++ version 5.0.0-alpha
Revision: 7acd841b0cdaa64ecdbd962d2db13419ddfd02ea
MD5 checksum: 7f8fff732c07d3a6e70fd1baa1760770
Code compiled on Feb 27 2020 at 15:46:05

B.Dudson (University of York), M.Umansky (LLNL) 2007
Based on BOUT by Xueqiao Xu, 1999

Processor number: 0 of 16

pid: 29336

Compile-time options:
	Checking enabled, level 2
	Signal handling enabled
	netCDF support enabled
	Parallel NetCDF support disabled
	OpenMP parallelisation disabled
	Compiled with flags : "-DMD5SUM=7f8fff732c07d3a6e70fd1baa1760770 -DREVISION=7acd841b0cdaa64ecdbd962d2db13419ddfd02ea -g -DHAS_PRETTY_FUNCTION -Wall -Wextra -Wnull-dereference -O2 -DCHECK=2 -DSIGHANDLE -DLOGCOLOR -DBOUT_VERSION_STRING=\"5.0.0-alpha\" -DBOUT_VERSION_DOUBLE=5.00 -DBACKTRACE -DBOUT_HAS_FFTW -DNCDF -DHDF5 -DBOUT_HAS_PVODE -DBOUT_HAS_GETTEXT -DBOUT_LOCALE_PATH=/usr/local/share/locale"
	Command line options for this run : ./lapd_drift 
Reading options file data/BOUT.inp
Writing options to file data/BOUT.settings
	Option grid = uedge.grd.nc (data/BOUT.inp)
	Option mesh:file = uedge.grd.nc (default)

Getting grid data from file uedge.grd.nc
	Option format =  (default)
	Option mesh:format =  (default)
	Using NetCDF format for file 'uedge.grd.nc'
	Option mesh:type = bout (default)
	Option mesh:StaggerGrids = 0 (default)
	Option mesh:maxregionblocksize = 64 (default)
	Option mesh:calcParallelSlices_on_communicate = 1 (default)
	Option mesh:ddx:first = c4 (data/BOUT.inp)
	Option mesh:ddx:second = c4 (data/BOUT.inp)
	Option mesh:ddx:upwind = w3 (data/BOUT.inp)
	Option mesh:ddy:first = c4 (data/BOUT.inp)
	Option mesh:ddy:second = c4 (data/BOUT.inp)
	Option mesh:ddy:upwind = w3 (data/BOUT.inp)
	Option mesh:ddz:first = c4 (data/BOUT.inp)
	Option mesh:ddz:second = c4 (data/BOUT.inp)
	Option mesh:ddz:upwind = w3 (data/BOUT.inp)
	Option mesh:ddy:first = c4 (data/BOUT.inp)
	Option mesh:ddy:second = c4 (data/BOUT.inp)
	Option mesh:ddy:upwind = w3 (data/BOUT.inp)
	Option mesh:ddx:first = c4 (data/BOUT.inp)
	Option mesh:ddx:second = c4 (data/BOUT.inp)
	Option mesh:ddx:upwind = w3 (data/BOUT.inp)
	Option mesh:ddy:first = c4 (data/BOUT.inp)
	Option mesh:ddy:second = c4 (data/BOUT.inp)
	Option mesh:ddy:upwind = w3 (data/BOUT.inp)
	Option mesh:ddz:first = c4 (data/BOUT.inp)
	Option mesh:ddz:second = c4 (data/BOUT.inp)
	Option mesh:ddz:upwind = w3 (data/BOUT.inp)
	Option mesh:ddy:first = c4 (data/BOUT.inp)
	Option mesh:ddy:second = c4 (data/BOUT.inp)
	Option mesh:ddy:upwind = w3 (data/BOUT.inp)
	Option mesh:ddz:fft_filter = 0 (default)
	Option mesh:symmetricGlobalX = 1 (default)
	Option optionfile = BOUT.inp ()
WARNING: The default of this option has changed in release 4.1.
If you want the old setting, you have to specify mesh:symmetricGlobalY=false in BOUT.inp
	Option mesh:symmetricGlobalY = 1 (default)
Loading mesh
	Option nx = 54 (uedge.grd.nc)
	Option ny = 32 (uedge.grd.nc)
	Option nz = 0 (uedge.grd.nc) (default)
	Option input:transform_from_field_aligned = 1 (default)
	Option input:max_recursion_depth = 0 (default)
	Option mz = 32 (data/BOUT.inp)
	Option nz = 32 (default)
	Grid size: 54 x 32 x 32
	Option MXG = 0 (uedge.grd.nc) (default)
	Option mxg = 2 (data/BOUT.inp)
	Option MYG = 0 (uedge.grd.nc) (default)
	Option myg = 2 (data/BOUT.inp)
	Guard cells (x,y,z): 2, 2, 0
	Option ixseps1 = 54 (uedge.grd.nc)
	Option ixseps2 = 54 (uedge.grd.nc)
	Option jyseps1_1 = -1 (uedge.grd.nc)
	Option jyseps1_2 = 16 (uedge.grd.nc)
	Option jyseps2_1 = 16 (uedge.grd.nc)
	Option jyseps2_2 = 31 (uedge.grd.nc)
	Option ny_inner = 16 (uedge.grd.nc) (default)
Finding value for NXPE (ideal = 5.000000)
	Candidate value: 1
	 -> Good value
	Candidate value: 2
	 -> Good value
	Domain split (NXPE=2, NYPE=8) into domains (localNx=25, localNy=4)
	Option IncIntShear = 0 (default)
	Option periodicX = 0 (default)
	Option async_send = 0 (default)
	Option zperiod = 5 (data/BOUT.inp)
	EQUILIBRIUM IS SINGLE NULL (SND) 
Connection between top of Y processor 7 and bottom of 0 in range 0 <= x < 54
=> This processor sending in down
WARNING adding connection: poloidal index -1 out of range
	MYPE_IN_CORE = 1
	DXS = 29, DIN = 14. DOUT = -1
	UXS = 0, UIN = -1. UOUT = 2
	XIN = -1, XOUT = 1
	Twist-shift: DI 
	Option twistshift = false (data/BOUT.inp)
Boundary regions in this processor: core, 
Constructing default regions
	Boundary region inner X
	Option mesh:extrapolate_x = 0 (default)
	Option mesh:extrapolate_y = 1 (default)
WARNING: extrapolating input mesh quantities into y-boundary cells. Set option extrapolate_y=false to disable this.
	Option zperiod = 5 (data/BOUT.inp)
	Option dz = 0.0392699 (uedge.grd.nc) (default)
	WARNING: Could not read 'g11' from grid. Setting to 1.000000e+00
	WARNING: Could not read 'g22' from grid. Setting to 1.000000e+00
	WARNING: Could not read 'g33' from grid. Setting to 1.000000e+00
	WARNING: Could not read 'g12' from grid. Setting to 0.000000e+00
	WARNING: Could not read 'g13' from grid. Setting to 0.000000e+00
	WARNING: Could not read 'g23' from grid. Setting to 0.000000e+00
	Local maximum error in diagonal inversion is 0.000000e+00
	Local maximum error in off-diagonal inversion is 0.000000e+00
	WARNING: Could not read 'J' from grid. Setting to 0.000000e+00
	WARNING: Jacobian 'J' not found. Calculating from metric tensor
	Maximum difference in Bxy is 9.600000e-01
Calculating differential geometry terms
	Communicating connection terms
	Option non_uniform = true (data/BOUT.inp)
	WARNING: Could not read 'd2x' from grid. Setting to 0.000000e+00
	WARNING: differencing quantity 'd2x' not found. Calculating from dx
	WARNING: Could not read 'd2y' from grid. Setting to 0.000000e+00
	WARNING: differencing quantity 'd2y' not found. Calculating from dy
	WARNING: Could not read 'ShiftTorsion' from grid. Setting to 0.000000e+00
	WARNING: No Torsion specified for zShift. Derivatives may not be correct
	Option mesh:paralleltransform = identity (default)
	Option parallel_transform =  (uedge.grd.nc) (default)
	done
	Option append = 0 (default)
	Option dump_format = nc (data/BOUT.inp)
Setting up output (dump) file
	Option output:parallel = 0 (default)
	Option output:flush = 1 (default)
	Option output:guards = 1 (default)
	Option output:floats = 0 (default)
	Option output:openclose = 1 (default)
	Option output:enabled = 1 (default)
	Option output:init_missing = 0 (default)
	Option output:shiftOutput = 0 (default)
	Option output:shiftInput = 0 (default)
	Option output:flushFrequency = 1 (default)
	Using NetCDF format for file 'data/BOUT.dmp.nc'
	Option restart:parallel = 0 (default)
	Option restart:flush = 1 (default)
	Option restart:guards = 1 (default)
	Option restart:floats = 0 (default)
	Option restart:openclose = 1 (default)
	Option restart:enabled = 1 (default)
	Option restart:init_missing = 0 (default)
	Option restart:shiftOutput = 0 (default)
	Option restart:shiftInput = 0 (default)
	Option restart:flushFrequency = 1 (default)
	Option solver:type = pvode (data/BOUT.inp)
	Option solver:monitor_timestep = 0 (default)
	Option solver:is_nonsplit_model_diffusive = 1 (default)
	Option solver:mms = 0 (default)
	Option solver:mms_initialise = 0 (default)
	Option restart = 0 (default)
Solving LAPD drift test case
	WARNING: Could not read 'Ve0' from grid. Setting to 0.000000e+00
	WARNING: Could not read 'rho0' from grid. Setting to 0.000000e+00
	WARNING: Could not read 'Ajpar0' from grid. Setting to 0.000000e+00
	Reading contravariant vector bxcv
	Option Te_x = 5 (uedge.grd.nc)
	Option Ti_x = 0.1 (uedge.grd.nc)
	Option Ni_x = 0.0250191 (uedge.grd.nc)
	Option bmag = 0.04 (uedge.grd.nc)
	Option ixseps1 = 54 (uedge.grd.nc)
	Option timestep = 2 (data/BOUT.inp)
	Option 2fluid:aa = 4 (data/BOUT.inp)
	Option 2fluid:zz = 1 (data/BOUT.inp)
	Option 2fluid:estatic = true (data/BOUT.inp)
	Option 2fluid:zeroelmass = false (data/BOUT.inp)
	Option 2fluid:zeff = 1 (data/BOUT.inp)
	Option 2fluid:nu_perp = 1e-20 (data/BOUT.inp)
	Option 2fluid:shearfactor = 0 (data/BOUT.inp)
	Option 2fluid:nuionneutral = 0.002 (data/BOUT.inp)
	Option 2fluid:arakawa = false (data/BOUT.inp)
	Option 2fluid:bout_exb = true (data/BOUT.inp)
	Option 2fluid:niprofile = 0 (default)
	Option 2fluid:evolve_source_ni = false (data/BOUT.inp)
	Option 2fluid:evolve_source_te = false (data/BOUT.inp)
	Option 2fluid:source_response = 1 (default)
	Option 2fluid:source_converge = -1 (default)
	Option 2fluid:ni_perpdiff = 0.002 (data/BOUT.inp)
	Option 2fluid:rho_perpdiff = 0.002 (data/BOUT.inp)
	Option 2fluid:te_perpdiff = 0.002 (data/BOUT.inp)
	Option 2fluid:input_source = 0 (default)
	Option 2fluid:remove_tor_av_ni = true (data/BOUT.inp)
	Option 2fluid:remove_tor_av_te = false (data/BOUT.inp)
	Option 2fluid:nonlinear = true (data/BOUT.inp)
	Option 2fluid:filter_z = false (data/BOUT.inp)
	Option 2fluid:filter_z_mode = 1 (data/BOUT.inp)
	Option rho:evolve_rho = true (data/BOUT.inp)
	Option rho:rho_jpar1 = true (data/BOUT.inp)
	Option rho:rho_nuin_rho1 = true (data/BOUT.inp)
	Option rho:rho_rho1 = false (data/BOUT.inp)
	Option rho:rho_rho0_phi1 = false (data/BOUT.inp)
	Option rho:rho_rho1_phi0 = false (data/BOUT.inp)
	Option rho:rho_ve2lin = false (data/BOUT.inp)
	Option rho:rho_rho1_phi1 = true (data/BOUT.inp)
	Option rho:rho_ve2t = false (data/BOUT.inp)
	Option rho:rho_diff = true (data/BOUT.inp)
	Option ni:evolve_ni = true (data/BOUT.inp)
	Option ni:ni_jpar1 = true (data/BOUT.inp)
	Option ni:ni_ni0_phi1 = true (data/BOUT.inp)
	Option ni:ni_ni1_phi0 = false (data/BOUT.inp)
	Option ni:ni_ni1_phi1 = true (data/BOUT.inp)
	Option ni:ni_src_ni0 = 0 (default)
	Option ni:ni_diff = true (data/BOUT.inp)
	Option ajpar:evolve_ajpar = true (data/BOUT.inp)
	Option ajpar:ajpar_phi1 = true (data/BOUT.inp)
	Option ajpar:ajpar_jpar1 = true (data/BOUT.inp)
	Option ajpar:ajpar_te_ni = true (data/BOUT.inp)
	Option ajpar:ajpar_te = false (data/BOUT.inp)
	Option ajpar:ajpar_ajpar1_phi0 = false (data/BOUT.inp)
	Option ajpar:ajpar_ajpar1_phi1 = true (data/BOUT.inp)
	Option ajpar:ajpar_ve1_ve1 = true (data/BOUT.inp)
	Option te:evolve_te = false (data/BOUT.inp)
	Option te:te_te1_phi0 = false (data/BOUT.inp)
	Option te:te_te0_phi1 = false (data/BOUT.inp)
	Option te:te_te1_phi1 = false (data/BOUT.inp)
	Option te:te_ajpar_te = false (data/BOUT.inp)
	Option te:te_te_ajpar = false (data/BOUT.inp)
	Option te:te_nu_te1 = false (data/BOUT.inp)
	Option te:te_nu_tet = false (data/BOUT.inp)
	Option te:te_jpar = false (data/BOUT.inp)
	Option te:te_diff = false (data/BOUT.inp)
	Option mesh:paralleltransform = identity (default)
Collisions: nueix = 7.381523e+06, nu_hat = 7.705139e+00
	Option hthe0 = 2.70563 (uedge.grd.nc)
    ****NOTE: input from BOUT, Z length needs to be divided by 2.372542e+02
Error encountered
application called MPI_Abort(comm=0x84000002, 1) - process 2

**Comment by johnomotani** [comment]
I tried running the `lapd-drift` example, and it's missing a necessary option
```
[mesh]
StaggerGrids = true
```
in the `data/BOUT.inp` file. However, even when I add that, I get another exception and then a segfault while the exception is being thrown... Very strange. Will have a quick look into it now.

**Comment by johnomotani** [comment]
@ZedThree, @bendudson The staggered derivative operators in `lapd_drift.cxx` were being used the opposite way round to what I thought they meant. `Grad_par_CtoL()` was taking a flux (which I expected to be at `CELL_YLOW`) as argument, and returning a result for a scalar equation (which I expected to be at `CELL_CENTRE`), I thought it should be the other way around: i.e. `CtoL` meant 'argument at `C`' and 'result at `L`'. Doesn't really matter now that the `CtoL` and `LtoC` operators are deprecated anyway, but noting here in case issues come up converting old physics models.

**Comment by johnomotani** [comment]
@bellsis83 I think I've fixed the problems that stopped `lapd-drift` from running in #1925. If you checkout the `lapd-drift-fixes` branch you can try it out now.

@ZedThree @bendudson the segfault goes away when I fix the exceptions, but I still don't know why it was happening in the first place. The segfault happened where `PvodeSolver::~PvodeSolver()` called `CVodeFree(cvode_mem);` at l.65. The destructor is called while the exception is terminating the program.

**Comment by bellsis83** [comment]
Thanks @johnomotani 
I tried to configure the fixed version but I've got a error as below:

$ ./configure
checking for mpic++... mpic++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether mpic++ accepts -g... yes
checking for function MPI_Init... yes
checking for mpi.h... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking whether ln -s works... yes
checking whether make sets $(MAKE)... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking for gmake... make
checking for ranlib... ranlib
checking whether mpic++ supports C++14 features with -std=c++14... yes
checking for sqrt in -lm... yes
checking how to run the C++ preprocessor... mpic++ -std=c++14 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for strings.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for vprintf... yes
checking for _doprnt... no
checking does C++ compiler support __PRETTY_FUNCTION__... yes
checking for a sed that does not truncate output... /bin/sed
checking whether to build with code coverage support... no
checking whether C++ compiler accepts -Werror=unknown-warning-option... no
checking whether C++ compiler accepts -we10006,10148... no
checking whether C++ compiler accepts -Wall... yes
checking whether C++ compiler accepts -Wextra... yes
checking whether C++ compiler accepts -Wnull-dereference... yes
checking whether C++ compiler accepts -Wno-cast-function-type... no
configure: Enabling default optimisations
checking whether C++ compiler accepts -O2... yes
configure: Run-time checking enabled
configure:  -> Level 2 (Basic checking + stack tracing)
configure: Segmentation fault handling enabled
configure: Output coloring enabled
configure: Field name tracking disabled
configure: Signaling floating point exceptions disabled
checking for addr2line... yes
checking for popen... yes
checking for backtrace... yes
checking execinfo.h usability... yes
checking execinfo.h presence... yes
checking for execinfo.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking for library containing dladdr... -ldl
configure: Native backtrace enabled
fatal: not a git repository (or any of the parent directories): .git
checking for fftw-wisdom... /usr/bin/fftw-wisdom
checking for fftw3.h... yes
checking for libfftw3... yes
checking for ncxx4-config... no
checking for nc-config... /usr/bin/nc-config
checking if /usr/bin/nc-config has C++4 support... no
checking if /usr/bin/nc-config has C++ support... no
checking if we can compile NetCDF with C++... yes
configure:  -> Legacy NetCDF support enabled
configure: Parallel-NetCDF support disabled
checking for gawk... no
checking for mawk... mawk
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for h5cc... /usr/bin/h5cc
checking for HDF5 type... serial
checking for HDF5 libraries... yes (version 1.10.0-patch1)
checking hdf5.h usability... yes
checking hdf5.h presence... yes
checking for hdf5.h... yes
checking for H5Fcreate in -lhdf5... yes
checking for main in -lhdf5_hl... yes
configure: Found HDF5
configure: Parallel HDF5 support disabled
configure: Supported file formats: netCDF HDF5
checking for libblas... no
checking for liblapack... no
configure: Scorep support disabled
configure: PVODE being built without OpenMP support
configure: Building PVODE
configure: Successfully built PVODE
configure: Installing PVODE into BOUT++ sourcetree
checking whether NLS is requested... yes
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for shared library run path origin... /bin/bash: build-aux/config.rpath: No such file or directory
done
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking for GNU gettext in libc... yes
checking whether to use NLS... yes
checking where the gettext function comes from... libc
configure: Enabling language support with gettext
make: Entering directory '/home/bhseo/BOUT-dev/locale'
Building language:  de
Building language:  es
Building language:  fr
Building language:  zh_CN
Building language:  zh_TW
make: Leaving directory '/home/bhseo/BOUT-dev/locale'
checking for .git... no
configure: creating ./config.status
config.status: creating make.config
config.status: linking ./externalpackages/fmt/src/format.cc to src/fmt/format.cxx
config.status: error: ./externalpackages/fmt/src/format.cc: file not found

**Comment by johnomotani** [comment]
@bellsis83 try doing `git submodule update --init --recursive` and then configure again. Sorry, sometimes the submodules (external packages) get confused. This command resets them. [I think Cmake may do a better job of updating them automatically, so once we switch over this problem should hopefully go away. Our use of Cmake is currently still a bit experimental.]

**Comment by bellsis83** [comment]
Hi @johnomotani,

Thanks,
I tried to do git submodule update --init --recursive but it did not give the fixed code so I manually downloaded and tried to run the lapd-drift. But I've got an error when doing make:

$ make
  Compiling  lapd_drift.cxx
lapd_drift.cxx: In member function ‘virtual int LAPDdrift::init(bool)’:
lapd_drift.cxx:280:76: warning: too many arguments for format [-Wformat-extra-args]
     output.write("Collisions: nueix = {:e}, nu_hat = {:e}\n", nueix, nu_hat);
                                                                            ^
lapd_drift.cxx:286:104: warning: too many arguments for format [-Wformat-extra-args]
 **NOTE: input from BOUT, Z length needs to be divided by {:e}\n", hthe0/rho_s);
                                                                              ^
lapd_drift.cxx:300:58: warning: too many arguments for format [-Wformat-extra-args]
     output.write("\tNormalising to rho_s = {:e}\n", rho_s);
                                                          ^
lapd_drift.cxx:420:35: error: no match for ‘operator=’ (operand types are ‘std::unique_ptr<Laplacian>’ and ‘Laplacian*’)
     phiSolver = Laplacian::create();
                                   ^
In file included from /usr/include/c++/7/memory:80:0,
                 from ../../include/dataformat.hxx:40,
                 from ../../include/datafile.hxx:20,
                 from ../../include/bout.hxx:40,
                 from ../../include/bout/physicsmodel.hxx:40,
                 from lapd_drift.cxx:6:
/usr/include/c++/7/bits/unique_ptr.h:281:7: note: candidate: std::unique_ptr<_Tp, _Dp>& std::unique_ptr<_Tp, _Dp>::operator=(std::unique_ptr<_Tp, _Dp>&&) [with _Tp = Laplacian; _Dp = std::default_delete<Laplacian>]
       operator=(unique_ptr&& __u) noexcept
       ^~~~~~~~
/usr/include/c++/7/bits/unique_ptr.h:281:7: note:   no known conversion for argument 1 from ‘Laplacian*’ to ‘std::unique_ptr<Laplacian>&&’
/usr/include/c++/7/bits/unique_ptr.h:301:2: note: candidate: template<class _Up, class _Ep> typename std::enable_if<std::__and_<std::__and_<std::is_convertible<typename std::unique_ptr<_Up, _Ep>::pointer, typename std::__uniq_ptr_impl<_Tp, _Dp>::pointer>, std::__not_<std::is_array<_Up> >, std::__or_<std::__and_<std::is_reference<_Dp>, std::is_same<_T2, _U2> >, std::__and_<std::__not_<std::is_reference<_Dp> >, std::is_convertible<_Ep, _Dp> > > >, std::is_assignable<_T2&, _U2&&> >::value, std::unique_ptr<_Tp, _Dp>&>::type std::unique_ptr<_Tp, _Dp>::operator=(std::unique_ptr<_Up, _Ep>&&) [with _Up = _Up; _Ep = _Ep; _Tp = Laplacian; _Dp = std::default_delete<Laplacian>]
  operator=(unique_ptr<_Up, _Ep>&& __u) noexcept
  ^~~~~~~~
/usr/include/c++/7/bits/unique_ptr.h:301:2: note:   template argument deduction/substitution failed:
lapd_drift.cxx:420:35: note:   mismatched types ‘std::unique_ptr<_Tp, _Dp>’ and ‘Laplacian*’
     phiSolver = Laplacian::create();
                                   ^
In file included from /usr/include/c++/7/memory:80:0,
                 from ../../include/dataformat.hxx:40,
                 from ../../include/datafile.hxx:20,
                 from ../../include/bout.hxx:40,
                 from ../../include/bout/physicsmodel.hxx:40,
                 from lapd_drift.cxx:6:
/usr/include/c++/7/bits/unique_ptr.h:310:7: note: candidate: std::unique_ptr<_Tp, _Dp>& std::unique_ptr<_Tp, _Dp>::operator=(std::nullptr_t) [with _Tp = Laplacian; _Dp = std::default_delete<Laplacian>; std::nullptr_t = std::nullptr_t]
       operator=(nullptr_t) noexcept
       ^~~~~~~~
/usr/include/c++/7/bits/unique_ptr.h:310:7: note:   no known conversion for argument 1 from ‘Laplacian*’ to ‘std::nullptr_t’
../../make.config:318: recipe for target 'lapd_drift.o' failed
make: *** [lapd_drift.o] Error 1

**Comment by johnomotani** [comment]
@bellsis83 what branch are you using? It looks like you are on `next`, but now have the wrong version of `lapd_drift.cxx`. If you cloned the repo with git, could you post the output of `git status`?

**Comment by bellsis83** [comment]
@johnomotani 

Here is the git status:

$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   BOUT.inp
	modified:   ../lapd_drift.cxx

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by johnomotani** [comment]
@bellsis83 I've made a fix based on the `master` branch. Could you please try this:
```
$ git reset --hard
$ git fetch
```
to return your repo to a clean state and get the new branch. Then (in the top-level BOUT-dev directory)
```
$ git checkout lapd-drift-fixes-master
$ make clean
$ make
```
Then try to re-build `lapd_drift` and run it.

**Comment by bellsis83** [comment]
@johnomotani 
It works very well!!
I appreciate your help very much!
Have a great weekend!
