### ISSUE TITLE
cmake: bout++.cxx is not rebuild

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1933]
With configure, whenever any file is rebuild, `bout++.cxx` is rebuild, to get the correct time stamp.

**Comment by ZedThree** [comment]
I've not worked out how to do this that doesn't result in `bout++.cxx` getting marked as always out of date -- that is, every time you build, it rebuilds `bout++.cxx` even if nothing has changed.

Might be possible to use an intermediate object library with all the files except `bout++.cxx`, and add a dependency between that file and the object library. Will investigate at some point, but it's not a high priority for me right now.

**Comment by ZedThree** [comment]
Fixed in #2301
