### ISSUE TITLE
cmake: generate files

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1934]
I cannot find code that seems to generate the generated fieldops?

Also adding `#error` to `src/field/gen_fieldops.jinja` does not break the build with cmake.

**Comment by dschwoerer** [comment]
Should be doable with:
https://cmake.org/cmake/help/latest/command/add_custom_command.html

I'll have a look ...

**Comment by ZedThree** [comment]
Fixed in #2119
