### ISSUE TITLE
Deprecated options

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1951]
There seem to be more examples currently broken:
```
$ for f in $(grep -e 's_opt\|s_mode' $(find|grep BOUT.inp )|cut -d: -f1|sort -u) ; do echo " - [ ] $f" ; done
```
gives

 - [ ] ./examples/2Dturbulence_multigrid/data/BOUT.inp
 - [ ] ./examples/advdiff2/data/BOUT.inp
 - [ ] ./examples/constraints/laplace-dae/data/BOUT.inp
 - [ ] ./examples/dalf3/data/BOUT.inp
 - [ ] ./examples/elm-pb/eigen/BOUT.inp
 - [ ] ./examples/elm-pb/Python/data0/BOUT.inp
 - [ ] ./examples/elm-pb/Python/data/BOUT.inp
 - [ ] ./examples/elm-pb/test/BOUT.inp
 - [ ] ./examples/gas-compress/advect1d/BOUT.inp
 - [ ] ./examples/gas-compress/sod-shock/BOUT.inp
 - [ ] ./examples/IMEX/advection-reaction/data/BOUT.inp
 - [ ] ./examples/lapd-drift/BOUT.inp
 - [ ] ./examples/lapd-drift/BOUT.inp.nn
 - [ ] ./examples/lapd-drift/BOUT.inp.nn_zem
 - [ ] ./examples/lapd-drift/data/BOUT.inp
 - [ ] ./examples/lapd-drift/lapd/BOUT.inp
 - [ ] ./examples/lapd-drift/pisces/BOUT.inp
 - [ ] ./examples/orszag-tang/data/BOUT.inp_1
 - [ ] ./examples/shear-alfven-wave/data/BOUT.inp
 - [ ] ./examples/tokamak-2fluid/data/BOUT.inp
 - [ ] ./examples/tokamak-2fluid/data/BOUT.inp_nl
 - [ ] ./examples/tokamak-2fluid/data/BOUT.inp_simple
 - [ ] ./examples/uedge-benchmark/data/BOUT.inp
 - [ ] ./tests/integrated/test-invpar/data/BOUT.inp
 - [ ] ./tests/integrated/test-simple-diffusion/data/BOUT.inp
 - [ ] ./tests/MMS/diffusion2/X/BOUT.inp
 - [ ] ./tests/MMS/diffusion2/XYZ/BOUT.inp
 - [ ] ./tests/MMS/diffusion2/Y/BOUT.inp
 - [ ] ./tests/MMS/diffusion2/Z/BOUT.inp
 - [ ] ./tests/MMS/diffusion/data/BOUT.inp
 - [ ] ./tests/MMS/spatial/diffusion/X/BOUT.inp
 - [ ] ./tests/MMS/wave-1d/data/BOUT.inp

**Comment by ZedThree** [comment]
Fixing this now
