### ISSUE TITLE
Throwing `BoutException` if restart fails

### ISSUE THREAD

**Issue by loeiten** [boutproject/BOUT-dev#196]
Is there any reason why a `BoutException` is not thrown if a restart variable fails to read?

The current behaviour in `bool Datafile::read()` (around line `315` in `datafile.cxx`) is to write a warning that the variable failed to read, and set the variable to 0. Wouldn't it be better to throw a `BoutException` instead?

**Comment by d7919** [comment]
Whilst I think this would make sense in most uses of restart I can imagine that there are some situations where you may want to use restart files from a reduced model as input to a model which evolves more fields for example. As such, this may be something where we want to introduce an input flag to decide if such things are fatal errors or not (defaulting to fatal)?

**Comment by bendudson** [comment]
Yes, turning on new equations from simpler runs was the motivation. I agree
though that in some cases this has bad consequences, and that throwing an
exception should be the default. An input flag ("restart:missing_is_fatal"
? ) could set the variable to zero as done now, but probably more useful
would be to initialise the variable from the input ("restart:init_missing"
?).

**Comment by ZedThree** [comment]
My vote would be for `restart:init_missing`, defaulting to `false` and throwing an exception. If true, do the current behaviour. `PhysicsModel::init` takes a bool for restarting, so if a model needs fancier behaviour than default initialisations for missing variables, it can check that and then do what it wants.

As long as the `BoutException` has a nice message reminding you to set `restarting:init_missing` if that's what you meant, any broken models will be easy to fix.

**Comment by loeiten** [comment]
Fixed in  16509eb
