### ISSUE TITLE
cmake: CXXFLAGS

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1977]
Is there a way to pass specific flags to cmake?
`cmake .. CXXFLAGS=fu`
seem to be ignored.

**Comment by johnomotani** [comment]
Passing on some info I got from @ZedThree: use the `CMAKE_CXX_FLAGS` argument to pass flags through cmake.

PS to search through possible variable names, the interactive interface that you get by running `ccmake ..` can be useful.

**Comment by ZedThree** [comment]
Just to expand on what @johnomotani says, use `-DCMAKE_CXX_FLAGS="<flags>"`

I think it does also pick up the usual environment variables, but you'd then need to do `CXXFLAGS cmake <args>`. Best to use the explicit option above though.

Also, I recommend using `cmake . -B <build dir>`. This basically does the same as the following:

```
mkdir build
cd build
cmake ..
```
