### ISSUE TITLE
cmake: shared library

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1978]
cmake has no way to build shared library?

**Comment by johnomotani** [comment]
You can use `-DBUILD_SHARED_LIBS=ON`. It's even in the examples in the manual https://bout-dev.readthedocs.io/en/latest/user_docs/installing.html#cmake under "A more complicated CMake configuration command might look like:" :smiley:

**Comment by dschwoerer** [comment]
Thanks, sorry for the noise.
I was looking at `-LH` but didn't see any options related to this.
