### ISSUE TITLE
interpolateAndExtrapolate not working as expected

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1982]
I had some issues with tests failing on coordinate_3d with next merged.

It seems the boundaries are not properly initialised. Specifically I was looking at `tests/integrated/test-coordinates-initialization` which failed with `J` not being positive. There it seems the boundaries (`J.fieldmesh->getBoundaries()`) only contain x boundaries, not y. Therefore only into the x boundaries is interpolated, not the y ones. I did not understand what could have broken this, until I realised this is the same for next.

This patch makes the error obvious:
```
diff --git a/src/mesh/coordinates.cxx b/src/mesh/coordinates.cxx
index a463cba32..c8a365f21 100644
--- a/src/mesh/coordinates.cxx
+++ b/src/mesh/coordinates.cxx
@@ -32,7 +32,16 @@ Field2D interpolateAndExtrapolate(const Field2D& f, CELL_LOC location,
     bool no_extra_interpolate = false) {
 
   Mesh* localmesh = f.getMesh();
-  Field2D result = interp_to(f, location, "RGN_NOBNDRY");
+  Field2D result_ = interp_to(f, location, "RGN_NOBNDRY");
+  result_.allocate();
+  Field2D result = result_;
+  result.allocate();
+  BOUT_FOR(i, result.getRegion("RGN_ALL")){
+    result[i]=BoutNaN;
+  }
+  BOUT_FOR(i, result.getRegion("RGN_NOBNDRY")){
+    result[i]=result_[i];
+  }
   // Ensure result's data is unique. Otherwise result might be a duplicate of
   // f (if no interpolation is needed, e.g. if interpolation is in the
   // z-direction); then f would be communicated. Since this function is used
@@ -40,7 +49,6 @@ Field2D interpolateAndExtrapolate(const Field2D& f, CELL_LOC location,
   // field lines (due to dependence on integrated shear), we don't want to
   // communicate f. We will sort out result's boundary guard cells below, but
   // not f's so we don't want to change f.
-  result.allocate();
   localmesh->communicate(result);
 
   // Extrapolate into boundaries (if requested) so that differential geometry
```
This ensure that after `interp_to` only the region `RGN_NOBNDRY` is valid, and the boundaries contain NaNs.

Am I missing something?
Is there a bug that there are no y boundaries?
Is there a bug in communicate? (the communicate test also fails)

**Comment by johnomotani** [comment]
`test-coordinates-initialization` and `test-communications` both pass for me using `next`.

The defaults for `ixseps1` and `ixseps2` (which are `nx`) mean that `test-coordinates-initialization` should be in a 'core' region, with the y-guard cells all set by communication. So there should be no y-boundaries in that test, and it seems like you probably have a bug in `communicate` that I don't see with `next` (gcc7.5.0, openmpi2.1.1).

**Comment by dschwoerer** [comment]
Thanks for the quick reply. I'll look into the communications :-)

At least for test-communications this seems to be now reproducible on travis. After it fail for me with pvode that no variable is evolved, I added `f` to be evolved and that causes the problem: https://travis-ci.org/github/boutproject/BOUT-dev/builds/665637249

**Comment by johnomotani** [comment]
This is strange... `next` passed on Travis 5 days ago! #1885 went in recently and did make changes to the communications though, so not impossible it's introduced a bug of some sort.

**Comment by dschwoerer** [comment]
It is only reproducible if `f` is evolved - without evolving `f` this works. What I am not certain of is why `f` doesn't need to be evolved, maybe because travis is using petsc/slepc in all cases, rather then pvode?

**Comment by johnomotani** [comment]
Travis is probably using cvode rather than pvode (and I am too). Maybe the implementations have some different check?

**Comment by johnomotani** [comment]
The problem is the boundaries, not the communications. Once you call `SOLVE_FOR(f)`, f has boundary conditions applied, which default to Dirichlet. The test was not expecting those (it sets the boundary cells to special values to test their communications), so this causes the fail. Adding
```
[f]
bndry_all = none
```
in `data/BOUT.inp` and `data_limiter/BOUT.inp` makes the `SOLVE_FOR` version of the test pass.

This might show why a test like this should use a custom main rather than a PhysicsModel... I converted while checking this error, so I'll make a PR.

**Comment by dschwoerer** [comment]
Have you also tried to apply the above patch? I have pushed it to travis, and that breaks the unit-tests, so I am not sure the integrated tests would all pass ...
