### ISSUE TITLE
'VERSIONS' file

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#1992]
We have a `VERSIONS` file in the top level https://github.com/boutproject/BOUT-dev/blob/next/VERSIONS that hasn't been updates since 1.0 in 2011, and is superseded by the `CHANGELOG.md`. Maybe it should be removed?

**Comment by bendudson** [comment]
Yes, I think this can go. It's funny that some things never change. May 2010: "...there are a few things like boundary conditions and topology which need working on"

**Comment by ZedThree** [comment]
Funny sometimes the stuff that's right under your nose and you never notice!
