### ISSUE TITLE
example:  lapd_drift - how to get a perpendicular wave number?

### ISSUE THREAD

**Issue by bellsis83** [boutproject/BOUT-dev#2013]
Hi,

I am trying to run the example of the lapd drift. I want to get a perpendicular mode number. However, there is no option for a m_theta. There is only option for a mode number filter of z. I would appreciate if you could give an answer of how to get a results with a specific azimuthal mode number.

**Comment by bendudson** [comment]
In this simulation the z direction is the azimuthal angle, so filtering z filters the azimuthal mode number. Filtering in y (parallel, axis of the device) or x (radial) is more difficult, but could probably be done if needed.

Getting support might be easier through Slack; send me an email if you would like to be added (benjamin.dudson at york dot ac dot uk)

**Comment by ZedThree** [comment]
I think this is solved now
