### ISSUE TITLE
only add once to dump file isn't working

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#2014]
The test only passed by incidence.
https://github.com/boutproject/BOUT-dev/commit/73e7ad8c54545d627c26919f50e2d025410aff17 shouldn't change anything, but [travis fails](https://travis-ci.org/github/boutproject/BOUT-dev/builds/673521478)

Observed something similar on [copr on centos 8](https://download.copr.fedorainfracloud.org/results/davidsch/epel8/epel-8-x86_64/01334298-bout++/builder-live.log.gz) while trying to build 4.3.1 for epel 8

**Comment by ZedThree** [comment]
Is this the same issue that was fixed in #2093 ?

**Comment by dschwoerer** [comment]
f42b15e should tell :+1:

**Comment by dschwoerer** [comment]
Yes this is resolved, tests pass now.
