### ISSUE TITLE
PETSc changed, breaking tests

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#2033]
We are checking [here](https://github.com/boutproject/BOUT-dev/blob/next/tests/unit/include/bout/test_petsc_vector.cxx#L211) that petsc fails on some things. However, that isn't the case anymore.

This makes next now fail, while it did work in the past.
This is the case for PETSc 3.13.1 and 3.12.5

After fixing that,  PetscVectorTest/0.TestDestroy fails:
```
[ RUN      ] PetscVectorTest/0.TestDestroy
Fatal error in MPIR_CommGetAttr: Invalid communicator, error stack:
MPIR_CommGetAttr(286): MPIR_Comm_get_attr(MPI_COMM_NULL, comm_keyval=-1539309568, attribute_val=0x7fff8ef1ec30, flag=0x7fff8ef1ec2c) failed
MPIR_CommGetAttr(58).: Null communicator
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1007315461
```

This is also in both cases.

**Comment by ZedThree** [comment]
I can't see anything in their changelogs about changing this :(
And the [doc page](https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/Vec/VecSetValues.html#VecSetValues) still says it's an error.

Should that test be in `#if CHECKLEVEL >= 1`? Looks like the calls to `PetscVector/Matrix::operator()` only throw if that condition is met.

Does this test fail too: https://github.com/boutproject/BOUT-dev/blob/next/tests/unit/include/bout/test_petsc_matrix.cxx#L246

Don't know about the destroy test yet

**Comment by dschwoerer** [comment]
I doubt it's a checklevel - I have configured with default checklevel.
Yes, the other mixed test is also affected.

I don't see where it mentions that mixing adding and replacing is supposed to be an error?

**Comment by ZedThree** [comment]
> Calls to VecSetValues() with the INSERT_VALUES and ADD_VALUES options cannot be mixed without intervening calls to the assembly routines.

It doesn't say what will happen if you do though.

**Comment by dschwoerer** [comment]
Sorry, was an error on my side.
I had system libraries installed, which interfered with the other version.
Thanks for the help :+1:
