### ISSUE TITLE
Get rid of macros/functions taking different number of arguments

### ISSUE THREAD

**Issue by JensMadsen** [boutproject/BOUT-dev#204]
There are the macros GRID_LOAD, GRID_LOAD2 ...., GRID_LOAD6. which take 1 to 6 arguments. 
We could use List initializers or variadic templates instead see e.g. 

http://stackoverflow.com/questions/10044449/a-function-with-variable-number-of-arguments-with-known-types-the-c11-way

**Comment by bendudson** [comment]
Yes, definitely. At the moment the "master" branch is compatible with C++98, but lots of C++11 features are already used in the "next" branch. Many of these macros (SOLVE_FOR is similar) could be replaced with variadic functions in the next branch.

**Comment by ZedThree** [comment]
Unfortunately, it looks like all the variadic macros used in BOUT++ stringify one of their arguments (i.e. turn it into a literal string). To my knowledge, this is literally impossible without a preprocessor macro.

I'm marking this as "won't fix", but it's really more like "can't fix".
