### ISSUE TITLE
autoreconf broken?

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#2050]
After running autoreconf, `autoconf_build_defines.hxx.in` is changed:
```diff
@@ -72,4 +72,122 @@
 /* Enable field name tracking */
 #undef BOUT_USE_TRACK
 
-// NOTE TO DEVELOPERS: PLEASE KEEP THIS LINE AND DELETE AUTOGENERATED CONTENT BELOW!
+/* Define to 1 if translation of program messages to the user's native
+   language is requested. */
+#undef ENABLE_NLS
 ...
```

Is this important?
It seems like that might break the `autoreconf && ./configure` workflow.

**Comment by ZedThree** [comment]
No, they're just defines that we don't use and are un-namespaced so potentially conflict with other libraries defines. The note is there so that we don't commit those changes.
