### ISSUE TITLE
verbose-field-compat protected?

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#2057]
I cannot delete the branch: https://github.com/boutproject/BOUT-dev/tree/verbose-field-compat

Is there a reason it is protected or can someone delete it?

**Comment by ZedThree** [comment]
I think the pattern for protected branches only accepts wildcards, rather than actual regexes. It's `v*-*` which captures that branch name. Oops!

**Comment by dschwoerer** [comment]
maybe change to `v?.?.?-*`?
That fails if we go past version 9, and needs to be updated.
Otherwise `v*.*.*-*` ... ?

Regexp would be much nicer -.-

**Comment by ZedThree** [comment]
Changed to `v*.*-*` which seemed to be sufficient.
