### ISSUE TITLE
Error installing BOUT with Pnetcdf

### ISSUE THREAD

**Issue by aeiou6630** [boutproject/BOUT-dev#2067]
Hi, 

I'm trying to install the latest version (4.3.1) of BOUT++ on my Ubuntu subsystem in Windows 10. 

When I configured BOUT-dev it with
`--with-pnetcdf=/usr/local`
, it could find the file "pnetcdf.h", but then seemed trying to find "libpnetcdf.a" in "/lib" directory, and showed:
```
configure: Searching for Parallel-NetCDF library
checking for /usr/local/include/pnetcdf.h... yes
checking for /lib/libpnetcdf.a... no
checking for /lib64/libpnetcdf.a... no
configure: error: in `/home/fchang/BOUT-dev-4.3.1/BOUT-dev':
configure: error: *** Parallel-NetCDF requested but not found
See `config.log' for more details
```

Of course it could not find it, because my "libpnetcdf.a" had been installed into "/usr/local/lib". So I wonder if there's any way to specify the path to the library.

I attach the config.log file here. Please let me know if further information is needed. Thanks!
[config.log](https://github.com/boutproject/BOUT-dev/files/5050155/config.log)

**Comment by bendudson** [comment]
Thanks for the report. At the moment I recommend not using pnetcdf; it's an experimental feature and I'm not sure that it works even once configured and compiled. For now please use NetCDF or HDF5 (many examples need netcdf support to read the input files). 
Overhauling the file I/O, partly for performance and parallel I/O, is a high priority for the next major release, but as far as I know no-one's working on it at the moment.

**Comment by aeiou6630** [comment]
Got it. 

Thanks for your reply.
