### ISSUE TITLE
Error installing with SUNDIALS >3.0

### ISSUE THREAD

**Issue by aeiou6630** [boutproject/BOUT-dev#2068]
Hi,

I'm trying to install the latest version (4.3.1) of BOUT++ on my Ubuntu subsystem in Windows 10.

I built sundials-v4.1.0 in "/usr/local" and then built BOUT-dev with sundials by
`./configure --with-pnetcdf=no --with-sundials=/usr/local --with-petsc=/home/fchang/BOUT-dev-4.3.1/petsc-3.9.4 --enable-openmp`

The configure step was successful. Unfortunately, when trying to `make` BOUT, I got such error:
```
  Compiling  arkode.cxx
arkode.cxx:51:10: fatal error: arkode/arkode_spgmr.h: No such file or directory
   51 | #include <arkode/arkode_spgmr.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Though the [BOUT web page](https://bout-dev.readthedocs.io/en/latest/user_docs/advanced_install.html#sundials) said it supported sundials v2.6-v4.1, I found actually "arkode_spgmr.h" has no longer existed since sundials-3.0. So I guess either the information given on the web page is wrong, or my installation setting is incorrect. 

I attach the config.log and the messages shown on screen here. Hope they're helpful.
[config.log](https://github.com/boutproject/BOUT-dev/files/5050843/config.log)
[message_on_screen.txt](https://github.com/boutproject/BOUT-dev/files/5050844/message_on_screen.txt)

Thanks.

**Comment by bendudson** [comment]
Thanks for the report. A quick workaround for now would be to not use arkode: `--with-sundials` enables all SUNDIALS solvers: CVODE, IDA and ARKODE. Please try `--with-cvode` instead, which is the most commonly used solver.

**Comment by aeiou6630** [comment]
Understood. Thanks!

**Comment by ZedThree** [comment]
You're right that `arkode_spgmr.h` doesn't exist since SUNDIALS 3. We should only be including it for version 2: https://github.com/boutproject/BOUT-dev/blob/14a36b1eb005586182fbe856502a266275b6fdf5/src/solver/impls/arkode/arkode.cxx#L42-L53

The `SUNDIALS_VERSION_MAJOR` should be coming from here: https://github.com/boutproject/BOUT-dev/blob/14a36b1eb005586182fbe856502a266275b6fdf5/src/solver/impls/arkode/arkode.hxx#L38

You might need to check `/usr/local/include/sundials/sundials_config.h` contains that macro. Close to the top you should see something like

```
/* Define SUNDIALS version numbers */
#define SUNDIALS_VERSION "4.1.0"
#define SUNDIALS_VERSION_MAJOR 4
#define SUNDIALS_VERSION_MINOR 1
#define SUNDIALS_VERSION_PATCH 0
```

If you don't have that, I think something must have gone wrong installing SUNDIALS. If you do have that, something has gone wrong at our end.

**Comment by aeiou6630** [comment]
Hi,

I do have the code you mentioned in the last part. Let me attach my sundials_config.h here:
[sundials_config.h.txt](https://github.com/boutproject/BOUT-dev/files/5057389/sundials_config.h.txt)

Thanks for your reply!

**Comment by ZedThree** [comment]
Hi @aeiou6630, sorry it's taken me some time to look at this. Is it possible you built PETSc with SUNDIALS enabled? I'm currently thinking it's picking up PETSc's version of SUNDIALS which was v2.5 for PETSc v3.9.4

`configure` is supposed to check if PETSc was built with SUNDIALS and, if so, warn/fail if you try to build BOUT++ with both. That seems to be failing us here.

**Comment by ZedThree** [comment]
Sorry, I forgot to actually write the solution -- either remove the `--download-sundials` flag when building PETSc, or don't use SUNDIALS directly with BOUT++. It is possible to use SUNDIALS through PETSc

**Comment by aeiou6630** [comment]
Hi,

Exactly, I built PETSc with `--download-sundials`. Do you mean that gave rise to the conflict between two versions of SUNDIALS, installed for PETSc and for BOUT, and thus lead to the problem I got? 

Anyway, I'll try what you say and reply if I have any problem.

Thanks for your reply.

**Comment by ZedThree** [comment]
I assume this is fixed and was due to the conflicting SUNDIALS versions. @aeiou6630 feel free to reopen this if you're still having issues.
