### ISSUE TITLE
Error about "MPL_wtime" when make check with PETSc 

### ISSUE THREAD

**Issue by aeiou6630** [boutproject/BOUT-dev#2069]
Hi, 

I'm installing BOUT++ with PETSc-3.9.4 on a Ubuntu-20.04.1 LTS subsystem in Windows 10. I got an error about "MPL_wtime" when doing `make check` step. 

The commands I used to build PETSc-3.9.4 were:
```
./configure --with-cc=gcc --with-cxx=g++ --with-fc=gfortran --with-precision=double --with-scalar-type=real --with-shared-libraries=0 --with-debugging=yes --download-sundials --download-mumps --download-scalapack --download-blacs --download-fblas-lapack=1 --download-parmetis --download-ptscotch --download-metis --download-mpich
make PETSC_DIR=/home/fchang/BOUT-dev-4.3.1/petsc-3.9.4 PETSC_ARCH=linux-gnu-c-debug all
make PETSC_DIR=/home/fchang/BOUT-dev-4.3.1/petsc-3.9.4 PETSC_ARCH=linux-gnu-c-debug check
```
And the commands I used to build BOUT++ were:
```
export PATH=$/usr/local/bin:$PATH
export LD_LIBRARY_PATH=$-L/usr/local/lib:$LD_LIBRARY_PATH
export PETSC_DIR=/home/fchang/BOUT-dev-4.3.1/petsc-3.9.4
export PETSC_ARCH=arch-linux2-c-debug
./configure --with-pnetcdf=no --with-cvode=/usr/local --with-petsc=/home/fchang/BOUT-dev-4.3.1/petsc-3.9.4
make
make check
```
Then came the error message like the following when processing `linking tests` in `make check`
```
/usr/bin/ld: /home/fchang/BOUT-dev-4.3.1/petsc-3.9.4/arch-linux2-c-debug/lib/libmpifort.a(lib_libmpifort_la-wtimef.o): in function `init_wtick':
/home/fchang/BOUT-dev-4.3.1/petsc-3.9.4/arch-linux2-c-debug/externalpackages/mpich-3.3b1/src/mpl/include/mpl_timer.h:235: undefined reference to `MPL_wtime'
/usr/bin/ld: /home/fchang/BOUT-dev-4.3.1/petsc-3.9.4/arch-linux2-c-debug/externalpackages/mpich-3.3b1/src/mpl/include/mpl_timer.h:237: undefined reference to `MPL_wtime'
/usr/bin/ld: /home/fchang/BOUT-dev-4.3.1/petsc-3.9.4/arch-linux2-c-debug/externalpackages/mpich-3.3b1/src/mpl/include/mpl_timer.h:238: undefined reference to `MPL_wtime_diff'
/usr/bin/ld: /home/fchang/BOUT-dev-4.3.1/petsc-3.9.4/arch-linux2-c-debug/externalpackages/mpich-3.3b1/src/mpl/include/mpl_timer.h:244: undefined reference to `MPL_wtime_diff'
```
It seems to indicate improper linkage between PETSc and the MPICH it downloaded. If that's the case, maybe the way I built PETSc was wrong. But perhaps the settings in BOUT's tests could also lead to the error. I cannot judge that by myself, so write this post to ask for suggestions. 

Thanks!

------Attached files------
[config.log](https://github.com/boutproject/BOUT-dev/files/5057145/config.log)
[config-build.log](https://github.com/boutproject/BOUT-dev/files/5057147/config-build.log)
[make.config.txt](https://github.com/boutproject/BOUT-dev/files/5057152/make.config.txt)
[message_on_screen.txt](https://github.com/boutproject/BOUT-dev/files/5057175/message_on_screen.txt)

**Comment by ZedThree** [comment]
It looks like you're getting PETSc to download and compile MPICH. This might be conflicting with the version of MPI you're using to build BOUT++.

I suggest to try removing `--download-mpich` when configuring PETSc. You may then need to change `--with-cc`, `--with-cxx` to point to the MPI wrappers (`mpicc` and `mpic++`), especially if you are not using the system MPI.

**Comment by aeiou6630** [comment]
Hi,

Thanks for your reply. That solves the problem.
