### ISSUE TITLE
boundary width MXG and MYG from grid files

### ISSUE THREAD

**Issue by JensMadsen** [boutproject/BOUT-dev#207]
As far as I can see these parameters are not read from the gridfile? They must be set from the BOUT.inp file.  

Is this an intended feature? I would prefer to keep as much information in the grid file as possible (information that belongs there only of course)

**Comment by bendudson** [comment]
This is a good point, it  is really a property of the grid. I think the motivation for putting it in the BOUT.inp file is that the MXG and MYG values which are needed depend on the order of the differencing schemes, which are set in BOUT.inp: High order schemes can't be used if MXG=1, for example.

**Comment by johnomotani** [comment]
This issue was repeated in #493 and fixed in #494.
