### ISSUE TITLE
Update {fmt} for NVCC

### ISSUE THREAD

**Issue by bendudson** [boutproject/BOUT-dev#2081]
The master branch of `{fmt}` includes some fixes for the nvidia compiler
https://github.com/fmtlib/fmt/pull/1818
Can we update the submodule to the latest master commit?

**Comment by ZedThree** [comment]
Yes! I'm hoping there's also a fix for an annoying warning with GCC 9.
Might be good to bump googletest too

**Comment by ZedThree** [comment]
Found a possible bug either with us or `{fmt}` with fmt#1818, one single unit test fails. Will investigate.

The annoying warning is actually in mpark.variant, so I will bump that too

**Comment by ZedThree** [comment]
Fixed in #2082
