### ISSUE TITLE
data attributes of BOUT.dmp.*.nc change

### ISSUE THREAD

**Issue by ZhaoZhmeng** [boutproject/BOUT-dev#2092]
Now, i install bout++ on the new cluster ,.After running a new code ,when i analysics data of BOUT.dmp.*.nc by python ,i don't do  this . 

When i use collect to collect data ,display as follows
      Python 3.8.3 (default, Jul  2 2020, 16:21:59) 
      [GCC 7.3.0] :: Anaconda, Inc. on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from boutdata.collect import collect
    >>> ni=collect("Ni")
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/zhaozhimeng/bout-2020/tools/pylib/boutdata/collect.py", line 158, in collect
        raise ValueError("Missing MXSUB variable")
    ValueError: Missing MXSUB variable

Through display ,i know the problem should happend the variable MXSUB.

Next , I write a script to read variable by python .

  from boututils.datafile import DataFile
  import netCDF4      ##read netcdf4 library
  from boututils.plotdata import plotdata
  f=DataFile("BOUT.dmp.0.nc")
  mxsub=f.read("MXSUB")
  print(f.list())
  print(mxsub)

The result don't have MXSUB .

Then , i tried to analysics two BOUT.dmp.*.nc by matlab. 
The first file is old version . And  we can  normally use the data of this file . When i used ncread command to read this file and ncdisp command to display the variable information . (file:1.txt)
[1.txt](https://github.com/boutproject/BOUT-dev/files/5193443/1.txt)

The second file is new vertion  which generate after install bout on new cluster .  And this file is the same file as the starting file above . I applied the same menthod to deal this file , but I gain the different variable information.(file:0.txt)
[0.txt](https://github.com/boutproject/BOUT-dev/files/5193451/0.txt)

I don't know why or how this problem .Please give some me some solutions to the problems.
Thanks!

**Comment by johnomotani** [comment]
@ZhaoZhmeng what version of BOUT++ are you using? `MXSUB` should always be written, at least if you use the `PhysicsModel` interface - which you will be unless you wrote your own custom `int main()` function.

**Comment by ZhaoZhmeng** [comment]
> @ZhaoZhmeng what version of BOUT++ are you using? `MXSUB` should always be written, at least if you use the `PhysicsModel` interface - which you will be unless you wrote your own custom `int main()` function.

Thanks！I think it is probably because the version of my netcdf-c is too high. 
When I reinstalled a lower version of netcdf-c, the problem was solved

**Comment by johnomotani** [comment]
Not sure what the problem was here - I've tested the conduction example in `next` with netcdf-4.7.4 (which is the latest release). It writes `MXSUB` correctly, through the Ncxx4 interface. I don't seem to have a convenient place to test the legacy interface...
