### ISSUE TITLE
Issues with testing 

### ISSUE THREAD

**Issue by griffinfarrow** [boutproject/BOUT-dev#2096]
I've been trying to set up BOUT++ on a virtual machine using Ubuntu 18.04. Configuring and compiling seems to run fine, as well as the unit tests, but there is an issue in the integrated tests (in test-io). I've attached the log files and the make.config file

[log.zip](https://github.com/boutproject/BOUT-dev/files/5202313/log.zip)

Griffin

**Comment by griffinfarrow** [comment]
This is the actual error message:

[error.txt](https://github.com/boutproject/BOUT-dev/files/5202386/error.txt)

**Comment by johnomotani** [comment]
We found the bug causing this yesterday. There's a fix on the way in https://github.com/boutproject/BOUT-dev/pull/2093

**Comment by johnomotani** [comment]
The bottom line is this problem is unlikely to affect you - the workaround is to be careful not to add any `FieldPerp` to the output file more than once, which would be a pretty strange thing to do anyway!

**Comment by ZedThree** [comment]
Fixed in #2093
