### ISSUE TITLE
Providing netcdf-cxx4

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#2105]
I think we discussed a while back what interface to use to netcdf if/when we refactor `DataFile`, etc. and the consensus was that we'd want to keep using [netcdf-cxx4](https://github.com/Unidata/netcdf-cxx4/tree/master/cxx4) because otherwise we'd end up basically wanting a C++ wrapper around the netcdf C-interface anyway. Issue is that `netcdf-cxx4` is often not provided on clusters, or only provided for a specific compiler (e.g. for icc and I want to use gcc). Could something be done to make life easier? Maybe include `netcdf-cxx4` as a submodule, or provide a `--download-netcdf-cxx4` option (or cmake-equivalent - I guess we're going to cmake-only for 5.0?) like PETSc does for external packages?

**Comment by ZedThree** [comment]
Yes, it's absolutely crucial that it's easy to build BOUT++, including all of our hard dependencies, so I will put the work in to make sure that it is! I have got some changes merged into netcdf-cxx4 that should help here, but it's possible more changes are needed.

CMake has a `FetchContent` function that can download dependencies if we don't want to end up with a ton of submodules.

I would like to go CMake-only for 5.0, it would make my life a bit easier, but I'm not BDFL :smile:

**Comment by johnomotani** [comment]
I'd vote for CMake-only 5.0. I'm only still using `configure` with existing set-ups on the principle of 'if it ain't broke don't fix it'.

**Comment by dschwoerer** [comment]
I wouldn't mind switching to cmake, but there are still some [outstanding issues](https://github.com/boutproject/BOUT-dev/issues?q=is%3Aissue+is%3Aopen+label%3Abuild-system) that make the current cmake a no-go (imho)

https://github.com/boutproject/BOUT-dev/pull/2025 is also having issues with the cmake system.

**Comment by bendudson** [comment]
I too would vote for having a single build system rather than supporting two. It seems that CMake is the way things are going, and if it can make handling dependencies less painful then that's another point in its favour. 
At the moment I'd be happy to treat the CMake as the main way to build BOUT++ 5.0: We aim to remove autoconf in 5.0, replacing all its functions with CMake. If at the 5.0 release time CMake can't do everything we need then we keep autoconf as a legacy/backup.

**Comment by ZedThree** [comment]
Thanks @bendudson , that seems like the most reasonable way forward.

I will say for those people still unsure about CMake, if you use Ninja\* it is _significantly_ faster to build. Using shared libraries as well makes it much faster to link (and uses less disk space).

\* `pip install ninja` to get it, and then just pass `-G Ninja` to CMake

**Comment by ZedThree** [comment]
Added in #2138
