### ISSUE TITLE
documentation on processor splitting

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#2106]
The documentation on what values of `NXPE` and `NYPE` are allowed is a bit terse - from l.297 onward here https://github.com/boutproject/BOUT-dev/blame/next/manual/sphinx/user_docs/bout_options.rst.

> In BOUT++, grids can be split between processors in both X and Y directions. By default BOUT++ automatically divides the grid in both X and Y, finding the decomposition with domains closest to square, whilst satisfying
constraints. These constraints are:
>
>- Every processor must have the same size and shape domain
>
>- Branch cuts, mostly at X-points, must be on processor boundaries. This is because the connection between grid points is modified in BOUT++  by changing which processors communicate.

I think all the following information is useful, but it's too long-winded, and I'm having a brain-freeze at the moment about how to write something nicer

* the option `nx` is the total number of points in the x-direction including boundary points, so `nx` is usually "(number of grid points in x-direction) + 4". [This will probably change for the 5.0 release to be nx is the number of grid points, but I don't think it has been changed yet]
* the option `ny` is the number of points in the y-direction *not* including boundary cells. [i.e. this is inconsistent at the moment with the way `nx` is defined]
* NXPE must divide the number of grid points in the x-direction (i.e. nx-4)
* for simple slab grids NYPE must divide the number of grid points in the y-direction (i.e. ny)
* for general topologies, the number of points per processor `mysub=ny/nype` (which must be an integer) must divide the number of points in each region (2 divertor legs and core for single-null; 4 divertor legs, inner core and outer core for double-null; here when I write 'core' I mean 'the region including the core but also part of the SOL' - sorry, I don't know a good word for it so 'core' is sometimes used in BOUT++ when talking about the grid topology as a shorthand even though it's not totally accurate).
* When BOUT++ automatically chooses NXPE and NYPE it finds all valid pairs which give (total number of procs)=NXPE*NYPE and satisfy the constraints above, then chooses the one which makes the grid on each processor as close to square as possible.

**Comment by ZedThree** [comment]
Thanks John! Probably even just what you've written here is a good starting point, at the very least.

>  here when I write 'core' I mean 'the region including the core but also part of the SOL' - sorry, I don't know a good word for it so 'core' is sometimes used in BOUT++ when talking about the grid topology as a shorthand even though it's not totally accurate

Getting a good name for this would be lovely. Suggestions off the top of my head:
- "edge" is sometimes used for this region, although I've found it's overloaded depending on who you talk to. It might also get confused for the very outer edge of the grid
- "separatrix"
- "trans-separatrix"
- "threshold"
- "liminal"

It would be very nice to have consistent definitions for `nx, ny, nz` in 5.0 (including boundaries in Z), though I am a little worried about exactly what will break if we make that change for `nx`.

**Comment by johnomotani** [comment]
Yeah, I'd avoid 'edge' - it's too ambiguous already!
Trouble with 'separatrix' is that there is a separatrix in the divertor legs between SOL and PFR regions.
I asked Sarah and she came up with 'core and adjacent SOL' which I think is my favourite suggestion so far. Maybe we could abbreviate to 'core+adjacent' sometimes.

**Comment by dschwoerer** [comment]
(As things in closed PRs / issues tend to get lost)
https://github.com/boutproject/BOUT-dev/pull/2109#discussion_r495072180

**Comment by ZedThree** [comment]
Thanks for the reminder, done in b4e0935b8
