### ISSUE TITLE
Issue with pow() with non-integer powers

### ISSUE THREAD

**Issue by griffinfarrow** [boutproject/BOUT-dev#2112]
I'm trying to write a nonlinear conduction problem, similar to the normal conduction example described in the documentation. I'm trying to solve the equation dT/dt = Div(q), with q = Af(T) Grad(T). I'm just using f(T) = T^some power.

Whilst my setup works fine for integer powers, it fails immediately for non-integer powers. I've been trying to use f(T) = T^(2.5) to get something resembling Spitzer-Harm heat flow. However, even if I make the power extremely close to an integer (e.g. 2.0000001), the code will still fail. In the long run, I'd like to implement a code with Braginskii transport coefficients, which I would naively try to implement in the same way. 

I appreciate that this is probably not a bug, and more likely to be me not implementing this correctly, but I'd appreciate any help/pointing in the direction of some documentation for a better way to implement transport coefficients/fluxes

I've attached my cxx file and input script (saved as textfiles)

[conduction.txt](https://github.com/boutproject/BOUT-dev/files/5312509/conduction.txt)
[BOUT.inp.txt](https://github.com/boutproject/BOUT-dev/files/5312510/BOUT.inp.txt)

**Comment by johnomotani** [comment]
It would help if you could post the error message when it 'fails'.

I guess if `T` goes negative somewhere it would make a difference whether the power is integer or not, but physically that should not be happening...

**Comment by griffinfarrow** [comment]
This is the logfile produced:
[BOUT.log](https://github.com/boutproject/BOUT-dev/files/5312582/BOUT.log)

**Comment by griffinfarrow** [comment]
Thank you so much, I understand the problem now.
