### ISSUE TITLE
MXG and MYG saved to the restart files

### ISSUE THREAD

**Issue by loeiten** [boutproject/BOUT-dev#212]
Currently `MXG` and `MYG` are not saved in the restart files, and as far as I see there are no unique way to identify the `MXG` and `MYG` used in the run from the restart file alone. Would it be an idea to include these in the restart files?

**Comment by bendudson** [comment]
Currently MXG and MYG are saved in the output (dmp) files, but not in the
restart files. I agree this would be good to add, though it should be done
in the BoutMesh class I think, since these are really Mesh specific things.

**Comment by bendudson** [comment]
This is fixed by PR #508
