### ISSUE TITLE
Why is shiftangle set to zshift if not found? 

### ISSUE THREAD

**Issue by JensMadsen** [boutproject/BOUT-dev#214]
Is this ever correct?

**Comment by bendudson** [comment]
This calculation from zshift will always be slightly wrong, but is a guess
for the shiftangle if nothing better is available. A warning is printed,
but it probably would be best to throw an error unless the user explicitly
turns on a flag to say that this should be done.

**Comment by JensMadsen** [comment]
I agree :-D
