### ISSUE TITLE
Restart files can be read incorrectly

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#2141]
I have some tests that load restart files, run and then check the output against expected output. I changed `MXG` in the input file and ran the tests. Unsurprisingly they failed, but they failed by producing incorrect output rather than throwing an error. I think what happened is that since `LocalNx` and `LocalNy` when I tried to run with `MXG=1` are smaller than when the restart files were created with `MXG=2`, the arrays in the restart files are big enough that they never go out of bounds when being read, and BOUT++ reads in values from the file offset by 1 from where it should be reading.

The simplest fix would be to just check that relevant things are the same in the restart file as in the run: [`MXG`, `MYG`, `MZG`] and/or the array size compared to [`LocalNx`, `LocalNy`, `LocalNz`].

Since we generally don't need the guard or boundary cells from restart files, in principle it should be possible to load from them even if `MXG`, `MYG` or `MZG` change. We'd need to get the values of those variables that the restart file was created with, and use those to calculate the appropriate offsets, etc. This would be a lot more work though, and I'd be happy with just throwing an error.

**Comment by johnomotani** [comment]
Just realised that since I create the restart files for my tests with a Python script, I can probably fix the tests in there, so I really don't need a new feature to allow changing `MXG`...

**Comment by johnomotani** [comment]
PS this happened using the `Ncxx4` I/O implementation, and also happens when I set `CHECK=3`.

**Comment by ZedThree** [comment]
Yes, definitely a good idea to add some checks that the mesh sizes are the same in the restarted run. We can always relax that later if we add a feature to restart with different sizes.

**Comment by johnomotani** [comment]
Fixed by #2145
