### ISSUE TITLE
Problem running hasegawa-wakatani-3d example in next-hypre-outerloop branch with petsc3damg type for Laplacian

### ISSUE THREAD

**Issue by ADimits** [boutproject/BOUT-dev#2169]
Opening this issue to communicate/document the problem - remind me how best to pass information, e.g., environment, run logs, etc.

Bout.inp:

[mesh]

nx = 68  # Note 4 guard cells in X
ny = 16 
nz = 64  # Periodic, so no guard cells in Z

dx = 0.2
dy = 1.
dz = 0.2

NXPE = 1

# Set periodic boundary condition in y
ixseps1 = nx
ixseps2 = nx 

[laplace]

flags = 0   # Flags for Laplacian inversion
type = petsc3damg

.
.

$ mpirun -n 1 hw
.
.

Run started at  : Mon 07 Dec 2020 10:23:48 AM PST
	Option restart = false (default)
	Option append = false (default)
	Option dump_on_restart = 1 (default)
	Option wall_limit = -1 (default)
	Option stopCheck = 0 (default)
Sim Time  |  RHS evals  | Wall Time |  Calc    Inv   Comm    I/O   SOLVER

0.000e+00          1       6.82e-01    98.8    0.0    0.1    0.8    0.3
1.000e+00        435       2.54e+01    95.5    0.0    0.3    0.1    4.1
.
.

$ mpirun -n 2 hw

.
.
Finding value for NXPE (ideal = 2.828427)
	Candidate value: 1
	 -> Good value
	Candidate value: 2
	 -> Good value
	Domain split (NXPE=2, NYPE=1) into domains (localNx=32, localNy=16)
.
.

Run started at  : Mon 07 Dec 2020 10:23:16 AM PST
	Option restart = false (default)
	Option append = false (default)
	Option dump_on_restart = 1 (default)
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: Caught signal number 11 SEGV: Segmentation Violation, probably memory access out of range
.
.

**Comment by ADimits** [comment]
Runs OK for several of the other solver options (e.g. cyclic)

Results of key unit and integrated tests:

Unit tests - all serial?

$ make check-unit-tests

[==========] 1918 tests from 127 test suites ran. (4851 ms total)
[  PASSED  ] 1918 tests.


With the following in
tests/integrated/test-laplace-petsc3d/runtests
.
.
test_directories = [('data_slab_core', 4),
                    ('data_slab_sol', 4),
                    ('data_circular_core', 4),
                    ('data_circular_core-sol', 4)]

tolerance = 1.e-6

build_and_log('Laplace 3D with PETSc')

success = True
for directory,nproc in test_directories:
    command = './test-laplace3d -d ' + directory
.
.




$ make check-integrated-tests
.
.
.
test-laplace-petsc3d             ✓   0.008 s
.
.

**Comment by johnomotani** [comment]
This is strange. I managed to run successfully (input and log file attached)
[BOUT.inp.txt](https://github.com/boutproject/BOUT-dev/files/5654623/BOUT.inp.txt)
[BOUT.log.0.txt](https://github.com/boutproject/BOUT-dev/files/5654624/BOUT.log.0.txt)

Versions:
BOUT++ - `next-hypre-outerloop` branch at 04e06534223a41d968bec82a78c4c2cfe466e050
gcc - 9.3.0
OpenMPI - 4.0.3
Petsc - 3.12.4
Sundials - 3.1.2
Hypre - 2.18.2

**Comment by johnomotani** [comment]
I tried checking my version of hw3d (using petsc3damg solver) with Valgrind. Serial and 2 processors with nxpe=2 give the same result. It's almost clean - the only errors reported are 'use of uninitialised value' when writing output, which I think is not surprising as it's an optimised build (not sure if we always zero-initialise everything with checks turned on, but would expect us not to with all checks off), and there will be some boundary cells or something that never need to be set.

**Comment by ADimits** [comment]
Hi John, 

After too many distractions, I tried this. I think the Ubuntu and current apt-get software I have are essentially identical to yours. It seems to work fine, and was "too easy." 

One comment: The manual says "Currently, BOUT++ supports PETSc versions 3.4 - 3.9," which then seems to be outdated. I wasn't sure if PETSc versions are backward compatible. This, besides the NERSC Sundials issue, was a motivator for my trying the Spack installations. I may encounter the same issues again at NERSC, but this experience points to some problem with (perhaps my use of) the Spack installations. Perhaps, despite my efforts, I was not able to keep everything consistent.

Anyway, please feel free to close this issue or if there is any other documentation to add to it for future reference, I can do so.

**Comment by ADimits** [comment]
... and thanks again.

**Comment by johnomotani** [comment]
Thanks @ADimits
