### ISSUE TITLE
-DCHECK and -DTRACK compile flags no longer valid?

### ISSUE THREAD

**Issue by JensMadsen** [boutproject/BOUT-dev#217]
these are replaced by e.g. "--with-check",  when running configure

If correct -DCHECK and -DTRACK  flags should be removed from the use_manual section 21

**Comment by dschwoerer** [comment]
I think we should fix --with-check and conform to the standard and use --enable-check and --enable-track.

With should be used if an external library should be used, whereas enable should be used if it enables an internal feature, like tracking or debugging.
Unfortunately I can't find a reference for this, but e.g. openmp is supported by autoconf only with --enable-openmp.

**Comment by dschwoerer** [comment]
They are still valid, but not any more the only way to do it.

Not sure they need to be removed from the docs ...
