### ISSUE TITLE
Deprecation of netcdf-4.1.3?

### ISSUE THREAD

**Issue by loeiten** [boutproject/BOUT-dev#218]
After an update on the system where I have root access,  I found that the `libnetcdf-dev` package has changed from `version 1:4.1.1-6` (used in  `precise (12.04LTS)`-like managers) to `version 1:4.4.0-2` (used in  [`xenial (16.04LTS)`](http://packages.ubuntu.com/xenial/libnetcdf-dev)-like managers), where the `c++` support has been removed.

The workaround for this seems to be to install the package `libnetcdf-cxx-legacy-dev` rather than `libnetcdf-dev`.

Are there any plans to update the `netcdf` interface to allow for higher version numbers (for example `4.4.1`)?

If not, I suggest to
- Remove the statement `Support for the more recent unbundled versions is coming soon` from the `user_manual`.
- Mentioned in the `user_manual` that `libnetcdf-cxx-legacy-dev` rather than `libnetcdf-dev` must be installed on newer distros.

**Comment by ZedThree** [comment]
From what I can tell, it should work fine with more recent NetCDF versions, it's just that you might have to install the C++ bindings separately. I'm not sure what they're called in Ubuntu.

I've just submitted a pull request (#219) which fixes at least one issue with the 4.x API. Other than that, it all works for me with 4.4.1 (and netcdf-cxx4-4.3.0).

**Comment by loeiten** [comment]
Ok, good to know :).

Would you have a "recipie" on how to build which you could append to the `user_manual`?

**Comment by ZedThree** [comment]
You shouldn't need to do anything special to get it to work, other than having `ncxx4-config` in your `$PATH` (or specifying the location to the top-level directory using `--with-netcdf=/path/to/netcdf`).

I'll update the manual and try and make `configure` a bit more robust with detecting it.

**Comment by ZedThree** [comment]
Fixed in release candidate
