### ISSUE TITLE
"netcdf" requirement in tests broken with legacy netcdf

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#2182]
I configured `next` (at 940575da8afd925951b4ce6783e2a20ef6c5b95c plus a few unrelated (I think!) modifications) with legacy netcdf using `./configure --enable-debug`, and running the integrated tests failed. The cause seems to be that in `bin/bout-config` I have
```
has_netcdf=""
```
where it should be
```
has_netcdf="yes"
```
not sure why. I've worked around the problem by editing `bin/bout-config` and it's not super important to fix since I think we're getting rid of legacy netCDF support in `next` anyway, but if anyone knows a quick fix that would be nice!

**Comment by ZedThree** [comment]
Should be fixed in #2062 ?

**Comment by johnomotani** [comment]
Fixed by #2062.
