### ISSUE TITLE
Ability to output variables that are not physics model members

### ISSUE THREAD

**Issue by JensMadsen** [boutproject/BOUT-dev#221]
What works fine is :

`hest.hxx`

```cpp
class hest : public PhysicsModel {

Field3D hund;
}
```

in `hest.cxx`

```cpp
# include "hest.hxx"

int hest::init(bool restarting) {
hund = 0.;  
SAVE_ONCE(hund);
}
```

but if we have a class method e.g.
`hest.hxx`:

```cpp
class hest : public PhysicsModel {
  int cat();
}
```

`hest.cxx`

```cpp
# include "hest.hxx"

int hest::init(bool restarting) {
  cat();
}

int hest::cat(bool restarting) {
  Field3D hund(0.);
  SAVE_ONCE(hund);
}
```

It does not work. This is because the `hund` is now declared in the `cat`. `hund` is dead before BOUT++ do any output actions. 

Would it be a good idea to support saving variables which are not members of a physcis model object? It would at least save memory i guess and you would get rid of fields only used once in the class declaration making the code easier to read?

**Comment by dschwoerer** [comment]
SAVE_ONCE does not save anything. It just adds the variable to be saved later.

One option would be to copy the object, so we would need to add additional code ...

Yes it would save memory, but I don't think BOUT is actually limited on any machine by the available memory ...
If you have such an case, I would be in favour of adding such functions, but I would assume it wouldn't help, as it would keep a copy until you start your run, so if you run out of memory, you will do so in the beginning.

One way around this is of course to write the stuff from the init to a different file, so you don't have to have the variable around until the run starts (or just call `dump.write()` earlier)

**Comment by dschwoerer** [comment]
I would be in favor in closing this as wont fix.

@JensMadsen: objections?

**Comment by JensMadsen** [comment]
Fine with me
