### ISSUE TITLE
No support for saving strings to BOUT++ datafile? 

### ISSUE THREAD

**Issue by JensMadsen** [boutproject/BOUT-dev#222]
I would like to save a string to the output file. Is this possible?

**Comment by ZedThree** [comment]
This is not currently supported, but both HDF5 and NetCDF do support strings. I have no idea if PDB (the other file format supported by BOUT++) does though. I'm not sure anybody actually uses PDB, so that might not be a problem.

**Comment by bendudson** [comment]
I don't think anyone uses PDB any more, or at least I really hope not.

**Comment by ZedThree** [comment]
Can we just remove PDB functionality in next? Is there any reason to not just support NetCDF/HDF5 only?

**Comment by bendudson** [comment]
I would support dropping support for PDB

**Comment by JensMadsen** [comment]
drop PDB? how to debug then?

**Comment by dschwoerer** [comment]
How do you use PDB for debugging?

**Comment by JensMadsen** [comment]
Sorry. Drank too much coffee. Was trying to joke (python pdb). Not funny. Sorry :-1:

**Comment by ZedThree** [comment]
Fixed in #1350 using file-level attributes
