### ISSUE TITLE
BOUT++ in visit

### ISSUE THREAD

**Issue by JensMadsen** [boutproject/BOUT-dev#223]
Dear all 

I am trying to visualise bout++ files in visit. I have found a tutorial from Eric Brugger. However, I cannot find any documentation on how the bout++ datafile has to be organizxed in order to read the mesh in the right way. As far As I understand I have to have a string in the bout++ file which contains the filename of the grid file?

**Comment by ZedThree** [comment]
For reference, there is https://github.com/boutproject/VisBoutIt, but it is unsupported.

Closing this as we have no current plans for supporting VisIt

**Comment by jdasmith** [comment]
Jens,

You might try talking with Tech-X (www.txcorp.com). I used to work there
but do not any more. There are people there who have expertise with
visualisation of BOUT++ and who are heavy VisIt users. They wrote an open
markup for hdf5 files called VizSchema which allows them to be read into
VisIt. I cannot speak to how much work this would be for your files.

Kind regards,

Jonathan Smith

**Comment by JensMadsen** [comment]
Dear Jonathan 

Thank you for your suggestion :-) I am no longer in the plasma physixs business (legaltech)

Best

Jens

(lets turn github into a chat forum; why not?)
