### ISSUE TITLE
Region::getUnion() is actually the intersection of the sets

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#2236]
I think we should rename `Region::getUnion()` to `Region::getIntersection()` (it's only used in `petsc_interface.hxx`). `ShiftedMetricInterp` was using `getUnion()` and expecting an actual union, which is a bug. If there are no objections, I'll make these changes on the branch where I'm fixing #2225.

**Comment by ZedThree** [comment]
Oops, good catch! Looks like the docstring is correct, it's just the wrong name. Poke me when you've done that and I'll add a unit test.

**Comment by johnomotani** [comment]
`operator+=` actually does the same as I'd expect `getUnion()` to do, so we don't need a `getUnion()`.

**Comment by ZedThree** [comment]
Fixed in #2237?
