### ISSUE TITLE
Can BOUT++ model my device geometry?

### ISSUE THREAD

**Issue by DrJoelMartens** [boutproject/BOUT-dev#2249]
I am new to both plasma physics modelling and GitHub so apologies for any ignorance or naivety if this is an improper place for this question. I am seeking a software package to model pure electron plasmas in cylindrical coordinates with a magnetic field aligned with the z-axis of the cylindrical coordinates, looking to model turbulence behavior. From reading the documentation, BOUT++ is clearly capable of modelling the appropriate turbulence but I cannot tell if it can be adapted to a geometry where the cylindrical coordinates axis is the B-field aligned axis. The paper attached below contains such modelling using the WARP software package, however BOUT++ looks to me to be better documented and more user friendly if it is capable of reproducing the results. Ultimately I wish to extend the model in the attached paper to include a magnetic field whose strength varies along the z-axis.

Any advice or push in the right direction would be greatly appreciated.

Thanks for your time,

Joel Martens

[Experimental and numerical analysis of the electron injection in a Malmberg-Penning trap.pdf](https://github.com/boutproject/BOUT-dev/files/6080266/Experimental.and.numerical.analysis.of.the.electron.injection.in.a.Malmberg-Penning.trap.pdf)

**Comment by bendudson** [comment]
Hi Joel, Welcome! 
- The cylindrical geometry with B field down the axis should be ok; its what's used to model linear plasma devices like LAPD. There are two ways to do this: One is to use cylindrical coordinates, which enables FFTs to be used in the azimuthal direction, and simplifies handling of boundaries, but makes modelling the region around the axis hard (possible though).
- More difficult is the set of PDEs you'd like to solve. If there's a model already, which has been developed and tested, then that would save a lot of time. Developing a new model is possible but takes some effort. One thing to check: How collisional are these plasmas? Is a fluid model appropriate, or do you need a kinetic code? BOUT++ is limited to 3D, so a kinetic model would have to use some kind of moment or basis set in velocity space.
- Boundary conditions are often the most difficult part, in terms of defining the model and numerical stability. Is the system quite sensitive to the boundaries? One starting point is to make the whole thing periodic, modelling an infinitely long cylinder. If that isn't appropriate then more thinking will be needed.
Happy to discuss; if you like we could add you to the Slack group. If interested send me your email address (to bd512 at york dot ac dot uk)

**Comment by DrJoelMartens** [comment]
Hi Ben, thank you for the quick and informative reply. I believe I have examples of how similar problems have been modelled in similar solvers but I will also look into the LAPD. I also think that we can start with a fluid model as I dont believe our situation involves significant collisional rates, though this may be an extension of the model I need to look into in the future. I agree that I will start with simple infinite geometries with periodic boundary conditions but I need to work towards a model that electrostatically confines the electron plasma axially and also contains a filament that provides a constant source of electrons into the contained volume (until the emission is limited by space charge to the rate of the losses from the contained population).

With your confirmation that the basics of my model will be possible with BOUT++ I am keen to begin learning and working my way up to the full complexities of the device. I would like to be added to the Slack group to facilitate future assistance as needed, thank you. I am still using my old student email for my Slack account so please add me using c3076472@uon.edu.au

Thanks again for your time.

Joel Martens
________________________________
