### ISSUE TITLE
Building BOUT-dev with PETSc

### ISSUE THREAD

**Issue by darthveda** [boutproject/BOUT-dev#227]
Followed the steps listed in user manual and was able to build PETSc with sundials support but during the time of configuring BOUT-dev with PETSc ended up with errors. The command used was
./configure --with-petsc=$HOME/petsc-3.4.5 --with_sundials=$HOME/local

ended up with errors

make.config:45: /variables: No such file or directory
make: *** No rule to make target `/variables'.  Stop.
make.config:45: /variables: No such file or directory
make: *** No rule to make target `/variables'.  Stop.

Thought it might be an issue as PETSc 3.4 interface is not compatible and tried 3.6.4 but resulted in the same issue. Any help on setting up BOUT-dev with PETSc support would be much appreciated.

**Comment by loeiten** [comment]
You could try to follow the instructions found [here](https://github.com/loeiten/usingLinux/blob/master/installationProcedures/BOUT-dev.md).

**Comment by bendudson** [comment]
I think this issue was to do with specifying the location of PETSc, rather than setting the PETSC_DIR environment variable. I've modified the configure script slightly, so that specifying the path should be the same as setting the environment variable. A quick fix is now in master branch.

**Comment by darthveda** [comment]
Thanks Ioeiten and Ben, pulled the latest, reconfigured and it works.
