### ISSUE TITLE
autotools 2.71

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#2287]
Autotools 2.71 was released a while ago, and there seem to be some issues with the new autotools.

I managed to run autoreconf successfully with:
```
autoupdate
touch build-aux/config.rpath
autoreconf -fiv
```

However, it seems to only work if I have various packages installed, just having `autotools`, `autotools-archives` and `/usr/bin/aclocal` is not sufficient - so there are still some issues remaining ...

Is this something to be bothered about? I am tempted to rather work on switching to cmake instead.

**Comment by bendudson** [comment]
I think the cmake build is generally in pretty good shape (thanks @ZedThree), and with a bit more work could completely replace the autotools stuff.  If we can get the last bits done,  like boutcore,  then I'd be happy for cmake to be the recommended (only?)  build system for version 5
