### ISSUE TITLE
cmake summary wrong

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#2289]
after running `cmake -B build`

I get:
```*** Now run `cmake --build .` to compile BOUT++ ***```

which fails for obvious reasons. It would be better to give no (wrong) advice if correct advise isn't possible.

**Comment by ZedThree** [comment]
Looking through the CMake variables, it doesn't look like there's an easy way to get this right, as I'm not sure it's possible to work out where `cmake` was invoked.

So yep, best to delete this and just make sure it's clear in the docs what to do.

**Comment by ZedThree** [comment]
Fixed in #2298
