### ISSUE TITLE
How to compile/make code in subfolders 

### ISSUE THREAD

**Issue by JensMadsen** [boutproject/BOUT-dev#229]
Dear all. I need help. I have a physcis model in 
hest.hxx and hest.cxx

in hest.hxx i have 

#include "usefullmodule/usefullmodule.hxx"

my problem is to write the makefile? can you help? If I put usefullmodule in the same folder as hest.hxx everything works but if I move it to a subfolder I cannot figure out how to write the makefile? Please help

**Comment by dschwoerer** [comment]
Not sure whether this is the easiest way:
add to the make.config in line 164:
```
$(TARGET): makefile $(BOUT_TOP)/make.config $(OBJ) $(SUB_DIRS_FUU)
```
the `$(SUB_DIRS_FUU)` entry as dependency
Then you can specify 
```
SUB_DIRS = usefullmodule
SUB_DIRS_FUU = $(SUB_DIRS:%=%.dir)
%.dir:
        @make -C $(@F:.dir=)
```

**Comment by JensMadsen** [comment]
Hi David

Thank you for trying to help 

I cannot make it work. 

What I have now is a folder structure similar to: 

home
| 
| 
|

**Comment by dschwoerer** [comment]
I guess it would be possible to change it that way, but that would be a bit nasty - and taking into account that people want to organize code into folders - I think it would make sense to push these changes - once they work - upstream.

Now I realized that you are unsure how to write the make files for the sub directories - I will have a look later on ...
