### ISSUE TITLE
Globalny set in boutmesh defaults to ny + 4 

### ISSUE THREAD

**Issue by JensMadsen** [boutproject/BOUT-dev#230]
on line 126 in boutmesh.cxx

```
GlobalNy = ny + 4;
```
should be:

GlobalNy = ny + 2*myg;

?

**Comment by bendudson** [comment]
Which branch of the code is this in? In master branch, line 148:

GlobalNy = ny + 2*MYG;

git blame says this has been there since 2014-05-07. Line 126 doesn't seem
to have anything on GlobalNy...

https://github.com/boutproject/BOUT-dev/blob/master/src/mesh/impls/bout/boutmesh.cxx#L148

**Comment by JensMadsen** [comment]
Sorry I have the same thing. 

I think this is in an old BOUT++ version which my Eclipse editor jumped to when I read the source. Sorry
