### ISSUE TITLE
cmake: shared objects are unversioned

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#2320]
Installing BOUT++ results in unversioned shared objects

**Comment by dschwoerer** [comment]
It would be great if we would have a ABI that is independent on the configuration options. That would result in slightly bigger memory consumption, but would allow to switch the library at run time, and make it easier to switch between debug and performance. It would also make providing installed libraries more useful ...

**Comment by bendudson** [comment]
@dschwoerer  A stable ABI would be good. I don't think I know what this would require. To what extent can header files depend on configuration options, and keep the ABI unchanged? e.g. when dependencies are not included we usually have a dummy class which throws an exception if it is ever used.

**Comment by dschwoerer** [comment]
That is generally possible, as long as the structure in memory stays the same, and the same function and methods are exposed. Whether they are dummy or not is unimportant, as long as they are present.
Also adding symbols is fine, although that then breaks running against the newly compiled with an old library, but upgrades of the library are fine.

I can add a test to see what would be required ...

**Comment by ZedThree** [comment]
Versioned shared libraries should be as simple as `set_target_properties(bout++ SOVERSION ${correct_soversion})` I think.

Do you know which configuration options currently change the ABI? I guess most likely candidates are `BOUT_ENABLE_TRACK` (although I think we fixed this?) and `CHECK`.

**Comment by ZedThree** [comment]
Will be fixed in #2358
