### ISSUE TITLE
`max_nonlinear_it`/`max_nonlinear_iterations` should be the same option?

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#2337]
Just noticed that `imexbdf2` and `beuler` have a `max_nonlinear_it` option, which is (I guess) identical to the `maximum_nonlinear_iterations` option that I added in #2303/#2304 for `cvode`. Probably should rename the `cvode` option to be consistent with the others, and list `cvode` beside that option in the manual?

**Comment by bendudson** [comment]
Good spot John.  I think your longer banner l name is better,  so happy for imexbdf2 and beuler to be changed

**Comment by ZedThree** [comment]
Fixed in #2338
