### ISSUE TITLE
Running a simulation in a notebook hides output

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#2354]
If BOUT++ is running in a jupyther notebook, the output does not end up in the notebook, but rather in the terminal.

It would be nice to get the output into the notebook, but not sure this is possible.

**Comment by dschwoerer** [comment]
I guess we need to pass `sys.stdout` which is not the real stdout to boutcore/BOUT++.

Far more annoyingly, exceptions in callbacks are not printed.

**Comment by ZedThree** [comment]
Here's a couple of ideas:

1. use `Output::getInstance()->add/remove` to drop `std::cout` and add `sys.stdout` -- but that needs some way of converting `sys.stdout` to `std::ostream`, and I have no idea if that's possible
2. Capture `std::cout` in `boutcore.init` and redirect it to `sys.stdout` -- this is probably easier

> Far more annoyingly, exceptions in callbacks are not printed.

I'm not sure exactly which callbacks you mean here, but it probably means something in the Cython needs to be marked `except +raise_bout_py_error`

**Comment by dschwoerer** [comment]
Works with python 3.11.0.rc1 and jupyter-4.10.0

**Comment by dschwoerer** [comment]
https://pypi.org/project/wurlitzer/ could be used, in case this pops up again ...
