### ISSUE TITLE
cmake: parallel check

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#2356]
autotools test suite can run tests in parallel. It would be nice to do the same with cmake.
Especially on HPC systems this makes all the difference.

I haven't looked into this further, but it might be possible to only run one test which calls `./test_suite`.

**Comment by ZedThree** [comment]
`ctest` has this built-in already with the `-j` flag. We can also set the [`PROCESSORS`](https://cmake.org/cmake/help/latest/prop_test/PROCESSORS.html#prop_test:PROCESSORS) property on each test to help out here
