### ISSUE TITLE
/usr/bin/ld: cannot find -lnetcdf

### ISSUE THREAD

**Issue by xiaoheimissu** [boutproject/BOUT-dev#2364]
I have compiled bout++4.3.0 successfully,but when I compile the tests/MMS/elm-pb/elm-pb.cxx , an error occurred.
```shell
[~/code/work/BOUT++-v4.3.0/tests/MMS/elm-pb]$ make
  Linking elm_pb
/usr/bin/ld: cannot find -lnetcdf_c++4
/usr/bin/ld: cannot find -lnetcdf
collect2: error: ld returned 1 exit status
make: *** [../../../make.config:287: elm_pb] Error 1
```

The /usr/bin/ld told that it can't find the netcdf_c++4 and netcdf, but I have already written the -L/where/netcdf/lib in the make.config.
I even In -s the netcdf's lib to /usr/local/lib,but the error is always there . I think is my mistake,but I don't know how to solve it.

**Comment by ZedThree** [comment]
Hi @xiaoheimissu, do you get errors when running `make check` from `~/code/work/BOUT++-v4.3.0`?

Please could you attach the `config.log` file, and your `make.config`? It would also be good to see the output of `locate libnetcdf`.
