### ISSUE TITLE
Access to BOUT++ Slack channel

### ISSUE THREAD

**Issue by JonMcCullough** [boutproject/BOUT-dev#2377]
Good morning,

I'm involved in a recently awarded project that will be supporting some aspects of BOUT++ development. Could I please get access to the BOUT++ Slack channel to help support this?

Thanks,
Jon

**Comment by ZedThree** [comment]
Hi @JonMcCullough! Certainly! Please could you drop an email to peter.hill(at)york.ac.uk and I'll send you an invite
