### ISSUE TITLE
bindex ignores RGN_NOY and RGN_NOZ

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#239]
the start_index, next_index? etc seem to all ignore the two flags, or more precisely always assume them.

If you take e.g. the perpendicular derivative of an interpolated field in y, the boundary (in z) didn't get interpolated - if I am not mistaking ...
I guess in the STORM module e.g. this should cause issues with the accuracy of bracket, as it uses phi_stag.

**Comment by dschwoerer** [comment]
I guess the example was bad, as the extra point in z is mostly ignored, anyway this may cause issues ...

**Comment by bendudson** [comment]
I think the start_index and bindex code should be removed in next, as this can all now be done with DataIterator (issue #185 )

**Comment by dschwoerer** [comment]
I completely agree with removing it in next, was just not sure it should be fixed in the master ...
Or whether the performance penalty / risk of breaking existing code might outweigh the risks of this unexpected behavior ....

**Comment by dschwoerer** [comment]
fixed by #804
