### ISSUE TITLE
shared object broken with recent releases

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#2399]
I noticed that BOUT++ v4.4.0 doesn't [build](https://kojipkgs.fedoraproject.org//work/tasks/956/73970956/build.log)

The issue is this:
```
ll lib/
lrwxrwxrwx 1 dave ipg        18 Aug 17 15:29 libbout++.so -> libbout++.so.4.4.0
-rwxr-xr-x 1 dave ipg 103795656 Aug 17 15:29 libbout++.so.4.3.1
```
i.e. there is a mismatch in the so-version.

The same is true with the 4.3.3 release, but there I didn't notice the error, as 4.3.3 also builds the static library, so the python library silently linked to the static version, and everything seemed to work.

Is this enough of an error to make new releases with the so version fixed consistently?

The fix is trivial, just change https://github.com/boutproject/BOUT-dev/blob/master/makefile#L14 always along with https://github.com/boutproject/BOUT-dev/blob/master/makefile#L19 and for the future introduce a variable that contains the so-version.

**Comment by dschwoerer** [comment]
Should I create a v4.3.x branch and open a PR against for this branch: https://github.com/boutproject/BOUT-dev/tree/2399-v433 ?

**Comment by ZedThree** [comment]
Could you backport #2401 for v4.3.x instead? I'm not overly keen on supporting multiple released versions, but this is an easy fix, so let's try and get v4.3.4 sorted quickly

**Comment by dschwoerer** [comment]
Rebased here:

https://github.com/boutproject/BOUT-dev/tree/43x-2401

**Comment by dschwoerer** [comment]
Another minor issue, I need to replace `\#\#` to `##` in `make.config`. I am not sure what makes that change necessary -.-
