### ISSUE TITLE
FV::Div_par() incorrect on double-null grids?

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#2416]
In `FV::Div_par()`
https://github.com/boutproject/BOUT-dev/blob/c3ca1ce21064e05999ac530d0d7bc081cf568392/include/bout/fv_ops.hxx#L181-L183
`firstY()` and `lastY()` are used in various places to apply special handling to y-boundaries. I think this would mean that the upper divertor in a double-null would not get the special handling, which presumably it needs. Suggest replacing them with `mesh->hasBndryLowerY()` and `mesh->hasBndryUpperY()` - that might also remove the need for some of the `periodicY()` checks (as long as `hasBndry*Y()` return `false` on periodic 'boundaries' - I'm not 100% sure they do).

**Comment by bendudson** [comment]
Hey @johnomotani yes I think you are right: This currently treats the upper and lower target boundaries differently. The same is probably true for other parallel finite volume differencing operators.

**Comment by bendudson** [comment]
I've spent a while going through this. The handling of boundaries is so messy, and the comments are misleading, but I think the code using `firstY(i)` is correct. The code takes the set of processors along the flux surface at index `i` and works out if the present processor is at the start (or end for `lastY`) of that flux tube. `hasBndryLowerY` checks if there is a boundary anywhere in X.

**Comment by johnomotani** [comment]
@bendudson :+1: sorry, I'd only remembered the `firstY()` and `lastY()` without argument when I looked at this! The versions with an x-index argument indeed look correct.
