### ISSUE TITLE
Issues with including Sundials library in compilation

### ISSUE THREAD

**Issue by EdmundBenedict** [boutproject/BOUT-dev#2420]
I have compiled Sundials 5.4.0 in the /home/user/local directory with no issues. I then configure the BOUT++ install with the command:

`./configure  --with-sundials=/home/user/local/lib/
`
And it seems to have no issue with the sundials install:
```
checking for /home/user/local/lib//include/sundials/sundials_config.h... no
checking for SUNDIALS config header... yes
checking for SUNDIALS minor version... ok
configure: Searching for SUNDIALS IDA library
configure: Checking for IDA header files
checking for /home/user/local/lib//include/ida/ida.h... no
checking for /home/user/local/lib//include/ida/ida_spgmr.h... no
checking for /home/user/local/lib//include/ida/ida_bbdpre.h... no
checking for /home/user/local/lib//include/nvector/nvector_parallel.h... no
checking for /home/user/local/lib//include/sundials/sundials_types.h... no
checking for /home/user/local/lib//../include/ida/ida.h... yes
checking for /home/user/local/lib//../include/ida/ida_spgmr.h... no
checking for /home/user/local/lib//../include/ida/ida_bbdpre.h... yes
checking for /home/user/local/lib//../include/nvector/nvector_parallel.h... yes
checking for /home/user/local/lib//../include/sundials/sundials_types.h... yes
configure: Found IDA include path: /home/user/local/lib//../include
checking if SUNDIALS IDA library path is /home/user/local/lib/... yes
configure: => IDA solver enabled
configure: Searching for SUNDIALS CVODE library
configure: Checking for CVODE header files
checking for /home/user/local/lib//include/cvode/cvode.h... no
checking for /home/user/local/lib//include/cvode/cvode_spgmr.h... no
checking for /home/user/local/lib//include/cvode/cvode_bbdpre.h... no
checking for /home/user/local/lib//include/nvector/nvector_parallel.h... (cached) no
checking for /home/user/local/lib//include/sundials/sundials_types.h... (cached) no
checking for /home/user/local/lib//../include/cvode/cvode.h... yes
checking for /home/user/local/lib//../include/cvode/cvode_spgmr.h... no
checking for /home/user/local/lib//../include/cvode/cvode_bbdpre.h... yes
checking for /home/user/local/lib//../include/nvector/nvector_parallel.h... (cached) yes
checking for /home/user/local/lib//../include/sundials/sundials_types.h... (cached) yes
configure: Found CVODE include path: /home/user/local/lib//../include
checking if SUNDIALS CVODE library path is /home/user/local/lib/... yes
configure: => CVODE solver enabled
configure: Searching for SUNDIALS ARKODE library
configure: Checking for ARKODE header files
checking for /home/user/local/lib//include/arkode/arkode.h... no
checking for /home/user/local/lib//include/arkode/arkode_spgmr.h... no
checking for /home/user/local/lib//include/arkode/arkode_bbdpre.h... no
checking for /home/user/local/lib//include/nvector/nvector_parallel.h... (cached) no
checking for /home/user/local/lib//include/sundials/sundials_types.h... (cached) no
checking for /home/user/local/lib//../include/arkode/arkode.h... yes
checking for /home/user/local/lib//../include/arkode/arkode_spgmr.h... no
checking for /home/user/local/lib//../include/arkode/arkode_bbdpre.h... yes
checking for /home/user/local/lib//../include/nvector/nvector_parallel.h... (cached) yes
checking for /home/user/local/lib//../include/sundials/sundials_types.h... (cached) yes
configure: Found ARKODE include path: /home/user/local/lib//../include
checking if SUNDIALS ARKODE library path is /home/user/local/lib/... yes
configure: => ARKODE solver enabled
```

And shows no errors during “make”, but when I try to run one of the examples (or use make check to test the installation) I get the following error:

`error while loading shared libraries: libsundials_nvecparallel.so.5: cannot open shared object file: No such file or directory`

But this file is contained within the ~/local/lib/ directory, which is referenced within the make.config file as 

```
EXTRA_INCS        = $(CPPFLAGS)  -I/usr/include -Wdate-time -D_FORTIFY_SOURCE=2 -I/usr/include -I/usr/include/hdf5/serial -I/home/user/local//include -I/home/user/local//include -I/home/user/local//include  -I/home/user/local//include -I/home/user/local//include -I/home/user/local//include 
EXTRA_LIBS        = $(LIBS)  -lfftw3 -L/usr/lib/x86_64-linux-gnu -lnetcdf_c++4 -lnetcdf -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lhdf5_hl -lhdf5  -lpthread -lsz -lz -ldl -lm -lblas -llapack -L/home/user/local//lib -lsundials_ida -lsundials_nvecparallel  -L/home/user/local/ -lsundials_cvode -lsundials_nvecparallel  -L/home/user/local/ -lsundials_arkode -lsundials_nvecparallel  -L$(BOUT_LIB_PATH)  -lpvode -lpvpre  -fopenmp -DOPENMP_SCHEDULE=static
```

I cannot find why BOUT++ is unable to find these libraries. Is there something else I should add to the make.config file? 
Thank you very much.

**Comment by johnomotani** [comment]
I think you probably need to add `/home/user/local/lib/` to the `LD_LIBRARY_PATH` environment variable. This is (as far as I understand it) used only at run-time to find the `.so` library files, so it's not used/set in the configuration process, and has to be set separately. If it seems like the manual could use some extra info on this, a PR would be welcome!

**Comment by EdmundBenedict** [comment]
You were correct; when I added /home/user/local/lib to the LD_LIBRARY_PATH it ran without issues. I apologise, I was not aware at all of the need to define library locations with that variable. But yes, it would have helped me (and other similarly inexperienced users) greatly to have a line about this in the documentation. I'd be happy to make a note of this, what is a PR and how would I do it?
Thank you!

**Comment by EdmundBenedict** [comment]
Ah, I checked the /manual/sphinx/user_docs/advanced_advanced_install.rst and there is already a note about this included! (A the bottom of the Sundials section)
https://github.com/boutproject/BOUT-dev/blob/master/manual/sphinx/user_docs/advanced_install.rst
The issue is that I was using the documentation at: https://bout-dev.readthedocs.io/en/latest/user_docs/advanced_install.html#sec-advancedinstall
I guess this is not up to date?

**Comment by johnomotani** [comment]
In principle `dev.readthedocs.io/en/latest/user_docs` should be the most up to date, but I guess the changes from #2311 might have got lost in the merge #2396 (`master` and `next` have diverged a long way, so the merge was complicated!). It'd be a good idea to cherry-pick 6d0b4c81071a5a273e3bbfcba59b7e31f1845eb1 into `next`. I'll make a PR...
