### ISSUE TITLE
Zenodo not updated

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#2435]
here: https://zenodo.org/record/5167527

Since 4.3.1 the date in the releases did not change. Also the author list is wrong (I noticed on the 4.4.0 I am listed as Schwörer not Bold). Also the "Alternate identifiers" is https://github.com/boutproject/BOUT-dev/releases/tag/v4.3.0 (Software) for v4.4.0

**Comment by ZedThree** [comment]
Thanks @dschwoerer, I've fixed these.

**Comment by dschwoerer** [comment]
https://zenodo.org/record/5142504 (v4.3.3) has still the old list of authors - not clue how much work it is to fix it ...

Thanks for fixing @ZedThree :+1:

**Comment by ZedThree** [comment]
Sorted!
