### ISSUE TITLE
SignalHandlerTestDeathTest.SegFault fails on aarch64 with gcc 12

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#2486]
After updating gcc to version 12, the unit tests start failing on aarch64:
```
[ RUN      ] SignalHandlerTestDeathTest.SegFault
src/test_bout++.cxx:341: Failure
Death test: std::raise(11)
    Result: died but not with expected error.
  Expected: contains regular expression "SEGMENTATION FAULT"
Actual msg:
[  DEATH   ] 
[  DEATH   ] Sighandler called on process 0 with sig 11
[  DEATH   ] 
[  FAILED  ] SignalHandlerTestDeathTest.SegFault (359 ms)
```
Are we doing something dodgy, or is that probably a bug in gcc 12?

From Fedora rawhide.
[full log](https://kojipkgs.fedoraproject.org//work/tasks/4482/81474482/build.log)
[build](https://koji.fedoraproject.org/koji/taskinfo?taskID=81474312)
[koshei](https://koschei.fedoraproject.org/package/bout++?collection=f36) (for what changed with the first failing build)

**Comment by ZedThree** [comment]
I think our signal handler is UB. See also #1989
