### ISSUE TITLE
Trouble compiling next with intel compilers

### ISSUE THREAD

**Issue by bendudson** [boutproject/BOUT-dev#2487]
Compiling the latest `next` branch on NERSC's Cori, intel/19.1.2.254 compiler. No options to CMake, just basic build.

First I get a warning:
```
BOUT-dev/externalpackages/fmt/include/fmt/format.h(1973): warning #4041: constexpr if statements are a C++17 feature
      if constexpr (std::numeric_limits<double>::is_iec559) {
```

Looks like we might have to update C++ to 17. Changing the target language from C++14 to C++17 doesn't however make any difference to the error which comes next:

```
BOUT-dev/externalpackages/fmt/include/fmt/core.h(1714): error: static assertion failed with "Cannot format a const argument."
    static_assert(formattable_const, "Cannot format a const argument.");
    ^
          detected during:
            instantiation of "auto fmt::v8::detail::make_arg<IS_PACKED,Context,<unnamed>,T,<unnamed>>(T &&)->fmt::v8::detail::value<Context> [with IS_PACKED=true, Context=fmt::v8::format_context, <unnamed>=fmt::v8::detail::type::custom_type, T=const Options &, <unnamed>=0]" at line 1856
            instantiation of "fmt::v8::format_arg_store<Context, Args...>::format_arg_store(T &&...) [with Context=fmt::v8::format_context, Args=<Options>, T=<const Options &>]" at line 1872
            instantiation of "auto fmt::v8::make_format_args(Args &&...)->fmt::v8::format_arg_store<Context, fmt::v8::remove_cvref_t<Args>...> [with Context=fmt::v8::format_context, Args=<const Options &>]" at line 3148
            instantiation of "auto fmt::v8::format_to(OutputIt, fmt::v8::format_string<T...>, T &&...)->OutputIt [with OutputIt=fmt::v8::detail::buffer_appender<char>, T=<const Options &>, <unnamed>=0]" at line 859 of "/global/homes/d/dudson/BOUT-dev/src/sys/options.cxx"
```

Any line involving formatting an Options causes a similar error. I've checked and `fmt::v8::formatter<const Options&>` is being defined (I defined it again and got an error about re-defining) so I'm a bit puzzled. Since the gitlab tests pass presumably GCC and Clang are ok, and this is an Intel issue... any suggestions @ZedThree ?

**Comment by ZedThree** [comment]
This is a compiler bug. The code in the first warning is guarded by `#ifdef __cpp_if_constexpr` which should completely avoid the `if constexpr` if it's not available.

The following works (returns 0) on Intel 19.0.1 and 20212.0, but fails (warns and returns 1) on 19.0.5 and 19.1.1:

```
constexpr bool bar = true;

int main() {
#ifdef __cpp_if_constexpr
  if constexpr (bar) { return 1;}
#endif
  return 0;
}
```

Annoyingly you can't check this on godbolt, because they don't have the buggy versions.

The second compile error seems to only happen on 19.1.1 -- 19.0.5 works ok (although it has the spurious warning), and so does 2021.2.0.

**Comment by bendudson** [comment]
Thanks @ZedThree !  19.0.8.324 emits the warning about constexpr if, but compiles without the error.
I'll make a note in the Cori section of the manual
