### ISSUE TITLE
Mesh branch cut documentation

### ISSUE THREAD

**Issue by bendudson** [boutproject/BOUT-dev#25]
There is currently no documentation of the branch cut system used to specify limiters and X-points. The BOUT manual contains an out-of-date figure on page 34, but it is not all that useful unless you already know what the system is.

**Comment by nick-walkden** [comment]
I have added a section in the user manual, starting on page 52, containing some details of branch cuts. These can be found in the topology_manual_update branch. I think it contains the basics needed to understand the branch cut system, with the help of Luke's very useful figure and one of my own.

 I have tried the new 'Basic, Advanced, Implementation' format for the section suggested by Ben. I might have been a bit arbitrary in what is 'basic' and what is 'advanced' so this might need reordering slightly. I haven't put anything into the implementations section. 

It might be worthwhile adding something about creating limiter configurations in the section somewhere.

**Comment by ZedThree** [comment]
I've expanded on this further in #2245, I think it's now in a fairly decent state.
