### ISSUE TITLE
Parallel derivative order /=2 incorrect on next for field3d

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#251]
With the new `yup`/`ydown` treatment of the parallel transform the `stencil.pp` and `stencil.mm` values are now set to 0 in `field3d::setYStencil` -- this means that schemes for the derivatives that require these (e.g. `C4`) no longer give the correct answer.

Note this does not apply to `field2d` which does not use `yup` or `ydown` when populating stencils.

**Comment by bendudson** [comment]
To fix this we either have to have an option to store two planes in each y direction (5 fields rather than 3, compared to 1 in master), or give up on 4th-order operators.

**Comment by JensMadsen** [comment]
I vote for making the machinery flexible for higher order schemes. In principle the number of stored planes should always equal MGY?

**Comment by dschwoerer** [comment]
I'd consider it very bad coding style to break stuff silently.

If .pp isn't set, set it to nan("");
If somebody is using it, he will know very fast it is wrong. Without that people will spend weeks or months debugging!

**Comment by d7919** [comment]
Yes I think it would be useful to ensure that this is easily noticed -- Perhaps we can add a check for the derivative order and abort if not supported?

**Comment by dschwoerer** [comment]
Seems to me rather complicated.

Set it to nans.

Merge #124 (it adds support for enabling SIGFPE) and you will get the immediate feedback if the nan is used. True it might not be obvious where it came from, but at least you don't need to know what stancil is what order ...

**Comment by dschwoerer** [comment]
Somewhat worrying: interchange-instability uses forth order in parallel direction, yet it didn't notice this error ...

We really need more (and more precise) tests ...

**Comment by dschwoerer** [comment]
Another idea: Does the FCI scheeme need to be in the standard mesh?
As the derivative options are part of the mesh, using an FCI mesh, then FCI could drop the support for higher order, without breaking the rest of bout. Also it would still allow the non FCI code to be optimized ...

However, that would require set?Stencil not to be part of field3D, but rather of the mesh. But then if the Mesh knows what is where connected, and the field has only the data, it might make sense ...

**Comment by d7919** [comment]
Whilst this is perhaps obvious I thought I'd also point out that this issue doesn't just impact the fourth order accurate stencils, it also impacts:
* The `d4dy4` operator that may sometimes be used in artificial dissipation etc.
* The `U2` upwind operator (`VDDX_U2`)
* The `W3` upwind operator (`VDDX_WENO3`/`VDDX_CWENO3`)
* The `FDDX_NND` operator.
* The MUSCL scheme operator (`DDX_KT_LR`)

In addition, I think this will also cause problems from the `interp` (and hence `interp_to`) routine(s) when interpolating in `y`.

**Comment by d7919** [comment]
Any code using `Field3D::setYStencil(forward/backward_stencil,...)` will be incorrect for `paralleltransform/=identity` (any order operator) as these routines don't make use of `yup` and `ydown`.

**Comment by d7919** [comment]
Related work in [mgy-yup-ydown](https://github.com/boutproject/BOUT-dev/tree/mgy-yup-ydown) branch.

**Comment by johnomotani** [comment]
I'm still working on [mgy-yup-ydown](https://github.com/boutproject/BOUT-dev/tree/mgy-yup-ydown), but have a question: is it worth allowing for MYG>2? If MYG will never be bigger than 2 it would be simpler to just have 2 fields for e.g. yup1, yup2 rather than an array, and maybe that would be better?

**Comment by bendudson** [comment]
I don't think there's much point to having more than 2 points.  Getting more than 2nd order with a finite difference method with boundary conditions seems to be essentially impossible.

**Comment by d7919** [comment]
Is this going to make v4.2 or will it be pushed back?

**Comment by ZedThree** [comment]
Pushed back :(

**Comment by ZedThree** [comment]
Fixed in #1345
