### ISSUE TITLE
Field2D y-derivatives don't use yup/ydown in next

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#252]
In the next branch the `field2d::setYStencil` routine still uses the "old" approach -- this should be updated to be consistent with `field3d`

**Comment by dschwoerer** [comment]
I am in favour of undoing this change in field3d, as it is broken, see. #253 

* FCI should be an independent mesh (probably inherting from boutmesh and replace the derivatives)
* set?Stencil should be removed, as it should be part of the mesh.

**Comment by d7919** [comment]
Note, this means that when a Field2D gets implicity cast/promoted to a 3D we need to do further communication of the new 3D field in order to by able to take y-derivatives (rather than copying the yup/ydown fields, which don't exist in a 2D).

**Comment by dschwoerer** [comment]
I don't mind having field2d/3d have the yup/ydown.
I just think the current implementation is broken, and the most easy way I can see is having FCI as its own mesh.
This requires to remove the (anyway slow) set?Stencil functions ...

**Comment by bendudson** [comment]
Agreed that set stencil functions are not need anymore, and should be replaced by data iterators. 

The yup, ydown fields are not just for FCI, but also when shifted metrics are used, which is pretty much all Tokamak simulations. The alternative to storing yup and ydown is to do zshifting for every x derivative operator, as done in master. If no shifting is needed, then yup and ydown just point to the same field, and there should be no overhead. It's possible there's a better way to incorporate standard meshes, shifted metrics and FCI with minimal differences between them though. Now is the time to choose the scheme before next becomes master... 

-------- Original Message --------

**Comment by d7919** [comment]
Is this going to make v4.2 or will it be pushed back?

**Comment by ZedThree** [comment]
Fixed in 1948f60734379dfb92b10a00f9949b54a06ccdcc
