### ISSUE TITLE
DEPRECATED macros conflict with ROCm HIP

### ISSUE THREAD

**Issue by alephpiece** [boutproject/BOUT-dev#2527]
I'm trying to port some CUDA interfaces to HIP, but it seems that the `DEPRECATED` macro conflicts with some HIP headers.

Maybe the `DEPRECATED` macro should be replaced with the C++14 `deprecated` keyword?

**Comment by bendudson** [comment]
Hi @alephpiece this sounds good to me.

**Comment by alephpiece** [comment]
BTW, is it possible to port vector operators, e.g., `Div`, to CUDA?

**Comment by ZedThree** [comment]
This will be fixed in #2291
