### ISSUE TITLE
Remove `Field3D.background`?

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#2543]
Setting 'backgrounds' for `Field3D` variables has been disabled/deprecated, see #430, #448. Should the private member `Field3D.background` be removed completely now, along with the related code in `applyBoundary()`?

There was some discussion that a replacement mechanism could be needed (https://github.com/boutproject/BOUT-dev/issues/430#issuecomment-270929071, https://github.com/boutproject/BOUT-dev/issues/430#issuecomment-433983085), but nobody seems to have been complaining since `setBoundary()` was removed in 2017! I guess the current solution is just to write a `PhysicsModel` explicitly in terms of separate background and perturbed variables, maybe that is good enough?

**Comment by ZedThree** [comment]
As you said, nobody's complained in 5 years, so let's get rid of it.
