### ISSUE TITLE
Naming of output files

### ISSUE THREAD

**Issue by mir1995** [boutproject/BOUT-dev#2553]
One pass the flags `-o <settings filename>`, `-l <log filename>` to the executable to change the default settings and log filenames from BOUT.settings and BOUT.log to <settings filename> and <log filename>
respectively. But how do I change the filename of the output .nc data? What flag shoud I pass?

**Comment by dschwoerer** [comment]
This is currently unfortunately not possible, as it is hard coded:
https://github.com/boutproject/BOUT-dev/blob/2b2223b51cb4c1f2013950a4586619f8a917d32c/src/bout%2B%2B.cxx#L547

Would it be easy enough to just put it in a different folder? It shouldn't be that hard to change it ...

**Comment by mir1995** [comment]
> This is currently unfortunately not possible, as it is hard coded:
> 
> https://github.com/boutproject/BOUT-dev/blob/2b2223b51cb4c1f2013950a4586619f8a917d32c/src/bout%2B%2B.cxx#L548
> 
> Would it be easy enough to just put it in a different folder? It shouldn't be that hard to change it ...

That would work if I am running one simulation at a time. However, I need to run multiple simulations in parallel and consequently the outputs .nc files would override  each other

**Comment by dschwoerer** [comment]
You could also copy your input files to different folders - that is what most people do, to have one folder for each run.

https://pypi.org/project/bout-runners/ is a python tool that can be used to do this, but I haven't used.

But I think if we allow to modify those two names, it probably makes sense to also allow modifying the the dump names.
