### ISSUE TITLE
Delete the dirichlet and neuman boundary operators

### ISSUE THREAD

**Issue by JensMadsen** [boutproject/BOUT-dev#256]
In the current version of BOUT++ the default discretization has boundaries staggered between first (last) inner point and ghost points. In that case the local truncation error of the Dirichlet and Neumann boundary operator is of order one. In most cases  this implies that the the global error is of order on as well and not two as it is supposed to be since the default order of most differential operators is two. Moreover, the code usually slows down when boundary operators do not have a sufficiently low local truncation error

I suggest to:

1) delete the operators (or rename them to explicitly specify that they assume a grid point on boundary )or
2) let the Dirichlet and Neumann boundary operators call Dirichlet_02 and Neumann_20, respectively.

**Comment by ZedThree** [comment]
I'm in favour of deleting the operators. Or possibly making them only work if the boundary is on a grid point?

**Comment by JensMadsen** [comment]
Another possibility would be to name them appropriately e.g.:

dirichlet_o2 -> dirichlet_o2_staggered
dirichlet -> dirichlet_o2_nonstaggered

**Comment by ZedThree** [comment]
I don't think `BoundaryOnCell` is an option any more. After some discussion with @d7919, I think deleting them entirely is probably the most appropriate.

**Comment by ZedThree** [comment]
Should `BoundaryNeumann2﻿⁠⁠⁠⁠` and `BoundaryNeumann_2ndOrder` also be deleted?

**Comment by ZedThree** [comment]
Ok, they will be deprecated, and removed in 5.0

**Comment by dschwoerer** [comment]
So for stagger grids, I need to write operators for the boundaries as well? Or does the current code handle these cases?

**Comment by ZedThree** [comment]
I believe `_o2` forms should handle staggered grids. It certainly looks like there's code in there to handle them. These will become the default in 4.0 (i.e. `dirichlet` and `neumann` will be synonyms for `dirichlet_o2` and `neumann_o2`), but I've not made that change in `v4.0.0-RC` yet - will happen on Monday!

**Comment by ZedThree** [comment]
Fixed in d3403e7 and 2492563
