### ISSUE TITLE
Document building examples with CMake

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#2563]
It would probably be good for the 'Getting started' section to document how to build the examples when using CMake, i.e. (I think this is the recommended process - @ZedThree?):
1. check `BOUT_BUILD_EXAMPLES=ON` is set (it should be by default)
2. to build `<xyz>` go to the `examples/<xyz>` subdirectory *of your build directory*
3. run `make`

**Comment by johnomotani** [comment]
@jonycastagna - re https://github.com/boutproject/BOUT-dev/pull/2557#issuecomment-1196784933 does this help? Sorry I can't test myself right now, Marconi's refusing to download FFTW just now...

**Comment by jonycastagna** [comment]
Hi @johnomotani , tust tried but I get same error... (also tried the hw-3d and same error too)

**Comment by johnomotani** [comment]
@jonycastagna If the `examples` subdirectory exists in your build directory and the CMake build completed, I don't know how you could get that error. Try deleting the build directory and rebuilding. If you're not sure what I mean by 'build directory' when using CMake, see https://bout-dev.readthedocs.io/en/latest/user_docs/installing.html#cmake.

**Comment by ZedThree** [comment]
@johnomotani Good point, I'm having a BOUT++ day, so I'll add that to the manual this afternoon.

@jonycastagna Just to be clear, the full steps, starting from a clean checkout:

1. `cmake . -B build` (plus any flags you need to set to enable PETSc, tell cmake where netcdf is, etc)
2. `cmake --build build`
3. `cd build/examples/hasegama-wakatani && make`

You should also be able to run `cmake --build build --target hasegama-wakatani` from the top level.

This definitely works in `next`, I think it does work in `master` too, I will need to double-check.

**Comment by jonycastagna** [comment]
HI @johnomotani, I cleaned everything and tried again and it works now :) Many thanks for your help! I opened a [https://github.com/boutproject/BOUT-configs/pull/6]MR about the issue with CMake on Marconi

**Comment by ZedThree** [comment]
Some instructions here: https://bout-dev--2564.org.readthedocs.build/en/2564/user_docs/installing.html#cmake
and further details in the physics model section: https://bout-dev--2564.org.readthedocs.build/en/2564/user_docs/physics_models.html#building-physics-models
