### ISSUE TITLE
Unit test failures on next with debug build

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#2574]
On the current `next` (1707893f0f28525c310a2c82b836aafa71c87a44) with checks enabled, two of the unit tests fail for me (on Linux Mint 20.2, gcc-9.4.0, OpenMPI-4.0.3)
```
[ RUN      ] IndexOffsetStructTests/0.SubtractFromIndex
unknown file: Failure
C++ exception with description "Offset in y (-2) would go out of bounds at 0" thrown in the test body.
[  FAILED  ] IndexOffsetStructTests/0.SubtractFromIndex, where TypeParam = SpecificInd<(IND_TYPE)0> (2 ms)
```
and
```
[ RUN      ] IndexOffsetStructTests/1.SubtractFromIndex
unknown file: Failure
C++ exception with description "Offset in y (-2) would go out of bounds at 0" thrown in the test body.
[  FAILED  ] IndexOffsetStructTests/1.SubtractFromIndex, where TypeParam = SpecificInd<(IND_TYPE)1> (2 ms)
```

**Comment by johnomotani** [comment]
I don't have time to follow this up right now. Not sure why the CI would have missed (?) this either - it looks like there isn't a debug build using CMake, but there is a debug build using configure.

**Comment by ZedThree** [comment]
There's a working debug build with CMake in #2514, so this issue seems to be resolved
