### ISSUE TITLE
Help with cylindrical geometry

### ISSUE THREAD

**Issue by eatocco** [boutproject/BOUT-dev#2575]
I would like to use BOUT++ for some plasma modeling of a cylindrical fusion reactor we're studying at my university. As a first step I'm trying to replicate some MHD analysis done by a previous student showing stabilization of an interchange instability in the azimuthal direction by shear flow. From what I've read in the documentation and examples, it seems that BOUT should be capable of doing this, but I haven't been able to get it to work. I'm still quite new to this type of analysis, so I'm having some trouble isolating what I'm doing wrong. 

The equations are isothermal MHD equations with viscous and resistive effects added, so very similar to the MHD example. I'd like to model the radial direction and a portion of the azimuthal direction, with the magnetic field down the axis. The geometry portion of my BOUT.inp file looks like this: 

nx = 104
ny = 100

Rmin = 4
Rmax = Rmin+1

Rxy = Rmin + (Rmax - Rmin)*(x)   # Rxy = [Rmin, ..., Rmax]
dr = (Rmax - Rmin) / (nx-4)

dy = pi/6/ny # theta direction
dx = dr          # radial direction

"""

g11 = 1.0
g22 = 1/(Rxy^2)
g33 = 1.0

J = Rxy

My question is, assuming my initial values for velocity, density, and magnetic field are correct, would this produce a geometry like I'd expect, or are there further modifications I'd need to make. Thank you!

**Comment by johnomotani** [comment]
You're going to have to put up with the BOUT++ coordinate system where the `y`-direction is parallel to the magnetic field. The `z`-direction is periodic (often the toroidal direction of a tokamak, but also suitable for an azimuthal coordinate in cylindrical geometry). So a slight modification of your input

nx = 104
nz = 100

Rmin = 4
Rmax = Rmin+1

Rxy = Rmin + (Rmax - Rmin)*(x) # Rxy = [Rmin, ..., Rmax]
dr = (Rmax - Rmin) / (nx-4)

dz = pi/6/nz # theta direction
dx = dr # radial direction

"""

g11 = 1.0
g22 = 1.0
g33 = 1/(Rxy^2)

J = Rxy

should give the cylindrical geometry you want. You could also skip defining `dz` explicitly and put `zperiod = 12`, but the result would be identical.

If you plan to use FFT-based operators in the azimuthal direction, it might be slightly more efficient to pick a power of 2 `nz` (see the FFTW docs for more info on what numbers are suitable).

If/when you're running in parallel only the x- and y-directions are split up in the domain decomposition, so it can be useful to choose those in some way that suits splitting over the number of cores on your workstation or HPC cluster. For example powers of 2 if your nodes have 32 cores per node, or 3*2^n if you have 24 cores per node.

**Comment by eatocco** [comment]
Thanks for the help!  That seems to have gotten me most of the way there. In the original MHD example, what was the significance of setting a vector as covariant vs. contravariant in terms of how it's handled by BOUT?

**Comment by johnomotani** [comment]
> what was the significance of setting a vector as covariant vs. contravariant in terms of how it's handled by BOUT?

Vector operations are done component-by-component. Some require one or other of covariant/contravariant components (e.g. divergence requires contravariant components), and BOUT++ will convert the input between covariant and contravariant if necessary. So if the initial components of a `Vector3D` are set to some values, it's also necessary to set whether the `Vector3D` contains covariant or contravariant components.
