### ISSUE TITLE
Error in user_manual. no field twistshift

### ISSUE THREAD

**Issue by JensMadsen** [boutproject/BOUT-dev#258]
In the user manual page 78:

> Twist-shift matching condition twistshift[nx]. This is applied in the “core” region
> between indices jyseps2 2, and jyseps1 1 + 1, if enabled in the options file. If not
> given, this is set to zero.

As far as I understand there is a boolean [l:157 in boutmesh.hxx](https://github.com/boutproject/BOUT-dev/blob/b53b3affd7b2377222fa42d0aff3661afe258103/src/mesh/impls/bout/boutmesh.hxx#L157)

`bool TwistShift;   // Use a twist-shift condition in core?`

[and] (https://github.com/boutproject/BOUT-dev/blob/b53b3affd7b2377222fa42d0aff3661afe258103/src/mesh/impls/bout/boutmesh.hxx#L136)

`vector<BoutReal> ShiftAngle;  ///< Angle for twist-shift location`

so the manual should say ShiftAngle[nx]? If you agree I change it and add information about the need for setting the twistshift flag

**Comment by bendudson** [comment]
Your understanding is correct, and the manual is wrong/out of date.
Thanks!
