### ISSUE TITLE
Docs formatting of table

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#2586]
It would be nice to have line breaks in the tables (e.g. table 16 is hard to read):

https://bout-dev.readthedocs.io/en/latest/user_docs/laplacian.html?highlight=inner_boundary_flags#usage-of-the-laplacian-inversion

**Comment by ZedThree** [comment]
I think we can set explicit widths for the tables: https://docutils.sourceforge.io/docs/ref/rst/directives.html#table
