### ISSUE TITLE
Performance issues 

### ISSUE THREAD

**Issue by mredenti** [boutproject/BOUT-dev#2590]
I am having performance issues when compiling BOUT++ with `./configure && make` vs `cmake`. 
The code compiled with `cmake` is much slower than the code compiled with `./configure && make`. 
These are the run times for the Hasegawa-Wakatani example

All simulations have in common the following parameters:
- `alpha = 1.0`
- `kappa = 2.0`
- `solver:type=rk4`
- `solver:adaptive=true`
- `solver:mxstep=2000 solver:timestep=0.0001 solver:atol=0.000001 solver:rtol=0.0001`
- `mesh:nx=1028 mesh:dx=0.05 mesh:nz=1024 mesh:dz=0.05`

| Branch | git rev-parse --short HEAD | Machine | Compilation | Nodes | Tasks per node | Nout | Wall time |
| :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
| master | 796caabae | Archer2 | CMAKE | 1 | 64 | 50 | 7 h 44 m 7 s 
| master | 5df721f45 | Archer2 | CONFIGURE | 1 | 64 | 50 | 1 h 46 m 36 s 

## Compilation steps with `./configure && make`
```shell
git clone https://github.com/boutproject/BOUT-dev.git
cd BOUT-dev 
module load cray-fftw
module load cray-parallel-netcdf
module load cray-hdf5-parallel
module load cray-netcdf-hdf5parallel
./configure MPICC=cc MPICXX=CC --with-netcdf --without-lapack
make
make check-all
cd examples/hasegawa-wakatani 
make
```
## Compilation steps with `CMAKE`
```shell
git clone https://github.com/boutproject/BOUT-dev.git
cd BOUT-dev 
module load cray-fftw
module load cray-parallel-netcdf
module load cray-hdf5-parallel
module load cray-netcdf-hdf5parallel
module load cmake
CC=cc MPICXX_CXX=cc CXX=cc MPICXX=cc cmake . -B build -DBOUT_USE_LAPACK=off  -DBOUT_BUILD_EXAMPLES=ON
cmake --build build -j 6
cmake --build build --target check-unit-tests
cmake --build build --target hasegama-wakatami
```

**Comment by mredenti** [comment]
> If you're using v4 of BOUT++ then I think cmake defaults to a Debug build whilst v5 defaults to an optimised one.
> 
> Passing `-DCMAKE_BUILD_TYPE=Release` to the cmake line should hopefully get you an optimised build.

Would it still be `Checking enabled, level 2` with `-DCMAKE_BUILD_TYPE=Release`? Because I have noticed that both runs mentioned above have `Checking enabled, level 2`. In other words, where would I see the "signature" of `-DCMAKE_BUILD_TYPE=Release`?

**Comment by d7919** [comment]
I think the build type only influences the compiler optimisation flags and does not automatically disable or enable potentially expensive BOUT++ features/options. You may find that disabling checks with regular `make` leads to yet faster runs (depending on the model).

**Comment by mredenti** [comment]
> -DCMAKE_BUILD_TYPE=Release

Right, so the default build type with `configure` is `Release` instead? How can I specify a `Debug` build type?

**Comment by d7919** [comment]
I think you would pass `--enable-debug=on` to configure to get a debug build.

**Comment by mredenti** [comment]
Solution is indeed `-DCMAKE_BUILD_TYPE=Release` as you suggested
