### ISSUE TITLE
Incompatible with PETSc 3.18

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#2597]
From the changelog:
- Remove ``PCGAMGSetSymGraph()`` and ``-pc_gamg_sym_graph``. The user should now indicate symmetry and structural symmetry using  ``MatSetOptions()`` and GAMG will symmetrize the graph if a symmetric options is not set

This breaks using the latest PETSc

**Comment by dschwoerer** [comment]
This fixes the build error but the tests fail: https://github.com/boutproject/BOUT-dev/commit/489270184ba9e03cb9996c614050cb92513424e6

@cmacmackin and @johnomotani, you  worked recently on this - do you have maybe a better understanding how to fix this?

**Comment by johnomotani** [comment]
I think the `MatSetOption(*operator3D.get(), MAT_SYMMETRIC, PETSC_TRUE);` call is not needed - actually is wrong. The `PCGAMGSetSymGraph()` option apparently told GAMG that the matrix was not symmetric, and therefore the 'graph' needed to be symmetrized. From 3.18, GAMG will use the `Mat` object to detect whether the matrix is symmetric or not, and symmetrize as necessary. Our matrix is not symmetric, so it looks to me like for PETSc>=3.18 just not doing anything should get us the correct result.

**Comment by sagitter** [comment]
Hi all.

> This fixes the build error but the tests fail: [4892701](https://github.com/boutproject/BOUT-dev/commit/489270184ba9e03cb9996c614050cb92513424e6)
> 
> @cmacmackin and @johnomotani, you worked recently on this - do you have maybe a better understanding how to fix this?

This patch cannot be applied to `bout++-4.4.2`
Does exist a compatibility patch for building against `PETSc-3.18+`?

**Comment by ZedThree** [comment]
PETSc 3.19 is out, so it would be useful if someone was able to fix this.

**Comment by dschwoerer** [comment]
fixed in https://github.com/boutproject/BOUT-dev/pull/2704
