### ISSUE TITLE
NetCDF file format support

### ISSUE THREAD

**Issue by bendudson** [boutproject/BOUT-dev#26]
The default output format is currently NetCDF3, using NetCDF versions before 4.2 (released 2012). This is because in 4.2 the C++ interface changed, and is not compatible with the BOUT++ wrapper.

A branch exists,  "netcdf4" which started to implement a wrapper using the C interface to NetCDF, which has remained stable. Last commit 1fb108a4  (January 2014). This should be tested and merged if possible.

**Comment by ZedThree** [comment]
Fixed in #219 / #357
