### ISSUE TITLE
CMake configure error if Python headers aren't present

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#2610]
I've helped a couple of people with this issue, where if the Python development headers aren't found, CMake will error unless `BOUT_ENABLE_PYTHON` is explicitly turned off. The default for `BOUT_ENABLE_PYTHON` is `MAYBE`, and if we don't find the required packages, we're supposed to turn it off automatically.

I've not reproduced this myself, but I suspect the problem is here:

https://github.com/boutproject/BOUT-dev/blob/4acdfdcb42dd0d8abfde06b5c2544c80d0bf0622/cmake/FindNumpy.cmake#L15

I think the `REQUIRED` is messing things up, and we actually want to set `Numpy_FOUND` to `FALSE` and return if that call doesn't work.

**Comment by dschwoerer** [comment]
Can they try 3f647a6e7f9 [branch find-numpy](https://github.com/boutproject/BOUT-dev/tree/find-numpy)?
