### ISSUE TITLE
Please allow to use externally installed googletest

### ISSUE THREAD

**Issue by yurivict** [boutproject/BOUT-dev#2614]
[here](https://github.com/boutproject/BOUT-dev/blob/master/.gitmodules#L2)

**Comment by dschwoerer** [comment]
It is recommended by googletest to not use a pre-compiled version, but to compile it with the same flags as the project.

I am not sure it is worth to break this recommendation. Do you have a good motivation to do so?

**Comment by ZedThree** [comment]
Only the unit tests get linked against googletest, and I'm not sure when you would ever need to link against something else that was also linked against googletest. Closing this for now, but feel free to reopen if you have a convincing use case
