### ISSUE TITLE
Latest boutdata and boututils are incompatible with BOUT++ v5.0.0

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#2663]
This issue is related to PR #2657

While trying to update them, I noticed they are incompatible.

So the difference between old and new boututils/boutdata is this
```
		fperp_lower:yindex_global = 0 ;
```
changed to this:
```
		fperp_lower:yindex_global = 0LL ;
```

The question is, should this be reverted in the python packages?
Why does bout++ not handle reading the `LL` version?

Should we stop supporting evolving fperp?

**Comment by ZedThree** [comment]
I think this is fixed now
