### ISSUE TITLE
RTD defaults to `main` branch

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#2688]
The "Suggest edit" button isn't working, as one needs to replace main with next in the url

Not sure where to change this ...

**Comment by ZedThree** [comment]
There's a `.readthedocs.yaml` config file, though it's not currently set there

**Comment by dschwoerer** [comment]
It seems default_branch can only be set in the web interface:
https://docs.readthedocs.io/en/stable/config-file/v2.html#migrating-from-the-web-interface

I think I don't have access ...

**Comment by ZedThree** [comment]
Ah, no, I bet that is actually set from the `html_theme_options` settings in `conf.py`. We use `sphinx-book-theme`. But we probably should also change the default branch to stable, which I will do now.
