### ISSUE TITLE
v5.0.0 Release tarball contains BOUT++-v5.0.0.dev10626+gd935fa1ea

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#2691]
The content is correct, but due to #2683 the folder name was wrong.

Should we upload a corrected version?

**Comment by dschwoerer** [comment]
It seems I can delete the old tar.gz and upload a new one. The question now is - should I do it?

**Comment by ZedThree** [comment]
Sorry, missed this originally. Yes please, if you can, I'm very pressed for time at the moment.

**Comment by dschwoerer** [comment]
I am by now a bit hesitant, as that will break all downstream works, that are working around that by now.

If you think v5.0.0 will be used (by humans) after v5.0.1 release, I can update, but I am a bit hesitant.

If you think this is still worth while doing, I am will, but otherwise I would close this as `wont fix` - it is fixed in master, so should be fine on the next release.
