### ISSUE TITLE
HDF5 file support

### ISSUE THREAD

**Issue by bendudson** [boutproject/BOUT-dev#27]
It would be nice to be able to read input and write output to HDF5 formatted files. This involves writing an implementation of the DataFormat interface. See existing implementations under

BOUT-dev/src/fileio/impls

e.g. "netcdf" and "pdb"

**Comment by johnomotani** [comment]
Mostly done in hdf5 branch. ```configure.ac``` still needs updating to set -DHDF5 and link to libhdf5.a if --with-hdf5 is given.

Some changes have been made to Datafile to enable parallel I/O, but this is not yet implemented.

**Comment by johnomotani** [comment]
HDF5 read routines now work (test-io_hdf5 has both input and output in HDF5 format).

Parallel I/O is supposed to be enabled (./configure --with-parallelhdf5), but either it is broken or it needs a parallel file system to test.
