### ISSUE TITLE
Identity transform with twistshift is impossible

### ISSUE THREAD

**Issue by bshanahan** [boutproject/BOUT-dev#2703]
At the moment, the twistshift condition cannot be applied to fields with an identity transform, as they do not have YDirectionType::Aligned. See, for instance: https://github.com/boutproject/BOUT-dev/blob/232e77e3112d785aacae0307dcbf272fe39e276d/src/mesh/impls/bout/boutmesh.cxx#L1423-L1426

The documentation explicity states that it is possible to have an identity transform with a twistshift condition.

**Comment by johnomotani** [comment]
One workaround is to do, in your physics-model code, something like
```f = f.toFieldAligned()```
for each variable you have. It should be possible to do this just in initialisation somewhere.

**Comment by dschwoerer** [comment]
Maybe something like this:
```
if (Options::getRoot()->getSection("mesh:paralleltransform")["type"] .as<std::string>();== "identity") {
   f = f.toFieldAligned();
  ...
}
```

Of course, that is only a work around until there is a proper fix ...
