### ISSUE TITLE
Docs: User registered methods

### ISSUE THREAD

**Issue by aratava** [boutproject/BOUT-dev#2738]
I acknowledge that the [documentation](https://bout-dev.readthedocs.io/en/latest/user_docs/differential_operators.html#user-registered-methods) shows an example of how to define and register a "user registered method" (C2 in that example), but I need more information as to how to do this. I am trying to implement a method using a stencil that is made of f_1, f_-1, f_2, and f_-2 points (relative to f_0 which is the current point). Would you please help me with it? Thank you in advance!

**Comment by johnomotani** [comment]
The stencil object does include 5 points:
f.mm is f[i-2]
f.m is f[i-1]
f.c is f[i]
f.p is f[i+1]
f.pp is f[i+2]

Does that help? You might also want to look through the BOUT++-implemented derivatives in https://github.com/boutproject/BOUT-dev/blob/master/src/mesh/index_derivs.cxx.

**Comment by aratava** [comment]
> The stencil object does include 5 points: f.mm is f[i-2] f.m is f[i-1] f.c is f[i] f.p is f[i+1] f.pp is f[i+2]
> 
> Does that help? You might also want to look through the BOUT++-implemented derivatives at https://github.com/boutproject/BOUT-dev/blob/master/src/mesh/index_derivs.cxx.

It of course helps a lot, thank you! So I assume there is no easy way to have a 7-point stencil including f[-3] and f[3]?

**Comment by ZedThree** [comment]
Unfortunately not, though this is something that's on our wishlist for future work.
