### ISSUE TITLE
DataIterator::offset()

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#278]
`DataIterator::offset(dx,dy,dz)` returns invalid Indices, if `nz < -dz`, e.g. if there is only one z point and `.offset(0,0,-2)` is used.

For `dz=2` I have implemented 

```
  const Indices zpp() const { int zp=(z == zend ? zstart : z+1); return {x, y, zp == zend ? zstart :zp+1 }; }
  const Indices zmm() const { int zm=(z == zstart ? zend : z-1); return {x, y, zm == zstart ? zend : zm-1}; }
```

the more general solution would be:

```
    return {x+dx, y+dy, ((z+dz-zstart + 8*nz) % nz) + zstart};
```

hoping that nobody is using an larger offset than 8 while only using a single point in z direction ...

**Comment by dschwoerer** [comment]
In more detail:
% of a negative number is negative (or zero)
therefore, if -dz is larger than z+nz, the argument for modulo is zero, and the result is outside of the domain. This may not be the case for most simulations, but it is still wrong, and I don't think we should keep wrong code, just because it is faster (which I am not sure)

**Comment by bendudson** [comment]
Another possibility:

(( ( (z+dz-zstart) % nz) + nz) % nz) + zstart;

This should (I think) always be in the range zstart to (zstart+nz-1) inclusive. It does involve two modulus operations though. 

Or we could put in guard cells in Z...

**Comment by dschwoerer** [comment]
| range | model | mean | stddev | min | max |
|------|--------|---------|-----------|--------|-----------|
| 0 1 | BEN | 0.166138 | 0.003665 | 0.157014 | 0.169787 |
| 0 1 | ORG | 0.102617 | 0.002643 | 0.095798 | 0.106146 |
| 0 1 | DAVE | 0.061518 | 0.018036 | 0.038645 | 0.089279 |
| 0 63 | BEN | 0.165118 | 0.001613 | 0.162381 | 0.168256 |
| 0 63 | ORG | 0.096228 | 0.000952 | 0.094580 | 0.097771 |
| 0 63 | DAVE | 0.087226 | 0.026324 | 0.043176 | 0.127765 |
| 1 126 | BEN | 0.169272 | 0.002777 | 0.164576 | 0.174476 |
| 1 126 | ORG | 0.098711 | 0.001328 | 0.095508 | 0.101161 |
| 1 126 | DAVE | 0.082887 | 0.024832 | 0.040657 | 0.119596 |

I made some [timings](https://gist.github.com/dschwoerer/cbd813e168e0597262fec1335586a489) -  and I don't think it matters that much ...

**Comment by bendudson** [comment]
Nice! Thanks David, good to have some hard data. Happy to accept your pull request as it seems fastest and correct
