### ISSUE TITLE
function evaluation in "global" part of BOUT.inp

### ISSUE THREAD

**Issue by JensMadsen** [boutproject/BOUT-dev#28]
It would be useful if expressions like 

zmax = mesh:Lz/(2*pi)

could be evaluated

**Comment by bendudson** [comment]
Hey Jens,

Yes, this should be possible with the changes in commit ea5da2e5
Any real valued scalar, 2D or 3D field can be specified in the options (BOUT.inp or command line). For now integers can't be expressions though, so  

ny = mesh:N
nx = mesh:N + 2*MXG

will not work yet. In principle it could, but would probably need to rely on rounding a real valued expression to the nearest integer.

**Comment by JensMadsen** [comment]
ok. I test again. Thought I had the latest pull. Perhaps my really bad git skills prevent me from merging my own changes and that commit:-D


Jens Madsen
PPFE, DTU Physics
Denmark
________________________________
