### ISSUE TITLE
No "datafile.hxx" when compile BOUT with hypre option

### ISSUE THREAD

**Issue by Feifeijpy** [boutproject/BOUT-dev#2817]
Problem occurred when compiling BOUT with hypre option after compiling hypre successfully.

BOUT version : 5.1.0
hypre version : 2.26.0

`BOUT-dev-gcc-mpich/src/invert/laplace/impls/hypre3d/hypre3d_laplace.cxx:42:10: fatal error: datafile.hxx: No such file or directory`

`#include <datafile.hxx>`
`         ^~~~~~~~~~~~~~`
`compilation terminated.`

`gmake[2]: ***[CMakeFiles/bout++.dir/build.make:780:CMakeFiles/bout++.dir/src/invert/laplace/impls/hyre3d/hypre3d_laplace.cxx.o]Error 1`
`gmake[1]:*** [CMakeFiles/Makefile2:2493: CMakeFiles/bout++.dir/all] Error 2`

**Comment by johnomotani** [comment]
Looks like the same issue that was fixed in #2791?

**Comment by Feifeijpy** [comment]
It worked, thank you @johnomotani  @bendudson.
