### ISSUE TITLE
Compilation of BOUT++ on ARCHER and batch jobs

### ISSUE THREAD

**Issue by fulviomilitello** [boutproject/BOUT-dev#282]
In the last few months, I've experienced problems running BOUT++ batch jobs on ARCHER. I think I figured out why I and would like to bring this to the attention of the group. 

When configuring BOUT++ without flags, ARCHER now selects mpicxx as a compiler. The code compiles alright and passes all the tests. An interactive mpirun command gives the expected results, i.e. the code works. However, when batch jobs are lunched with the aprun command, the code does not work as some mpich libraries are not found.

To solve the problem, one has to configure BOUT++ with this command: ./configure MPICXX=CC. This sets the parallel C++ compiler to be the CC wrapper, which has all the correct links to the libraries. The code can then be made without errors. _However, when I tried to run the test_suite, all the tests FAILED_ ! I suspect it is because the tests are lunched with mpirun... On the other hand, now the batch jobs respond to the aprun command and everything works as expected. In other words, this is the right configuration, the only flaw is the test_suite. 

I hope this is helping, it might be worthwhile adding a line or two about this on the manual, when discussing the Archer installation

**Comment by dschwoerer** [comment]
To run the test suite on archer, submit an job.
This way you will test the code in the environment you want to run the code.
Otherwise you are only testing everything is setup fine for running jobs on the login node.

**Comment by d7919** [comment]
Note that if you wish to build with the intel compilers on Archer then as of v4 of BOUT++ it's necessary to do `module load gcc` before configuring. Failure to do this will lead the configure script to believe that the compiler doesn't support c++11 features. With this module loaded the configuration should successfully complete.

**Comment by d7919** [comment]
Some issues seem to arise when linking, probably due to compilation of some of the libraries with older compilers or similar.

The question at https://stackoverflow.com/questions/33394934/converting-std-cxx11string-to-stdstring represents some of the issues that arise, with the fix being to add `-D_GLIBCXX_USE_CXX11_ABI=0` to `BOUT_FLAGS`.
