### ISSUE TITLE
MPI failure with mpich 4.1.2 on s390x

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#2833]
I am seeing the following error in BOUT++ v5.1.0 on s390x:
```
0.000e+00          1       4.66e-02   -1195.7    1.8  1197.7  146.8  -50.6
1.000e+03         20       3.00e-01    12.6    3.7   40.6   14.2   28.8
/  Step 1 of 30. Elapsed 0:00:00.3 ETA 0:00:08.1Abort(5843983) on node 1 (rank 1 in comm 0): Fatal error in internal_Barrier: Other MPI error, error stack:
internal_Barrier(84).......................: MPI_Barrier(comm=0x84000001) failed
MPID_Barrier(167)..........................: 
MPIDI_Barrier_allcomm_composition_json(132): 
MPIDI_POSIX_mpi_bcast(219).................: 
MPIDI_POSIX_mpi_bcast_release_gather(132)..: 
MPIDI_POSIX_mpi_release_gather_release(218): message sizes do not match across processes in the collective routine: Received 0 but expected 1
```

I am only seeing this with mpich, but not with openmpi 5.0.1

Might that be a bug in BOUT++?
Do you have any ideas on how to debug this further?

The following tests failed before the timeout:
test-delp2
test-drift-instability
test-drift-instability-staggered
test-fieldgroupComm
test-interchange-instability

The all use the cvode solver, but I could not find another test that did run succesfully and uses a different time solver ...

Error log: [builder-live.log.gz](https://github.com/boutproject/BOUT-dev/files/13870958/builder-live.log.gz)

Build: https://copr.fedorainfracloud.org/coprs/davidsch/testing-all/build/6872187/

**Comment by dschwoerer** [comment]
MMS tests pass all. The unit tests pass, but that is also without MPI.

`test-invertable-operator` is stuck - which causes the timeout ...

**Comment by ZedThree** [comment]
I don't think we support mainframes
