### ISSUE TITLE
Failure to open output file is ignored

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#285]
If an output file could not be opened, this is ignored:
```
        File extension not recognised for 'fuu.dmp'
        Option :nout = 100 (Command line)
        [...]
```
As the whole simulation is probably useless if I don't get these values, I would prefer an exception.
I am not sure where the implemention is dependend on ignoring `errors` in the Datafile, but it seems to me there are quite a number of cases where things are ignored, if they cannot be done, e.g.:
```
  if(!enabled)
    return true; // Pretend to be valid   
```

**Comment by bendudson** [comment]
Agreed, this should cause an exception. The second example, where an output
is disabled, is mainly for timing benchmarks, where the I/O is not
important.
