### ISSUE TITLE
Datafile grow

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#287]
There is an int option to the Datafile, called grow.
I have been wondering 
* why an int is used (as it is anyway 'cast' to an bool)
* why negative ints are converted to false, which is non-intuitive as it is not default C/C++ behaviour
* whouldn't save_repeat be a better name

**Comment by bendudson** [comment]
Not sure... this is probably a hangover from old (old) C code. Yes, agreed a bool would be better, and save_repeat would be a much better name. I think most user code uses the SAVE_ONCE and SAVE_REPEAT macros anyway, so wouldn't be affected by this change.

Perhaps even better (debatable) is whether there should be two functions, so the reader doesn't have to remember whether

    dump.add(Var, "Var", true);

means save once or save repeatedly. Instead maybe

    dump.saveOnce(Var, "Var"); 
    dump.saveRepeat(Var, "Var");

**Comment by ZedThree** [comment]
I definitely prefer two sensibly-named functions over one mysterious argument. Pity C++ doesn't have keyword arguments :/
