### ISSUE TITLE
FieldAligned operators in next

### ISSUE THREAD

**Issue by bendudson** [boutproject/BOUT-dev#293]
The next branch has changed the default coordinates, from being field aligned to being in orthogonal X-Z space. This removes FFT shifts when taking radial (X) derivatives, but adds them when taking parallel (Y) derivatives. It also adds overheads when taking derivatives of expressions:

```
Grad_par(A + B) 
```

Now either A+B must also operate on the yup() and ydown() fields, or an additional communication step and boundary condition is needed. 

1) In many cases this is just a matter of being more careful about which things are communicated, so writing Grad_par(A) + Grad_par(B). We should make sure that Grad_par(A+B) fails with a useful warning message, rather than producing a wrong answer

2) In some cases it is useful to have the field in field-aligned coordinates, particularly for flux conserving schemes. Perhaps it would be good to have a set of operators which use the toFieldAligned() and fromFieldAligned() functions:

Grad_par(f)   -- Use f.yup() and f.ydown(), needs communication 

FieldAligned::Grad_par(f)  -- Shift f to field aligned coordinates, don't use yup() or ydown(). No communication required 

for naming, we could either use namespaces or longer names like Grad_par_FA()?

**Comment by ZedThree** [comment]
This should probably be documented in the change notes for v4.

I think that if the argument is a [*prvalue*][1], that's when we have problems. We could maybe put in some nature of detection for prvalues and warn/throw exception until this is fixed. See [here][2] for one way of doing this.

[1]: http://en.cppreference.com/w/cpp/language/value_category#prvalue
[2]: http://stackoverflow.com/a/16638081/2043465

**Comment by ZedThree** [comment]
I say prvalue, that might be too specific - maybe just rvalues?

**Comment by JosephThomasParker** [comment]
It's worth noting that this can have reproducibility implications for physics models as they change from v3 to v4.  While `Grad_par(U-V)` will be the same as `Grad_par(U)-Grad_par(V)`, numerically `Grad_par(n*T)` is not the same as `n*Grad_par(T)+T*Grad_par(n)`.  The two can even be qualitatively different, like having different [stability properties](http://www.ams.org/journals/mcom/1973-27-121/S0025-5718-1973-0395249-2/).

It would be nice to have a natural way of doing `Grad_par(n*T)` without having to make and communicate another `Field3D`.

Actually, I'm not clear what the correct way of doing `Grad_par(n*T)` now is.  Is it:
`Field3D nT = n*T;
mesh->communicate(nT);
Grad_par(nT); ` ?

**Comment by d7919** [comment]
At the moment I think your last suggest would be the "recommended" way.

It would be possible to change the underlying code to either automatically calculate the auxiliary data when there are such `field3d` operations (but this would add a lot of computational overhead when it's not needed), or we could modify parallel operators to always communicate (but this could potentially add a lot of communication overhead). It should be possible to detect when a field doesn't have the required data yet and then auto-communicate -- this would reduce the additional cost a bit (such that `Grad_par(f)` doesn't lead to a communicate, assuming `f` has been communicated at some point ) but it would still be an overhead compared to v3.

I would like to be able to split the `communicate` step from the `calcYUpYDown` step as I think it's usually only the later that is needed in these cases (although maybe not with `twist-shift` -- motivation for updating how this works ?).

**Comment by bendudson** [comment]
I am encountering this problem at the moment, trying to tidy up and get the fluid dynamics examples working (Rayleigh-Taylor and Sod shock). Vectors, and operations on vectors are tricky, and often involve changing between co- and contravariant. Using yup() and ydown() then means these fields need to be changed to be consistent, preferably without communicating.

What I'm coming around to is a bit of a compromise, but perhaps it might work. For operators which need derivatives in Y (like Grad_par)

o If a field does not have yup() and ydown() fields, like Grad_par(n*T), then transform to field aligned coordinates using mesh->toFieldAligned(field). For shifted metric coordinates this would then be similar to the old system, except now shifting for Y derivatives rather than X derivatives. FCI would fail, with a message that the field could not be transformed to field aligned coordinates.

o If a field does have yup() and ydown() then these are used for parallel derivatives. 

What this would mean is that Grad_par(n*T) would transform to field-aligned coordinates, failing if it couldn't be done. We could have a variant of the ShiftedMetric parallel transform which left all yup() and ydown() fields as nullptr, so all parallel derivatives would transform to/from field-aligned coordinates. This would then be similar to the system used in master: more FFTs for transforms, but fewer communicates/calculations.

To do the same thing with FCI (using yup() and ydown()) you would have to either use:

Field3D nT = n*T; mesh->communicate(nT); result = Grad_par(nT);

or to avoid communications but increase number of calculations:

Field3D nT = n*T;
nT.splitYupdown(); // Creates yup() and ydown() fields
nT.yup() = n.yup() * T.yup();
nT.ydown() = n.ydown() * T.ydown();
result = Grad_par(nT);

which I think you'll agree is really ugly. This could be tidied up / hidden using a method or function:

result = Grad_par( all(n) * all(T) );
or
result = Grad_par( n.all() * T.all() );

where all() would return an object with a reference to the field, and then overload operators to operate on the field, field.yup() and field.ydown()

**Comment by d7919** [comment]
I like that idea -- things just work for the user (with minimal overhead) but the advanced user can customise further if required.

**Comment by bendudson** [comment]
Your idea of automatically calculating yup() and ydown() if not present sounds good.. I can't decide. 
The calcYupDown() method can be made public by either making Mesh::getParallelTransform() public, or adding a function calcYupDown() to Mesh (which might be cleaner, like toFieldAligned).

If an operator (like Grad_par) is given a field without yup() and ydown() fields, like Grad_par(n*T), then it could either
a) communicate. As @d7919 says this is probably too much overhead in most cases and the user should know this is being done
b) transform to field-aligned coordinates. This is only possible in some cases, though they are the most common cases.
c) calculate Yup and Ydown, without communicating in the case of shifted metric (again, most common case).

Some operators only work in field aligned coordinates, so will need to do (b), but others could do either a or b. Preferences? Different namespaces or naming convention?

**Comment by d7919** [comment]
I've experimented with making `calcYupYdown` public but found that this doesn't work correctly (well -- it gives a different result) when `TwistShift=true` -- presumably because the y twisted boundary condition is applied when using `communicate` but not when calling `calcYupYDown` directly -- although I've not thought this through in detail. Therefore I think case (c) would require further work to be robust (I assume this approach would also work correctly for the `identity` transform?).

**Comment by bendudson** [comment]
Probably the twistshift condition should be made part of paralleltransform... this would then also allow the twist-shift location to be at any y location, not just at processor boundaries.

**Comment by bendudson** [comment]
I've had a go at implementing Div_par operator to handle the many possible cases:

https://github.com/boutproject/BOUT-dev/tree/v4-difops/src/mesh/difops

At the moment I'm not sure that the code compiles, let alone works as intended, but just to get an idea of how this might be, and the extent of the code explosion.

I think this approach addresses the following problems:
* There is no longer a function pointer in the inner loop, no more Stencils. Instead DataIterator indexing is used. This should allow everything to be inlined and OpenMP parallelised. Preliminary tests (in https://github.com/boutproject/BOUT-dev/tree/v4-difops/examples/performance/difops) indicated about a factor of 2 speedup.
* Since Div_par is calculated directly, rather than using Grad_par, the problem of calculating f/B in the yup/ydown fields doesn't arise
* If the input doesn't have yup/ydown fields (such as a compound A + B), then the default method will fail. The user can however explicitly select a field aligned method e.g. Div_par(A+B, Difop::C2_FA) to select at run-time, or Div_par_C2_FA(A+B) to call directly, which will transform into field-aligned coordinates, perform the operation, then transform back. 
* By selecting the "FA" (Field Aligned) methods, a user can avoid any use of yup,ydown fields and presumably avoid any performance penalty they incur.
*  Issue #419 -- Trying to use unavailable options results in an exception
* Issue #312 -- The code is simplified (imho), and separating into a different file for each operator also helps clarify things. 
* The FCI method has been extended to be more robust, by using more than one point to calculate divergences, and instead integrating over an area. By making Div_par implementations different functions, a future implementation can be included which uses this or other more complicated methods which don't fit into a simple 1D stencil approach.

The code is still quite long for what it does, with a fair bit of repetition. Suggestions for ways to shorten welcome, but otherwise I think it might be a price worth paying for the above benefits.

The choice of method is not (here) selected using an option. This could be added, or we could leave it up to the user to decide how to set the Difop method to use at run-time, if that's what they want.

**Comment by bendudson** [comment]
Updated a bit, now with headers here for each operator:
https://github.com/boutproject/BOUT-dev/tree/v4-difops/include/bout/difops
and source code here:
https://github.com/boutproject/BOUT-dev/tree/v4-difops/src/difops

**Comment by dschwoerer** [comment]
I don't think the support for staggered grids is working ...
I don't always want my derivatives at the cell_centre - further I also want to have the position at ylow if my data is at cell_centre. By default the old code stayed at the same position (CELL_DEFAULT)

Taking that into account, this leads to even more repetition. Implementing further stencils would even more repetition.
I have [pushed](https://github.com/dschwoerer/BOUT-dev/tree/v4_aiolos_mesh/src/mesh/impls/aiolos) my AIOLOS branch, which generates the repetitive code using python.
I know it is currently quite chaotic, but this is (at least partially) due to the fact that I parse the old stencil c-code and also include the free boundary code. Both could be droped if it/something similar was adopted as the main method ...

Concerning speedup: For the STORM module I have seen a speedup of factor 10 for the 1D case (thanks to AVX/SSE) - for the C4 stencils the speedup is less, but still > 2 ...

**Comment by bendudson** [comment]
An issue is that the current treatment of staggered grids is only correct if the grid spacing is uniform. If it is not uniform, then going from Centre->Centre is not the same as Low->Low. Rather than trying to support every possibility, it might be better to have a smaller number of functions, but check that they each do the correct thing. 

I'm having a play with templates at the moment, to see if there is a way to reduce the amount of code repetition. Looks promising so far, but staggered grids complicates everything.

**Comment by d7919** [comment]
I've mostly ignored staggering when looking through the internals etc. so the following may not be very sensible.

Would staggering be simplified if we allowed there to be multiple meshes in existence -- variables could then be defined on either the standard or offset mesh and whatever code we develop to allow interaction between meshes could then be used to transform data back and forth as required? This may be somewhat similar to what we have now but would perhaps move the staggering logic away from the derivative application allowing less repetition and easier templating?

**Comment by dschwoerer** [comment]
I am not in favor of using templates, mainly because it is really hard to achieve vectorization with templates.

I am fully aware that Low -> Low is different - but then again we don't support non uniform meshes anyway ... if that would be changed, fixing this for the staggered grids wouldn't be impossible to change.

In STORM Low->Low is used (as well as C->L, C->C and L->C) therefore I would prefer if that upstream wouldn't break that (or at least allow a simple way to override this with the AIOLOS derivatives)

I don't think different meshes would simplify things - as C->L and L->C would be rather challenging, as they are a (I guess) very simple case of different meshes. I guess the standard behaviour would be to take the derivative within the same mesh, and then interpolate to the other (or vice versa)

**Comment by bendudson** [comment]
This is probably the most correct way to do this, but may be more
complicated. Staggered grids are really complicated in general, since to
have conservation properties the cell volumes associated with staggered
grids should be kept track of as well as the cell centre values. If
momentum is evolved on cell boundaries, then it has a different control
volume from density, for example, and then dividing momentum by density to
get a velocity is messy in general. For uniform grids things are much
simpler.

**Comment by dschwoerer** [comment]
One thing, I would like to see the function signatures changed - instead of an bool to include a range, a RANGE flag would be nice to have, as it imho easier to use as user...

**Comment by bendudson** [comment]
Agreed, a range flag would be much better.

**Comment by bendudson** [comment]
I wasn't aware of a problem with vectorisation and templates: If done properly it should all be inlined by the compiler, and produce code as it would be if hand-written. There is lots of vectorised template code e.g. https://github.com/awishnick/vectorize

**Comment by dschwoerer** [comment]
I had even troubles without templates, as the compiler is afraid the data fields may be aligned ...
The vectorize header seems promising, but needs to be extended for AVX instructions (and maybe more features - features about the cpu the compiler knows better than I do)

**Comment by bendudson** [comment]
Would it be possible to see a part of the generated code, to see how these loops have been vectorised? Perhaps it would be possible to do something similar but with templates. Not sure how to combine it with the DataIterator iteration, but as I understand it, it's basically a matter of loading everything into small arrays then looping over the small arrays.

**Comment by dschwoerer** [comment]
I don't use the DataIterator, because auto-vectorization failed.
Right now I use the gnu extension `__restrict__`, but I would be able to separate these function to a separate c file, and use any C (std99) compiler, as `restrict` is a valid keyword in C (but not in C++) ...
```
// This file is auto-generated - do not edit!
static void indexDDX_on_DIFF_C2_field3d(BoutReal * __restrict__ result_ptr, const BoutReal * __restrict__ in_ptr) {
    const int Nx = mesh->LocalNx;
    const int Ny = mesh->LocalNy;
    const int Nz = mesh->LocalNz;
#ifdef CHECK
    if (mesh->xstart < 1) {
        throw BoutException("Cannot compute derivative - need at least 1 guard cells in X direction!");
    }
#endif
    for (int x = 1; x < Nx+0; ++x ) {
        for (int y = 0 ; y < Ny; ++y ) {
            for (int z = 0 ; z < Nz; ++z ) {

                result_ptr[((x+0)*Ny + y)*Nz + z]
                    =  in_ptr[((x+0)*Ny + y)*Nz + z]
                       - in_ptr[((x-1)*Ny + y)*Nz + z]
                       ;

            }
        }
    }
    int x =0 ;
    for (int y =0; y < Ny ; ++y ) {
        for (int z =0; z < Nz ; ++z ) {

            result_ptr[((x+0)*Ny + y)*Nz + z]
                = -2.*in_ptr[((x+0)*Ny + y)*Nz + z]
                  +3*in_ptr[((x+1)*Ny + y)*Nz + z]
                  -in_ptr[((x+2)*Ny + y)*Nz + z]
                  ;
        }
    }
}

// This file is auto-generated - do not edit!
static Field3D indexDDX_on_DIFF_C2 (const Field3D &in) {
    //output.write("Using method indexDDX_on_DIFF_C2!\n");
#ifdef CHECK
    if (mesh->LocalNx < 2) {
        throw BoutException("AiolosMesh::indexDDX_on_DIFF_C2 - Not enough guards cells to take derivative!");
    }
#endif
    Field3D result;
    result.allocate();
    BoutReal * __restrict__ result_ptr = & result ( 0 , 0 , 0 );
    checkData(in);
    const BoutReal * __restrict__ in_ptr = & in ( 0 , 0 , 0 );
    indexDDX_on_DIFF_C2_field3d(result_ptr,in_ptr);
    result.setLocation(CELL_XLOW);
    checkData(result);
    return result;
}
```

**Comment by bendudson** [comment]
It's unfortunate that this method seems to be the way to get best performance, since code generation like this seems fragile and difficult to extend or adapt in future. Premature optimisation being the root of all evil and all that... Still, it seems to be the approach taken by OPS (http://www.oerc.ox.ac.uk/projects/ops) and OpenSBLI (https://opensbli.github.io/) which uses it.

I think if this approach is used, then the inputs to the code generation (i.e. the differencing algorithms) should be in a format which is easier to understand and debug, rather than pulled from C/C++ code. They could be in Python, or stored in a separate file. 

If non-uniform dx,dy,dz meshes are not handled properly, should dx and dy be constants like dz? Non-uniform grids are handled through the metric tensor. Otherwise I think we should try to handle them correctly where possible.

**Comment by loeiten** [comment]
Maybe it would also be an idea to state where the file is auto-generated from?

**Comment by bendudson** [comment]
I've tried a template approach which reduces the line count considerably, but doesn't fix the underlying combinatorial explosion problem.

Template code for Div_par here: https://github.com/boutproject/BOUT-dev/blob/v4-difops/src/difops/div_par_templates.cxx#L126

    const Field3D Div_par_C2_TEST(const Field3D &f) {
      OpDivParC2<Field3D,   // Operates on Field3D input
                 ValueStencilYud  // Use Yup and Ydown to get values from stencils
                 > op(f);
      return evalOperator<Field3D>(op, RGN_NOBNDRY); // Evaluate over a Field3D region
    }

compared to hand-written version which does the same thing here: https://github.com/boutproject/BOUT-dev/blob/v4-difops/src/difops/div_par.cxx#L87

    const Field3D Div_par_C2(const Field3D &f) {
      TRACE("Div_par_C2(Field3D)");
      ASSERT1(f.getLocation() == CELL_CENTRE);
      Field3D result;
      result.allocate();
      result.setLocation(CELL_CENTRE);
      Field3D fyup = f.yup();
      Field3D fydown = f.ydown();
      Coordinates *coord = mesh->coordinates();  
      for(auto i : f.region(RGN_NOBNDRY)) {
        auto yp = i.yp();
        auto ym = i.ym();
        result[i] = coord->Bxy[i]*( (fyup[yp]/coord->Bxy[yp]) - (fydown[ym]/coord->Bxy[ym]) ) / (2.*coord->dy[i]*sqrt(coord->g_22[i]));
      }
      return result;
    }

Test case to compare results and timing is in https://github.com/boutproject/BOUT-dev/blob/v4-difops/examples/performance/templates/test_div_par.cxx

With checks disabled, optimisation flag -O3

Hand written      : 0.0102679 
Templates         : 0.00942375
Original          : 0.0133223

so templates aren't hurting, but haven't particularly helped. The amount of copying and pasting to do goes down, and the algorithms are now split up so only in one place, but it's still not particularly nice.

**Comment by bendudson** [comment]
Some useful things for optimisation, not sure where else to put them for now...

Disassembly: objdump -S --disassemble <object file>

Vectorizing article (2003): http://www.drdobbs.com/programming-guidelines-for-vectorizing-c/184401611

Specify that a loop can be executed in any order:
#pragma ivdep
or 
#pragma GCC ivdep

    g++ vectorisation reports: -O2 -ftree-vectorize -ftree-vectorizer-verbose=1 -fopt-info-vec -fopt-info-vec-missed

Compiling the following loop (in examples/performance/iterator) with above options:

    for (auto i : result) {
        result[i] = a[i] + b[i];
    }
gives:

`iterator.cxx:169: note: ===== analyze_loop_nest =====
iterator.cxx:169: note: === vect_analyze_loop_form ===
iterator.cxx:169: note: not vectorized: multiple nested loops.
iterator.cxx:169: note: bad loop form.
Analyzing loop at ../../../include/bout/dataiterator.hxx:131

../../../include/bout/dataiterator.hxx:131: note: ===== analyze_loop_nest =====
../../../include/bout/dataiterator.hxx:131: note: === vect_analyze_loop_form ===
../../../include/bout/dataiterator.hxx:131: note: not vectorized: multiple nested loops.
../../../include/bout/dataiterator.hxx:131: note: bad loop form.
Analyzing loop at ../../../include/bout/dataiterator.hxx:136

../../../include/bout/dataiterator.hxx:136: note: ===== analyze_loop_nest =====
../../../include/bout/dataiterator.hxx:136: note: === vect_analyze_loop_form ===
../../../include/bout/dataiterator.hxx:136: note: ===== analyze_loop_nest_1 =====
../../../include/bout/dataiterator.hxx:136: note: === vect_analyze_loop_form ===
../../../include/bout/dataiterator.hxx:136: note: not vectorized: control flow in loop.
../../../include/bout/dataiterator.hxx:136: note: bad inner-loop form.
../../../include/bout/dataiterator.hxx:136: note: not vectorized: Bad inner loop.
../../../include/bout/dataiterator.hxx:136: note: bad loop form.
Analyzing loop at ../../../include/bout/dataiterator.hxx:133

../../../include/bout/dataiterator.hxx:133: note: ===== analyze_loop_nest =====
../../../include/bout/dataiterator.hxx:133: note: === vect_analyze_loop_form ===
../../../include/bout/dataiterator.hxx:133: note: not vectorized: control flow in loop.
../../../include/bout/dataiterator.hxx:133: note: bad loop form.`

dataiterator.hxx:131 is
    inline bool operator!=(const DataIterator& rhs) const

dataiterator.hxx:136 is 
    return  !(x == rhs.x && y == rhs.y && z == rhs.z);

dataiterator.hxx:133 is
    if (rhs.isEnd)

**Comment by d7919** [comment]
Is this activity now complete?

**Comment by ZedThree** [comment]
This discussion encompassed several things, some of which are complete:

1. Vectorisation of derivatives: done in #1384 
2. Correct handling of staggering: partly?
3. Handling of situations like `Grad_par(A + B)`: done by converting to field aligned, but could be improved by overloading on rvalues

**Comment by ZedThree** [comment]
My understanding is staggering is now handled correctly, and `Grad_par(A + B)` is now handled reasonably for most cases.
