### ISSUE TITLE
CVODE mxorder setting no longer works

### ISSUE THREAD

**Issue by mikekryjak** [boutproject/BOUT-dev#2946]
I've noticed that CVODE won't stay on first order in some of my recent test runs. From @Steven-Roberts: 

> There's been two options to set the max order: cvode_max_order and mxorder. In some of the recent changes, I accidentally have mxorder going unused. A temporary fix is to switch to cvode_max_order. For a proper fix, some options are:
Allow both options as it was before
Allow one option and remove the unused other option so at least there will be an error when parsing the input file.

**Comment by ZedThree** [comment]
Ah, we probably want to restore the option in master/5.1.1, mark it as deprecated (not sure we actually have a way of doing this for input options), and then add it to the input upgrader when we remove it.

**Comment by Steven-Roberts** [comment]
I can make a PR fix Monday. Which should be deprecated? `cvode_max_order` or `mxorder`?

**Comment by ZedThree** [comment]
I think maybe deprecate `mxorder` and keep `cvode_max_order`? 

To be honest, looking through the rest of the options, we don't have terribly consistent naming scheme -- another one for the to do list, sort out option names!

**Comment by Steven-Roberts** [comment]
Ok, sounds good. I'll get started on a fix
