### ISSUE TITLE
field::applyBoundary

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#300]
why are the corners set to zero in Field3D::applyBoundary(true)?
It may well be that the corner include not the right values - but if I use e.g. the field factory, I don't want them to be overwritten, otherwise I to do again what the fieldFactory did ...

If you want to make sure it does not break a simulation by introducing unexpected results, than set to `nan("")` - that way it is observable if things break ...

**Comment by bendudson** [comment]
This should probably not be there; either leaving the corner cells untouched, or setting to nan

**Comment by JensMadsen** [comment]
This also gives problems when running with check >= 3 or higher when calculating log (Field3D) because log(0)  = -\infty and hence the the "finite" check throws an error

**Comment by ZedThree** [comment]
This is the [original issue][1].

I've managed to get uedge_benchmark running. After one timestep, it doesn't make any difference if field3d.cxx:792-814 are commented out or not. As the test suite also still passes, I propose it's just removed.

[1]: https://github.com/bendudson/BOUT/issues/11
