### ISSUE TITLE
boutdata.settings internals could be replaced with ConfigParser

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#304]
`ConfigParser` is in the Python standard library so adds no external dependencies. The 'global', sectionless part causes a minor complication, but is easily fixed (see, e.g. http://stackoverflow.com/a/2819788/2043465).

All the heavy lifting is then done in the standard library, plus grants us lots of other features for free, e.g. iterating over all present sections.

**Comment by bendudson** [comment]
I looked into this, and it would be nice to use ConfigParser if possible. The two things I couldn't work out were:

1. The global sectionless variables, but it looks like there is a solution to that
2. The sub-sections with format [section:subsection]

I just adapted the C++ code, so the python code parses the file in the same as in BOUT++.

**Comment by ZedThree** [comment]
I think the subsections could be implemented with a bit of extra parsing. I think we'd end up probably subclassing `ConfigParser`.

A full parser for input files would be nice. It looks like @loeiten's `bout_runner` stuff does some of this. Maybe splitting it out would be a good idea.

This is pretty low priority for now though, I think.

**Comment by loeiten** [comment]
Sounds neat.
@ZedThree: The `bout_runners` does not have any parser, but is sometimes using @nick-walkden's `BOUTOptions`.
