### ISSUE TITLE
Cannot make install on ubuntu 16.04

### ISSUE THREAD

**Issue by Jeppembo** [boutproject/BOUT-dev#308]
Following the manual and using:
./configure && make && make install
I get an error:
Installing header files into /usr/local/include
cp: cannot create regular file '/usr/local/include/boundary_factory.hxx': Permission denied
cp: cannot create regular file '/usr/local/include/boundary_op.hxx': Permission denied

But I don't understand why it wants to install headers in /usr/local

**Comment by ZedThree** [comment]
Hi @Jeppembo, typically there's no need to do `make install`.

**Comment by Jeppembo** [comment]
I have also tried to not do make install, but then I get an error when I try to run ./test_suite_make in examples, where i get an error with undefined references to std::__cxx11:

/home/jmbols/BOUT-dev/examples/test-io/../../include/boutmain.hxx:115: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
test_io.o: In function `void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag)':
/usr/include/c++/5/bits/basic_string.tcc:223: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
../../lib/libbout++.a(datafile.o): In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':

**Comment by ZedThree** [comment]
I think I need a bit more information. Which branch are you trying to make?
Could you also give me the output of `g++ --version` and `ldd --version` on your system, please?

**Comment by Jeppembo** [comment]
I am trying to make the test_suite in the master branch.

g++ (Ubuntu 4.8.5-4ubuntu2) 4.8.5

ldd (Ubuntu GLIBC 2.23-0ubuntu3) 2.23

I downgraded GCC from 5.4 to 4.8, since it appeared that the issue may have been due to changes in GCC version 5. This gave me quite a lot fewer error messages, but I still get:

/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libnetcdf_c++.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'

**Comment by dschwoerer** [comment]
undefined reference to c++ stdlib?
are you using gcc instead of g++?

**Comment by Jeppembo** [comment]
No, as far as I can see it finds g++ in the config.log, and is using it when compiling.
It appeared to be a problem with g++ version 5.4. When I downgraded it to version 4.8, a lot of the undefined references went away. Only those in libnetcdf_c++.so remained.

**Comment by Jeppembo** [comment]
Solved the issue.
Downgrading GCC from 5.4 to 4.8 solved most of it. The last bit was solved by reinstalling anaconda, which was giving me trouble with mpich2.
Thank you very much for your time looking at this.
