### ISSUE TITLE
Rewrite index derivs code

### ISSUE THREAD

**Issue by bendudson** [boutproject/BOUT-dev#312]
The code to calculate derivatives in index space is inefficient, and has become increasingly tangled and incomprehensible over the years. 

In master:
 https://github.com/boutproject/BOUT-dev/blob/master/src/sys/derivs.cxx

In next:
 https://github.com/boutproject/BOUT-dev/blob/next/src/mesh/index_derivs.cxx

This uses a set of lookup tables to find the correct function to use, given combinations of field type (2D/3D), staggered variable locations, and choice of method in the input file. The way this is written prevents efficient code generation since it uses function pointers inside inner loops.

A replacement must be able to handle the combinatorial problem: differential operators are needed for:
- Each direction (X,Y,Z)
- Each type of field (Field2D, Field3D) and combinations for operations like VDDX which combine two fields
- Staggered and non-staggered fields
- A variety of methods, ideally able to be chosen in an input file or hard wired.

**Comment by bendudson** [comment]
A start at a replacement is in branch next-derivs

https://github.com/boutproject/BOUT-dev/tree/next-derivs

with code in src/difops

https://github.com/boutproject/BOUT-dev/tree/next-derivs/src/difops

Test case here:

https://github.com/boutproject/BOUT-dev/blob/next-derivs/examples/test-difops/test_difops.cxx

shows a good speedup 

Old VDDX(Field3D, Field3D) : 43 microseconds
New VDDX(Field3D, Field3D) : 16 microseconds

**Comment by dschwoerer** [comment]
I have been working on a new mesh, and these are my timings:
```
*****************************
AIOLOS-Mesh

real    0m9.558s
user    0m9.504s
sys     0m0.053s
*****************************
BOUT-Mesh

real    1m9.448s
user    1m9.387s
sys     0m0.054s
```
It still needs some testing ...

It will however not support FCI ...

**Comment by d7919** [comment]
I think #1384 should help address this (just two years and 1000 entries later).
