### ISSUE TITLE
Obsolete communicator in reference.pdf

### ISSUE THREAD

**Issue by loeiten** [boutproject/BOUT-dev#32]
The Communicator as described under 3.5 Communicator in the reference.pdf manual is obsolete.

**Comment by bendudson** [comment]
I'm not sure if having separate manuals for users and developers really makes sense, since almost all users are developers. It would probably be better to merge the bits of the reference manual which are up to date (which 3.5 is not) into the user manual.

**Comment by bendudson** [comment]
Reference manual deleted in commit 2b3587ce7b51
