### ISSUE TITLE
^ exponentation operator in Field3d not working

### ISSUE THREAD

**Issue by JensMadsen** [boutproject/BOUT-dev#33]
for

Field3D n; 

I get an error when: 

ddt(n) = n*n^(2.) 

but no bug when 

ddt(n) = n*(n^(2.))

**Comment by bendudson** [comment]
The "^" operator isn't really a good choice for exponentiation, as it has low precedence. 
  n*n^(2.)   =  (n*n) ^ 2

Suggest removing "^" operators, as only causing problems, and replacing with pow() functions.

**Comment by JensMadsen** [comment]
I agree. ^operator should be replced by pow functions. As far as I understand precedence of operatrs cannot be changed. 

I get an error something like operation on infinite data as far as I remember

**Comment by dschwoerer** [comment]
Should be fixed in next, as it is has been replaced with pow.
