### ISSUE TITLE
Why throw exception when both gij and g_ij are given?

### ISSUE THREAD

**Issue by JensMadsen** [boutproject/BOUT-dev#338]
I calculate the metric tensor using lambdified sympy expressions. I have symbolic expressions for gij and g_ij and is therefore able to calculate both tensor with high precision. 

When I provide e.g gij and let BOUT++ calculate the inverse g_ij i get much higher errors than if I calculate it using lambdified sympy expressions. 

My problem is that if I provide gij and g_ij BOUT boutmesh throws an exception line 565. I suggest to remove this exception and perhaps testing $$g^{ij} \* g_{ij} - I < \epsilon$$ instead?

If you agree I of course do the fix :-D

**Comment by bendudson** [comment]
Agreed, this sounds like a better solution. I think the intention was to avoid confusion, and potential inconsistencies, but the checks would take care of that. Thanks!

**Comment by bendudson** [comment]
I think this issue is now fixed, since both metric tensors are read if present:

https://github.com/boutproject/BOUT-dev/blob/master/src/mesh/coordinates.cxx#L93
