### ISSUE TITLE
Monitors rewrite

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#346]
There are currently two open PRs (#321 and #343) and two issues (#56 and #329) regarding the monitors. I think both PRs are useful features, and I definitely want them in BOUT++, but I can see that we might need to rewrite the monitors somewhat in order to get multiple monitors working correctly. I propose that some nature of monitor rewrite be a feature for 4.1, and we hold off on including the two PRs until then.

**Comment by bendudson** [comment]
This is now resolved: PRs #321 and #343 have been merged, whilst the issues have been fixed by #364
