### ISSUE TITLE
non-recognized command line option should raise a message or halt the program 

### ISSUE THREAD

**Issue by JensMadsen** [boutproject/BOUT-dev#35]
When running a program called "diffusion": 

./diffusion -ben=44

The program has no option named ben. A suggestion is to warn the user that he/she has used a commandline option not recognized by the program. Especially if one has misspelled an option it would be nice with a warning.

**Comment by ZedThree** [comment]
This is solved in my help message branch. Might need some tidying up before
merging now.

**Comment by JensMadsen** [comment]
Ok. Should I keep the issue (you will then delete it when merged) or should I remove it ?

Jens Madsen
PPFE, DTU Physics
Denmark
________________________________

**Comment by ZedThree** [comment]
Keep it, I'll merge it and close the issue

**Comment by ZedThree** [comment]
I think this might be a "won't fix". My branch only solves a subset of this problem - the "-d" and "-f" flags, which are not handled by the options parser, and adds a "-h/--help" flag. All the other command line options are added to a list and (possibly) consumed later, so it's not possible to know beforehand what options exist.

One workaround might be the following:
There is an [`Options::printUnused()`](https://github.com/boutproject/BOUT-dev/blob/cbe528207ba3230321b9482e7516f4d492cd460e/src/sys/options.cxx#L197) method which could be called (maybe in the `BOUTMAIN` macro?) and if any options are unused, pause the simulation for ~15-30 seconds with a message to the effect of "Warning, following options unrecognised. Hit Ctrl-C to abort run".

**Comment by ZedThree** [comment]
Won't fix -- doesn't seem possible to do, short of requiring all possible options to be registered at load time. Even then, we'll still have the problem of e.g. mutually exclusive options.
