### ISSUE TITLE
Enable -DCHECK to get trace doesn't work

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#353]
Setting the DCHECK flag doesn't enable the trace, therefore CHECK neeeds to be larger than 1.

However backtrace tries to use it ...

Should backtrace be changed, and message say check needs to be at least 2, or should we enable the backtrace with check (and not as now, with check=2)?

**Comment by ZedThree** [comment]
I'm afraid I don't quite follow. Are you setting `-DCHECK` on the command line, rather than with a configure flag? Are you saying that *should* enable the backtrace but doesn't? Or it should enable the TRACE messages but doesn't?

**Comment by dschwoerer** [comment]
Yes, as that way I don't have to remember all options I used to run configure (and also that is what the message says).

I see, my message was a bit confusing, sorry.

I tried to fix it in PR #368 ...
I was not sure whether the BoutException or the msg_stack should be changed ...

**Comment by ZedThree** [comment]
Fixed in #368
