### ISSUE TITLE
getName/setName only available for -DTRACK

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#362]
The `getName` and `setName` functions defined in `field.hxx` are only defined when we have defined `TRACK`. This means we would have to guard any reference to these functions inside `#ifdef TRACK` blocks. Ideally we would have these available no matter what we do with `TRACK`, with null functions when we haven't asked for tracking (or specialised defaults on the different children).

**Comment by ZedThree** [comment]
Closed by #599
