### ISSUE TITLE
PVODE fails to build in next

### ISSUE THREAD

**Issue by bshanahan** [boutproject/BOUT-dev#369]
Trying to configure in next for the first time causes a failure when building PVODE.  See attached config-build.log (which was converted to txt so github could attach it).  

[config-build.log.txt](https://github.com/boutproject/BOUT-dev/files/591681/config-build.log.txt)

**Comment by ZedThree** [comment]
What compiler are you using? It looks like you might be using an incompatible version of GCC with Intel, maybe GCC 4.9 with Intel 14?

If so, try switching to GCC 4.8 or Intel 15+.

**Comment by d7919** [comment]
This looks like similar issues I've had on helios using the intel compiler. The intel compiler uses some of the gnu headers etc. I think you need to make sure you're working with compatible versions but I'm not sure

**Comment by bshanahan** [comment]
Will try to do this (not sure how -- still learning the system here) -- just interesting that I can build with master, but not in next.

**Comment by d7919** [comment]
I'd guess it's the c++ 11 features that we enable/use in next but not master.

**Comment by bshanahan** [comment]
Worked when switching to Intel 16, and it looks like it was probably the c++ 11 features, as David and Peter rightly suggested.
