### ISSUE TITLE
Metric tensor components (g_13) in b0xGrad_dot_Grad

### ISSUE THREAD

**Issue by bshanahan** [boutproject/BOUT-dev#377]
Is it a typo that g_13 is never used when calculating b0xGrad_dot_Grad?

For instance in:
const Field3D b0xGrad_dot_Grad(const Field2D &phi, const Field3D &A), 

should   
vy = metric->g_23*dpdx; 

actually be   
vy = metric->g_13*dpdx; ?

**Comment by AlxMar** [comment]
As far as I understand, vector b0 has components (g21, g22, g23);
vy is the y component of a vector product b0 x Grad(phi), where Grad(phi) = (dpdx, dpdy, 0), and it is giving exactly mesh->g_23*dpdx.
