### ISSUE TITLE
Version for BOUT++ 4.0

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#383]
Is the 4.0 release named 4.0, or 4.0.0?
Git branch indicates the later of the two, but I don't think we will have releases that often ...

**Comment by ZedThree** [comment]
The plan is be a bit more regular with releases. 4.0 has been a long time coming! I'm hoping we'll be able to follow semantic versioning fairly well, so 4.0.1 will be just have bug fixes, 4.1.0 will have non-breaking changes, and 5.0.0 will have breaking, backwards incompatible changes.

**Comment by dschwoerer** [comment]
Thanks 👍
