### ISSUE TITLE
BoutInitialise failure

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#39]
Since update b3bf0d8fc38984175389526dde3dacf589083589 (" Make BoutInitialise return an int and cause BOUT++ to exit if non-zero//Fixes segfault for some command line options"), BOUT++ fails to run for me. It crashes silently, apparently during BoutInitialise; e.g. running test_io the console output ends with
```
WARNING: Magnitude of B field 'Bxy' not found. Calculating from metric tensor
Calculating differential geometry terms
	Communicating connection terms
Boundary regions in this processor: core, sol, 
	done
jto22@john-laptop ~/Code/BOUT-dev/examples/test-io $ 
```
Attempting to debug with gdb: setting a breakpoint at BoutInitialise the execution does not stop at all. Breaking at main and trying to step into BoutInitialise results in a SegFault.

Failure occurs with a clean install of BOUT++, no extra options to configure (and also occurs when setting --with-debug only). Tested on my (Linux Mint) laptop. Also fails in apparently identical fashion on CCFE linux server.

Does a clean install work/fail for anyone else?

**Comment by johnomotani** [comment]
Update: I think this problem is caused by a missing return statement in BoutInitialise. It should now return an int, but if it encounters no error, there is no return statement. Adding 'return 0' at the end seems to fix the problem. Behaviour on reaching the end of a function without encountering a return statement (where a return value is required) is apparently undefined, so I guess this may be dependent on compiler, etc.?

The gdb weirdness seems to happen only on my laptop, so is probably an unrelated issue.

**Comment by ZedThree** [comment]
Ah, that's embarrassing. I forgot to commit that part and didn't check it worked in a clean install. test-griddata doesn't work for me now. Investigating...

**Comment by ZedThree** [comment]
Further embarrassment. When checking out a clean copy, remember to change your $PYTHONPATH. All tests passed in clean install.
