### ISSUE TITLE
Fix tools to have the correct number of z points in version 4

### ISSUE THREAD

**Issue by loeiten** [boutproject/BOUT-dev#394]
I stumbled upon one of the bugs in `restart.py`, but I guess the problem are occurring elsewhere as well.

**Comment by ZedThree** [comment]
I think this is mostly fixed in #440, but that leaves all the other interfaces broken (IDL, Mathematica, Matlab, Octave). I don't think any of them are used nearly as much as the python routines, so I'm not too worried. A nice easy task for someone who knows those languages though!

**Comment by bendudson** [comment]
Agreed, I think this would be nice but is not essential. IDL is probably the next-most used, and should be fixed at some point... more urgent things to do though

**Comment by dschwoerer** [comment]
Would it make sense to break them in an obvious way, so people know they need to be fixed, and don't silently get wrong results?

**Comment by ZedThree** [comment]
That's a good idea, but it might be just as much effort to fix them properly.

Also, I think only idllib has this functionality anyway.

**Comment by bendudson** [comment]
Yes, agreed. The collect routines for IDL, matlab, mathematica could just throw an error saying "This is broken, fix before using"

**Comment by d7919** [comment]
Is this going to make v4.2 or will it be pushed back?

**Comment by ZedThree** [comment]
#1312 should at least bring people to here, where they will hopefully read this nice message asking them to please fix it for us? :)

I'm removing the milestone for now, but leaving the issue open. I don't think these tools are used much, else we would've had more complaints!

**Comment by ZedThree** [comment]
Non-python tools are now unsupported. Let's remove them entirely or shift them to other repos with big "Here be dragons" messages

**Comment by bendudson** [comment]
Agreed, the IDL, matlab, octave tools should be separate repos

**Comment by bshanahan** [comment]
My only objection would be the case for tokamak grid generation.

Is the python version of hypnotoad fully functioning?

**Comment by bendudson** [comment]
Sadly no, the python replacement is not a full replacement. Hypnotoad could be a separate repo though.
