### ISSUE TITLE
Merge Policy

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#395]
Right now there seems to be no policy on what gets merged, and what not.
I personally think it is annoying if I don't get any feedback what so ever, and my pull request are just rotting there.

If you think my pull requests are shit, than please tell and close them, or tell me what I can improve.

Some of them fix serious issues, some not so serious ones.

#272 is only a tiny change, and I think it should have been merged ages ago.
#186 no objections, not merged for over 2 months
#87 not even feedback - sitting for over a year. I don't think the author will make another pull request ...

I don't think they all should be merged right now (although that would make me happy) but I think we should have a policy what gets merged, when, who is responsible and so on.

**Comment by bendudson** [comment]
Sorry David. All your hard work and improvements are really appreciated, but it's hard to find the time to do all this in between other things. Peter is working on formalising the policy on things like merges, hopefully to be announced and put on the website soon. Now that the Great Merge is done, we can go through all these pull requests and decide which to merge in now, and which have to wait for a little.

**Comment by dschwoerer** [comment]
I perfectly understand that reviewing isn't the most exciting part - and that everybody is busy.

This is not so much that I feel ignored, it is more that even from a purely economic point of view, if there are unmerged pull requests, others may depend on it. Without them, others try to fix / work around stuff that is fixed. Otherwise they could work on other issues.
One example: @ZedThree set up https://github.com/boutproject/BOUT-dev/projects/2
In my opinion this is a waste of time, as the monitors are rewritten.
What is left to do is writing tests / documentation ...

FunFact: Around 55 PRs were merged by the person who opened them, while around 111 where opened and merged by different people ...

**Comment by bendudson** [comment]
Major changes to the code were put on hold for a short while, until next and master were merged. Now that things have settled down a bit, we can start to think about the next major changes, such as monitors. 

You have implemented a new monitor system, which looks good, and may be the version we adopt. It's a fairly important bit of functionality though, so we should try to get it right or we'll end up rewriting it again. Personally I haven't had time to try it out and really think about whether it satisfies all use cases, and others should also comment on any changes they'd like to see in the interface or implementation. 

The plan is to focus on documenting and fixing things which are actually broken until January, then the first new feature will be deciding on this monitor system.

**Comment by dschwoerer** [comment]
* All the PRs I mentioned where available before the final call for v4.0 ended
* The code may not be the best. In case of the monitors, it is designed to not break any thing, by hiding that there are several output frequencies from the monitors. Further if the frequency isn't set, nothing changes.
* If nobody had 5 minutes to respond to #87 in the last 18 months, I am really sorry for all of you ...
