### ISSUE TITLE
Field3D Operation in shifted metrics

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#396]
It seems that if `a*b` where `a` and `b` are at different grids (e.g. CELL_CENTRE and CELL_YLOW), this is currently ignored, and the results location is set to `a`'s location.

I would have assumed that it interpolates to one location.
I guess it may be best to throw an error if this happens, as the user is the one who should make sure both fields are at the same location ...
This would cause currently probably issues with Field2d, as they are not shiftable, and therefore e.g. in the metrics area (after calculating the derivative, multiplying with dy etc)

**Comment by bendudson** [comment]
Agree that this should throw an exception rather than silently interpolating

-------- Original Message --------

**Comment by dschwoerer** [comment]
This is fixed by #458 ...
