### ISSUE TITLE
BoutMesh ignores non-available differentiation-options

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#419]
* If I manage so set the derivative scheme to something non-available, this is (nearly silently) ignored:
```
Setting X differencing methods
	First       :  No match for 'awesomescheeme' ->  Second order central (C2)
```
* Expected outcome:
Exit with error, as the code cannot do what is expected.
The aiolos mesh prints in such a case the possible options and throws an exception.

**Comment by dschwoerer** [comment]
This breaks existing code - so maybe a feature for 5.0?

**Comment by bendudson** [comment]
I would be in favour of fixing this earlier, since silently ignoring an input is probably a bug
