### ISSUE TITLE
Boundary conditions documentation

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#42]
The new `dirichlet_o2`, `neumann_o2`, etc. boundary conditions are not documented in the user manual. The manual should probably be updated to recommend them as the defaults and warn against using `dirichlet` and `neumann` together, since that degrades convergence to 1st order.

**Comment by JensMadsen** [comment]
Perhaps consider that dirichlet_o2 should raise a warning if symmetricglobalx and symmetricglobaly are not set.


Jens Madsen
PPFE, DTU Physics
Denmark
________________________________

**Comment by ZedThree** [comment]
The `*_o2` routines are now the default
