### ISSUE TITLE
laplacexz should exit when g13 \neq 0

### ISSUE THREAD

**Issue by JensMadsen** [boutproject/BOUT-dev#425]
lalplacexz assumes that gxz = g13 = 0. Therefore, if g13 \neq 0 the code should exit. Perhaps we could allow the user to set a flag which specifically allowed using laplacexz with gxz \neq 0 ?

**Comment by d7919** [comment]
I think this is the sort of check that would be very useful to have and I'd be keen to have the ability to check consistency of assumptions and operators as widely as possible. To avoid introducing a large number of specialist flags we could consider introducing a new configure flag that switches between "rigorous" and "production" modes -- this way people can compile with rigorous and check that their model and setup is consistent and then if they need performance etc. they can switch to "production". Obviously this has quite a bit of overlap with `--with-checks` etc.  but those tend to be checks of the numerics whilst here we're talking about the assumptions/physics.

**Comment by JensMadsen** [comment]
I agree. Lets NOT put a flag unless someone really needs it

**Comment by bendudson** [comment]
Perhaps a flag in the options like check_g13 which defaults to true. A user could explicitly disable the check if they wanted to. 

Alternatively, someone could add the g13 tends to LaplaceXZ 

-------- Original Message --------

**Comment by bendudson** [comment]
Now fixed by #513
