### ISSUE TITLE
paralleltransform and shiftOutput should be saved in output files by default

### ISSUE THREAD

**Issue by JensMadsen** [boutproject/BOUT-dev#426]
This information is important for interpreting output files (was e.g. the shifted metric procedure used)

Implementation of this requires capability to write string to net-cdf files (see #222   )

**Comment by ZedThree** [comment]
Do we actually do this now? I guess it can in principle be done very easily with a file-level attribute or by dumping the `Options` to NetCDF. The `BOUT.settings` file should also contain this info.

@johnomotani or @dschwoerer Can we close this?

**Comment by johnomotani** [comment]
The `Field` attributes save whether a variable was field-aligned or x-z orthogonal now. It looks like we don't save `zShift`. Probably we want to even though it's in the grid file, to keep the output together and in case the physics model modifies zShift or something weird like that. We've got `Mesh::outputVars` and `Coordinates::outputVars` already, it probably makes sense to add `ParallelTransform::outputVars` to save `zShift` from `ShiftedMetric`. `FCI` could output some stuff too, if it wants to? I'll check we really don't output `zShift` yet, and then make a PR to add it...
