### ISSUE TITLE
Free boundaries

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#429]
If a variable uses the `BoundaryFree` boundary operator for a region, then all variables use free boundaries for that region. The `BoundaryFree::apply` methods are noops, and the work is instead done in `Mesh::apply{X,Y,Z}diff`.

This seems a little surprising and in contrast to the `BoundayFree_O{2,3}` operators which instead set the guard cells via extrapolation.

Does anybody use `BoundaryFree` in practice? Can it be deprecated and removed in 5.0? This would simplify `Mesh::apply{X,Y,Z}diff`.

**Comment by bendudson** [comment]
These have now been removed in 4.1
