### ISSUE TITLE
`applyBoundary` on Fields with background set

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#430]
If a `Field3D` has `background` set, then the boundary conditions may not be applied correctly, e.g. [here][1]:
```c++
  if(background != NULL) {
    // Apply boundary to the total of this and background
    
    Field3D tot = *this + (*background);
    tot.applyBoundary(init);
    *this = tot - (*background);
  } else {
```

`tot.bndry_op` is empty, so no boundaries get applied. I think this is only important for `applyBoundary(bool init)` and `applyBoundary(BoutReal t)`. The solution is just to add `tot.copyBoundary(*this)`.

[1]: https://github.com/boutproject/BOUT-dev/blob/v4.0.0-RC/src/field/field3d.cxx#L782

**Comment by ZedThree** [comment]
Is setting a field background essentially deprecated now? Out of the examples, only the uedge-benchmark actually uses it. I have no idea if it's used out in the wild.

Could it be deprecated entirely and removed in 5.0?

**Comment by bendudson** [comment]
Yes, this sounds like a good idea. The background field just complicates
things, and there is probably a better way to achieve the same thing.
Before removing entirely it would be good to find that Better Thing..

**Comment by ZedThree** [comment]
We deprecated `setBackground` and removed it entirely in #1326. We don't have a replacement yet -- do we need one?

If not, we can remove a bunch of code that uses `background`, if so, we should put it on the roadmap!
