### ISSUE TITLE
RangeIterator created by mesh->iterateBndryLowerY() return wrong indices when nxpe!=0

### ISSUE THREAD

**Issue by JensMadsen** [boutproject/BOUT-dev#435]
This was found in the v4.0.0-RC branch. 

On a mesh with e.g. nx = 66 with the y-boundary starting at x index 33 :
```
		RangeIterator x_RI = mesh->iterateBndryLowerY();
		output << x_RI.ind <<endl;
```
the output is 33 when NXPE = 1. When NXPE = 2 I get 1059368544

I think this is a bug?

**Comment by ZedThree** [comment]
Any chance you could create an [MVCE][1]?

[1]: http://stackoverflow.com/help/mcve

**Comment by dschwoerer** [comment]
I cannot reproduce this.

It seems to me that there is no boundary to iterate over, could you show what `x_RI.isDone()` is?

I could only reproduce this, by setting `NYPE=2`.
Do you keep the number of processes constant. or does `NYPE` also change from 1 to 2?

**Comment by dschwoerer** [comment]
@JensMadsen please re open if you can reproduce this.
