### ISSUE TITLE
Zoidberg issues

### ISSUE THREAD

**Issue by bshanahan** [boutproject/BOUT-dev#443]
Various issues with Zoidberg.  When trying to produce a stellarator of resolution (for instance) 128x16x128, a memory error occurs.  When creating grids with smaller OR larger resolutions, no memory error occurs.  

Additionally, a generated grids sometimes have empty values for random mapped quantities (i.e. forward_xt_prime). This happens irregularly, not solely on boundaries.  This happens with straight field lines, where no interpolation should be needed.

**Comment by bshanahan** [comment]
The second issue has been (kind-of) resolved; lambdify returns an integer 0 if there is no function, and odeint does not like this, so you get holes.  If one wants a straight-field-line system, use the Slab geometry with Bp and Bpprime = 0, since this defines Bxfunc as np.zeros(nx,ny,nz).

Still no idea about the memory error.

**Comment by ZedThree** [comment]
What's the status of this? Did we get everything fixed?

**Comment by bshanahan** [comment]
I haven't gotten around to testing this with the new Zoidberg.  Will do soon-ish (not next week).

**Comment by d7919** [comment]
@bshanahan  any updates on this?

**Comment by bshanahan** [comment]
Fixed in the newest version of zoidberg, which handles each poloidal plane separately.
