### ISSUE TITLE
Increase verbosity of option reader

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#451]
The problem:
-------------
I have in my `BOUT.inp`
```
[blob]
dx                    = perp_size
dz                    = perp_size
dz_n                  = dz
```
So that I can set easily the filament size of my simulations with the command line, by running
```
./filaments blob:perp_size=0.005
```
Although this is very convenient, it is completely hidden in the logs that the perp_size was set on the command line:
```
        Option blob:dz = perp_size (size_05/data_rd_n_1p000_t_1p20/BOUT.inp)
        Option blob:dz_n = 0.005 (size_05/data_rd_n_1p000_t_1p20/BOUT.inp)
```
Why this is an issue
---------------
In order to reproduce it is beneficial to know how a simulation was run.

Possible solutions
-------------
* It would be nice if the complete stack, how an option was read is printed.
 Depending on how this is done, it may however lead to extremly verbose logs. So a compromis may be to only write out the root-option only once. The root option in this case would be `blob:perp_size`

* Another option would to dump additional information to e.g. `BOUT.cfg.nc` - including BOUT++ version, the version of the physics model (if applicable), the command line options and the content of `BOUT.inp`

**Comment by d7919** [comment]
Presumably we can dump the entire `argv`  passed into main? This way we would also capture the options passed through to `PETSc` etc.

**Comment by d7919** [comment]
I should note that I'm strongly in favour of including the input file (and other provenance information like version/hash etc.) as a part of the dump file(s).

**Comment by bendudson** [comment]
I think the origin of perp_size should also be printed. In addition to the line
    Option blob:dz = perp_size (size_05/data_rd_n_1p000_t_1p20/BOUT.inp)
there should also be a line
    Option blob:perp_size = 0.005 (Command line)
It might be printed earlier, as it's only printed once when perp_size is first resolved.

Another possibility would be to dump the Options tree to an output (BOUT.settings?) which could then be renamed to BOUT.inp to rerun the simulation

**Comment by bendudson** [comment]
I think this is now fixed in next: The whole stack is printed to the log file, and the settings used are written to BOUT.settings
