### ISSUE TITLE
ffmpeg_path specified in showdata.py

### ISSUE THREAD

**Issue by lukeeasy** [boutproject/BOUT-dev#47]
In showdata.py, the ffmpeg_path is specified explicitly: 

```
plt.rcParams['animation.ffmpeg_path'] = '/opt/local/bin/ffmpeg'
```
But the location of ffmpeg will not be the same on every user's machine.  So this can cause problems when trying to save a movie to file.  

I suggest removing this line completely, and that the user should set the ffmpeg_path in their python session before calling showdata if necessary.  Alternatively, an optional argument could be added to showdata to set the ffmpeg_path.

**Comment by bendudson** [comment]
Agree, this should be removed from showdata.py
