### ISSUE TITLE
Should mergeYupYdown check for ydown_field too?

### ISSUE THREAD

**Issue by bshanahan** [boutproject/BOUT-dev#474]
At the moment mergeYupYdown checks if yup_field==this and if it isnt, deletes both yup and ydown if yup_field!=nullptr.  Should this also check ydown_field?
[link to line](https://github.com/boutproject/BOUT-dev/blob/master/src/field/field3d.cxx#L182)

**Comment by bendudson** [comment]
Possibly... at the moment both fields are always created and deleted together, so if one exists then the other must do too. I suppose in future someone might add one and not the other, in which case shortcuts like this would cause strange things to happen.

**Comment by bshanahan** [comment]
Changed in PR [480](https://github.com/boutproject/BOUT-dev/pull/480), if desired.
