### ISSUE TITLE
getters for nx, ny and nz

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#498]
I am wondering whether theses getters should be part of the mesh, or of the field.

I guess there are used most of the time to loop over a field, or do something with a field.
Not sure where else they would be used, if not in combination with a field.

As we want to support multiple meshes, wouldn't be easier to directly ask the field?
The reason is, that otherwise I first need to ask the field for its mesh, and then query the mesh, in case it has one, otherwise query the global mesh.

**Comment by JensMadsen** [comment]
nx, ny, and nz are variables in boutmesh. so in some sense they belong to boutmesh and not field? If we one day allow different fields to have different meshes then nx, ny an nz still belong to a mesh? In the end I guess that the reason why we discuss where to put these getters is an outcome of that the division between mesh, coordinates and fields is a bit unclear and not very precise? 

In any case it would be a good idea to put the getters in field and not in field2d and in field3d which both inherit from field?

**Comment by dschwoerer** [comment]
but nx etc are also copied in the fields, e.g. [Field3D](https://github.com/boutproject/BOUT-dev/blob/next/include/field3d.hxx#L493)

Yes, they should go into field 👍

**Comment by dschwoerer** [comment]
fixed
