### ISSUE TITLE
Parallel transforms are not documented

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#503]
The parallel transforms are not documented, and the ["Updating Physics Models from v3 to v4"](http://bout-dev.readthedocs.io/en/latest/user_docs/updating_to_4.html) section should probably mention `shiftXDerivs` has been replaced.

**Comment by JensMadsen** [comment]
I uploaded a draft to slack at some point

Sendt fra min Sony Xperia™-smartphone

---- Peter Hill skrev ----


The parallel transforms are not documented, and the "Updating Physics Models from v3 to v4"<http://bout-dev.readthedocs.io/en/latest/user_docs/updating_to_4.html> section should probably mention shiftXDerivs has been replaced.

**Comment by ZedThree** [comment]
Fixed in #525

**Comment by JensMadsen** [comment]
Hi Peter. 

There is still no explanation of what the shifted metric is etc. If you like feel free to put my notes in the docs. I can send you the latex file if necessary. Cheeeeers

**Comment by ZedThree** [comment]
Hi Jens, that would be great, thanks! I couldn't find them on slack, please could you email them to me?
