### ISSUE TITLE
release notes

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#504]
I think somebody had a summary of the changes between 3.0 to 4.0.0 - I think it would be handy to have this in the repository, and hopefully keep it up to date during development.

**Comment by ZedThree** [comment]
I did have a changelog. From looking at other projects, by having a strict format for merge commit messages, we can build the changelog automagically. I will investigate.

**Comment by ZedThree** [comment]
Fixed in b392e0
