### ISSUE TITLE
Intel compiler and C++11

### ISSUE THREAD

**Issue by bendudson** [boutproject/BOUT-dev#509]
The Intel compiler, even quite recent versions (16.0.1 20151021) does not set the __cplusplus macro to 201103L, so fails in configure when the macro on line of 144 configure.ac

    AX_CXX_COMPILE_STDCXX([11], [noext], [mandatory])

tries to compile a code with the lines

    #elif __cplusplus < 201103L
    #error "This is not a C++11 compiler"

See this (old) thread:
https://software.intel.com/en-us/forums/intel-c-compiler/topic/286974

Not sure what the solution is: We could check for the features we need, fix the macro, or make the check non-mandatory so when it fails configure keeps going.

**Comment by ZedThree** [comment]
Easiest fix is to just remove those lines from the macro, as it does go on to test a bunch of C++11 features. Maybe emit a warning instead?

**Comment by JosephThomasParker** [comment]
I find something similar on current `next` - except the Intel compilers are recognized as C++ compilers, but are not found to have C++11 features.  Again, these are recent versions - I've tested 16.0.1 and 17.0.2.

**Comment by bendudson** [comment]
Do they not admit to supporting C++11, but actually support many features? i.e. is it just failing because __cplusplus < 201103L ?

**Comment by JosephThomasParker** [comment]
Oops - according to [footnote 1 here](https://software.intel.com/en-us/articles/c0x-features-supported-by-intel-c-compiler), my gcc environment was too old.  But using newer environments, I find Intel 15.0.3, 16.0.1 and 17.0.2 all configure fine.

**Comment by ZedThree** [comment]
This is entirely down to the gcc environment. We should put something in the documentation.
