### ISSUE TITLE
Laplacian Flags invert_set, invert_rhs implementation

### ISSUE THREAD

**Issue by lukeeasy** [boutproject/BOUT-dev#52]
Currently, the laplace flags invert_set, invert_rhs set the guard points of the result equal to the values given in the guard cells of the field, or in the guard cells of the RHS field respectively.  

One use for these is to set a Dirichlet boundary condition that varies in y.  But the problem is that if these functions are being used to set Dirichlet BCs, their implementation is inconsistent with the definition of the boundary being half way between the first guard point and first domain point.  

It depends on how these flags are interpreted.  Should they be interpreted as a Dirichlet BC or should they be interpreted as setting the guard cells to the values given (current behaviour)?

It's a relatively easy change to make them consistent with being a Dirichlet BC, but it will require also ensuring the test case data also reflects these changes.  (Otherwise the test suite fails)

**Comment by johnomotani** [comment]
With the current definitions of boundary conditions half-way between grid points, there is no situation is which it makes sense to just set the value of the guard cells (i.e. it will not converge at higher than 1st order). On the other hand, it would be useful to be able to set Dirichlet boundary conditions to a non-zero value (and one could allow setting Neumann to a non-zero value as well).

In summary, I strongly support the proposed change.

**Comment by bendudson** [comment]
I think I agree. The most common use that I have for this is setting
potential equal to 3*Te on the boundary. In that case it should be a
midpoint like everything else. Change on condition that whoever makes the
change also documents it in the manual :)
