### ISSUE TITLE
Cannot compile next with PETSc 3.7

### ISSUE THREAD

**Issue by bshanahan** [boutproject/BOUT-dev#534]
After successfully running ./configure --with-petsc, with the most recent version of PETSc 3.7, I get:

`  

> Compiling  petsc_laplace.cxx
> In file included from petsc_laplace.hxx:59:0,
>                  from petsc_laplace.cxx:28:
> ../../../../../include/bout/petsclib.hxx:51:0: warning: "PETSC_DEPRECATED" redefined
>  #define PETSC_DEPRECATED(a)
>  ^
> In file included from /home/brendan/petsc/include/petscsys.h:14:0,
>                  from /home/brendan/petsc/include/petscis.h:7,
>                  from /home/brendan/petsc/include/petscvec.h:9,
>                  from /home/brendan/petsc/include/petscmat.h:6,
>                  from /home/brendan/petsc/include/petscpc.h:6,
>                  from /home/brendan/petsc/include/petscksp.h:6,
>                  from petsc_laplace.hxx:56,
>                  from petsc_laplace.cxx:28:
> /home/brendan/petsc/arch-linux2-c-debug/include/petscconf.h:29:0: note: this is the location of the previous definition
>  #define PETSC_DEPRECATED(why) __attribute((deprecated))
>  ^
> petsc_laplace.cxx: In constructor ‘LaplacePetsc::LaplacePetsc(Options*)’:
> petsc_laplace.cxx:95:25: warning: ‘MPI_Comm Mesh::getXcomm()’ is deprecated [-Wdeprecated-declarations]
>    comm = mesh->getXcomm();
>                          ^
> In file included from ../../../../../include/globals.hxx:30:0,
>                  from petsc_laplace.hxx:54,
>                  from petsc_laplace.cxx:28:
> ../../../../../include/bout/mesh.hxx:303:23: note: declared here
>    DEPRECATED(MPI_Comm getXcomm()) {return getXcomm(0);} ///< Return communicator containing all processo
>                        ^
> ../../../../../include/bout/deprecated.hxx:20:26: note: in definition of macro ‘DEPRECATED’
>  #define DEPRECATED(func) func __attribute__ ((deprecated))
>                           ^
> petsc_laplace.cxx:281:59: error: ‘KSPNASH’ was not declared in this scope
>    else if(type == "nash")                       ksptype = KSPNASH;
>                                                            ^
> petsc_laplace.cxx:282:59: error: ‘KSPSTCG’ was not declared in this scope
>    else if(type == "stcg")                       ksptype = KSPSTCG;
>                                                            ^
> petsc_laplace.cxx:283:59: error: ‘KSPGLTR’ was not declared in this scope
>    else if(type == "gltr")                       ksptype = KSPGLTR;
>                                                            ^
> ../../../../../make.config:219: recipe for target 'petsc_laplace.o' failed
> make[5]: *** [petsc_laplace.o] Error 1
> ../../../../make.config:99: recipe for target 'petsc' failed
> make[4]: *** [petsc] Error 2
> ../../../make.config:99: recipe for target 'impls' failed
> make[3]: *** [impls] Error 2
> ../../make.config:99: recipe for target 'laplace' failed
> make[2]: *** [laplace] Error 2
> ../make.config:99: recipe for target 'invert' failed
> make[1]: *** [invert] Error 2
> make.config:99: recipe for target 'src' failed
> make: *** [src] Error 2

`

Ideas?

**Comment by bendudson** [comment]
Strange... KSPNASH, KSPSTCG and KSPGLTR should all be defined in petscksp.h:
http://www.mcs.anl.gov/petsc/petsc-current/include/petscksp.h.html#KSPType

One option would be to delete the code from here:
https://github.com/boutproject/BOUT-dev/blob/master/src/invert/laplace/impls/petsc/petsc_laplace.cxx#L281
to
https://github.com/boutproject/BOUT-dev/blob/master/src/invert/laplace/impls/petsc/petsc_laplace.cxx#L283

It would be nice to just write

ksptype = type;

(might have to be ksptype = type.c_str(); )

since that is basically all that chunk of code is doing.

**Comment by d7919** [comment]
Can you verify that /home/brendan/petsc/include/petscksp.h contains these definitions?

This file has an include guard, I can't believe this is an issue but is it possible that this is preventing us from seeing these defs a second time? It might be worth trying to add  `#undef __PETSCKSP_H` before including this file (again I don't imagine this is correct/possible).

**Comment by ZedThree** [comment]
Also, check your `$PETSC_DIR` and `$PETSC_ARCH` again, the directories look a bit inconsistent.

**Comment by bshanahan** [comment]
@d7919 /home/brendan/petsc/include/petscksp.h does not contain these definitions.  it does, however, contain KSPCGNASH, KSPCGSTCG, and KSPCGGLTR. (there is an extra "CG" in there)

@ZedThree PETSC_DIR and PETSC_ARCH seem okay, as the configuration seems to work fine.

**Comment by bendudson** [comment]
Ah, bleeding edge PETSc has renamed those KSP types...

https://github.com/petsc/petsc/blob/master/include/petscksp.h

**Comment by d7919** [comment]
**https://bitbucket.org/petsc/petsc/pull-requests/544/tmunson-kspcg-fix-trust-region-functions/diff**

**Comment by d7919** [comment]
Ah yes, can be dangerous to stray from the official releases

**Comment by bshanahan** [comment]
Ah, okay.  I was using an old version of the manual which suggested using
the developer version for best features.

Will now install an older version (3.4.5?)

**Comment by d7919** [comment]
I'm not aware of any issues using the most current releases, at least 3.6 should be supported I think although I seem to recall Ben was doing something with 3.7.

**Comment by bendudson** [comment]
3.6 definitely should work, and 3.7 should work in the next branch
