### ISSUE TITLE
nype is not written to log

### ISSUE THREAD

**Issue by JensMadsen** [boutproject/BOUT-dev#539]

**Comment by bendudson** [comment]
This is output, but agreed not in a particularly clear way:

Domain split (1, 18) into domains (256, 4)

This is (NXPE, NYPE), then (MXSUB, MYSUB)

**Comment by JensMadsen** [comment]
Ah yes. Sorry. But NXPE it written explicitly

**Comment by bendudson** [comment]
Now fixed
