### ISSUE TITLE
FieldGroup adding const fields

### ISSUE THREAD

**Issue by bendudson** [boutproject/BOUT-dev#540]
Passing const fields to FieldGroup constructor results in segfault. 

    Field3D a(0.0);
    FieldGroup g(a);  // ok
    FieldGroup h(2*a); // compiles, but segfault

This then also affects mesh->communicate(). It's ok that this doesn't work; communicate shouldn't be able to modify const or temporary fields, but a more useful error message than "segfault" would be good. A stack trace produces:

...
#223592 FieldGroup<Field3D const> (this=0x7fffffffc6d0)
    at ../..//include/bout/fieldgroup.hxx:53
#223593 FieldGroup<Field3D const> (this=0x7fffffffc6a0)
    at ../..//include/bout/fieldgroup.hxx:53
#223594 FieldGroup<Field3D const> (this=0x7fffffffc670)
    at ../..//include/bout/fieldgroup.hxx:53
#223595 FieldGroup<Field3D const> (this=0x7fffffffc640)
    at ../..//include/bout/fieldgroup.hxx:53
#223596 FieldGroup<Field3D const> (this=0x7fffffff0250)
    at ../..//include/bout/fieldgroup.hxx:53
#223597 physics_run (t=<optimized out>) at elm_6f.cxx:1381

so it looks like the constructor is calling itself until it overruns the stack. Some way to catch const fields being added to FieldGroup maybe?

**Comment by ZedThree** [comment]
We could use `std::is_const` to check for `const`ness and then `throw` an exception?

**Comment by dschwoerer** [comment]
This does not fix the issue:
```
int i;
FieldGroup f(i);
```

We should add a template that requires at least 2 arguments, passes the first to a real implemntation, and calls with the remaining ones ether itself or implemntation for that:
```
template <typename T, typename... Args>
FieldGroup (T a, Args... args){
  return FieldGroup(a)+FieldGroup(args);
}
```

**Comment by bendudson** [comment]
Another possibility is to add:

template<typename T>
void add(T &v) = delete;
  
which results in the error message:

error: use of deleted function ‘void FieldGroup::add(T&) [with T = const Field3D]’
     add(ts...);
     ^
../..//include/bout/fieldgroup.hxx:112:8: error: declared here
   void add(T &v) = delete

It does also mean changing void add(FieldData &f)  to void add(Field2D &f), so only Field2D, Field3D, Vector2D and Vector3D types can be added.
