### ISSUE TITLE
python2 compatible?

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#547]
Most of bout++ seems to python2 compatible, so far I think only `examples/test-initial/runtest` and `BOUT-dev-4.0.0/examples/fci-slab/runtest` requires python3.

Do we want to fade out py2 support?

**Comment by bendudson** [comment]
Yes, agree we should move towards python 3. Many bits of python code have imports at the top to try and support both python 2 and 3 which I think is probably right: if both can be supported then great, but if forced to choose then we should support py3.

**Comment by ZedThree** [comment]
Python 2.7 will be end of life in 2020, just less than 3 years from now.

Given that we expect a C++11 compiler, I think it is reasonable to expect python 3 as well. The libraries we need all support python 3.

I'm definitely in favour of not worrying about python 2 support, and aiming for everything to be python 3.

**Comment by dschwoerer** [comment]
Ok, seems fair 👍
