### ISSUE TITLE
nx and ny constant for different processors

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#560]
Why have nx and ny to be constant across the nodes?

If there are no major reasons to keep this, I would like to remove this in the future (in part due to issues with staggered grids)

**Comment by bendudson** [comment]
No fundamental reason, but mainly to make mapping from local to global indices easier, or finding which processor has a given global index. This could all be extended to be more general.

**Comment by dschwoerer** [comment]
👍 Thanks
