### ISSUE TITLE
Consistency of CHECK usage

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#569]
In most locations in the code we check if the value of `CHECK` is greater than a certain value to decide if we do that relevant test, however in a few places we just have `#ifdef CHECK`. This may be slightly confusing for some as it means even if `CHECK` is set to 0 (or -1 etc.) then we will still have some checks. 

Of course whilst we'd hope the users are using the configure option `--enable-checks=no` to disable checks, it's still common for people to edit make.config manually, which could lead to people setting `-DCHECK=0`.

Should we consider ensuring that `CHECK` is always used in a comparison operation (and if not defined we give it a default value)?

**Comment by d7919** [comment]
A related point to note is that using `--enable-checks=4`, `--enable-checks=-100` or  `--enable-checks=off` etc. in the configure command we will end up with `-DCHECK=2` in all cases. Is it possible to catch invalid values and abort with a helpful message? Could/should values >3 be capped to 3 (guessing someone setting to a large number wants most rigorous checking)?

**Comment by bendudson** [comment]
I think I would prefer aborting with a helpful message over capping values. Does the compiler treat a missing definition as 0? Would replacing all ifdefs with if CHECK > 0 be sufficient?

**Comment by d7919** [comment]
I think the C standard says that an undefined identifier will be replaced by a 0, so switching ifdef to CHECK>0 should be sufficient ([see here](https://stackoverflow.com/a/13149212))

I agree that aborting with a helpful message would probably be the best option.

**Comment by d7919** [comment]
fbad805 should provide a "fix" for the main "issue".

Note a large number of these checks are actually associated with `msg_stack.push/pop` calls which can probably be replaced with the `TRACE` macro.

**Comment by d7919** [comment]
Helped by #575 which removes a number of `#ifdef CHECK` blocks associated with `msg_stack` calls.

**Comment by d7919** [comment]
Closed by #577
