### ISSUE TITLE
Collect on Marconi-Fusion

### ISSUE THREAD

**Issue by fulviomilitello** [boutproject/BOUT-dev#579]
I'm trying to use 'collect' on MARCONI-Fusion but it does not work as netcdf4-python is not installed. I created a virtual environment, I have installed Cython and netcdf4-python, but that did not seem to work either, despite the fact that a 'pip freeze' gives me netcdf4-python installed. Substantially, 'import netCDF4' returns errors, boututil selects scipy.io.netcdf instead and that cannot read the netcdf4 dump files. Any suggestion? (PS let me know if it is useful/appropriate to raise issues like this here).

**Comment by fulviomilitello** [comment]
I sorted this out, installing netCDF4-python using pip install (not recommended on the netcdf4-python website, which gives manual procedure) does the trick.

**Comment by d7919** [comment]
Can you specify what errors you're seeing when you try to import `netCDF4`?

I just ran `pip install --user netcdf4` and `pip install --user ipython`. Starting `ipython` and typing `import netCDF4` didn't seem to lead to any errors, but using various `runtest` scripts did cause `collect` to fall back to scipy.

**Comment by d7919** [comment]
Ah I see you've found the same approach! 

It may be worth noting that even if you've done `module load python/3.5.2` the system python still seems to take precedence (`which python` returns `/usr/bin/python` and `python --version` returns 2.7.5). This may cause some problems.
