### ISSUE TITLE
Proposal to remove backward-compatible initialisation flags

### ISSUE THREAD

**Issue by bendudson** [boutproject/BOUT-dev#58]
The old / BOUT compatible initialisation flags are confusing and less powerful than then FieldFactory based expressions. The proposal is to drop support for the following:

xs_opt, ys_opt, zs_opt    -- switch between constant, gaussian, sinusoidal, mix of modes
*s_s0, *s_wd   -- Mean and width of Gaussian
*s_mode, *s_phase -- Z mode number and phase for sinusoidal option
scale  -- A multiplying factor 

The initialisation code first looks in the variable section, then if not found looks in the "All" section. This behaviour would be removed. 

In addition there is a top-level flag "ballooning" which affects how the y direction is interpreted in the core region. This is currently being replaced with a function ballooning() which could be included in analytic functions. 

The only way to initialis for variable "X" would be to use the "function" setting:
[X]
function = ... 

The initialprofiles.cxx code would be deleted, and all initialisation done in the Solvers base class.

**Comment by johnomotani** [comment]
It might be useful to add some sort of mixed-mode special function for 
quick (less verbose) initialisation of turbulence simulations; the 
old-style *s-opt=3 was quite useful for this purpose.

**Comment by ZedThree** [comment]
Fixed in next
