### ISSUE TITLE
ASSERT0 in "per element" functions

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#580]
Currently there is no way to disable `ASSERT0` from performing the requested check and throwing if the assertion fails. This probably isn't too much of a problem, however it does mean we probably need to be careful about where we but these. Currently there are `ASSERT0` calls in `set?Stencil` routines (as well as a few other places), these `*Stencil` routines are typically called once per grid point when applying stencil operators, which means the corresponding assertion tests are also called for each point. This is probably excessive (these specific conditions check at the field level). I doubt this has a large performance impact but probably worth avoiding anyway.

**Comment by dschwoerer** [comment]
solved in #581
