### ISSUE TITLE
Separating examples and tests

### ISSUE THREAD

**Issue by bendudson** [boutproject/BOUT-dev#588]
Would it make sense to organise the examples/ directory into examples and tests? Perhaps examples/ should contain only examples, and there should be a separate directory "tests" or "testing" which would contain the test suite and other things which are pass/fail tests.

**Comment by d7919** [comment]
Yes I think splitting examples and tests is a good idea. People would still be able to look at the tests for a specific feature if they wish, but it's perhaps clearer that the tests may be doing "special" things compared to the recommended approach (as used in examples). It would also allow us to "spin off" the examples to a git sub-module or similar in the future if we wanted to have a leaner core.

**Comment by ZedThree** [comment]
In my unit tests branch, I've put the unit tests under `tests/`, and started moving some of the simpler "test" examples from `examples/` to there. Moving the test suite stuff under there too is a good idea.

When I get back from Belfast, I'll submit a PR so people can see what the test framework looks like.

**Comment by ZedThree** [comment]
See: https://github.com/boutproject/BOUT-dev/tree/tests

Not quite ready for a PR yet, but basic structure is there. Currently has 122 tests that run in 4ms (not including compile time...)

**Comment by d7919** [comment]
Will this be completely fixed with v4.1 or is it just a start?

**Comment by bendudson** [comment]
Now fixed in 4.1
