### ISSUE TITLE
Laplacian maxmode limits

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#589]
Looking through some of the Laplacian solvers I noticed a few possible issues/inefficiencies.

* Shoot_laplace seems to use loop limits that are up to but not including `maxmode`, whilst other solvers are up to and including `maxmode`.
* The following impls solve for all mode numbers, not just those `<=maxmode`; serial_tri, serial_band

**Comment by bendudson** [comment]
shoot_laplace can probably be removed. It never worked, but seemed like an idea worth trying. Left in as a warning to others really... There may be a better way to record that something has been tried and doesn't work.

**Comment by d7919** [comment]
Ah ok, if we don't remove it I guess we could just add a `throw` that is always triggered in the constructor?

**Comment by d7919** [comment]
Maybe we should have a graveyard section in the manual for things that have gone in and then been removed?

**Comment by d7919** [comment]
Closed by #592
