### ISSUE TITLE
-DCHECK changes memory layout

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#594]
After hours of debugging, I noticed that `-DCHECK=...` can change the memory layout of bout objects.
There are some other flags as well `-DTRACK`.

While this seem perfectly fine in most current use cases, it is an issue if you want to build anything that wants to link against bout++. In which case, the specific set of `-D` flags needs to be provided for every project down the line, and everything needs to be recompiled, if they change.

One option would to put all optional elements at the end of an object, but that doesn't help:
* if there is more than one optional element
* if there are derived objects
Therefore I think they should all be included always ...

Another option, which wouldn't solve the recompile issue, would be to put all `-D` flags in an file (maybe `include/bout/config.hpp`) that is always included.
This would ensure that if bout is included from another project, it doesn't have to add all the `-DCHECK` and so on from the bout library as flags.

<s>As part of the decisions are header files only, different projects could be compiled with different levels of checking (not sure this causes no bugs - probably not a good idea ...)</s>

**Comment by d7919** [comment]
Should these flags be provided by `bout-config`? 

Could you expand a little on where this is an issue; presumably if you're just linking against the BOUT++ library then you don't care what these flags are, so is this a case of trying to link specific object files (possibly individually compiled with a different set of flags) into a different project or am I missing something (likely)?

**Comment by dschwoerer** [comment]
If you link against the bout library, you probably want to use functions, so if you define "linking against the bout library" to include using (and therefore compiling) functions like `Field3D::getNx()` - then, this is an issue.
For that you need the header files, which is the issue, as they provide inline functions which are flags dependent.

Using `bout-config` works - so this is not a bug, but I guess rather a feature request.

Background: I am trying to call these functions from cython - which means in the future, a change in the flags requires to rebuild + regenerate the cython files, which is possible, but I don't think it is ideal ...

**Comment by d7919** [comment]
This is a little similar to common usage for PETSc, where there may be several different configurations available (the PETSC_ARCH options) but users of the library don't have to worry too much about the configuration beyond saying what PETSC_ARCH is. They get around this by making you (or providing) things that can be included and contain all the relevant settings, as you've suggested earlier. To do this I think we'd probably want to "namespace" all the BOUT flags to ensure no conflicts etc.

This is probably a bad idea, but would another alternative be that in the process of building the BOUT library "package" be that the header files that are "shipped" are the processed header files, i.e. with the specific choices hard-coded? Then the lib+headers define exactly the configuration chosen by the user. 
Of course this still requires a recompile if the desired flags change, but I think this is reasonable -- if you want to use a different configuration of compile time flags you have to reconfigure. This would have the advantage of ensuring that other projects using BOUT don't have to carry around and use all the BOUT flags.
