### ISSUE TITLE
Building for KNL @ Archer

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#597]
Managed to successfully configure, build and link a full physics model using BOUT++ on the KNL system at Archer using the following:

Configure with

`./configure MPICXX=CC  --host=knl --with-netcdf --with-pnetcdf=no --with-hypre=no`

Edit `make.config` to add the following to `BOUT_FLAGS`

`-xMIC-AVX512  -D_GLIBCXX_USE_CXX11_ABI=0`

(the first is optional, aiming to produce more efficient code. but the second is required as a workaround).

This is with the following set of modules, `module list`  :

~~~~~
Currently Loaded Modulefiles:
  1) modules/3.2.10.5                  7) gni-headers/5.0.7-3.1            13) sysadm/2.2.2-3.39                19) cray-mpich/7.4.4                 25) cray-netcdf/4.4.1
  2) alps/6.1.6-20.1                   8) dmapp/7.1.0-12.37                14) lustre-utils/2.3.4-6.74          20) pbs/default                      26) fftw/3.3.4.10
  3) nodestat/2.2-2.40                 9) xpmem/0.1-4.5                    15) Base-opts/2.1.3-2.16             21) cray-libsci/16.09.1              27) papi/5.4.3.3
  4) sdb/2.2.1-3.119                  10) llm/20.2.4-3.18                  16) craype-mic-knl                   22) pmi/5.0.10-1.0000.11050.0.0.ari  28) intel/17.0.0.098
  5) udreg/2.3.2-4.6                  11) nodehealth/5.2.0-5.46            17) craype-network-aries             23) atp/2.0.3                        29) gcc/6.2.0
  6) ugni/6.0.12-2.1                  12) system-config/2.2.18-3.38        18) craype/2.5.7                     24) PrgEnv-intel/6.0.3
~~~~~

**Comment by dschwoerer** [comment]
If you don't want to edit the make.config file, you can provide the options at configure time (than the pvode should also be build with them) by running:
`./configure MPICXX=CC --host=knl --with-netcdf --with-pnetcdf=no --with-hypre=no CXXFLAGS="-xMIC-AVX512 -D_GLIBCXX_USE_CXX11_ABI=0"`

Currently, there are some configure scripts for different systems included in bout - should we add this one as well?

**Comment by d7919** [comment]
Yes that's a good point, I have a habit of editing make.config directly as I tend to have a few specific tweaks that I want to make but we probably shouldn't encourage this!

I think providing an example configure could be helpful (maybe in the docs?) but I'd suggest we hold off on adding this particular configure script for now as it is not ideal (work arounds and minimal support) and hopefully just provides a starting point for getting a better setup once people start using this particular system a bit more.
