### ISSUE TITLE
Reading data from binary files

### ISSUE THREAD

**Issue by bendudson** [boutproject/BOUT-dev#60]
The interface to binary files doesn't make it very easy for users to read data into simulations, or to mix mesh data in BOUT.inp and binary files.

The DataFormat interface to files is too low level, and doesn't have any facilities for handling data which should be distributed across processors. It''s also a bit clunky to use, see examples/test-dataformat

The DataFile design could be better, since it stores pointers to variables, and doesn't allow processors to access different parts of a file unless using a parallel format like pNetCDF. It also uses char arrays and pointers in too many places.

**Comment by ZedThree** [comment]
Now tracked in #1254
