### ISSUE TITLE
BOUT overwrites input file with -f BOUT.settings

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#600]
Bout generetes on exit the file BOUT.settings.
Nothing is preventing me from using this as new input file.
Is this intended behaviour that this is overwritten on exit?

**Comment by bendudson** [comment]
Yes. It's written at the start and again at the end. The settings don't (or shouldn't) change, but the comments do: it's only known at the end whether a setting is used.  The write at the start is in case the run is stopped or crashes before the end

**Comment by dschwoerer** [comment]
My question was rather whether we are fine to happily overwrite the __input__ file?

I think there should be some protection for the user - just in case the disc is full, or for some reason the code crashes while writing, so that the user does always have an input file.

And the options might very well change, if I supply other or new options, `BOUT.settings` will have changed.

**Comment by bendudson** [comment]
Ah ok... I suppose someone could try to do that. I had assumed people would rename BOUT.settings -> BOUT.inp. We could prevent the user from setting the input file to BOUT.settings, but they could make a soft or hard link. 

Perhaps we could use a different name for the settings file written at the start and end, but I think it's difficult to prevent a user from potentially overwriting their input if they really try. Maybe just a warning in the manual?

**Comment by dschwoerer** [comment]
fixed by #601
