### ISSUE TITLE
Bindex squashing, avoid out of range but gives wrong result

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#604]
The `bindex` object used alongside the stencil objects for applying a derivative function is meant to store the indices for `x`, `x+1`, `x+2`, `x-1` and `x-2` along with others. Unfortunately if for the current `x`,  `x+1` or `x+2` is outside the local range (i.e. `>= LocalNx`) then the code currently just silently sets these to `LocalNx-1` (and similarly for the `x-1` and `x-2` cases). See [here](https://github.com/boutproject/BOUT-dev/blob/master/src/sys/stencils.cxx#L494) for an example.

This means that you can get the wrong result being returned at certain points when we should instead have an abort. For example, consider `MXG=1` -- if I use `D4DX4` in my model this should try to access out of bounds (`jx`=1, `jxm`=0 but `jxmm`=-1 which is out of bounds). Instead `jxmm` is set to 0 and I get the wrong result without any warning.

Unfortunately just removing this behaviour means the code will not run with checks turned on because in some places (e.g. [here](https://github.com/boutproject/BOUT-dev/blob/master/src/field/field2d.cxx#L294)) we try to populate all stencil entries even if we're not going to use them. Consider again the previous case with `MXG=1` and now I just want to apply `DDX_C2`, this only needs `jxp` and `jxm` but it still tries to get the value for `jxmm` and `jxpp` -- causing an out of bounds error.

I'm aware there's been some discussion of replacing this stencil code in various ways, so I'd suggest we maybe don't spend too much effort trying to fix this specific issue, but it may be worth thinking about if we can check at runtime if the number of guard cells is sufficient for a particular method (similar to #323). I suspect this may not be trivial, but it may be possible as a temporary fix whilst we investigate stencil changes.

**Comment by dschwoerer** [comment]
An option would be to check in the set stencil code, and if they would be out of bounds, set them to (nonthrowing) `nan("")`.
Then, only if they are used, an error will be thown (if sig fpe is enabled).

It does not give great error messages, but it should make it obvious that there is an error ...

**Comment by ZedThree** [comment]
Did #804 completely obviate this problem?

**Comment by d7919** [comment]
Yes as far as I'm aware this was entirely within the calc_index/next_index and related routines which have all been removed.

**Comment by ZedThree** [comment]
Fixed in #804
