### ISSUE TITLE
BOUT.log files too noisy

### ISSUE THREAD

**Issue by bendudson** [boutproject/BOUT-dev#608]
The output log files (BOUT.log.*) contain too much noise, which makes it hard to pick out important information or warnings. Most of this is options, but these are (mostly) now output to BOUT.settings.

One problem is how to handle default settings which are not set in BOUT.inp, and are not (currently) output to BOUT.settings. The value used could be put in BOUT.settings perhaps? i.e. if an option is requested from the options tree which has not been set, then it could be added to the options with a "default" label for the source (rather than "command line" or "BOUT.inp"). A problem could arise if the same option has different defaults in different places, but that would probably be a bug anyway.
An advantage is that the default values used are recorded in a machine-readable format (BOUT.settings), and can be reproduced even if the default is changed in the code.

**Comment by d7919** [comment]
Agreed. The most helpful bit about the "header" in my usage is that I can diff the logs of two runs to find any difference in setup -- this should now be possible by diffing BOUT.settings (if the defaults are recorded).

Would it be possible to check when on the default path if that route has already been followed but with a different default (for example checking if the variable is in the option tree with a source of default and a different value -- I'm not familiar with the tree so don't know if it stores this information)?

This change would of course mean it wouldn't be so easy to compare to old log files, but I guess that's not a particularly important change.

**Comment by bendudson** [comment]
This is addressed by PRs #615, #629 and #630
