### ISSUE TITLE
CVODE number of preconditioner calls

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#61]
I'm currently trying out some preconditioning routines for use with `CVODE`. I noticed that when enabling the `CVODE` diagnostics (diagnose=true) the number of preconditioner evaluations is being reported as 0.  

It seems we're using `CVSpilsGetNumPrecEvals` to query `CVODE` for the number of evaluations. It seems from the guide (https://computation.llnl.gov/casc/sundials/documentation/cv_guide/node5.html) that there is also `CVSpilsGetNumPrecSolves`. I'm not sure what the distinction is between evals and solves, but the later seems to return non-zero numbers in my case.

Should we replace  `CVSpilsGetNumPrecEvals` with `CVSpilsGetNumPrecSolves`? 

Two things to note; I'm using a user supplied preconditioner and I'm using the most recent sundials release (with ARKODE support).

**Comment by bendudson** [comment]
Hey David,

Sounds like something's a bit strange... Should probably be an issue first.
Like to see what happens on older versions of CVODE, and if
CVSpilsGetNumPrecSolves
is a new function.

Best

ben

**Comment by d7919** [comment]
Just googling `CVSpilsGetNumPrecSolves` returns hits from at least as far back as 2006 (http://computation.llnl.gov/casc/sundials/documentation/cv_examples/node10.html)

**Comment by d7919** [comment]
Just to add to this, if not using newton iteration (i.e. `func_iter = true`) then when diagnose is on querying the number of preconditioner evals/solves leads to many instances of:

~~~~
[CVSPILS ERROR]  CVSpilsGetNumPrecEvals
  Linear solver memory is NULL.
~~~~

**Comment by d7919** [comment]
It seems that `CVSpilsGetNumPrecEvals` corresponds to how many times we call a preconditioner setup routine whilst `CVSpilsGetNumPrecSolves` corresponds to the number of times we call the precondtioner itself. As we don't specify a setup routine at the moment in the `CVODE` solver (the second argument to `CVSpilsSetPreconditioner` is always `NULL`) I think we probably want to use `CVSpilsGetNumPrecSolves` in the diagnose output.
