### ISSUE TITLE
get/set?array in Field/Field2D

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#610]
The `get?array` and `set?array` routines in Field/Field2D are not used anywhere in the examples or the main part of `BOUT++`  and seem to be against the usual ethos of data access being directly through fields (where as here we extract vectors containing pieces of data). 

Can/should we remove these (either with a deprecation stage or more quickly)?

**Comment by bendudson** [comment]
I vote for deprecating now, and removing after the next release (4.2?).

**Comment by ZedThree** [comment]
It would be nice if `DEPRECATED` emitted a warning that said "we will remove this in version X.Y". Not sure if that's possible/portable

**Comment by d7919** [comment]
Compile time or run time? 

We could add a `#warning ....` pragma to the DEPRECATED macro -- this would give you a customisable compile time message (although that's what the DEPRECATED message is as well, just not customised). Run time isn't possible the way we have it at the moment though (I think).
