### ISSUE TITLE
Missing deletes

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#611]
There are a number of places where memory is allocated during the initialisation phase that is not freed during the final phase. I've started branch [more_deletes](https://github.com/boutproject/BOUT-dev/tree/more_deletes) to try to start to fix this.

This is generally not a major issue as the memory will be freed when the program halts anyway, but it's probably nice to try to fix these if we can to make things a little more robust etc.

I've also come across some places I'm not sure how best to fix including:

* RangeIterator
* Lapack_routines (static variables)
* FFTW routine (static variables)
* invert_parderiv_simple.cxx (static variables)
* pdd laplacian (static variables)
* full_gmres.cxx (static variables)
* orig_boundary_standard/nonorthog_boundary_standard (static variables)

I've "tagged" many of these places with `//Never freed` for easy location.

**Comment by bendudson** [comment]
Many of the static variables can probably be replaced with Array objects, since they can be cleaned up

**Comment by d7919** [comment]
Yes I suspect there are quite a few places we would be better off using arrays.

I didn't pay too much attention to `matrix` objects either, but these should be freed using `free_matrix` -- could probably get these to use array as a backend as well.

**Comment by bendudson** [comment]
Much of this is fixed by PR #631

**Comment by ZedThree** [comment]
Update, only three tagged places left:

./src/invert/lapack_routines.cxx:445:    al = matrix<dcomplex>(n, m1); //Never freed
./src/invert/fft_fftw.cxx:225:      p = new fftw_plan[n_th]; //Never freed
./src/invert/fft_fftw.cxx:296:      p = new fftw_plan[n_th]; // Never freed

The fftw ones could be solved by wrapping all the fft stuff up in a class, and creating/freeing the plans in the ctor/dtor?

**Comment by d7919** [comment]
I think the fft ones could actually use an `Array<fftw_plan>`.

**Comment by d7919** [comment]
This is being further improved with the introduction of `Matrix`, `Tensor` and replacing some uses of `new` with `Array`.

**Comment by d7919** [comment]
#902 removes the need for a number of these.

**Comment by bendudson** [comment]
I think this is now largely fixed. Replace raw pointers with Array/Matrix/Tensor etc. on sight.
