### ISSUE TITLE
start_index()/next_index() uses global mesh

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#616]
Therefore derivatives still don't work ...

**Comment by bendudson** [comment]
There is a branch which replaces the start/next index stuff with DataIterators and may improve this. I'll try to tidy up and create a pull request

**Comment by dschwoerer** [comment]
I managed to calculate derivatives (in z direction) using the [fieldops](https://github.com/dschwoerer/BOUT-dev/tree/fieldops) and the [aiolos](https://github.com/dschwoerer/BOUT-dev/tree/v4_aiolos_mesh) branches ...

The aiolos branch needs probably significant cleaning, documentation etc before it can be merged ...

**Comment by bendudson** [comment]
There is now a PR #633 to replace start/next index stuff with DataIterator.

I think the aiolos branch is a good idea, and I don't object to code generation in general. I think the main thing is a cleaner separation between generator input and generator code. I'd like to be able to have a relatively short input file which goes through a preprocessor to produce the output code (e.g the yacc tool). At the moment I need to understand too much about what the generator is doing to be able to debug or improve it. There are some C/C++ code generators out there which we may be able to use or adapt.

**Comment by ZedThree** [comment]
Fixed in #804
