### ISSUE TITLE
Split operator not currently possible when using LegacyModel

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#624]
I've been using an "old style" model that isn't implemented using a physics model class. I just tried setting this up to use a split operator but this didn't lead to any change in the output/behaviour.

It turns out that whilst `solver->setSplitOperator` still exists and "works", because the default `main` always constructs a `LegacyModel` to use with the solver, the `split_operator` flag is set from querying the model's `split` flag, which can't be set to anything other than `false` in such a setup.

The obvious solution is to convert my model to implement a physics model class, however I think it might also be helpful to strip out things like `Solver::setSplitOperator` (presumably also an issue for preconditioning etc.) and the code paths that check to see if we've set a `model` or not (so only the with model path is kept). This would help people realise the old approach is being removed and they need to update if they want to keep access to all the useful features.

**Comment by bendudson** [comment]
Closing as the legacy models are not supported. The issue of simplifying code paths and the Solver interface still stands though.
