### ISSUE TITLE
v4.1 release candidate

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#640]
I've just made a new branch for the v4.1 release candidate (https://github.com/boutproject/BOUT-dev/tree/v4.1-RC). Preferably only bug/warning fixes, documentation and tests should now go in, with the exception of currently open PRs.

**Comment by dschwoerer** [comment]
I hoped #550 could be included, so that providing binaries could be done without many patches ...

**Comment by ZedThree** [comment]
I remember why I hadn't merged already, I meant to ask you to change the PR to merge into next rather than master!

**Comment by dschwoerer** [comment]
Ah, I think I wanted it to go into master, as it was mentioned in may that the 4.0.1 release would be in about a week, and the 4.1 in about a month, so I hoped that I could continue with official builds soon with a officially released version, without additional patches ....

**Comment by ZedThree** [comment]
I think the last thing that needs fixing is the catching exceptions by value, rather than reference, and removing the exception name when we don't use it.

Other than that, (and the open PRs), I think 4.1 is good to go!

**Comment by bendudson** [comment]
I think this is nearly ready to go. I think only PRs #629 , #674 and #681 to go in, then v4.1 can be released. Anything else?

**Comment by ZedThree** [comment]
I had some minor tidying up stuff, but it can wait. I think I'd rather get this out!

**Comment by ZedThree** [comment]
Oh, we should update the changelog...

**Comment by d7919** [comment]
Can this be closed now that 4.1 is released?
