### ISSUE TITLE
Suspicious unused parameters for DataFormat::setLocalOrigin

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#644]
In dataformat.cxx:26:

```cpp
bool DataFormat::setLocalOrigin(int x, int y, int z, int offset_x, int offset_y, int offset_z) {
  return setGlobalOrigin(x + mesh->OffsetX, y + mesh->OffsetY, z + mesh->OffsetZ);
}
```

where `offset_[xyz]` all default to 0. However, `setLocalOrigin` is called with non-zero offsets in the `Datafile::open*` routines if `Datafile::parallel` is true.

Are any of the parallel file formats actually supported? I'm not sure we have actual tests for them (presumably they need testing on parallel filesystems).

**Comment by bendudson** [comment]
I think pnetcdf "worked" at some point: It produced some output, but I think it was buggy and would frequently corrupt or garble the data. Possibly related to handling of array offsets...
