### ISSUE TITLE
genZMode no longer used?

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#645]
`genZMode` doesn't appear to be used any more. It's not called in the main library and none of the examples use it, at least. It also takes an unused parameter, `n`, so it's possible it doesn't even do the "right" thing either.

Should we deprecate/remove it?

**Comment by bendudson** [comment]
I think it should be removed. From the documentation it looks like "n" should be inside the sin() function, but is not used so doesn't do the right thing. This can easily be replaced by clearer methods e.g. FieldFactory

**Comment by ZedThree** [comment]
Will deprecate in 4.1, to be removed/replaced in a future version

**Comment by ZedThree** [comment]
Fixed in #735
