### ISSUE TITLE
Extra boundary files

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#646]
In `src/mesh` there is `boundary_standard.cxx`, `orig_boundary_standard.cxx` and `nonorthog_boundary_standard.cxx`. Only this first is included in the build.

It looks like `nonorthog` is a superset of `orig` -- containing a few additions (fixes/generalisations/not relevant?).

The `boundary_standard` version is the version we actually use and is essentially an up to date version of things, but doesn't seem to include some of the additions that are in `nonorthog`.

I think these extra files can probably be removed but we might want to see if the extra things in `nonorthog` should be merged first or not.

**Comment by ZedThree** [comment]
These *should* be merged already, but I will check before deleting them

**Comment by d7919** [comment]
See https://github.com/boutproject/BOUT-dev/tree/removeUnusedBoundaryFiles

**Comment by d7919** [comment]
Fixed in v4.1 with #652
