### ISSUE TITLE
Boundary non-staggered dirichlet with Field3D

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#651]
Commit 1fd2315c48741365c48a73b6d538d193cba22794 replaced extrapolation in the boundary cells with just setting all boundary cells to the Dirichlet value. I think the extrapolation should be the correct thing to do. 

I've just committed 519ebbfac6d5547a02333c30671ac5eed7f9250c which reverts this change and the MMS tests past.

**Comment by bendudson** [comment]
That commit changed what is done in the second guard cells, not the one closest to the boundary. This only affects high-order methods, not the 2nd order convergence tests. Whilst extrapolation is the correct thing to do for the first boundary, it's not obvious for other boundaries. I have heard that higher order boundaries are not stable.

 I think I found that setting the value was more robust when using 4th-derivatives for dissipation terms, but I can't remember now. Sorry my commit message doesn't explain why.

**Comment by d7919** [comment]
Ah ok, that makes sense -- I guess this is because the extrapolation is low order? Would the "correct" fix be a higher order extrapolation, or is it really that any extrapolation beyond setting the effective boundary point is unstable? I guess another option would be to switch to one sided differences with higher order methods near the boundary, but this is likely not easy to implement currently and may not even be desirable?

A potentially related issue is that the non-extrapolation approach is not used elsewhere, so when operating with staggered grids etc. we may experience these issues.

#652 includes the commit that reverts the mms fix -- I'll remove this commit from the PR and add some comments to outline what is being done and why.

**Comment by d7919** [comment]
Fixed in v4.1 with #652
