### ISSUE TITLE
Commit #626 breaks fci_slab

### ISSUE THREAD

**Issue by bshanahan** [boutproject/BOUT-dev#655]
#626 breaks fci_slab example.  I have a [branch](https://github.com/boutproject/BOUT-dev/tree/fci_slab_poloidal_grids) which is currently looking to fix this, but fci_slab still fails, and I haven't fixed all of the files such as generate.

**Comment by d7919** [comment]
What is the mode of failure? Wrong result, doesn't compile, etc.?

**Comment by bendudson** [comment]
Does it get first order convergence (in which case it might be a boundary-off-by-half-cell issue) or no convergence?

**Comment by bshanahan** [comment]
No convergence.

**Comment by bshanahan** [comment]
[fci-norm.pdf](https://github.com/boutproject/BOUT-dev/files/1228260/fci-norm.pdf)

**Comment by d7919** [comment]
Can this be closed now?

**Comment by bshanahan** [comment]
Yep sorry.  all fixed.
