### ISSUE TITLE
Use of floats in Coordinates::gaussj

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#656]
`Coordinates::gaussj` uses three `floats` `big`, `dum`, `pivinv`, which get set from `BoutReal`s. Should these actually be `BoutReal`s? If they should really be `floats`, we should probably use `static_cast<BoutReal>()` to convert them explicitly, and add a comment explaining why.

**Comment by d7919** [comment]
I can't see any reason this would need to be float and I think should probably be BoutReal. Possibly this is code reuse/inspired from another project?

**Comment by bendudson** [comment]
Agree, should be BoutReal. This code probably should use a different algorithm or library: LAPACK? gnu GSL?

**Comment by d7919** [comment]
We have some build structure etc. for using lapack already in  `src/invert/lapack_routines.cxx` so it might make sense to use lapack and add to `src/invert/lapack_routines.cxx` (possibly moving this into sys / utils?), with this algorithm as a fall back option for the no lapack case.

**Comment by ZedThree** [comment]
Fixed in #664

I'll make a new issue about replacing the whole function
