### ISSUE TITLE
Coordinates::gaussj should be replaced

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#668]
`Coordinates::gaussj` should be replaced with a more robust algorithm, e.g. one from LAPACK

**Comment by bendudson** [comment]
It's only inverting a symmetric 3x3 matrix. Can we just implement equation 6 from:
http://mathworld.wolfram.com/MatrixInverse.html

**Comment by d7919** [comment]
I think if we renamed the routine to something like `Coordinates::invertMetric` then it should be fine to hard code a 3x3 method (which could always be replaced with a call to a generic method should we have the need to implement one in future).

**Comment by d7919** [comment]
Closed by #883
