### ISSUE TITLE
Bugfixes available - but not in 4.1.0

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#675]
I cannot see any real reason to not merge master into the RC, besides that we have a different policy.
There are bug fixes in master. Is there any good reason they shouldn't be in the release?
Do we want to ship knowingly broken software, with available patches for the sake of complying with the policy?
I could cherry-pick the changes and add as new PR into RC, which I assume would follow the policy - but this can cause issues with merging down the line ... is this the only way to go to get the fixes in?

**Comment by bendudson** [comment]
The 4.1 release will be a tag which is made after v4.1-RC is merged into master. It will therefore contain all bugfixes in master. All merges go towards master, since that is the currently maintained release with bugfixes.
