### ISSUE TITLE
Configure fails to find liblapack unless CC=c++

### ISSUE THREAD

**Issue by kostukm** [boutproject/BOUT-dev#683]
There is an extern "C" declaration in conftest.c which configure attempts to compile with the C compiler. This correctly fails, yet prevents configure from finding various libraries, e.g. lapack. To reproduce this error, configure with/without setting CC to a C++ compiler:

`./configure --with-lapack=/usr/lib64
`
configure output terminates with:
...

> checking for gawk... gawk
> checking for gcc... gcc
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking how to run the C preprocessor... gcc -E
> checking for h5cc... no
> checking for HDF5 type... neither
> checking for HDF5 libraries... no
> configure: WARNING:
> Unable to locate serial HDF5 compilation helper script 'h5cc'.
> Please specify --with-hdf5=<LOCATION> as the full path to h5cc.
> HDF5 support is being disabled (equivalent to --with-hdf5=no).
> 
> configure: Serial HDF5 support disabled
> configure: Parallel HDF5 support disabled
> 
> Supported file formats: netCDF
> 
> checking for libblas... no
> configure: error: "LAPACK requested but not found."
> 

config.log shows that the extern "C" declaration is throwing the error:

>  configure:7834:
>  checking for libblas
> configure:7856: gcc -o conftest -g -O2  -I/fusion/usc/opt/fftw/fftw-3.3.6_mpich-3.2_gcc-4.9.2/include -L/fusion/usc/opt/fftw/fftw-3.3.6_mpich-3.2_gcc-4.9.2/lib  conftes
> conftest.c:31:8: error: expected identifier or '(' before string constant
>  extern "C"
>         ^    
> configure:7856: $? = 1
> configure: failed program was: 
> | /* confdefs.h */
> | #define PACKAGE_NAME "BOUT++"
> | #define PACKAGE_TARNAME "bout--"
> | #define PACKAGE_VERSION "4.0.0"
> | #define PACKAGE_STRING "BOUT++ 4.0.0"
> | #define PACKAGE_BUGREPORT "bd512@york.ac.uk"
> | #define PACKAGE_URL ""
> | #define HAVE_MPI 1
> | #define HAVE_CXX11 1
> | #define HAVE_LIBM 1
> | #define STDC_HEADERS 1
> | #define HAVE_SYS_TYPES_H 1
> | #define HAVE_SYS_STAT_H 1
> | #define HAVE_STDLIB_H 1
> | #define HAVE_STRING_H 1
> | #define HAVE_MEMORY_H 1
> | #define HAVE_STRINGS_H 1
> | #define HAVE_INTTYPES_H 1
> | #define HAVE_STDINT_H 1
> | #define HAVE_UNISTD_H 1
> | #define HAVE_MALLOC_H 1
> | #define HAVE_STDLIB_H 1
> | #define HAVE_STRING_H 1
> | #define HAVE_STRINGS_H 1
> | #define HAVE_STDLIB_H 1
> | #define HAVE_MALLOC 1
> | #define HAVE_STDLIB_H 1
> | #define HAVE_REALLOC 1
> | #define HAVE_VPRINTF 1
> | /* end confdefs.h.  */
> | extern "C"
> |     char zgemm_ ();
> | int
> | main ()
> | {
> | return zgemm_ ();
> |   ;
> |   return 0;
> | }

Yet if you force configure to use C++ it continues successfully 
`./configure CC=g++ --with-lapack=/usr/lib64
`
Now configure shows:

> configure: Serial HDF5 support disabled
> configure: Parallel HDF5 support disabled
> 
> Supported file formats: netCDF
> 
> checking for libblas... yes
> checking for liblapack... yes
> Using LAPACK

I suggest fixing this by having configure use CXX to compile conftest.c rather than CC.

**Comment by dschwoerer** [comment]
Can you try whether #684 resolves your issue?

**Comment by kostukm** [comment]
Yes, #684 fixed the problems that I was seeing. Thanks-
