### ISSUE TITLE
Dynamic casts in `ConditionalOutput`

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#691]
There are a couple of dynamic casts that have been introduced in `ConditionalOutput` ([here](https://github.com/boutproject/BOUT-dev/blob/master/include/output.hxx#L174) and [here](https://github.com/boutproject/BOUT-dev/blob/master/include/output.hxx#L194)), which will be used with stream output (but not `write`/`print`). Such casts can be relatively slow, so are best avoided when possible -- is it possible to avoid them here?

**Comment by dschwoerer** [comment]
`static_cast` should work just fine. The `dynamic_cast` should make it easier to detect if a bug is introduced.
Not sure whether the overhead is significant. Lots of printing will anyway cause performance issues, but if you want I can change it ...

**Comment by ZedThree** [comment]
I think this is likely ok for now. Later down the line, we may switch to spdlog or something anyway.
