### ISSUE TITLE
Field3D default move constructor leading to segfaults

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#698]
Just found an odd seg fault with code of the form

~~~~
a = func(b);
~~~~
where `a` and `b` are `Field3D` type and `func` returns a `const Field3D`. Depending on exactly what happens in `func` a seg fault arises. A backtrace suggests this is in a `Field3D` destructor when attempting to delete the `yup`/`ydown` fields. Suspect this is related to a move constructor being used leading to multiple pointers pointing at the `yup` etc. so end up with a double delete. Removing the `default` move constructor in `Field3d.hxx` seems to solve the issue.

**Comment by dschwoerer** [comment]
fixed by #699
