### ISSUE TITLE
Integrated tests don't all compile and not all used

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#701]
Just spotted some possible issues with the integrated tests; 

1. Out of the 39 test folders in `tests/integrated` only 19 are used in the test_suite. Whilst some of these represent optional features others, such as `test_yupdown`, don't and could presumably be included in the test suite without much cost. (We might need to revisit how the list of tests is built when we have optional dependencies enabled).
2. Some of the tests don't compile. Specifically `test_dataformat`, `test_interpolate`, `test_petsc_laplace_MAST_grid` (not a PETSc issue), `test-simple-diffusion`, `test_visitor`, `test_wave` and `test-fieldgroupComm`.
3. Some of the tests don't appear to be `valgrind` clean -- this is probably indicative of wider issues rather than an issue with the specific test. For example `test_yupdown` produces warnings/errors due to the the shifted metric routines.

**Comment by bendudson** [comment]
After PR #702 valgrind still outputs one warning from test_yupdown during communicate:

==1549== Invalid write of size 8
==1549==    at 0x4C33C33: memmove (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1549==    by 0x1592708F: ??? (in /usr/lib/openmpi/openmpi/mca_btl_self.so)
...
==1549==    by 0x21AE2D: BoutMesh::send(FieldGroup&) (boutmesh.cxx:881)
...
==1549==  Address 0x1562ca40 is 0 bytes inside a block of size 12,288 alloc'd
==1549==    at 0x4C2DC9F: operator new[](unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1549==    by 0x21F4F9: BoutMesh::get_handle(int, int) (boutmesh.cxx:1828)

The block it's inside is dmesg_recvbuff, but the buffer being sent is umsg_sendbuff. Making these buffers 10 times larger didn't remove the warning. This may be something strange in OpenMPI, or maybe not...

**Comment by bendudson** [comment]
With PR #702 the tests now compile except test-laplace3d, and I haven't tested test-petsc*
