### ISSUE TITLE
output.write still used in lots of places

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#719]
I notice there's still loads of `output.write`s scattered through the code, notable in the DataFile stuff, and lots that print "WARNING" or "INFO". Should these just be changed to `output_warn`, `output_info`, respectively, and those words deleted?

Actually, there's some "ERROR"s in there too.

**Comment by d7919** [comment]
I think having `Warning` etc. is helpful as there's no other way for the user to determine which stream a message has been sent to. (and these are the things that get coloured to draw attention to messages).

**Comment by bendudson** [comment]
If the word "warning" or "error" appears in the string then it can be highlighted by the coloring. Agreed that the output should be output.warning etc.

**Comment by ZedThree** [comment]
Fixed in #791
