### ISSUE TITLE
Scalasca/scorep support enabled if present in path

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#720]
The `--with-scorep` flag appears to be effectively ignored; when `scorep` is found in the path then support for it is enabled automatically no matter what the status of `--with-scorep`.

**Comment by ZedThree** [comment]
This is essentially "working as intended", in that it works similarly to e.g. NetCDF: we try to configure with NetCDF, even if `--with-netcdf` is not passed. As it is, we always try to configure with scorep, unless `--with-scorep=no` (or `--without-scorep`) is passed.

We could switch to `--enable-scorep[=path]` which would require the flag to be explicitly set, possibly with an optional path.

**Comment by d7919** [comment]
I thought I'd tried `--with-scorep=no` but this still added the scorep bits to the makefile.

**Comment by d7919** [comment]
I must have remembered incorrectly, can confirm `--with-scorep=no` works as intended. 

I think it would be better to explicitly request scorep support as builds with this enabled can behave differently (e.g. repeat runs of a case may fail due to blocking caused by existing scorep files etc.), i.e. better to leave as an "advanced" option rather than a default one.
