### ISSUE TITLE
Laplacian Serial_tri incorrect operation

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#727]
As spotted by Joseph Parker, the block [here](https://github.com/boutproject/BOUT-dev/blob/master/src/invert/laplace/impls/serial_tri/serial_tri.cxx#L205), active when `INVERT_KX_ZERO` flag set, modifies the `bk1d` object, which is not used again within this loop iteration and hence this operation is pointless. It is likely that this should instead by modifying the `xk1d` data instead.

**Comment by d7919** [comment]
Also looks like in the `periodicX` case there's an assumption that `MXG=2` (see [here](https://github.com/boutproject/BOUT-dev/blob/master/src/invert/laplace/impls/serial_tri/serial_tri.cxx#L197)).

**Comment by bendudson** [comment]
One option would be to remove the serial_tri implementation. The "cyclic" implementation works in serial or parallel, and this would be one less implementation to maintain.

**Comment by ZedThree** [comment]
Fixed in #729
