### ISSUE TITLE
Typo in unit test makefile?

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#730]
I think the dependency at https://github.com/boutproject/BOUT-dev/blob/next/tests/unit/makefile#L59 should be on `$(GTEST_SENTINEL)` rather than `$(TEST_SENTINEL)`?

**Comment by bendudson** [comment]
Yes, this should be GTEST_SENTINEL.

**Comment by bendudson** [comment]
Fixed in #731
