### ISSUE TITLE
"with" broken in the new datafile.py

### ISSUE THREAD

**Issue by loeiten** [boutproject/BOUT-dev#76]
Since 3142e0b1d1499f3b12318915149363a4ac9feb2d ```grid``` is returned as ```None``` in the following example.

```py
from boututils.datafile import DataFile
...
with DataFile("foo.grd.nc", write=True, create=True) as grid:
```
I'm not able to locate where the problem exactly lies myself, as it seems that ```__enter__``` and ```__exit__``` remains unchanged

**Comment by bendudson** [comment]
Agree, broken on my installation too. Seems we need a test suite for the Python routines as well as BOUT++ components.
