### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#761]
Is there a good reason to only install `boutdata` and `boututils` from the python suite?

I set up a repo for [spec files](https://fedoraproject.org/wiki/How_to_create_an_RPM_package) [1]
Should this be part of boutproject?

[1] https://github.com/dschwoerer/bout-spec

**Comment by bendudson** [comment]
Not particularly. Those are the essential ones to get the examples working, so to start with I was just trying to get a basic install working. We could also install other moduled, though I don't want to install things which could conflict with other packages.

**Comment by bendudson** [comment]
Thanks  for the spec file, looks good. Looks somewhere in between the tiny Arch install script, and the enormous and over-complicated Debian scripts.

**Comment by dschwoerer** [comment]
For fedora nothing provides `*zoidberg*` - and the other two contain bout in there name - so I guess the chances of a name conflict should be sufficiently low.
There are many `*bout*` files in python dirs - but most match `*about*`.
After filtering that, I only find a few stubout files and `/usr/lib64/python*/site-packages/astropy/io/ascii/tests/t/nls1_stackinfo.dbout`
So including everything should be fine 👍
