### ISSUE TITLE
Off by one error in filtering for DDZ::FFT?

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#768]
The loop at 
https://github.com/boutproject/BOUT-dev/blob/next/src/mesh/index_derivs.cxx#L1403
should go over the elements from `kmax+1` to the end of `cv`, setting them to zero. However the upper limit of the loop is `ncz/2` exclusive, whilst `cv` has length `ncz/2 + 1` so the upper index is `ncz/2`  so I think we miss this off this loop.

**Comment by bendudson** [comment]
Yes, I think you are right
