### ISSUE TITLE
collect when 'variable not found' broken

### ISSUE THREAD

**Issue by loeiten** [boutproject/BOUT-dev#77]
Since 3142e0b1d1499f3b12318915149363a4ac9feb2d reading one dimensional from ```collect``` is broken.

In line 140
```py
    if ndims < 2:
```
returns ```TypeError: unorderable types: NoneType() < int()```. I guess the reason for this is that line 130
```py
        #ndims = len(dimens)  
```
is out-commented.

**Comment by johnomotani** [comment]
ndims should be set by ```ndims = f.ndims(varname)``` in line 131 or 138. ```collect``` works for me with 1d data, at for least reading 't_array' from some old simulations.

**Comment by loeiten** [comment]
Sorry, I meant 0d data, my bad.
Anyway, the real problem was not to read the data after all, but rather the error occurring when the variable was not found (I noticed the problem in a ```try``` statement). 

A solution can be to add the following to line 132
```py
         if ndims == None:
             raise ValueError("ERROR: '"+varname+"' not found")
```
however, it is a bit "ugly", as it is raising an error in a ```try``` statement where ```except``` excepts everything.
A better solution would then maybe be to let ```except``` in line 132 just except a few errors.

NB! I initially tried to ```raise CollectError```. However, I get the return message ```NameError: name 'CollectError' is not defined```. Might be a problem as ```CollectError``` is raised several places in ```collect.py```

**Comment by johnomotani** [comment]
As I see it, the problem is actually that ```f.dimensions(varname)``` and ```f.ndims(varname)``` return ```None``` rather than raising an exception when the variable is not found (which is what I would expect them to do). If we go back to ```ndims = len(dimens)``` then an exception will be raised when dimens=None, but I think the natural thing to do is to remove
```
except KeyError:
    return None
```
from the dimens and ndims functions in DataFile. Of course one would need to check that doing so does not cause errors somewhere else...

**Comment by loeiten** [comment]
Commit dea363360719baabbd5d8c48abe8664e9e5daef8 closes this
