### ISSUE TITLE
Bad LaTeX in documentation

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#798]
LaTeX is bad on the following pages:

http://bout-dev.readthedocs.io/en/latest/user_docs/boundary_options.html
http://bout-dev.readthedocs.io/en/latest/user_docs/fluid_equations.html#initial-profiles

Probably other places too

**Comment by d7919** [comment]
In addition:
User docs

* [section links](http://bout-dev.readthedocs.io/en/latest/user_docs/introduction.html)
* [arrow](http://bout-dev.readthedocs.io/en/latest/user_docs/time_integration.html) Search for "The second matrix"
* [Inadditionwehave](http://bout-dev.readthedocs.io/en/latest/user_docs/laplacian.html)
* [arrow](http://bout-dev.readthedocs.io/en/latest/user_docs/differential_operators.html)

Dev docs

* [ensuremath](http://bout-dev.readthedocs.io/en/latest/developer_docs/derivatives.html)

**Comment by d7919** [comment]
Also table references/numbering broken/missing in places.

**Comment by ZedThree** [comment]
Fixed in #800
