### ISSUE TITLE
staggered derivatives

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#810]
if inloc is e.g. at YLOW, this produces a wrong result.
https://github.com/boutproject/BOUT-dev/blob/40d60c5f368cbe847e4a7d16f513554f31a38d87/src/mesh/index_derivs.cxx#L1856

This is wrong if all locations are at CELL_CENTRE
https://github.com/boutproject/BOUT-dev/blob/40d60c5f368cbe847e4a7d16f513554f31a38d87/src/mesh/index_derivs.cxx#L2681

Due to the code duplication, there are probably more cases where things are wrong.

I would suggest splitting the functions into smaller ones.
See e.g. https://github.com/dschwoerer/BOUT-dev/blob/ef41a53c04f6b349a63ac98038903b34b83a3a16/src/mesh/impls/aiolos/generated_derivs.cxx#L1672
After having determined whether we need staggered derivatives, it is much easier if you only need to consider that single case:
https://github.com/dschwoerer/BOUT-dev/blob/ef41a53c04f6b349a63ac98038903b34b83a3a16/src/mesh/impls/aiolos/generated_derivs.cxx#L1318

Further, I would be in favour of complete removing the StaggerGrids bool - which reduces and simplifies the code, without reducing its functionality. It further simplifies the use of BOUT. As this is a breaking change, we should probably wait till 5.0

**Comment by dschwoerer** [comment]
Additional to fixing, it would be worth adding MMS tests for:
- [ ] indexVDD?
- [ ] indexFDD?

**Comment by dschwoerer** [comment]
Somewhat related: also uses the global mesh (makes my test fail)

**Comment by d7919** [comment]
Does #1384 help with this?

**Comment by ZedThree** [comment]
Pretty sure this is fixed
