### ISSUE TITLE
derivative function signature

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#811]
the functions like indexDDZ, indexVDDX etc have different function signatures, which should be unified.
* first and second derivative in Z takes an optional argument of type bool
* the flux derivatives in x and y direction take an optional REGION argument
* the rest none.

I think they should all take a REGION flag.

Would simplify e.g.:
https://github.com/boutproject/BOUT-dev/pull/742/files#diff-c39c80b2402b613bcf6628ad3944ea38R199

But also for the python interface, as it would make the wrapping much easier.
And of course, it would give the user more control what regions are needed.

**Comment by d7919** [comment]
Just to note : the flux derivative in z gains a region in https://github.com/boutproject/BOUT-dev/pull/804/files#diff-5cead8040b32203dd2b4aac7358440c3R534 #804

**Comment by ZedThree** [comment]
Agreed, it would be good to be more consistent with this

**Comment by bendudson** [comment]
Yes, agreed. We can make them consistent, but backwards-compatible for now by providing wrappers or default arguments. The wrappers could be marked deprecated and removed in 5.0?

**Comment by ZedThree** [comment]
Default arguments that replicate the current behaviour sounds good

**Comment by dschwoerer** [comment]
I will have a go if #804 is merged, to avoid conflicts ...

**Comment by ZedThree** [comment]
Fixed in #815
