### ISSUE TITLE
Duplicated documentation

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#814]
derivs.hxx contains loads of duplicated documentation.
Can I remove the duplicated ones?

There are e.g. many DDZ(), and they all do the same.
If at all, there would be need for documentation to say what is the default for the parameters which are not part of the function signature.

**Comment by d7919** [comment]
A link to the example is [here](https://github.com/boutproject/BOUT-dev/blob/master/include/derivs.hxx#L151).  Those specific comments look like doxygen related things. I'm not sure how removing these comments would modify the generated documentation.

**Comment by dschwoerer** [comment]
I rewrote this in #815 
It would be easy enough to re-add all, but that would increase the file size of the header even more ...

**Comment by ZedThree** [comment]
This is because doxygen is super annoying with regards to overloads. Ideally, it would group all the overloads together into one block with identical documentation, but IIRC, that is very hard/impossible to do.

It would be nice to mention the default values though.

**Comment by dschwoerer** [comment]
I added the duplicate documentation.
The file has thereby increased around 3k lines.
