### ISSUE TITLE
All Fields should have a location

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#829]
Currently only Field3D supports it.

See #64 

See https://github.com/boutproject/BOUT-dev/pull/818#discussion_r165302485

**Comment by d7919** [comment]
Field2D has location now, is this enough to close the issue or should FieldPerp have a location as well?

**Comment by johnomotani** [comment]
I'd vote for FieldPerp having a location too. I think it's a 'nice to have' rather than important though. For example, if someone calls `Laplacian::solve(FieldPerp rhs)`, at the moment we can't check the location. Not the best example because `solve(Field3D)` 'should' be called, but still...

**Comment by ZedThree** [comment]
Fixed in #1198 and #1441
