### ISSUE TITLE
Invalidating guard cell values

### ISSUE THREAD

**Issue by bendudson** [boutproject/BOUT-dev#837]
It would be useful for debugging and catching errors, if boundary/guard cells were set to NaN if sufficiently high checking level is set. This could be in the field allocate routine, for example.

This would help catch user code broken by changes to boundary values e.g. PR #821

**Comment by d7919** [comment]
I have something in progress on this, will try to push soon.

**Comment by d7919** [comment]
I've updated my branch in which I was exploring this, added a unit test, make Field3D::allocate invalidate the guards and fixed the implementation (I was only doing some of the guard cells).

This is in https://github.com/boutproject/BOUT-dev/tree/invalidateGuards

Note I've currently forced this test to be inactive (by requiring check > 4, can force in makefile to try this out) as it causes several of the integrated tests to fail. This needs further investigation to see how harmful the failures are (could just be using RGN_ALL when really just need RGN_NOBNDRY etc.).

**Comment by d7919** [comment]
Exploring the reason for the test fails in `test-drift-instability` with invalidateGuards it seems the `phi` field, which is found from a laplacian solve does not have boundary values set in this case and this then causes a problem when we try to take a derivative of this wrt x in a bracket operator. Applying a boundary condition (tested with Dirichlet) after the solve is enough to avoid the test failing it seems. In conclusion I think in this case the invalidateGuards use has actually led to the identification of an error in a model.

**Comment by bendudson** [comment]
Strange.. x boundary conditions should be set as part of the Laplacian solve, since they're set in the flags. Is the solver only setting some of the boundary cells?

**Comment by d7919** [comment]
Yes it's odd. Probably related to invalidateGuards doing something odd/incorrect rather than a real error. The only other thing I can think is that there's an internal field that ends up not getting the boundaries set.

**Comment by d7919** [comment]
Ah worked it out. The `Field3D::operator=(FieldPerp)` routine is used to store each slice of the Laplacian solve with an iteration over `y`. This routine calls `allocate` every time, which in turn invalidates the guards (i.e. re-invalidating guards that had just been set!). With a small tweak to ensure we only invalidate the guards when we get a new block most tests now pass, just the fci and interchange ones fail. 

This should initialise new blocks created when the field has no block assigned to have invalid guards but doesn't do anything when the `ensureUnique` call results in getting a new block, which we probably  want as well. It's just the case where `ensureUnique` has no work to do that we don't want to invalidate. No easy way to detect this at the moment though unfortunately.

**Comment by d7919** [comment]
#871 introduced this feature.
