### ISSUE TITLE
LaplaceXZ Petsc inner boundary

### ISSUE THREAD

**Issue by bendudson** [boutproject/BOUT-dev#865]
The inner X boundary for the PETSc implementation of LaplaceXZ defaults to neumann, rather than dirichlet. 

Described in comments here:
https://github.com/boutproject/BOUT-dev/blob/master/src/invert/laplacexz/impls/petsc/laplacexz-petsc.cxx#L85

and implemented here:
https://github.com/boutproject/BOUT-dev/blob/next/src/invert/laplacexz/impls/petsc/laplacexz-petsc.cxx#L340

To be consistent with the other solvers, a boundary flag of 0 should be Dirichlet.

**Comment by ZedThree** [comment]
Fixed in #868
