### ISSUE TITLE
Pylib error

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#873]
pylib writes errors to stdout:
`ERROR: scipy.signal module not available`
Should be written to stderr / raised as error

**Comment by ZedThree** [comment]
Agree, hard errors should probably raise exceptions. We should use the `warnings` module for less serious warnings, etc. This would allow them to be optionally turned off by the user

**Comment by bendudson** [comment]
I think this should probably be a warning when the module is imported, if functionality is not available. An exception should be raised if a function which depends on this external module is actually used. Perhaps it does already.

**Comment by ZedThree** [comment]
Fixed in #1020
