### ISSUE TITLE
DataIterator with OpenMP

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#876]
I just came across an issue with the OpenMP version of the iterator. I had a loop of the form

~~~~
Field3D x;
x.allocate()
BOUT_OMP(parallel for)
for(int jy=ys; jy<=ye ; jy++){
    FieldPerp ss = sliceXZ(b,jy);
    x = solve(ss);
}
~~~~

The `Field3D::operator=(FieldPerp rhs)` has a loop like

~~~~
for (const &i: rhs){
     (*this)[i] = rhs[i];
}
~~~~

The dataiterator for the range based loop tries to parallelise itself, assuming that all threads will take part in this loop, which isn't the case here as each thread must do the full XZ assignment for the thread specific `jy` and hence means `x` will only get ~`ny/nthread` of the data being set.

I think this is one of the reasons why trying to OpenMP parallelise the loop at https://github.com/boutproject/BOUT-dev/blob/master/src/invert/laplace/invert_laplace.cxx#L199 has caused things to fail in previous attempts. I now have a version of this loop working by forcing the use of the serial DI.

**Comment by dschwoerer** [comment]
I think only the treads of the inner most parallel region are assumed to be taking part.
I wasn't aware of any way to determine whether the all inner most threads are takeing part - or not.

I think putting
```
BOUT_OMP(parallel)
for (const &i: rhs){
     (*this)[i] = rhs[i];
}
```
should basically serialize it:
https://github.com/boutproject/BOUT-dev/blob/master/include/bout/dataiterator.hxx#L339
https://gcc.gnu.org/onlinedocs/gcc-4.5.4/libgomp/omp_005fget_005fnum_005fthreads.html

**Comment by d7919** [comment]
Unfortunately that doesn't seem to help here, but it could be that a different issue arises, will need to dig further.

There's a branch that I'm using that should reference this issue.

**Comment by d7919** [comment]
I think I may have just needed to put `BOUT_OMP(parallel)` on more loops. Adding parallel to all of the assignment loops does indeed help avoid this issue, thanks! I'm not sure that there is much else we can do without leaving the splitting of work to OpenMP, but it does mean that at the moment we have to either OpenMP "everything" or nothing.

**Comment by d7919** [comment]
On a related note the Array implementation assumes the result of `omp_get_thread_num` is unique when accessing the memory store (basically when allocating fields). This may not be the case if we nest parallel regions. It should be possible to generalise this, but there's currently a need to know the maximum possible number of unique threads. We could also further avoid this by changing the Array arena from vector based to map based, although there could be some performance penalty for this.
