### ISSUE TITLE
Odd behaviour in cyclic_reduction

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#895]
Following on from the introduction of `Matrix` and `Tensor` I've been looking into replacing uses of the old style `matrix`. These are mostly just used in the different Laplacian methods, one example of the replacement is #891 which does it for serial_tri. 

I've now started looking at the `cyclic` method, which is mostly implemented in `cyclic_reduction.hxx` and is shared among a few different inversions (Laplace, parderiv, laplace-xy and Lapalace-xz). I'd replaced all `matrix` with `Matrix` except for `recvbuffer` and the tests all still passed. Changing `recvbuffer` to `Matrix` caused the `test-cyclic` test to fail when run in parallel (2 processes).

I tracked this down to the fact that on rank 1 the `recvbuffer` storage object is allocated with a second dimension of size 0. In practice this causes the size to be allocated as 1 in the old `matrix` method. Temporarilly patching in similar behaviour to the new `Matrix` class the test then failed in the statement ` xn[s0+i] = recvbuffer[fromproc][ 2*i + 1] ` as `i=0` so the second index is 1, which is outside the size of this dimension. This doesn't fail with the old method as there is no bounds checking, but I still think this is wrong unless the code is doing something very clever (this isn't actually completely out of bounds as long as the first index is not at its maximum value so could possibly be intentional).

The size of the second dimension is given by `nsys/nprocs` in this case (with the number of systems being smaller than the number of processors). There's also some slightly odd code

~~~~
int my = myns;
if(my == 0)
   my = 0
~~~~

which may suggest a typo?

The variable `my` is what is actually used to set the dimensions of several Matrix instances, some as the second dimension and others for the first dimension, which also seems suspicious.

**Comment by d7919** [comment]
A workaround seems to be to do ` my = 1 ` if `my = 0` but I'm not sure if this is just masking an underlying problem.

**Comment by ZedThree** [comment]
Fixed in #899
