### ISSUE TITLE
Overly strict checking for MUMPS?

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#912]
If the user asks for MUMPS support, we check for the following files during configure:

- dmumps_c.h 
- libdmumps.a 
- libmumps_common.a 
- libpord.a 
- libscalapack.a 
- libblacs.a 
- libparmetis.a 
- libmetis.a 
- libptscotch.a 
- libptesmumps.a

but I'm not sure we need all of these. The version of MUMPS in Ubuntu 14.04 (used on Travis), doesn't come with any of libscalapack.a, libblacs.a, libparmetis.a, or libmetis.a, so we turn off MUMPS support.

Do we know which of these are actually required?

**Comment by johnomotani** [comment]
If I remember right, MUMPS requires at least one of parmetis and ptscotch, and quite a lot of the other dependencies are dependencies of those libraries. I guess if MUMPS was compiled with support for both it will depend on all those libraries, but if it was only compiled with ptscotch it doesn't.

Don't know how to test in a sensible way which dependencies MUMPS actually needs; I remember the MUMPS build process being very unhelpful (I couldn't get it to work myself, so always used PETSc to compile MUMPS).

**Comment by d7919** [comment]
http://mumps.enseeiht.fr/index.php?page=faq#2.2 and/or http://mumps.enseeiht.fr/index.php?page=faq#2.3 may be useful to answer this.

http://mumps.enseeiht.fr/index.php?page=faq#2.4

**Comment by d7919** [comment]
The user docs discuss this a little as well http://mumps.enseeiht.fr/doc/userguide_5.1.2.pdf

**Comment by d7919** [comment]
It sounds like they're not strictly required, but strongly recommended. It may be that BOUT++ assumes they are available within MUMPS.

**Comment by ZedThree** [comment]
If they are dependencies of MUMPS, and we don't use them directly ourselves, can we not just check for MUMPS itself and assume it's been compiled correctly?

**Comment by d7919** [comment]
I don't think they are strict dependencies, just recommended.

**Comment by ZedThree** [comment]
Agreed that the right thing to do is to just check for MUMPS itself, and ignore everything else?

**Comment by d7919** [comment]
Unless the way we use MUMPS in BOUT++ assumes we have these optional dependencies available.

**Comment by ZedThree** [comment]
An update: recent versions of Scalapack come bundled with BLACS, so we don't always need libblacs.

I don't *think* we use any of the metis/scotch variants, but I gather they are "recommended" for the parallel version.

At any rate, #944 has some improvements to configure that should allow the user to get something linked at least.

**Comment by ZedThree** [comment]
Fixed in #944 -- need to check documentation is up-to-date
