### ISSUE TITLE
Potential issues with Field copy constructors.

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#914]
I've just come across a potential issue with the field copy constructors. These just give the new field a reference to the existing data block, which we call `checkData` on if `CHECK > 2`.

Consider the following case

~~~~
Field2D a;
a.allocate();
Field2D b(a);
~~~~

In the copy constructor call to make `b` we will `checkData` on the data block of `a`. This has been allocated but it has not been initialised so the `checkData` output is undefined (i.e. it could throw or it could not). 

I think the only ways to avoid this undefined behaviour would be to either remove the `checkData` call in copy constructors or to ensure `allocate` initialises the data block.

**Comment by d7919** [comment]
For example, I think this is the cause of the test failure [here](https://travis-ci.org/boutproject/BOUT-dev/jobs/348147681#L1534).

**Comment by ZedThree** [comment]
Fixed in #1533
