### ISSUE TITLE
Bug in Field2D with TRACK

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#923]
https://github.com/boutproject/BOUT-dev/blob/c1856a3d73571748bf61def0e3d0c7a72cad65ad/src/field/field2d.cxx#L80-L82
This should be ``name = f.name`` I think?
Compilation fails if tracking is enabled with ``--enable-track``: the Travis builds must not ever enable this option? Maybe we could add to the debugging build?

**Comment by ZedThree** [comment]
Good spot. I thought I out `--enable-track` in one of the coverage jobs, but I guess I missed it.

**Comment by ZedThree** [comment]
Fixed in #929
