### ISSUE TITLE
Changed header files does not trigger rebuild

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#931]
That should be fixed in the makefiles.
This could probably achieved (at least for gcc) with adding `-MM -MF .file.mk` to the compile command and include that in the makefile.

Would that be useful?

**Comment by bendudson** [comment]
Fixed by #953

**Comment by dschwoerer** [comment]
Not available currently.
If we are going to change things on the build system for 5.0, it would be nice if that would be possible.

**Comment by ZedThree** [comment]
Fixed by using CMake build system. We did have a fix in the autoconf build system, but backed it out after having issues with it.
