### ISSUE TITLE
Brackets operator [3D,2D] /= -[2D,3D]

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#94]
When using certain bracket methods and one argument is a `Field2D` and the other is a `Field3D` the method used reverts to `simple` for calls like [2D,3D] whilst using the selected method for calls like [3D,2D]. As such [2D,3D] /= -[3D,2D] as one may expect if using Arakawa brackets (for example). 

Is this a bug or am I overlooking something?

**Comment by bendudson** [comment]
This is probably a bug. I suspect the routines which were needed at the
time were implemented, and the rest left to revert to the old method.

**Comment by dschwoerer** [comment]
Is there a reason [2D,3D] does not simply return -[3D,2D]?
The performance penalty should be negligible.

**Comment by bendudson** [comment]
For fixed stencil methods, such as Arakawa, [2D,3D] could indeed be implemented as -[3D,2D]. For methods which have any upwinding or non-linear behavior, such as WENO (which is an option for the "standard" and "simple" bracket methods), the bracket is not antisymmetric.

**Comment by dschwoerer** [comment]
I assume this can be closed?

**Comment by d7919** [comment]
Yes I think this issue can be closed now. It might be useful to add a comment at some point to one of the manuals just to highlight the fact that the default method is not antisymmetric.
