### ISSUE TITLE
integer expressions in input files: documentation

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#947]
The manual [BOUT-dev/manual/sphinx/user_docs/input_grids.rst]( BOUT-dev/manual/sphinx/user_docs/input_grids.rst ) says
> Integer quantities such as nx must be numbers (like “260”), not expressions (like “256 + 2*MXG”).

but I used expressions to set ``ny = (nx-2*mxg)`` recently and it seemed to work... Does anyone know if this is supposed to have changed? Should the manual be updated?

**Comment by d7919** [comment]
It's possible that this gets interpreted as float and then converted to int (the options reader seems to try to be flexible). I suspect this is fine for many cases, but may cause issue when division is involved.

This is just speculation.

**Comment by ZedThree** [comment]
As @d7919 said, it gets interpreted as a float, and then `ROUND`ed to an int ([relevant code here][1]), and if it's not within 1e-3 of an integer, it throws.

Certainly the documentation needs updating, but I'm not sure about the code. Maybe we should not check if it's close to an int, and just return the integer part anyway? I think that's what I would probably expect to happen.

[1]: https://github.com/boutproject/BOUT-dev/blob/master/src/sys/options.cxx#L99

**Comment by bendudson** [comment]
The manual should be updated, sorry this changed a while ago. 

The aim of throwing was to make sure that any rounding to nearest integer is clear. If a user wants to round to the nearest integer then they can explicitly use `round()`. All calculations are currently done in floating point, so some error is allowed.
