### ISSUE TITLE
Python tools needs a tidy

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#949]
All python files should conform to [PEP8][1]. Very easy fix, just run a pep8-checker over them, e.g. flake8, pylint, pep8.

All docstrings should be in [numpydoc format][2]. A bit harder, as they will need manual editing. We can then use the "napoleon" Sphinx extension to make sure the docs are on readthedocs.

[1]: https://www.python.org/dev/peps/pep-0008/
[2]: https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt

**Comment by d7919** [comment]
Is this going to make v4.2 or will it be pushed back?

**Comment by ZedThree** [comment]
Partly fixed, more work needed

**Comment by ZedThree** [comment]
Basically done by moving `boutdata` and `boututils` into their own repos
