### ISSUE TITLE
libhdf5 link failure on OS X

### ISSUE THREAD

**Issue by erikgrinaker** [boutproject/BOUT-dev#95]
Attempting to build the `advect1d` example on OS X with the XCode toolchain fails:

```
advect1d $ make
  Compiling  gas_compress.cxx
  Linking gas_compress
Undefined symbols for architecture x86_64:
  "_SZ_BufftoBuffCompress", referenced from:
      _H5Z_filter_szip in libhdf5.a(H5Zszip.o)
  "_SZ_BufftoBuffDecompress", referenced from:
      _H5Z_filter_szip in libhdf5.a(H5Zszip.o)
  "_SZ_encoder_enabled", referenced from:
      _H5Z_init_interface in libhdf5.a(H5Z.o)
```

The linker is given the full path to `/usr/local/lib/libhdf5.a`, as specified in `make.config` by `configure`. However, on my system, it needs to link against `libhdf5.dylib` instead (HDF5 installed via Homebrew).

Wouldn't it be better to just pass `-lhdf5` to the linker instead of an explicit library path?

**Comment by bendudson** [comment]
The full path is passed in case the library has not been added to
LD_LIBRARY_PATH or equivalent. Perhaps something like

-L/usr/local/lib -lhdf5

i.e. pass the path as a -L argument

**Comment by dschwoerer** [comment]
I changed this in pull request #85 , and splitted this in an -L with the path and -lhdf5

**Comment by bendudson** [comment]
Merged now, sorry for delay! See if that works... Thanks David and Erik!

**Comment by erikgrinaker** [comment]
Indeed, #85 fixes this for me, although the linker throws a warning:

```
ld: warning: directory not found for option '-L/usr/local//usr/local/lib'
```

I believe this is caused by this line in `configure.ac`:

```
EXTRA_LIBS="$EXTRA_LIBS -L$HDFPATH/$HDFLIBPATH -lhdf5 -lz"
```

Where `-L$HDFPATH/$HDFLIBPATH` should probably be just `-L$HDFLIBPATH`.

**Comment by dschwoerer** [comment]
HDFLIBPATH should just be lib or lib64, to make it consistent, see pullrequest #96

**Comment by erikgrinaker** [comment]
Makes sense. Can confirm #96 works for me. Thanks!
