### ISSUE TITLE
Citations, credit, and papers

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#952]
The [CITATION][citation] file is massively out of date. It should at the very least have the [MMS paper][paper] in, but we probably also want to get a new paper in some form out in the next year or so -- we are missing some important contributors, e.g. @dschwoerer, @d7919, @bshanahan to name only a few. We do have a more complete list of contributors on [our website][aboutpage], but those contributors that are only listed there are likely not getting the credit they deserve.

Getting proper credit for software is a tricky problem though, and it's something the Research Software Engineer community is currently trying to get to grips with. I'll try to briefly summarise our options, which are not necessarily mutually exclusive:

- A traditional physics/research paper in something like PoP
    - This is probably the hardest, as we'd need to tackle a physics problem that showcased most/all of the recent developments in BOUT++
- A paper in CPC
    - Unlikely, they are not keen on software updates, they seem to much prefer new software
- A paper in [Journal of Open Research Software][jors] and/or [Journal of Open Source Software][joss]
    - These are new, novel journals aim specifically at tackling software citations. JOSS says
      > If your software is already well documented then paper preparation should take no more than an hour.

      JORS expects a bit more of a traditional paper (I think?), but they seem to be both aimed at more just getting a DOI and a traditional journal style citation for software, than expecting research like PoP/NF, etc. I don't know what either of their policies are on software updates and adding more collaborators. JOSS is free, and JORS is nominally £300, but pay-what-you-can.

As well as updating CITATION, we may also want to provide a [Citation File Format][cff] file. This is a YAML file which aims to standardise CITATION files by making them both machine- and human-readable. We probably also want to mention explicitly how to cite us in both the README.md and on our website.

[citation]: https://github.com/boutproject/BOUT-dev/blob/master/CITATION
[cff]: https://citation-file-format.github.io/
[paper]: https://aip.scitation.org/doi/abs/10.1063/1.4953429
[aboutpage]: http://boutproject.github.io/about/
[jors]: https://openresearchsoftware.metajnl.com/about/submissions/#software
[joss]: https://joss.theoj.org/about#author_guidelines

**Comment by ZedThree** [comment]
Somewhat related is [Zenodo][zenodo] that works with [Github][guide] to get a DOI for releases. I've enabled it so that will automatically give us a DOI for new releases. Unfortunately, it looks like I'll have to manually upload previous releases to get DOIs for them.

[zenodo]: https://zenodo.org/
[guide]: https://guides.github.com/activities/citable-code/

**Comment by bendudson** [comment]
Thanks Peter! A DOI would be a good start. Zenodo looks like a useful repository generally; we should probably encourage people to use it, and upload input files, analysis scripts to it.

**Comment by JosephThomasParker** [comment]
I've just gone to a talk by the developer of Citation File Format.  The slides are worth having a quick look at:
http://sdruskat.net/citation-file-format-cw18/
(The talk is in 2D... press down, not right.)

I like the format - it's nice that it's human readable.  You can tag different releases with different authors, and also put in release-specific messages.  However, he did seem to be a bit pessimistic about the prospects of CFF, and was wondering whether the project should be dropped or merged with [CodeMeta](https://codemeta.github.io/).  CodeMeta is based on json files, so it's not human readable, but also not that inaccessible.

**Comment by ZedThree** [comment]
Thanks Joseph, that was pretty interesting. I wasn't aware of CodeMeta. yaml > json for human readability, which I think is really important for a citation file.

We might have to see which way the wind blows for CFF/CodeMeta/something else. I imagine it'll come up at the RSE18 conference as well.

**Comment by ZedThree** [comment]
CFF file merged in #1274
