### ISSUE TITLE
Skipping tests

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#979]
It would be great to have some way to skip tests, if the current configuration/build does not support that test.
Currently we only run tests that can run under all build conditions.
That means, if somebody configured BOUT++ without netcdf, but with hdf5 the test suite will fail.
That also means that new feature that may only be conditionally be build, e.g. the cython interface will have to be always build, or not tested at all (or not merged)

Thus a way to skip test that are in the current configuration supported is required.

I thought putting the logic for whether to run a test or not, could be in the tests them self, as this way it is quite easy to add tests, and no extra scripts or lists are required.
For travis, it would be easy enough to make lists for each configuration and list what to skip. That is much work, as we could add e.g. some tests that require laplace etc. but it is doable.
However, a normal user will have most likely some failing tests, unless he specifies a list of what to skip - which is probably not lead to a great user experience.

Thus I would like to have some way of automatically getting the list of what to skip. One option would be to have a script in each test directory, that can be called, checks e.g. the bout-config script to determine on whether the unit test could be run.

Another option would be to generate the list at configure time.

I think what is required is:
* Good user experience. Just running make check should not fail unless something is wrong, not just a dependency not compiled in. (Experience)
* Easy to update the skipping requirement, if the test is updated. (Update)
* Run as many tests as possible (Coverage)

What | Experience | Update | Coverage 
--------|-----------------|----|-----
Minimal list| Yes | Yes | No
Build into test| Yes | Yes|Yes
Extra script | Yes | Somewhat|Yes
configure | Yes | No|Yes
User provided list | No | Maybe|Maybe

* Minimal list is what we have
* Build into test is implemented in #943 
* Extra script is a variant of #943 
* configure is probably quite hard to implement
* User provided list is easy to implement, but I doubt it is maintainable.

**Comment by dschwoerer** [comment]
Another way would be to add special comments to the runtest files.
I thought of something like
```
#Requires: boutcore
```
However to skip the specific test only on travis and only with mpich, we would need to implement somewhat more complex expressions, namely (at least) `AND`, `NOT` and probably also want `OR`, and parenthesis.
To not run on travis with mpich could then be:
```
#Requires: not travis and not mpich
```
Then all runtest scripts could be parsed, and a `test_suite_list` could be generated.

The list creation could be done ether during `./configure`, or at the start of `./test_suite(_make)`

**Comment by bendudson** [comment]
Nice! I like this general idea

#Requires: (not (and travis mpich))
?

The names "boutcore", "travis" etc. would have to be defined somehow. Perhaps a subdirectory of short scripts (named "boutcore", "travis" etc) which run and return true/false. The file names give the names, and running the scripts give true/false.

**Comment by dschwoerer** [comment]
Resolved by #980
