### ISSUE TITLE
Deprecating operator^

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#983]
Should we deprecate (and remove this) completely?
It seems currently to be only used in vector?d as cross product.
`grep 'operator[[:space:]]*\^' include/ -r`
I guess cross(vector1,vector2) would be easier to read?
Further we could remove the note from the user manual about `^` and move it to the developer manual for future reference as to why it was removed.

**Comment by bendudson** [comment]
Possibly... a better notation for cross products would be nice. 
The user manual part about fields has been significantly changed in PR #981 , including removing the `^` operator for exponentiation, since this was removed from the code some time ago.
